Dialplan/Users:
  path: '/Dialplan/Users'
  controller: 'kernel:handleRequestAction'

Dialplan/UserStatus:
  path: '/Dialplan/UserStatus'
  controller: 'kernel:handleRequestAction'

Dialplan/Trunks:
  path: '/Dialplan/Trunks'
  controller: 'kernel:handleRequestAction'

Dialplan/Residentials:
  path: '/Dialplan/Residentials'
  controller: 'kernel:handleRequestAction'

Dialplan/Retails:
  path: '/Dialplan/Retails'
  controller: 'kernel:handleRequestAction'

Dialplan/ResidentialStatus:
  path: '/Dialplan/ResidentialStatus'
  controller: 'kernel:handleRequestAction'

Dialplan/Friends:
  path: '/Dialplan/Friends'
  controller: 'kernel:handleRequestAction'

Dialplan/FriendStatus:
  path: '/Dialplan/FriendStatus'
  controller: 'kernel:handleRequestAction'

Dialplan/Headers:
  path: '/Dialplan/Headers'
  controller: 'kernel:handleRequestAction'

Dialplan/HuntGroups:
  path: '/Dialplan/HuntGroups'
  controller: 'kernel:handleRequestAction'

Dialplan/HuntGroupStatus:
  path: '/Dialplan/HuntGroupStatus'
  controller: 'kernel:handleRequestAction'

Dialplan/HuntGroupMember:
  path: '/Dialplan/HuntGroupMember'
  controller: 'kernel:handleRequestAction'

Dialplan/Queues:
  path: '/Dialplan/Queues'
  controller: 'kernel:handleRequestAction'

Dialplan/QueueStatus:
  path: '/Dialplan/QueueStatus'
  controller: 'kernel:handleRequestAction'

Dialplan/FaxDial:
  path: '/Dialplan/FaxDial'
  controller: 'kernel:handleRequestAction'

Dialplan/FaxDialStatus:
  path: '/Dialplan/FaxDialStatus'
  controller: 'kernel:handleRequestAction'

Dialplan/FaxSend:
  path: '/Dialplan/FaxSend'
  controller: 'kernel:handleRequestAction'

Dialplan/FaxSendStatus:
  path: '/Dialplan/FaxSendStatus'
  controller: 'kernel:handleRequestAction'

Dialplan/FaxReceiveStatus:
  path: '/Dialplan/FaxReceiveStatus'
  controller: 'kernel:handleRequestAction'

Voicemail/Sender:
  path: '/Voicemail/Sender'
  controller: 'kernel:handleRequestAction'

Hints/Generator:
  path: '/Hints/Generator'
  controller: 'kernel:handleRequestAction'
