imports:
    - { resource: "@ProviderBundle/Resources/config/config.yml" }
    - { resource: "@CoreBundle/Resources/config/doctrine_cache.yml" }

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    fastagi:
        synthetic: true

    ##################################
    ## External Services
    ##################################
    PhpMimeMailParser\Parser: ~

    ##################################
    ## Helpers & Wrappers
    ##################################
    Agi\Wrapper:
        lazy: true
        arguments:
            $fastagi: '@fastagi'
            $locutionPathResolver: '@Service\CommonStoragePathResolver::LocutionEncodedFile'
            $colorizer: '@Agi\Colorizer'

    Agi\Colorizer:
        arguments: ~

    Agi\ChannelInfo:
        arguments: ~

    Helpers\EndpointResolver:
        arguments: ~

    Voicemail\Sender:
        arguments:
            $parser: '@PhpMimeMailParser\Parser'
            $mailer: '@mailer'

    ##################################
    ## Handlers
    ##################################
    Dialplan\Headers:
        arguments: ~

    Dialplan\Trunks:
        arguments: ~

    Dialplan\Users:
        arguments: ~

    Dialplan\Residentials:
        arguments: ~

    Dialplan\Retails:
        arguments: ~

    Dialplan\Friends:
        arguments: ~

    Dialplan\FriendStatus:
        arguments: ~

    Dialplan\UserStatus:
        arguments: ~

    Dialplan\ResidentialStatus:
        arguments: ~

    Dialplan\HuntGroups:
        arguments: ~

    Dialplan\HuntGroupStatus:
        arguments: ~

    Dialplan\HuntGroupMember:
        arguments: ~

    Dialplan\Queues:
        arguments: ~

    Dialplan\QueueStatus:
        arguments: ~

    Dialplan\FaxDial:
        arguments:
            $faxStoragePathResolver:
                '@Service\CommonStoragePathResolver::FaxesInOutFile'

    Dialplan\FaxDialStatus:
        arguments: ~

    Dialplan\FaxSend:
        arguments: ~

    Dialplan\FaxSendStatus:
        arguments: ~
    Dialplan\FaxReceiveStatus:
        arguments: ~

    ##################################
    ## Actions
    ##################################
    Agi\Action\CallForwardAction:
        lazy: true
        arguments: ~

    Agi\Action\ConditionalRouteAction:
        lazy: true
        arguments: ~

    Agi\Action\ConferenceRoomAction:
        lazy: true
        arguments: ~

    Agi\Action\DdiAction:
        lazy: true
        arguments: ~

    Agi\Action\ExtensionAction:
        lazy: true
        arguments: ~

    Agi\Action\FaxReceiveAction:
        lazy: true
        arguments: ~

    Agi\Action\FaxReceiveStatusAction:
        lazy: true
        arguments:
            $mailer: '@mailer'

    Agi\Action\FriendCallAction:
        lazy: true
        arguments: ~

    Agi\Action\FriendStatusAction:
        lazy: true
        arguments: ~

    Agi\Action\HuntGroupAction:
        lazy: true
        arguments: ~

    Agi\Action\HuntGroupCallAction:
        lazy: true
        arguments: ~

    Agi\Action\HuntGroupStatusAction:
        lazy: true
        arguments: ~

    Agi\Action\IvrAction:
        lazy: true
        arguments: ~

    Agi\Action\QueueAction:
        lazy: true
        arguments: ~

    Agi\Action\QueueCallAction:
        lazy: true
        arguments: ~

    Agi\Action\QueueFullAction:
        lazy: true
        arguments: ~

    Agi\Action\QueueTimeoutAction:
        lazy: true
        arguments: ~

    Agi\Action\ResidentialCallAction:
        lazy: true
        arguments: ~

    Agi\Action\RetailCallAction:
        lazy: true
        arguments: ~

    Agi\Action\ResidentialStatusAction:
        lazy: true
        arguments: ~

    Agi\Action\RouterAction:
        lazy: true
        arguments: ~

    Agi\Action\UserCallAction:
        lazy: true
        arguments: ~

    Agi\Action\UserStatusAction:
        lazy: true
        arguments: ~

    Agi\Action\ExternalFilterAction:
        lazy: true
        arguments: ~

    Agi\Action\ExternalNumberAction:
        lazy: true
        arguments: ~

    Agi\Action\ExternalFaxCallAction:
        lazy: true
        arguments: ~

    Agi\Action\ServiceAction:
        lazy: true
        arguments: ~

    Agi\Action\VoicemailAction:
        lazy: true
        arguments: ~
