imports:
  - { resource: "@CoreBundle/Resources/config/config.yml" }
  - { resource: "@CoreBundle/Resources/config/doctrine_cache.yml" }
  - { resource: "@ApiBundle/Resources/config/config.yml" }
  - { resource: api_platform.yml }
  - { resource: security.yml }
  - { resource: services.yml }

parameters:
  #required to generate valid urls from console
  #https://symfony.com/doc/current/console/request_context.html
  router.request_context.base_url: /api/brand
  api_default_role: ROLE_BRAND_ADMIN

gesdinet_jwt_refresh_token:
  user_provider: 'Service\UserProvider'

framework:
  secret: '%secret%'
  router:
    resource: '%kernel.root_dir%/config/routing.yml'

# Twig Configuration
twig:
  paths:
    '%kernel.project_dir%/vendor/irontec/ivoz-api-bundle/Resources/views': ApiBundle
