#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: retailAccountsList_screen
  screens: &retailAccounts_screensLink
    retailAccountsList_screen: &retailAccountsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *RetailAccounts
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Retail Account', 'Retail Accounts', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        blacklist: &retailAccounts_blacklistLink
          domain: true
          transport: true
          auth_needed: true
          password: true
          areaCode: true
          countryId: true
          allow: true
          disallow: true
          direct_media_method: true
          update_callerid: true
          from_domain: true
          callerid_update_header: true
          directConnectivity: true
          ip: true
          port: true
          languageId: true
        order:
          name: true
          description: true
          companyId: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
