#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: companyAdminsList_screen
  screens: &companyAdmins_screensLink 
    companyAdminsList_screen: &companyAdminsList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *CompanyAdmins
      class: ui-silk-user-gray
      title: _("List of %s %2s", ngettext('Company admin', 'Company admins', 0), "[format| (%parent%)]")
      fields: &companyAdmins_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            companyAdminsEdit_screen: true
          dialogs: 
            companyAdminsDel_dialog: true
          default: companyAdminsEdit_screen
      options: 
        title: _("Options")
        screens: 
          companyAdminsNew_screen: true
        dialogs: 
          companyAdminsDel_dialog: true
    companyAdminsNew_screen: &companyAdminsNew_screenLink 
      <<: *CompanyAdmins
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Company admin', 'Company admins', 1), "[format| (%parent%)]")
      shortcutOption: N
    companyAdminsEdit_screen: &companyAdminsEdit_screenLink 
      <<: *CompanyAdmins
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Company admin', 'Company admins', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Company admin', 'Company admins', 1), "[format| (%item%)]")
  dialogs: &companyAdmins_dialogsLink 
    companyAdminsDel_dialog: &companyAdminsDel_dialogLink 
      <<: *CompanyAdmins
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Company admin', 'Company admins', 1))
      description: _("Do you want to delete this %s?", ngettext('Company admin', 'Company admins', 1))
      message: _("%s successfully deleted.", ngettext('Company admin', 'Company admins', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
