#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: dDIsList_screen
  screens: &dDIs_screenLink
    dDIsList_screen: &dDIsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *DDIs
      title: _("List of %s %2s", ngettext('DDI', 'DDIs', 0), "[format| (%parent%)]")
      class: ui-silk-lightning-go
      forcedValues:
        <<: *forcedCompany
      order:
        field:
          - DDI asc
          - routeType desc
      fields:
        order: &dDIsFieldsOder_Link
          countryId: true
          DDI: true
          externalCallFilterId: true
          routeType: true
          target: true
        options:
          title: _("Options")
          screens:
            dDIsEdit_screen: ${auth.isNotCompanyOperator}
            dDIsEditLimited_screen: ${auth.isCompanyOperator}
          dialogs:
            dDIsDel_dialog: ${auth.isNotCompanyOperator}
          default: dDIsEdit_screen
        blacklist:
          userId: true
          faxId: true
          IVRCommonId: true
          IVRCustomId: true
          huntGroupId: true
          conferenceRoomId: true
          friendValue: true
          DDIE164: true
          brandId: true
          recordCalls: true
          displayName: true
          billInboundCalls: true
          peeringContractId: ${auth.isCompanyOperator}
          languageId: true
          queueId: true
          retailAccountId: true
          conditionalRouteId: true
      fixedPositions: &dDIsFixedPositions_Link
        group0:
          label: _("Number data")
          colsPerRow: 3
          fields:
            countryId: 1
            DDI: 1
            peeringContractId: 1
            displayName: 2
            languageId: 1
        group1:
          label: _("Filters data")
          colsPerRow: 2
          fields:
            externalCallFilterId: 2
        group2:
          label: _("Recording data")
          colsPerRow: 12
          fields:
            recordCalls: 8
        group3:
          label: _("Routing configuration")
          colsPerRow: 3
          fields:
            routeType: 1
            userId: 1
            faxId: 1
            IVRCommonId: 1
            IVRCustomId: 1
            huntGroupId: 1
            conferenceRoomId: 1
            friendValue: 1
            queueId: 1
            retailAccountId: 1
            conditionalRouteId: 1
        group4:
          label: _("Additional configuration")
          colsPerRow: 12
          fields:
            billInboundCalls: 8
      options:
        title: _("Options")
        screens:
          dDIsNew_screen: ${auth.isNotCompanyOperator}
        dialogs:
          dDIsDel_dialog: ${auth.isNotCompanyOperator}
          importDDIs_dialog: false
    dDIsNew_screen: &dDIsNew_screenLink
      <<: *DDIs
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      defaultValues:
        countryId: ${auth.companyCountryId}
      forcedValues:
        <<: *forcedBrand
        <<: *forcedCompany
      title: _("Add %s", ngettext('DDI', 'DDIs', 1))
      fields:
        order:
          <<: *dDIsFieldsOder_Link
        blacklist:
          brandId: true
          target: true
          DDIE164: true
          recordCalls: ${auth.company.recordings.disabled}
      fixedPositions:
        <<: *dDIsFixedPositions_Link
    dDIsEdit_screen: &dDIsEdit_screenLink
      <<: *DDIs
      controller: edit
      class: ui-silk-pencil
      label: false
      forcedValues:
        <<: *forcedBrand
        <<: *forcedCompany
      title: _("Edit %s %2s", ngettext('DDI', 'DDIs', 1), "[format| (%item%)]")
      fields:
        order:
          <<: *dDIsFieldsOder_Link
        blacklist:
          target: true
          DDIE164: true
          brandId: true
          recordCalls: ${auth.company.recordings.disabled}
          billInboundCalls: ${auth.brand.billing.disabled}
      fixedPositions:
        <<: *dDIsFixedPositions_Link
    dDIsEditLimited_screen: &dDIsEdit_screenLink
      <<: *DDIs
      controller: edit
      class: ui-silk-pencil
      label: false
      forcedValues:
        <<: *forcedCompany
      title: _("Edit %s %2s", ngettext('DDI', 'DDIs', 1), "[format| (%item%)]")
      fields:
        order:
          <<: *dDIsFieldsOder_Link
        blacklist:
          target: true
          DDIE164: true
          peeringContractId: true
          brandId: true
          billInboundCalls: true
          recordCalls: ${auth.company.recordings.disabled}
        readOnly:
          DDI: true
          countryId: true
      fixedPositions:
        <<: *dDIsFixedPositions_Link
  dialogs: &dDIs_dialogsLink
    dDIsDel_dialog: &dDIsDel_dialogLink
      <<: *DDIs
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('DDI', 'DDIs', 1))
      description: _("Do you want to delete this %s?", ngettext('DDI', 'DDIs', 1))
      message: _("%s successfully deleted.", ngettext('DDI', 'DDIs', 1))
      multiItem: 1
      labelOnList: 1

    importDDIs_dialog:
      <<: *DDIs
      module: default
      title: _("Import %s", ngettext('DDI', 'DDIs', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-file
      action: import
      class:  ui-silk-page-gear
      freeUploadCommand: importDDIsFreeUpload_command
      delimiter: ";"
      enclosure: '"'
      escape: "\\"
      forcedValues:
        companyId: ${auth.companyId}
        brandId: ${auth.brandId}

  commands:
    importDDIsFreeUpload_command:
      <<: *DDIs
      controller: File
      action: free-upload

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
