#Entry point para el JS custom de selector de empresas para Usuario EKTAdmin
production:
  main:
    module: klearMatrix
    defaultCommand: initialData_command
    
  commands:
    searchEntity_command:
      module: default
      controller: klear-custom-extra-auth
      action: search

    initialData_command:
      module: default
      controller: klear-custom-extra-auth
      action: initial-data
      
    setData_command:
      module: default
      controller: klear-custom-extra-auth
      action: set-data


staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
