#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: faxesInOutList_screen
  screens: &faxesInOut_screensLink 
    faxesInOutList_screen: &faxesInOutList_screenLink 
      controller: list
      autoRefresh: true
      autoRefresh: 15
      pagination: 
        items: 25
      <<: *FaxesInOut
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Faxes in out', 'Faxes in out(s)', 0), "[format| (%parent%)]")
      fields: &faxesInOut_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            faxesInOutEdit_screen: true
          dialogs: 
            faxesInOutDel_dialog: true
          default: faxesInOutEdit_screen
      options: 
        title: _("Options")
        screens: 
          faxesInOutNew_screen: true
        dialogs: 
          faxesInOutDel_dialog: true
    faxesInOutNew_screen: &faxesInOutNew_screenLink 
      <<: *FaxesInOut
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Send new %s", ngettext('Fax in out', 'Faxes in', 1), "[format| (%parent%)]")
      shortcutOption: N
    faxesInOutEdit_screen: &faxesInOutEdit_screenLink 
      <<: *FaxesInOut
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Fax in out', 'Faxes in out', 1), "[format| (%item%)]")
  dialogs: &faxesInOut_dialogsLink 
    faxesInOutDel_dialog: &faxesInOutDel_dialogLink 
      <<: *FaxesInOut
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Fax in out', 'Faxes in out', 1))
      description: _("Do you want to delete this %s?", ngettext('Faxes in out', 'Faxes in out(s)', 1))
      message: _("%s successfully deleted.", ngettext('Faxes in out', 'Faxes in out(s)', 1))
      multiItem: 1
      labelOnList: 1
  commands: &faxesInOut_commandsLink 
    faxesInOutFileDownload_command: &faxesInOutFileDownload_commandLink 
      <<: *FaxesInOut
      controller: File
      action: force-download
      mainColumn: file
    faxesInOutFileUpload_command: &faxesInOutFileUpload_commandLink 
      <<: *FaxesInOut
      controller: File
      action: upload
      mainColumn: file
    faxesInOutFilePreview_command: &faxesInOutFilePreview_commandLink 
      <<: *FaxesInOut
      controller: File
      action: preview
      mainColumn: file
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
