#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: iVRCustomEntriesList_screen
  screens: &iVRCustomEntries_screensLink
    iVRCustomEntriesList_screen: &iVRCustomEntriesList_screenLink
      controller: list
      class: ui-silk-chart-organisation-add
      pagination:
        items: 25
      <<: *IVRCustomEntries
      title: _("List of %s %2s", ngettext('I v r custom entry', 'I v r custom entries', 0), "[format| (%parent%)]")
      fields:
        order:
          entry: true
          welcomeLocutionId: true
          targetType: true
          target: true
        blacklist:
          targetNumberValue: true
          targetExtensionId: true
          targetVoiceMailUserId: true
          targetConditionalRouteId: true
        options:
          title: _("Options")
          screens:
            iVRCustomEntriesEdit_screen: true
          dialogs:
            iVRCustomEntriesDel_dialog: true
          default: iVRCustomEntriesEdit_screen
      options:
        title: _("Options")
        screens:
          iVRCustomEntriesNew_screen: true
        dialogs:
          iVRCustomEntriesDel_dialog: true
    iVRCustomEntriesNew_screen: &iVRCustomEntriesNew_screenLink
      <<: *IVRCustomEntries
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('I v r custom entry', 'I v r custom entries', 1))
      shortcutOption: N
      fields:
        blacklist:
          target: true
      fixedPositions: &IVRCustomEntriesFixedPositions_link
        group0:
          label: _("Entry information")
          colsPerRow: 8
          fields:
            entry: 4
            welcomeLocutionId: 4
        group1:
          label: _("Routing configuration")
          colsPerRow: 8
          fields:
            targetType: 4
            targetNumberValue: 4
            targetExtensionId: 4
            targetVoiceMailUserId: 5
            targetConditionalRouteId: 5

    iVRCustomEntriesEdit_screen: &iVRCustomEntriesEdit_screenLink
      <<: *IVRCustomEntries
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('I v r custom entry', 'I v r custom entries', 1), "[format| (%item%)]")
      fields:
        blacklist:
          target: true
      fixedPositions:
        <<: *IVRCustomEntriesFixedPositions_link
  dialogs: &iVRCustomEntries_dialogsLink
    iVRCustomEntriesDel_dialog: &iVRCustomEntriesDel_dialogLink
      <<: *IVRCustomEntries
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('I v r custom entry', 'I v r custom entries', 1))
      description: _("Do you want to delete this %s?", ngettext('I v r custom entry', 'I v r custom entries', 1))
      message: _("%s successfully deleted.", ngettext('I v r custom entry', 'I v r custom entries', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
