#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: kamTrunksUacregList_screen
  screens: 
    kamTrunksUacregList_screen: &kamTrunksUacregList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *KamTrunksUacreg
      class: ui-silk-server-link
      title: _("List of %s %2s", ngettext('Kam trunks uacreg', 'Kam trunks uacreg(s)', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        blacklist:
          l_username: true 
          l_domain: true 
          realm: true 
          expires: true 
          auth_username: true
          auth_password: true
          auth_proxy: true
          flags: true
          reg_delay: true
        order:
          l_uuid: true
          r_username: true
          r_domain: true
        options: 
          title: _("Options")
          screens: 
            kamTrunksUacregEdit_screen: true
          dialogs: 
            kamTrunksUacregDel_dialog: true
          default: kamTrunksUacregEdit_screen
      fixedPositions: &kamTrunksUacregFixedPositions_link
        group0:
          label: _("Main Settings")
          colsPerRow: 12
          fields:
            r_username: 5
            r_domain: 5
            auth_password: 12
            l_uuid: 12
        group1:
          label: _("Optional Settings")
          colsPerRow: 12
          fields:
            auth_username: 5
            auth_proxy: 5
            realm: 6
            expires: 6
      options: 
        title: _("Options")
        screens: 
          kamTrunksUacregNew_screen: true
        dialogs: 
          kamTrunksUacregDel_dialog: true
    kamTrunksUacregNew_screen: &kamTrunksUacregNew_screenLink 
      <<: *KamTrunksUacreg
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Kam trunks uacreg', 'Kam trunks uacreg(s)', 1))
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fields:
        blacklist:
          l_username: true 
          l_domain: true 
          flags: true
          reg_delay: true
        order:
          r_username: true
          l_uuid: true
          r_domain: true
          auth_password: true
          auth_username: true
          auth_proxy: true
          realm: true 
          expires: true 
      fixedPositions:
        <<: *kamTrunksUacregFixedPositions_link
    kamTrunksUacregEdit_screen: &kamTrunksUacregEdit_screenLink 
      <<: *KamTrunksUacreg
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Kam trunks uacreg', 'Kam trunks uacreg(s)', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        blacklist:
          l_username: true 
          l_domain: true 
          flags: true
          reg_delay: true
        order:
          r_username: true
          l_uuid: true
          r_domain: true
          auth_password: true
          auth_username: true
          auth_proxy: true
          realm: true 
          expires: true 
      fixedPositions:
        <<: *kamTrunksUacregFixedPositions_link
  dialogs: &kamTrunksUacreg_dialogsLink 
    kamTrunksUacregDel_dialog: &kamTrunksUacregDel_dialogLink 
      <<: *KamTrunksUacreg
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Kam trunks uacreg', 'Kam trunks uacreg(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Kam trunks uacreg', 'Kam trunks uacreg(s)', 1))
      message: _("%s successfully deleted.", ngettext('Kam trunks uacreg', 'Kam trunks uacreg(s)', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
