#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: klearUsersList_screen
  screens: 
    klearUsersList_screen: &klearUsersList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *KlearUsers
      title: _("List of %s %2s", ngettext('Klear user', 'Klear users', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            klearUsersEdit_screen: true
          dialogs: 
            klearUsersDel_dialog: true
          default: klearUsersEdit_screen
      options: 
        title: _("Options")
        screens: 
          klearUsersNew_screen: true
        dialogs: 
          klearUsersDel_dialog: true
    klearUsersNew_screen: &klearUsersNew_screenLink 
      <<: *KlearUsers
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Klear user', 'Klear users', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          createdOn: true
    klearUsersEdit_screen: &klearUsersEdit_screenLink 
      <<: *KlearUsers
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Klear user', 'Klear users', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          createdOn: true
  dialogs: 
    klearUsersDel_dialog: &klearUsersDel_dialogLink 
      <<: *KlearUsers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Klear user', 'Klear users', 1))
      description: _("Do you want to delete this %s?", ngettext('Klear user', 'Klear users', 1))
      message: _("%s successfully deleted.", ngettext('Klear user', 'Klear users', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
