#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include OutgoingDDIRulesPatternsList.yaml


production:
  main:
    module: klearMatrix
    defaultScreen: outgoingDDIRulesList_screen
  screens: &outgoingDDIRules_screensLink
    outgoingDDIRulesList_screen: &outgoingDDIRulesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *OutgoingDDIRules
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Outgoing DDI Rule', 'Outgoing DDI Rules', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields: &outgoingDDIRules_fieldsLink
        blacklist:
          forcedDDIId: true
        order:
          name: true
          defaultAction: true
          forcedDDI: true
        options:
          title: _("Options")
          screens:
            outgoingDDIRulesEdit_screen: true
            outgoingDDIRulesPatternsList_screen: true
          dialogs:
            outgoingDDIRulesDel_dialog: true
          default: outgoingDDIRulesEdit_screen
      options:
        title: _("Options")
        screens:
          outgoingDDIRulesNew_screen: true
        dialogs:
          outgoingDDIRulesDel_dialog: true

    outgoingDDIRulesNew_screen: &outgoingDDIRulesNew_screenLink
      <<: *OutgoingDDIRules
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Outgoing DDI Rule', 'Outgoing DDI Rules', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          forcedDDI: true
      fixedPositions: &outgoingDDIRulesPositions_link
        group0:
          label: _("Basic data")
          colsPerRow: 12
          fields:
            name: 9
        group1:
          label: _("Action Configuration")
          colsPerRow: 12
          fields:
            defaultAction: 6
            forcedDDIId: 6
      shortcutOption: N

    outgoingDDIRulesEdit_screen: &outgoingDDIRulesEdit_screenLink
      <<: *OutgoingDDIRules
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Outgoing DDI Rule', 'Outgoing DDI Rules', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Outgoing DDI Rule', 'Outgoing DDI Rules', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          forcedDDI: true
      fixedPositions:
        <<: *outgoingDDIRulesPositions_link

    #outgoingDDIRulesPatterns:
    <<: *outgoingDDIRulesPatterns_screensLink
    outgoingDDIRulesPatternsList_screen:
      <<: *outgoingDDIRulesPatternsList_screenLink
      filterField: outgoingDDIRuleId
      parentOptionCustomizer:
        - recordCount
    outgoingDDIRulesPatternsNew_screen:
      <<: *outgoingDDIRulesPatternsNew_screenLink
      filterField: outgoingDDIRuleId
    outgoingDDIRulesPatternsEdit_screen:
      <<: *outgoingDDIRulesPatternsEdit_screenLink
      filterField: outgoingDDIRuleId

  dialogs: &outgoingDDIRules_dialogsLink
    outgoingDDIRulesDel_dialog: &outgoingDDIRulesDel_dialogLink
      <<: *OutgoingDDIRules
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Outgoing DDI Rule', 'Outgoing DDI Rules', 1))
      description: _("Do you want to delete this %s?", ngettext('Outgoing DDI Rule', 'Outgoing DDI Rules', 1))
      message: _("%s successfully deleted.", ngettext('Outgoing DDI Rule', 'Outgoing DDI Rules', 1))
      multiItem: 1
      labelOnList: 1

  # outgoingDDIRulesPatterns dialogs:
    <<: *outgoingDDIRulesPatterns_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
