#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production:
  main:
    module: klearMatrix
    defaultScreen: parsedCDRsList_screen
  screens: &parsedCDRs_screensLink
    parsedCDRsList_screen: &parsedCDRsList_screenLink
      controller: list
      csv: false
      order:
        field:
          - calldate
        type: desc
      pagination:
        items: 50
      <<: *ParsedCDRsGod
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Call registry', 'Call registries', 0), "[format| (%parent%)]")
      fields: &parsedCDRs_fieldsLink
        options:
          title: _("Options")
          screens:
            parsedCDRsView_screen: true
          default: parsedCDRsView_screen
        blacklist: &parsedCDRs_blacklistLink
          statId: true
          xstatId: true
          statType: true
          initialLeg: true
          initialLegHash: true
          cid: true
          cidHash: true
          xcid: true
          xcidHash: true
          proxies: true
          peeringContractId: true
          caller: true
          callee: true
          xCaller: true
          xCallee: true
          initialReferrer: true
          referrer: true
          referee: true
          lastForwarder: true
        order: &parsedCDRs_orderLink
          calldate: true
          brandId: true
          companyId: true
          type: tru
          subtype: true
          aParty: true
          bParty: true
          duration: true
    parsedCDRsView_screen: &parsedCDRsView_screenLink
      <<: *ParsedCDRsGod
      controller: edit
      class: ui-silk-eye
      label: false
      disableSave: true
      labelOnPostAction: _("View %s %2s", ngettext('Call registry', 'Call registries', 1), "[format| (%item%)]")
      title: _("View %s %2s", ngettext('Call registry', 'Call registries', 1), "[format| (%item%)]")
      fields:
        order:
          calldate: 1
          duration: 1
          brandId: 1
          companyId: 1
          statId: 1
          xstatId: 1
          proxies: 1
          type: 1
          subtype: 1
          aParty: 1
          bParty: 1
          caller: 1
          callee: 1
          xCaller: 1
          xCallee: 1
          statType: 1
          initialReferrer: 1
          referrer: 1
          referee: 1
          lastForwarder: 1
          initialLeg: 1
          initialLegHash: 1
          cid: 1
          cidHash: 1
          xcid: 1
          xcidHash: 1
          peeringContractId: 1
      fixedPositions:
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            calldate: 8
            duration: 4
            brandId: 12
            companyId: 12
        group1:
          label: _("Stat")
          colsPerRow: 12
          fields:
            statId: 6
            xstatId: 6
        group2:
          label: _("Type of call")
          colsPerRow: 12
          fields:
            proxies: 4
            type: 4
            subtype: 4
        group3:
          label: _("Call parties")
          colsPerRow: 12
          fields:
            aParty: 6
            bParty: 6
            caller: 3
            callee: 3
            xCaller: 3
            xCallee: 3
        group4:
          label: _("Refer information")
          colsPerRow: 12
          fields:
            initialReferrer: 4
            referrer: 4
            referee: 4
        group5:
          label: _("Forwarding information")
          colsPerRow: 1
          fields:
            lastForwarder: 1
        group6:
          label: _("Additional information")
          colsPerRow: 12
          fields:
            initialLeg: 8
            initialLegHash: 4
            cid: 8
            cidHash: 4
            xcid: 8
            xcidHash: 4
            peeringContractId: 8
            statType: 4
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
