#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include PeerServesRelNumericTransformRulesList.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: peerServersList_screen
  screens: &peerServers_screensLink
    peerServersList_screen: &peerServersList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *PeerServers
      class: ui-silk-server
      forcedValues:
        <<: *forcedBrand
      title: _("List of %s %2s", ngettext('Peer server', 'Peer servers', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            peerServersEdit_screen: true
          dialogs: 
            peerServersDel_dialog: true
          default: peerServersEdit_screen
        blacklist:
          domain: true
          params: true
          transport: true
          uri_scheme: true
          auth_needed: true
          auth_user: true
          auth_password: true
          sendPAI: true
          sendRPID: true
          strip: true
          prefix: true
          hostname: true
          ip: true
          port: true
          from_user: true
          from_domain: true
        order:
          sip_proxy: true
          outbound_proxy: true
      options: 
        title: _("Options")
        screens: 
          peerServersNew_screen: true
        dialogs: 
          peerServersDel_dialog: true
    peerServersNew_screen: &peerServersNew_screenLink 
      <<: *PeerServers
      forcedValues:
        <<: *forcedBrand
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Peer server', 'Peer servers', 1))
      shortcutOption: N
      fields:
        blacklist:
          ip: true
          hostname: true
          port: true
          strip: true
        order: &peerServersOrder_Link
          sip_proxy: true
          auth_needed: true
          sendPAI: true
          prefix: true
      fixedPositions: &peerServersFixedPositions_Link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            sip_proxy: 4
            outbound_proxy: 4
            uri_scheme: 2
            transport: 2
        group1:
          label: _("Authentication Settings")
          colsPerRow: 12
          fields:
            auth_needed: 4
            auth_user: 4
            auth_password: 4
        group2:
          label: _("Source number header")
          colsPerRow: 2
          fields:
            sendPAI: 1
            sendRPID: 1
        group3:
          label: _("R-URI customization (after numeric transformations)")
          colsPerRow: 12
          fields:
            prefix: 4 
            params: 6
        group4:
          label: _("From optional customization")
          colsPerRow: 12
          fields:
            from_user: 6
            from_domain: 6
    peerServersEdit_screen: &peerServersEdit_screenLink
      <<: *PeerServers
      forcedValues:
        <<: *forcedBrand
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Peer server', 'Peer servers', 1), "[format| (%item%)]")
      fields:
        blacklist:
          ip: true
          hostname: true
          port: true
          strip: true
        order:
          <<: *peerServersOrder_Link
      fixedPositions:
        <<: *peerServersFixedPositions_Link
      
  dialogs: &peerServers_dialogsLink
    peerServersDel_dialog: &peerServersDel_dialogLink 
      <<: *PeerServers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Peer server', 'Peer servers', 1))
      description: _("Do you want to delete this %s?", ngettext('Peer server', 'Peer servers', 1))
      message: _("%s successfully deleted.", ngettext('Peer server', 'Peer servers', 1))
      multiItem: 1
      labelOnList: 1
      
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
