#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include PricingPlansRelTargetPatternsList.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: pricingPlansRelCompaniesList_screen
  screens: &pricingPlansRelCompanies_screensLink 
    pricingPlansRelCompaniesList_screen: &pricingPlansRelCompaniesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *PricingPlansRelCompanies
      class: ui-silk-money
      title: _("List of %s %2s", ngettext('Pricing plan', 'Pricing plans', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      order:
        field:
          - metric asc
      fields: &pricingPlansRelCompanies_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            pricingPlansRelCompaniesEdit_screen: true
            pricingPlansRelTargetPatternsList_screen: true
          dialogs: 
            pricingPlansRelCompaniesDel_dialog: true
          default: pricingPlansRelCompaniesEdit_screen
      options: 
        title: _("Options")
        screens: 
          pricingPlansRelCompaniesNew_screen: true
        dialogs: 
          comparePlans_dialog: true
          pricingPlansRelCompaniesDel_dialog: true
      info:
        type: box
        position: left
        icon: help
        text: _("<p><b>Metric:</b> In case that two pricing plans were matched plan with lower metric will be applied.</p>")
        label: _("Help")
    pricingPlansRelCompaniesNew_screen: &pricingPlansRelCompaniesNew_screenLink 
      <<: *PricingPlansRelCompanies
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Pricing plan', 'Pricing plans', 1), "[format| (%parent%)]")
      shortcutOption: N
      forcedValues:
        <<: *forcedBrand
      fixedPositions: &pricingPlansRelCompaniesFixedPositions_Link
        group0:
          colsPerRow: 3
          fields:
            pricingPlanId: 2
            metric: 1
        group1:
          colsPerRow: 2
          fields:
            validFrom: 1
            validTo: 1
    pricingPlansRelCompaniesEdit_screen: &pricingPlansRelCompaniesEdit_screenLink 
      <<: *PricingPlansRelCompanies
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Pricing plan', 'Pricing plans', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fixedPositions:
        <<: *pricingPlansRelCompaniesFixedPositions_Link
        
    #pricingPlansRelTargetPatterns: 
    pricingPlansRelTargetPatternsList_screen: &pricingPlansRelTargetPatternsListEdit_screenLink 
      <<: *pricingPlansRelTargetPatternsList_screenLink
      title: _("List of %s", ngettext('price', 'prices', 0))
      filterClass: IvozProvider_Klear_Filter_CompanyPricingPlansPrices
      parentOptionCustomizer: 
        - recordCount
      fields:
        order:
          targetPatternId: true
        blacklist:
          pricingPlanId: true
      options: 
  dialogs: &pricingPlansRelCompanies_dialogsLink 
    pricingPlansRelCompaniesDel_dialog: &pricingPlansRelCompaniesDel_dialogLink 
      <<: *PricingPlansRelCompanies
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s de %2s", ngettext('Pricing plan', 'Pricing plans', 1), "[format| (%parent%)]")
      description: _("Do you want to delete this %s %2s?", ngettext('Pricing plan', 'Pricing plans', 1), "[format| (%parent%)]")
      message: _("%s successfully deleted.", ngettext('Pricing plan', 'Pricing plans', 1))
      multiItem: 1
      labelOnList: 1
    comparePlans_dialog: 
      <<: *PricingPlans
      module: default
      title: _("Simulate a call")
      label: false
      labelOnEdit: false   
      labelOnList: true
      labelOption: false
      labelOnEntityPostSave: false
      controller: klear-custom-tarificator
      action: test-company-plans
      class:  ui-silk-telephone
  commands: &pricingPlansRelCompanies_commandsLink
    <<: *pricingPlansRelTargetPatterns_commandsLink

staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
