#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: proxyTrunksList_screen
  screens: 
    proxyTrunksList_screen: &proxyTrunksList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *ProxyTrunks
      title: _("List of %s %2s", ngettext('Proxy Trunks', 'Proxies Trunks', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            proxyTrunksEdit_screen: true
          default: proxyTrunksEdit_screen
    proxyTrunksEdit_screen: &proxyTrunksEdit_screenLink 
      <<: *ProxyTrunks
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Proxy Trunks', 'Proxies Trunks', 1), "[format| (%item%)]")
      fixedPositions:
        group0:
          label: _("Basic Configuration")
          colsPerRow: 3
          fields:
            name: 1
            ip: 1
      fields:
        readOnly:
          name: true
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
