#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include CallForwardSettingsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: retailAccountsList_screen
  screens: &retailAccounts_screensLink
    retailAccountsList_screen: &retailAccountsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *RetailAccounts
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Retail Account', 'Retail Accounts', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
        <<: *forcedBrand
      fields:
        blacklist: &retailAccounts_blacklistLink
          transport: true
          auth_needed: true
          password: true
          areaCode: true
          countryId: true
          allow: true
          disallow: true
          direct_media_method: true
          update_callerid: true
          from_domain: true
          callerid_update_header: true
          directConnectivity: true
          ip: true
          port: true
          languageId: true
          status: true
        order:
          name: true
          domain: true
          description: true
          outgoingDDIId: true
          statusIcon: true
        options:
          title: _("Options")
          screens:
            retailAccountsEdit_screen: ${auth.canSeeBrand}
            callForwardSettingsList_screen: true
          dialogs:
            retailAccountsDel_dialog: ${auth.canSeeBrand}
          default: retailAccountsEdit_screen
      options:
        title: _("Options")
        screens:
          retailAccountsNew_screen: ${auth.canSeeBrand}
        dialogs:
          retailAccountsDel_dialog: ${auth.canSeeBrand}
    retailAccountsNew_screen: &retailAccountsNew_screenLink
      <<: *RetailAccounts
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Retail Account', 'Retail Accounts', 1), "[format| (%parent%)]")
      scripts:
        module: default
        name: jquery.passwordgennew.js
      plugin: passwordgennew
      forcedValues:
        <<: *forcedCompany
        <<: *forcedBrand
      fields:
        blacklist:
          domain: true
          direct_media_method: true
          update_callerid: true
          callerid_update_header: true
          auth_needed: true
          disallow: true
          outgoingDDIId: true
          callACLId: true
          countryId: true
          areaCode: true
          allow: true
          from_domain: true
          languageId: true
          status: true
          statusIcon: true
        order: &retailAccounts_orderLink
          name: true
          description: true
          priority: true
          password: true
          directConnectivity: true
          transport: true
          ip: true
          port: true
          callACLId: true
          outgoingDDIId: true
          countryId: true
          areaCode: true
          allow: true
          from_domain: true
          languageId: true
          statusIcon: true
          status: true
      fixedPositions: &retailAccounts_FixedPositionsLink
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            name: 4
            description: 6
            priority: 2
            password: 5
            directConnectivity: 3
            __empty1: 4
            transport: 4
            ip: 5
            port: 3
        group1:
          label: _("Outgoing Configuration")
          colsPerRow: 12
          fields:
            callACLId: 5
            outgoingDDIId: 5
            countryId: 5
            areaCode: 5
        group2:
          label: _("Advanced Configuration")
          colsPerRow: 6
          fields:
            allow: 2
            from_domain: 2
            languageId: 2
        group3:
          label: _("Status information")
          colsPerRow: 6
          fields:
            statusIcon: 6
            status: 6

      shortcutOption: N
    retailAccountsEdit_screen: &retailAccountsEdit_screenLink
      <<: *RetailAccounts
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Retail Account', 'Retail Accounts', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Retail Account', 'Retail Accounts', 1), "[format| (%item%)]")
      scripts:
        module: default
        name: jquery.passwordgenedit.js
      plugin: passwordgen
      fields:
        order:
          <<: *retailAccounts_orderLink
        blacklist:
          domain: true
          direct_media_method: true
          update_callerid: true
          callerid_update_header: true
          auth_needed: true
          disallow: true
          statusIcon: true
      fixedPositions:
          <<: *retailAccounts_FixedPositionsLink
      forcedValues:
        <<: *forcedCompany
        <<: *forcedBrand

    #callForwardSettings:
    <<: *callForwardSettings_screensLink
    callForwardSettingsList_screen:
      <<: *callForwardSettingsList_screenLink
      filterField: retailAccountId
      parentOptionCustomizer:
        - recordCount
      forcedValues:
        callTypeFilter: both
    callForwardSettingsNew_screen:
      <<: *callForwardSettingsNew_screenLink
      filterField: retailAccountId
      forcedValues:
        callTypeFilter: both
    callForwardSettingsEdit_screen:
      <<: *callForwardSettingsEdit_screenLink
      filterField: retailAccountId
      forcedValues:
        callTypeFilter: both

  dialogs: &retailAccounts_dialogsLink
    retailAccountsDel_dialog: &retailAccountsDel_dialogLink
      <<: *RetailAccounts
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Retail Account', 'Retail Accounts', 1))
      description: _("Do you want to delete this %s?", ngettext('Retail Account', 'Retail Accounts', 1))
      message: _("%s successfully deleted.", ngettext('Retail Account', 'Retail Accounts', 1))
      multiItem: 1
      labelOnList: 1

    # callForwardSettings dialogs:
    <<: *callForwardSettings_dialogsLink

  commands:
    generatePassword_command:
      <<: *RetailAccounts
      title: "Generate new secure password"
      class: ui-silk-arrow-refresh
      module: default
      controller: Password
      action: generate

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
