#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include CompaniesList.yaml
#include FaxesList.yaml
#include FriendsList.yaml
#include RetailAccountsList.yaml
#include UsersList.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: dDIsList_screen
  screens: &dDIs_screensLink 
    dDIsList_screen: &dDIsList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *DDIs
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Ddi', 'Ddis', 0), "[format| (%parent%)]")
      fields: &dDIs_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            dDIsEdit_screen: true
            companiesList_screen: true
            faxesList_screen: true
            friendsList_screen: true
            retailAccountsList_screen: true
            usersList_screen: true
          dialogs: 
            dDIsDel_dialog: true
          default: dDIsEdit_screen
      options: 
        title: _("Options")
        screens: 
          dDIsNew_screen: true
        dialogs: 
          dDIsDel_dialog: true
    dDIsNew_screen: &dDIsNew_screenLink 
      <<: *DDIs
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Ddi', 'Ddis', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          dDIsEdit_screen: true
    dDIsEdit_screen: &dDIsEdit_screenLink 
      <<: *DDIs
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Ddi', 'Ddis', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Ddi', 'Ddis', 1), "[format| (%item%)]")
    #companies: 
    <<: *companies_screensLink
    companiesList_screen: 
      <<: *companiesList_screenLink
      filterField: outgoingDDIId
      parentOptionCustomizer: 
        - recordCount
    companiesNew_screen: 
      <<: *companiesNew_screenLink
      filterField: outgoingDDIId
    companiesEdit_screen: 
      <<: *companiesEdit_screenLink
      filterField: outgoingDDIId

    #faxes: 
    faxesList_screen: 
      <<: *faxesList_screenLink
      filterField: outgoingDDIId
      parentOptionCustomizer: 
        - recordCount
    faxesNew_screen: 
      <<: *faxesNew_screenLink
      filterField: outgoingDDIId
    faxesEdit_screen: 
      <<: *faxesEdit_screenLink
      filterField: outgoingDDIId

    #friends: 
    friendsList_screen: 
      <<: *friendsList_screenLink
      filterField: outgoingDDIId
      parentOptionCustomizer: 
        - recordCount
    friendsNew_screen: 
      <<: *friendsNew_screenLink
      filterField: outgoingDDIId
    friendsEdit_screen: 
      <<: *friendsEdit_screenLink
      filterField: outgoingDDIId

    #retailAccounts: 
    retailAccountsList_screen: 
      <<: *retailAccountsList_screenLink
      filterField: outgoingDDIId
      parentOptionCustomizer: 
        - recordCount
    retailAccountsNew_screen: 
      <<: *retailAccountsNew_screenLink
      filterField: outgoingDDIId
    retailAccountsEdit_screen: 
      <<: *retailAccountsEdit_screenLink
      filterField: outgoingDDIId

    #users: 
    usersList_screen: 
      <<: *usersList_screenLink
      filterField: outgoingDDIId
      parentOptionCustomizer: 
        - recordCount
    usersNew_screen: 
      <<: *usersNew_screenLink
      filterField: outgoingDDIId
    usersEdit_screen: 
      <<: *usersEdit_screenLink
      filterField: outgoingDDIId

  dialogs: &dDIs_dialogsLink 
    dDIsDel_dialog: &dDIsDel_dialogLink 
      <<: *DDIs
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Ddi', 'Ddis', 1))
      description: _("Do you want to delete this %s?", ngettext('Ddi', 'Ddis', 1))
      message: _("%s successfully deleted.", ngettext('Ddi', 'Ddis', 1))
      multiItem: 1
      labelOnList: 1
  # companies dialogs: 
    <<: *companies_dialogsLink
  # faxes dialogs: 
    <<: *faxes_dialogsLink
  # friends dialogs: 
    <<: *friends_dialogsLink
  # retailAccounts dialogs: 
    <<: *retailAccounts_dialogsLink
  # users dialogs: 
    <<: *users_dialogsLink
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
