services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Provider\Domain\Service\Brand\BrandLifecycleServiceCollection:
    public: true

  provider.lifecycle.brand.service_collection: '@Ivoz\Provider\Domain\Service\Brand\BrandLifecycleServiceCollection'

  ##################################
  ## post_persist
  ##################################
  Ivoz\Provider\Domain\Service\Domain\UpdateByBrand:
    tags:
      - { name: provider.lifecycle.brand.post_persist, priority: 10 }
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Ivoz\Provider\Domain\Service\RoutingPattern\UpdateByBrand:
    tags:
      - { name: provider.lifecycle.brand.post_persist, priority: 20 }
    arguments:
      $countryRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\Country\\Country")'
      $routingPatternGroupByRoutingPatternAndCountry:
        '@Ivoz\Provider\Domain\Service\RoutingPatternGroup\UpdateByRoutingPatternAndCountry'
