services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Provider\Domain\Service\Domain\DomainLifecycleServiceCollection:
    public: true

  provider.lifecycle.domain.service_collection:
    '@Ivoz\Provider\Domain\Service\Domain\DomainLifecycleServiceCollection'

  Ivoz\Provider\Infrastructure\Domain\Service\Domain\SendUsersDomainReloadRequest:
    tags:
      ## post_persist
      - { name: provider.lifecycle.domain.post_persist, priority: 10 }
      ## post_remove
      - { name: provider.lifecycle.domain.post_remove, priority: 10 }
    arguments:
      $usersDomainReload:
        '@XmlRpc\XmlRpcUsersRequest::DomainReload'
