services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Provider\Domain\Service\Extension\ExtensionLifecycleServiceCollection:
    public: true

  provider.lifecycle.extension.service_collection:
    '@Ivoz\Provider\Domain\Service\Extension\ExtensionLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Provider\Domain\Service\Extension\SanitizeValues:
    tags:
      - { name: provider.lifecycle.extension.pre_persist, priority: 10}
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  ##################################
  ## post_persist
  ##################################
  Ivoz\Provider\Domain\Service\User\UpdateByExtension:
    tags:
      - { name: provider.lifecycle.extension.post_persist, priority: 10}
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $userRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\User\\User")'