services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Provider\Domain\Service\RoutingPattern\RoutingPatternLifecycleServiceCollection:
    public: true

  provider.lifecycle.routing_pattern.service_collection:
    '@Ivoz\Provider\Domain\Service\RoutingPattern\RoutingPatternLifecycleServiceCollection'

  ##################################
  ## post_persist
  ##################################
  Ivoz\Provider\Domain\Service\LcrRule\UpdateByRoutingPattern:
    tags:
      - { name: provider.lifecycle.routing_pattern.post_persist, priority: 10}
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  ##################################
  ## on_commit
  ##################################
  Ivoz\Provider\Infrastructure\Domain\Service\RoutingPattern\SendTrunksLcrReloadRequest:
    tags:
      - { name: provider.lifecycle.routing_pattern.on_commit, priority: 10 }
    arguments:
      $trunksLcrReload:
        '@XmlRpc\XmlRpcTrunksRequest::DialplanReload'
