production: 
  class: \IvozProvider\Model\BrandURLs
  fields: 
    brandId: 
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Brands
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
    url: 
      title: ngettext('Url', 'Urls', 1)
      type: text
      required: true
      maxLength: 255
    klearTheme: 
      title: ngettext('Klear theme', 'Klear themes', 1)   
      type: select
      defaultValue: redmond
      source:
        data: themes
    userTheme: 
      title: ngettext('User theme', 'User themes', 1)
      type: select
      defaultValue: redmond
      source:
        data: inline
        values:
          default:
            title: Default 
          cerulean:
            title: Cerulean
          cosmo:
            title: Cosmo
          cyborg:
            title: Cyborg
          darkly:
            title: Darkly
          flatly:
            title: Flatly
          fonts:
            title: Fonts
          journal:
            title: Journal
          lumen:
            title: Lumen
          paper:
            title: Paper
          readable:
            title: Readable
          sandstone:
            title: Sandstone
          simplex:
            title: Simplex
          slate:
            title: Slate
          spacelab:
            title: Spacelab
          superhero:
            title: Superhero
          united:
            title: United
          yeti:
            title: Yeti
    urlType: 
      title: _('Url type')
      type: select
      required: true
      source: 
        data: inline
        values: 
          'god':
            title: _('god')
            visualFilter:
              show: ["klearTheme"]
              hide: ["userTheme"]
          'brand':
            title: _('brand')
            visualFilter:
              show: ["klearTheme"]
              hide: ["userTheme"]
          'admin':
            title: _('admin')
            visualFilter:
              show: ["klearTheme"]
              hide: ["userTheme"]
          'user': 
            title: _('user')
            visualFilter:
              show: ["userTheme"]
              hide: ["klearTheme"]
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      default: true
      defaultValue: 
      maxLength: 200
    logo: 
      title: _('Logo')
      type: file
      source: 
        data: fso
        size_limit: 20M
        options:
          hiddenName: true
          download: 
            external: true
            type: command
            target: brandURLsLogoDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          delete:
            type: setNullFso
            icon: ui-silk-bin
            title: _("Delete file")
            onNull: hide
          upload: 
            type: command
            target: brandURLsLogoUpload_command
            title: _("Upload file")
            class: qq-uploader
            onNull: show
          preview: 
            target: brandURLsLogoPreview_command
            type: command
            class: filePreview
            external: 1
            props: 
              width: 150
              height: 150
              crop: false
            onNull: hide
          previewList: 
            target: brandURLsLogoPreview_command
            type: command
            class: filePreview
            listController: 1
            external: 1
            props: 
              width: 30
              height: 30
              crop: false
            onNull: hide
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
