production:
  class: \IvozProvider\Model\ExternalCallFilters
  fields:
    companyId:
      title: _('Company')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Companies
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      default: true
    welcomeLocutionId:
      title: _('Welcome locution')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Locutions
          filterClass: IvozProvider_Klear_Filter_Company          
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    holidayLocutionId:
      title: _('Holiday locution')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Locutions
          filterClass: IvozProvider_Klear_Filter_Company          
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    outOfScheduleLocutionId:
      title: _('Out of schedule locution')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Locutions
          filterClass: IvozProvider_Klear_Filter_Company          
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    holidayTargetType:
      title: _('Holiday target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title: _('Unassigned')
            visualFilter:
              hide: ['holidayNumberValue', 'holidayExtensionId', 'holidayVoiceMailUserId']
          'number':
            title: _('number')
            visualFilter:
              show: ['holidayNumberValue']
              hide: ['holidayExtensionId', 'holidayVoiceMailUserId']
          'extension':
            title: _('extension')
            visualFilter:
              show: ['holidayExtensionId']
              hide: ['holidayNumberValue', 'holidayVoiceMailUserId']
          'voicemail':
            title: _('voicemail')
            visualFilter:
              show: ['holidayVoiceMailUserId']
              hide: ['holidayNumberValue', 'holidayExtensionId']
    holidayNumberValue:
      title: _('Holiday number')
      type: text
      trim: both
      required: true
    holidayExtensionId:
      title: _('Holiday extension')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Extensions
          filterClass: IvozProvider_Klear_Filter_Company          
          fieldName:
            fields:
              - number
            template: '%number%'
          order: number
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    holidayVoiceMailUserId:
      title: _('Holiday voice mail user')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Users
          filterClass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order: name
        'null': _("Unassigned")
    outOfScheduleTargetType:
      title: _('Out of schedule target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title: _('Unassigned')
            visualFilter:
              hide: ['outOfScheduleNumberValue', 'outOfScheduleExtensionId', 'outOfScheduleVoiceMailUserId']
          'number':
            title: _('number')
            visualFilter:
              show: ['outOfScheduleNumberValue']
              hide: ['outOfScheduleExtensionId', 'outOfScheduleVoiceMailUserId']
          'extension':
            title: _('extension')
            visualFilter:
              show: ['outOfScheduleExtensionId']
              hide: ['outOfScheduleNumberValue', 'outOfScheduleVoiceMailUserId']
          'voicemail':
            title: _('voicemail')
            visualFilter:
              show: ['outOfScheduleVoiceMailUserId']
              hide: ['outOfScheduleNumberValue', 'outOfScheduleExtensionId']
    outOfScheduleNumberValue:
      title: _('Out of schedule number')
      type: text
      trim: both
      required: true
    outOfScheduleExtensionId:
      title: _('Out of schedule extension')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Extensions
          filterClass: IvozProvider_Klear_Filter_Company          
          fieldName:
            fields:
              - number
            template: '%number%'
          order: number
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    outOfScheduleVoiceMailUserId:
      title: _('Out of schedule voice mail user')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Users
          filterClass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order: name
        'null': _("Unassigned")
    ExternalCallFilterRelSchedules:
      title: _('Schedules')
      type: multiselect
      source:
        data: mapper
        config:
          relationMapper: \IvozProvider\Mapper\Sql\ExternalCallFilterRelSchedules
          relatedMapperName: \IvozProvider\Mapper\Sql\Schedules
          relatedFieldName: name
          relationProperty: Schedule
          filterClass: IvozProvider_Klear_Filter_Company
    ExternalCallFilterRelCalendars:
      title: _('Caledars')
      type: multiselect
      source:
        data: mapper
        config:
          relationMapper: \IvozProvider\Mapper\Sql\ExternalCallFilterRelCalendars
          relatedMapperName: \IvozProvider\Mapper\Sql\Calendars
          relatedFieldName: name
          relationProperty: Calendar
          filterClass: IvozProvider_Klear_Filter_Company
    holidayTarget:
      title: _('Holiday target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_ExternalCallFiltersTarget
        method: getHolidayData
    outOfScheduleTarget:
      title: _('Out of schedule target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_ExternalCallFiltersTarget
        method: getOutOfScheduleData
    blackListRegExp: 
      title: _('Black list reg exp')
      type: text
      maxLength: 255
      info:
        type: box
        text: _("Incoming numbers that match this expression will be always REJECTED without checking this filter configuration.")
        label: _("Need help?")      
    whiteListRegExp: 
      title: _('White list reg exp')
      type: text
      maxLength: 255
      info:
        type: box
        text: _("Incoming numbers that match this expression will be always ACCEPTED without checking this filter configuration.")
        label: _("Need help?")      
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
