production: 
  class: \IvozProvider\Model\GenericMusicOnHold
  fields: 
    brandId: 
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Brands
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
    originalFile: 
      title: ngettext('File', 'Files', 1)
      type: file
      required: true
      source: 
        data: fso
        size_limit: 20M
        options: 
          download: 
            external: true
            type: command
            target: genericMusicOnHold_FileDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          mediaembed:
            type: command
            title: _("Listen to MoH")
            class: jmedia
            onNull: hide
            target: genericMusicOnHold_FileDownload_command
            
          upload: 
            type: command
            target: genericMusicOnHold_FileUpload_command
            title: _("Upload file")
            class: qq-uploader
            onNull: show
    encodedFile:
      title: ngettext('File', 'Files', 1)
      type: file
      source: 
        data: fso
        size_limit: 20M
        options: 
          download: 
            external: true
            type: command
            target: genericMusicOnHold_FileDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          mediaembed:
            type: command
            title: _("Listen to MoH")
            class: jmedia
            onNull: hide
            target: genericMusicOnHold_FileDownload_command
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
