production:
  class: \IvozProvider\Model\IVRCustom
  fields:
    companyId:
      title: _('Company id')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Companies
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
      default: true
    welcomeLocutionId:
      title: _('Welcome locution id')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Locutions
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
    noAnswerLocutionId:
      title: _('No answer locution id')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Locutions
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    errorLocutionId:
      title: _('Error locution id')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Locutions
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    successLocutionId:
      title: _('Success locution id')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Locutions
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    timeout:
      title: _('Timeout')
      type: number
      defaultValue: 6
      required: true
      source:
        control: spinner
        max: 60
        min: 1
      info:
        type: box
        position: left
        icon: help
        text: _("Time in seconds the IVR will wait after playing the welcome locution or dialing a digit")
        label: _("Need help?")
    maxDigits:
      title: _('Max digits')
      type: number
      required: true
      defaultValue: 0
      source:
        control: Spinner
        min: 0
      info:
        type: box
        position: left
        icon: help
        text: _("Max number of digits the caller can enter. Set to 0 to disable.")
        label: _("Need help?")
    noAnswerTimeout:
      title: _('No aswer timeout')
      type: number
      defaultValue: 10
      source:
        control: Spinner
    timeoutTargetType:
      title: _('Timeout target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title:  _("Unassigned")
            visualFilter:
              hide: ["timeoutNumberValue", "timeoutExtensionId", "timeoutVoiceMailUserId" ]
          'number':
            title: _('number')
            visualFilter:
              show: ["timeoutNumberValue"]
              hide: ["timeoutExtensionId", "timeoutVoiceMailUserId" ]
          'extension':
            title: _('extension')
            visualFilter:
              show: ["timeoutExtensionId"]
              hide: ["timeoutNumberValue", "timeoutVoiceMailUserId" ]
          'voicemail':
            title: _('voicemail')
            visualFilter:
              show: ["timeoutVoiceMailUserId"]
              hide: ["timeoutExtensionId", "timeoutNumberValue"]
    timeoutNumberValue:
      title: _('Timeout number value')
      type: text
      trim: both
      required: true
    timeoutExtensionId:
      title: _('Timeout extension id')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Extensions
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - number
            template: '%number%'
          order: number
        'null': _("Unassigned")
    timeoutVoiceMailUserId:
      title: _('Timeout voice mail user id')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Users
          filterClass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order: name
        'null': _("Unassigned")
    errorTargetType:
      title: _('Error target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title:  _("Unassigned")
            visualFilter:
              hide: ["errorNumberValue", "errorExtensionId", "errorVoiceMailUserId"]
          'number':
            title: _('number')
            visualFilter:
              show: ["errorNumberValue"]
              hide: ["errorExtensionId", "errorVoiceMailUserId" ]
          'extension':
            title: _('extension')
            visualFilter:
              show: ["errorExtensionId"]
              hide: ["errorNumberValue", "errorVoiceMailUserId" ]
          'voicemail':
            title: _('voicemail')
            visualFilter:
              show: ["errorVoiceMailUserId"]
              hide: ["errorExtensionId", "errorNumberValue"]
    errorNumberValue:
      title: _('Error number value')
      type: text
      trim: both
      required: true
    errorExtensionId:
      title: _('Error extension id')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Extensions
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - number
            template: '%number%'
          order: number
        'null': _("Unassigned")
    errorVoiceMailUserId:
      title: _('Error voice mail user id')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Users
          filterClass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order: name
        'null': _("Unassigned")
    timeoutTarget:
      title: _('Timeout target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_IVRCustomTarget
        method: getTimeoutData
    errorTarget:
      title: _('Error target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_IVRCustomTarget
        method: getErrorData
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
