production: 
  class: \IvozProvider\Model\KamTrunksUacreg
  fields: 
    multiDDI: 
      title: _('Multiddi')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
            visualFilter:
              show: ["l_uuid"]
              hide: []
          '1': 
            title: _("Yes")
            visualFilter:
              show: []
              hide: ["l_uuid"]
    l_uuid: 
      title: _('DDI')
      type: text
      trim: both
      defaultValue: 
      default: true
      info:
        type: box
        position: left
        icon: help
        text: _("Is sent in the username of Contact header in generated REGISTER.")
        label: _("Need help?")
      required: true
    l_username: 
      title: _('L username')
      type: text
      trim: both
      defaultValue: 
    l_domain: 
      title: _('L domain')
      type: text
      trim: both
      defaultValue: 
    r_username: 
      title: _('Username')
      type: text
      trim: both
      defaultValue: 
      required: true
    r_domain: 
      title: _('Domain')
      type: text
      trim: both
      defaultValue: 
      required: true
    realm: 
      title: _('Realm')
      type: text
      trim: both
      defaultValue: 
      info:
        type: box
        position: left
        icon: help
        text: _("Dejar vac√≠o para utilizar el propuesto")
        label: _("Need help?")
    auth_username: 
      title: _('Auth username')
      type: text
      trim: both
      defaultValue: 
      required: false
      info:
        type: box
        position: left
        icon: help
        text: _("Solo en caso de ser distinto del Nombre de Usuario")
        label: _("Need help?")
    auth_password: 
      title: _('Password')
      type: password
      defaultValue: 
      adapter: PlainText
      required: true
    auth_proxy: 
      title: _('Registrar Server URI')
      type: text
      trim: both
      defaultValue:
      pattern: "^sip:.*$|^sips:.*$"
      required: false
      info:
        type: box
        position: left
        icon: help
        text: _("Tiene que empezar por sip o sips seguido de dos puntos")
        label: _("Need help?")
    expires: 
      title: _('Expire')
      type: number
      defaultValue: 3600
      source: 
        control: Spinner
      required: true
    brandId: 
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Brands
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
    peeringContractId: 
      title: _('Peering contract id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\PeeringContracts
          fieldName: 
            fields: 
              - description
            template: '%description%'
          order: description
    flags:
      title: _('Flag')
      type: number
      defaultValue: 0
      source:
        control: Spinner
    reg_delay:
      title: _('Reg delay')
      type: number
      defaultValue: 0
      source:
        control: Spinner
    targetDDI:
      title: _('DDI')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_KamTrunksUacRegTargetDDI
        method: getData
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
