production: 
  class: \IvozProvider\Model\PeerServers
  fields: 
    peeringContractId: 
      title: _('Peering contract')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\PeeringContracts
          fieldName: 
            fields: 
              - description
            template: '%description%'
          order: description
      default: true
    ip: 
      title: _('Destination IP address')
      type: text
      pattern: "^[.0-9]+$"
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Leave empty to send to Host field")
        label: _("Need help?")
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      defaultValue: 
      required: true
    description: 
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      trim: both
      defaultValue: 
    brandId: 
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Brands
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
    hostname: 
      title: _('Host')
      type: text
      trim: both
      required: true
      info:
        type: box
        position: left
        icon: help
        text: _("Use address or hostname")
        label: _("Need help?")
    port: 
      title: _('Port')
      type: number
      defaultValue: 5060
      source: 
        control: Spinner
    params: 
      title: _('R-URI params')
      type: text
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Add this params to R-URI (start with ';')")
        label: _("Need help?")
    uri_scheme: 
      title: _('Uri scheme')
      type: select
      defaultValue: 1
      source:
        data: inline
        values: 
          '1':
            title: _("sip")
          '2':
            title: _("sips")
    transport: 
      title: _('Transport')
      type: select
      defaultValue: 1
      source:
        data: inline
        values: 
          '1':
            title: _("udp")
          '2':
            title: _("tcp")
          '3':
            title: _("tls")
    strip: 
      title: _('Strip')
      type: number
      info:
        type: box
        position: left
        icon: help
        text: _("Strip N digits from the beginning of the callee")
        label: _("Need help?")
      source: 
        control: Spinner
    prefix: 
      title: _('Prefix')
      type: text
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Prepend this field to callee (after stripping)")
        label: _("Need help?")
    sendPAI: 
      title: _('Send PAI')
      type: checkbox
    sendRPID: 
      title: _('Send RPID')
      type: checkbox
    useAuthUserAsFromUser: 
      title: _('Set From to auth_user@peerserver_host')
      type: checkbox
    auth_needed:
      title: _('Auth needed')
      type: select
      defaultValue: 'no'
      source:
        data: inline
        values:
          'yes':
            title: _("yes")
            visualFilter:
              show: ["auth_user", "auth_password", "useAuthUserAsFromUser"]
              hide: []
          'no':
            title: _("no")
            visualFilter:
              hide: ["auth_user", "auth_password", "useAuthUserAsFromUser"]
              show: []
    auth_user:
      title: _('Auth user')
      type: text
      trim: both
      required: true
    auth_password:
      title: _('Auth password')
      type: password
      adapter: PlainText
      required: true
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
