production: 
  class: \IvozProvider\Model\PricingPlansRelTargetPatterns
  fields:  
    id: 
      title: ngettext('Id', 'Ids', 1)
      required: false
    connectionCharge: 
      title: _('Connection charge')
      type: text
      pattern: "^[0-9]{1,6}[.]{0,1}[0-9]*$"
      trim: both
      required: true
      default: true
      sufix: "€"
      info:
        type: box
        position: left
        icon: help
        text: _("Use point as decimal delimiter - e.g. 0.02")
        label: _("Need help?")
    periodTime: 
      title: _('Charge period')
      type: number
      defaultValue: 1
      required: true
      source: 
        control: Spinner
        min: 1
        step: 1
      sufix: "s"
    perPeriodCharge: 
      title: _('Per minute charge')
      type: text
      pattern: "^[0-9]{1,6}[.]{0,1}[0-9]*$"
      trim: both
      required: true
      sufix: "€"
      info:
        type: box
        position: left
        icon: help
        text: _("Use point as decimal delimiter - e.g. 0.02")
        label: _("Need help?")
    metric: 
      title: _('Metric')
      type: number
      defaultValue: 10
      source: 
        control: Spinner
      info:
        type: box
        position: left
        icon: help
        text: _("In case that two patterns were matched pattern with lower metric will be applied.")
        label: _("Need help?")
    pricingPlanId: 
      title: _('Pricing plan')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\PricingPlans
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
    targetPatternId: 
      title: _('Price pattern')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\TargetPatterns
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName: 
            fields:
              - name
              - regExp
            template: '%name% (%regExp%)'
          order: name
      decorators:
        autocomplete:
            command: targetPatternautocomplete_command
    brandId: 
      title: ngettext('Brand', 'Brands', 1)
      type: number
      required: true
      source: 
        control: Spinner
    targetPatternIdGhost:
      title: _('Price pattern')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_TargetPattern
        method: getTargetPattern
        searchMethod: getSearchConditionsForItem
staging:
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
