production:
  class: \IvozProvider\Model\ProxyUsers
  fields:
    name:
      title: _('Name')
      type: text
      trim: both
      maxLength: 100
      default: true
    ip:
      title: _('Ip')
      type: text
      trim: both
      maxLength: 100
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
