production:
  class: \IvozProvider\Model\Services
  fields:
    iden:
      title: ngettext('Iden', 'Idens', 1)
      type: text
      trim: both
      defaultValue:
      maxLength: 50
      default: true
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      defaultValue:
      maxLength: 50
    description:
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      trim: both
      defaultValue:
      maxLength: 255
    defaultCode:
      title: _('Code')
      type: text
      required: true
      prefix: '<span class="asterisc">*</span>'
      maxLength: 3
      pattern: '[#0-9*]+'
      info:
        type: box
        position: left
        icon: help
        text: _("Future brands will have services enabled with this codes by default")
        label: _("Need help?")
    extraArgs:
      title: _('Service has extra arguments')
      type: select
      readonly: true
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
