production:
  class: \IvozProvider\Model\Users
  fields:
    companyId:
      title: _('Company')
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Companies
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      trim: both
      required: true
    lastname:
      title: _('Lastname')
      type: text
      trim: both
      required: true
    email:
      title: ngettext('Email', 'Emails', 1)
      type: text
      maxLength: 100
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Used as voicemail reception and user portal credential")
        label: _("Need help?")
    pass:
      title: ngettext('Password', 'Passwords', 1)
      type: password
      adapter: PlainText
    active:
      title: _('Active')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              show: []
              hide: ["username", "pass"]
          '1':
            title: _("Yes")
            visualFilter:
              show: ["username", "pass"]
              hide: []
    timezoneId:
      title: _('Timezone')
      type: select
      defaultValue: 145
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Timezones
          fieldName:
            fields:
              - tz
            template: '%tz%'
          order: tz
    terminalId:
      title: _('Terminal')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Terminals
          filterClass: IvozProvider_Klear_Filter_Terminals
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    extensionId:
      title: _('Screen Extension')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Extensions
          filterClass: IvozProvider_Klear_Filter_Extensions
          fieldName:
            fields:
              - number
            template: '%number%'
          order: number
        'null': _("Unassigned")
    outgoingDDIId:
      title: _('Outgoing DDI')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\DDIs
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - DDIE164
            template: '+%DDIE164%'
          order: DDIE164
        'null': _("Company's default")
    outgoingDDIRuleId:
      title: _('Outgoing DDI Rules')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\OutgoingDDIRules
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
        'null': _("Company's default")
      info:
        type: box
        position: left
        icon: help
        text: _("Rules to manipulate outgoingDDI when user directly calls to external numbers.")
        label: _("Need help?")
    callACLId:
      title: _('Call ACL')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\CallACL
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
        'null': _("Allow all outgoing calls")
    doNotDisturb:
      title: _('Do not disturb')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
    isBoss:
      title: _('Is boss')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              show: []
              hide: ["bossAssistantId", "exceptionBoosAssistantRegExp"]
          '1':
            title: _("Yes")
            visualFilter:
              show: ["bossAssistantId", "exceptionBoosAssistantRegExp"]
              hide: []
    bossAssistantId:
      title: _('Assistant')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Users
          filterClass: IvozProvider_Klear_Filter_Bossassistant
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order: name
        'null': _("Unassigned")
    exceptionBoosAssistantRegExp:
      title: _('Exception boos assistant reg exp')
      type: text
      trim: both
      maxLength: 255
    username:
      title: _('Username')
      type: text
      trim: both
      maxLength: 65
    maxCalls:
      title: _('Max calls')
      type: number
      defaultValue: 0
      source:
        control: Spinner
        min: 0
        max: 100
      info:
        type: box
        position: left
        icon: help
        text: _("Limits the number of received calls if the user is handling simultaneously (inbound and outbound) more than the number set. Set 0 for unlimited calls.")
        label: _("Need help?")
    voicemailEnabled:
      title: _('Voicemail enabled')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              hide: ["voicemailSendMail", "voicemailAttachSound"]
              show: []
          '1':
            title: _("Yes")
            visualFilter:
              show: ["voicemailSendMail", "voicemailAttachSound"]
              hide: []
    voicemailSendMail:
      title: _('Voicemail send mail')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              hide: ["voicemailAttachSound"]
              show: []
          '1':
            title: _("Yes")
            visualFilter:
              show: ["voicemailAttachSound"]
              hide: []
    voicemailAttachSound:
      title: _('Voicemail attach sound')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
    PickUpRelUsers:
      title: _('Pick Up Groups')
      type: multiselect
      source:
        data: mapper
        config:
          extraDataAttributes:
            companyId: companyId
          relationMapper: \IvozProvider\Mapper\Sql\PickUpRelUsers
          relatedMapperName: \IvozProvider\Mapper\Sql\PickUpGroups
          relatedFieldName: name
          relationProperty: PickUpGroup
          filterClass: IvozProvider_Klear_Filter_Company
    countryId:
      title: _('Country code')
      type: select
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Countries
          fieldName:
            fields:
              - name
              - calling_code
            template: '%name% (+%calling_code%)'
          order: name_${lang}
        'null': _("Company's default")
    areaCode:
      title: _('Areacode')
      type: text
      maxLength: 10
      info:
        type: box
        position: left
        icon: help
        text: _("Calling a number within the same Area can omit Area Code")
        label: _("Need help?")
    HuntGroupsRelUsers:
      title: _('Hunt groups joined')
      searchable: false
      type: ghost
      source:
        predefined: list
      data: mapper
      config:
        mapperName: \IvozProvider\Mapper\Sql\HuntGroupsRelUsers
        filterField: userId
        showAsTable: true
        fieldName:
          fields:
            huntGroupId:
              title: _("Hunt group")
              mapperName: \IvozProvider\Mapper\Sql\HuntGroups
              field:
                - name
              pattern: "%name%"
            timeoutTime:
              title: _("Time out time")
            priority:
              title: _("Priority")
        options:
          dialogs:
            huntGroupsRelUsersDel_dialog: true
          screens:
            huntGroupsRelUsersEdit_screen: true
          default:
      options:
        screens:
          huntGroupsRelUsersNew_screen: true
    languageId:
      title: _('Language')
      type: select
      defaultValue: 1
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Languages
          fieldName:
            fields:
              - name
            template: '%name%'
          order: name
        'null': _("Company's default")
    externalIpCalls:
      title: _('Calls from non-granted IPs')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("None")
          '1':
            title: "1"
          '2':
            title: "2"
          '3':
            title: "3"
      info:
        type: box
        position: left
        icon: help
        text: _("Enable calling from non-granted IP addresses for this user. It limits the number of outgoing calls to avoid toll-fraud. 'None' value makes outgoing calls unlimited as long as company IP policy is fulfilled.")
        label: _("Need help?")

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
