production:
  class: \IvozProvider\Model\BrandServices
  entity: \Ivoz\Provider\Domain\Model\BrandService\BrandService
  fields: 
    serviceId:
      title: ngettext('Service', 'Services', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Services
          entity: \Ivoz\Provider\Domain\Model\Service\Service
          filterClass: IvozProvider_Klear_Filter_BrandServices
          fieldName: 
            fields: 
              - name${lang}
            template: '%name${lang}%'
          order:
            Service.name.${lang}: asc
      default: true
    brandId:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
    code:
      title: _('Code')
      type: text
      trim: both
      required: true
      maxLength: 3
      prefix: '<span class="asterisc">*</span>'
      pattern: '[#0-9*]+'
      info:
        type: box
        position: left
        icon: help
        text: _("Allowed characters are 0-9, * and #")
        label: _("Need help?")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
