production:
  entity: Ivoz\Provider\Domain\Model\CarrierServer\CarrierServer
  fields: 
    carrier:
      title: ngettext('Carrier', 'Carriers', 0)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Carrier\Carrier
          fieldName: 
            fields: 
              - description
            template: '%description%'
          order:
            Carrier.description: asc
      default: true
    ip:
      title: _('Destination IP address')
      type: text
      pattern: "^[.0-9]+$"
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Leave empty to send to Host field")
        label: _("Need help?")
    brand:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
    hostname:
      title: _('Host')
      type: text
      trim: both
      info:
        type: box
        position: left
        icon: help
        text: _("Use address or hostname")
        label: _("Need help?")
    port:
      title: _('Port')
      type: number
      defaultValue: 5060
      source:
        control: Spinner
    uriScheme:
      title: _('URI scheme')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '1':
            title: 'sip'
          '2':
            title: 'sips'
    transport:
      title: _('Transport')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '1':
            title: 'UDP'
          '2':
            title: 'TCP'
          '3':
            title: 'TLS'
    sendPAI:
      title: _('Send PAI')
      type: checkbox
      defaultValue: 1
    sendRPID:
      title: _('Send RPID')
      type: checkbox
    authNeeded:
      title: _('Auth needed')
      type: select
      defaultValue: 'no'
      source:
        data: inline
        values:
          'yes':
            title: _('Yes')
            visualFilter:
              show: [ authUser, authPassword ]
              hide: []
          'no':
            title: _('No')
            visualFilter:
              show: []
              hide: [ authUser, authPassword ]
    authUser:
      title: _('Auth user')
      type: text
      trim: both
      required: true
    authPassword:
      title: _('Auth password')
      type: password
      adapter: PlainText
      required: true
    sipProxy:
      title: _('SIP Proxy')
      type: text
      trim: both
      maxLength: 128
      required: true
      info:
        type: box
        position: left
        icon: help
        text: _("IP or domain name (port with ':')")
        label: _("Need help?")
    outboundProxy:
      title: _('Outbound Proxy')
      type: text
      trim: both
      maxLength: 128
      info:
        type: box
        position: left
        icon: help
        text: _("Send to IP[:PORT] instead of SIP Proxy address")
        label: _("Need help?")
    fromUser:
      title: _('From user')
      type: text
      maxLength: 64
      info:
        type: box
        position: left
        icon: help
        text: _("Use this instead in From header username")
        label: _("Need help?")
    fromDomain:
      title: _('From domain')
      type: text
      maxLength: 190
      info:
        type: box
        position: left
        icon: help
        text: _("Use this instead in From header domain")
        label: _("Need help?")
    statusIcon:
      title: _('Status')
      type: ghost
      dirty: true
      source:
        class: IvozProvider_Klear_Ghost_CarrierServerStatus
        method: getCarrierServerStatusIcon
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
