production: 
  class: \IvozProvider\Model\Countries
  entity: \Ivoz\Provider\Domain\Model\Countries\Country
  fields: 
    code:
      title: _('Code')
      type: text
      defaultValue: 
      maxLength: 100
      default: true
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      isMultilang: true
      maxLength: 100
    zone:
      title: _('Zone')
      type: text
      isMultilang: true
      maxLength: 55
    callingCode:
      title: _('Calling code')
      type: number
      source: 
        control: Spinner
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
