production:
  class: \IvozProvider\Model\Domains
  entity: \Ivoz\Provider\Domain\Model\Domain\Domain
  fields: 
    domain:
      title: _('Domain')
      type: text
      trim: both
      required: true
      maxLength: 255
      default: true
    scope:
      title: _('Scope')
      type: select
      defaultValue: global
      source:
        data: inline
        values:
          'global':
            title: _("global")
            visualFilter:
              show: []
              hide: ["brandId","companyId"]
          'company':
            title: ngettext('Company', 'Companies', 1)
            visualFilter:
              show: ["companyId"]
              hide: ["brandId","pointsTo"]
          'brand':
            title: ngettext('Brand', 'Brands', 1)
            visualFilter:
              hide: ["companyId"]
              show: ["brandId", "pointsTo"]
    pointsTo:
      title: _('Points to')
      type: select
      defaultValue: proxyusers
      source:
        data: inline
        values:
          'proxyusers': ngettext('Proxy Users', 'Proxies Users', 1)
          'proxytrunks': ngettext('Proxy Trunks', 'Proxies Trunks', 1)
    brandId:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
    companyId:
      title: ngettext('Company', 'Companies', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
    description:
      title: _('Description')
      type: text
      trim: both
      maxLength: 500
    target:
      title: _('Scope')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_DomainsScope
        method: getData
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
