production: 
  class: \IvozProvider\Model\ExternalCallFilterRelCalendars
  entity: \Ivoz\Provider\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendar
  fields: 
    filterId:
      title: _('Filter id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\ExternalCallFilters
          entity: \Ivoz\Provider\Domain\Model\ExternalCallFilter\ExternalCallFilter
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            ExternalCallFilter.name: asc
      default: true
    calendarId:
      title: _('Calendar id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Calendars
          entity: \Ivoz\Provider\Domain\Model\Calendar\Calendar
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Calendar.name: asc
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
