production: 
  class: \IvozProvider\Model\ExternalCallFilterRelSchedules
  entity: Ivoz\Provider\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelSchedule
  fields: 
    filterId:
      title: _('Filter id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          entity: \Ivoz\Provider\Domain\Model\ExternalCallFilter\ExternalCallFilter
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            ExternalCallFilter.name: asc
      default: true
    scheduleId:
      title: _('Schedule id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Schedules.name: asc
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
