production:
  entity: Ivoz\Provider\Domain\Model\ExternalCallFilter\ExternalCallFilter
  fields:
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
      default: true
    welcomeLocution:
      title: _('Welcome locution')
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Locution\Locution
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    holidayLocution:
      title: _('Holiday locution')
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Locution\Locution
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    outOfScheduleLocution:
      title: _('Out of schedule locution')
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Locution\Locution
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    holidayEnabled:
      title: _('Holiday enabled')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              hide:
                - calendars
                - holidayLocution
                - holidayTargetType
                - holidayNumberCountry
                - holidayNumberValue
                - holidayExtension
                - holidayVoicemail
              show: []
          '1':
            title: _("Yes")
            visualFilter:
              show:
                - calendars
                - holidayLocution
                - holidayTargetType
              hide: []
    holidayTargetType:
      title: _('Holiday target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title: _('Unassigned')
            visualFilter:
              show: []
              hide: &holidayFields
                - holidayNumberCountry
                - holidayNumberValue
                - holidayExtension
                - holidayVoicemail
          'number':
            title: _("Number")
            visualFilter:
              show: [ holidayNumberValue, holidayNumberCountry ]
              hide:
                <<: *holidayFields
          'extension':
            title: ngettext('Extension', 'Extension', 1)
            visualFilter:
              show: [ holidayExtension ]
              hide:
                <<: *holidayFields
          'voicemail':
            title: ngettext('Voicemail', 'Voicemails', 1)
            visualFilter:
              show: [ holidayVoicemail ]
              hide:
                <<: *holidayFields
    holidayNumberCountry:
      title: ngettext('Country', 'Countries', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - countryCode
            template: '%name${lang}% (%countryCode%)'
          order:
            Country.name.${lang}: asc
    holidayNumberValue:
      title: _("Number")
      type: text
      trim: both
      required: true
    holidayExtension:
      title: ngettext('Extension', 'Extension', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Extension\Extension
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - number
            template: '%number%'
          order:
            Extension.number: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    holidayVoicemail:
      title: ngettext('Voicemail', 'Voicemails', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Voicemail\Voicemail
          filterClass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Voicemail.name: asc
        'null': _("Unassigned")
    outOfScheduleEnabled:
      title: _('Out of schedule enabled')
      type: select
      defaultValue: 1
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              hide:
                - schedules
                - outOfScheduleLocution
                - outOfScheduleTargetType
                - outOfScheduleNumberCountry
                - outOfScheduleNumberValue
                - outOfScheduleExtension
                - outOfScheduleVoicemail
              show: []
          '1':
            title: _("Yes")
            visualFilter:
              show:
                - schedules
                - outOfScheduleLocution
                - outOfScheduleTargetType
              hide: []
    outOfScheduleTargetType:
      title: _('Out of schedule target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title: _('Unassigned')
            visualFilter:
              show: []
              hide: &outOfScheduleFields
                - outOfScheduleNumberCountry
                - outOfScheduleNumberValue
                - outOfScheduleExtension
                - outOfScheduleVoicemail
          'number':
            title: _('Number')
            visualFilter:
              show: [ outOfScheduleNumberValue, outOfScheduleNumberCountry ]
              hide:
                <<: *outOfScheduleFields
          'extension':
            title: ngettext('Extension', 'Extensions', 1)
            visualFilter:
              show: [ outOfScheduleExtension ]
              hide:
                <<: *outOfScheduleFields
          'voicemail':
            title: ngettext('Voicemail', 'Voicemails', 1)
            visualFilter:
              show: [ outOfScheduleVoicemail ]
              hide:
                <<: *outOfScheduleFields
    outOfScheduleNumberCountry:
      title: ngettext('Country', 'Countries', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - countryCode
            template: '%name${lang}% (%countryCode%)'
          order:
            Country.name.${lang}: asc
    outOfScheduleNumberValue:
      title: _("Number")
      type: text
      trim: both
      required: true
    outOfScheduleExtension:
      title: ngettext('Extension', 'Extension', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Extension\Extension
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - number
            template: '%number%'
          order:
            Extension.number: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    outOfScheduleVoicemail:
      title: ngettext('Voicemail', 'Voicemails', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Voicemail\Voicemail
          filterClass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Voicemail.name: asc
        'null': _("Unassigned")
    schedules:
      title: ngettext('Schedule', 'Schedules', 0)
      type: multiselect
      source:
        data: mapper
        config:
          relation: \Ivoz\Provider\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelSchedule
          relationProperty: filter
          relatedProperty: schedule
          related: \Ivoz\Provider\Domain\Model\Schedule\Schedule
          relatedFieldName: name
          filterClass: IvozProvider_Klear_Filter_Company
    calendars:
      title: ngettext('Calendar', 'Calendars', 0)
      type: multiselect
      source:
        data: mapper
        config:
          relation: \Ivoz\Provider\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendar
          relationProperty: filter
          relatedProperty: calendar
          related: \Ivoz\Provider\Domain\Model\Calendar\Calendar
          relatedFieldName: name
          filterClass: IvozProvider_Klear_Filter_Company
    holidayTarget:
      title: _('Holiday target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_RouteTarget
        method: getExternalCallFilterHolidayTarget
    outOfScheduleTarget:
      title: _('Out of schedule target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_RouteTarget
        method: getExternalCallFilterOutOfScheduleTarget
    whiteLists:
      title: _('White Lists')
      type: multiselect
      source:
        data: mapper
        config:
          relation: \Ivoz\Provider\Domain\Model\ExternalCallFilterWhiteList\ExternalCallFilterWhiteList
          relationProperty: filter
          relatedProperty: matchlist
          related: \Ivoz\Provider\Domain\Model\MatchList\MatchList
          relatedFieldName: name
          filterClass: IvozProvider_Klear_Filter_CompanyOrBrand
      info:
        type: box
        text: _("Incoming numbers that match this lists will be always ACCEPTED without checking this filter configuration.")
        label: _("Need help?")
    blackLists:
      title: _('Black Lists')
      type: multiselect
      source:
        data: mapper
        config:
          relation: \Ivoz\Provider\Domain\Model\ExternalCallFilterBlackList\ExternalCallFilterBlackList
          relationProperty: filter
          relatedProperty: matchlist
          related: \Ivoz\Provider\Domain\Model\MatchList\MatchList
          relatedFieldName: name
          filterClass: IvozProvider_Klear_Filter_CompanyOrBrand
      info:
        type: box
        text: _("Incoming numbers that match this lists will be always REJECTED without checking this filter configuration.")
        label: _("Need help?")

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
