production:
  class: \IvozProvider\Model\ExternalCallFilters
  entity: Ivoz\Provider\Domain\Model\ExternalCallFilter\ExternalCallFilter
  fields:
    companyId:
      title: ngettext('Company', 'Companies', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
      default: true
    welcomeLocutionId:
      title: _('Welcome locution')
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Locution\Locution
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    holidayLocutionId:
      title: _('Holiday locution')
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Locution\Locution
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    outOfScheduleLocutionId:
      title: _('Out of schedule locution')
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Locution\Locution
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    holidayTargetType:
      title: _('Holiday target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title: _('Unassigned')
            visualFilter:
              show: []
              hide: &holidayFields
                - holidayNumberCountryId
                - holidayNumberValue
                - holidayExtensionId
                - holidayVoiceMailUserId
          'number':
            title: _("Number")
            visualFilter:
              show: [ holidayNumberValue, holidayNumberCountryId ]
              hide:
                <<: *holidayFields
          'extension':
            title: ngettext('Extension', 'Extension', 1)
            visualFilter:
              show: [ holidayExtensionId ]
              hide:
                <<: *holidayFields
          'voicemail':
            title: ngettext('Voicemail', 'Voicemails', 1)
            visualFilter:
              show: [ holidayVoiceMailUserId ]
              hide:
                <<: *holidayFields
    holidayNumberCountryId:
      title: ngettext('Country', 'Countries', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - callingCode
            template: '%name${lang}% (%callingCode%)'
          order:
            Country.name.${lang}: asc
    holidayNumberValue:
      title: _("Number")
      type: text
      trim: both
      required: true
    holidayExtensionId:
      title: ngettext('Extension', 'Extension', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Extension\Extension
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - number
            template: '%number%'
          order:
            Extension.number: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    holidayVoiceMailUserId:
      title: ngettext('Voicemail', 'Voicemails', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\User\User
          filterClass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
        'null': _("Unassigned")
    outOfScheduleTargetType:
      title: _('Out of schedule target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title: _('Unassigned')
            visualFilter:
              show: []
              hide: &outOfScheduleFields
                - outOfScheduleNumberCountryId
                - outOfScheduleNumberValue
                - outOfScheduleExtensionId
                - outOfScheduleVoiceMailUserId
          'number':
            title: _('Number')
            visualFilter:
              show: [ outOfScheduleNumberValue, outOfScheduleNumberCountryId ]
              hide:
                <<: *outOfScheduleFields
          'extension':
            title: ngettext('Extension', 'Extensions', 1)
            visualFilter:
              show: [ outOfScheduleExtensionId ]
              hide:
                <<: *outOfScheduleFields
          'voicemail':
            title: ngettext('Voicemail', 'Voicemails', 1)
            visualFilter:
              show: [ outOfScheduleVoiceMailUserId ]
              hide:
                <<: *outOfScheduleFields
    outOfScheduleNumberCountryId:
      title: ngettext('Country', 'Countries', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - callingCode
            template: '%name${lang}% (%callingCode%)'
          order:
            Country.name.${lang}: asc
    outOfScheduleNumberValue:
      title: _("Number")
      type: text
      trim: both
      required: true
    outOfScheduleExtensionId:
      title: ngettext('Extension', 'Extension', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Extension\Extension
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - number
            template: '%number%'
          order:
            Extension.number: asc
          extraDataAttributes:
            iden: companyId
        'null': _("Unassigned")
    outOfScheduleVoiceMailUserId:
      title: ngettext('Voicemail', 'Voicemails', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\User\User
          filterClass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
        'null': _("Unassigned")
    schedules:
      title: ngettext('Schedule', 'Schedules', 0)
      type: multiselect
      source:
        data: mapper
        config:
          relation: \Ivoz\Provider\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelSchedule
          relationProperty: schedule
          relatedProperty: schedule
          related: \Ivoz\Provider\Domain\Model\Schedule\Schedule
          filterClass: IvozProvider_Klear_Filter_Company
          relatedFieldName: name
    calendars:
      title: ngettext('Calendar', 'Calendars', 0)
      type: multiselect
      source:
        data: mapper
        config:
          relation: \Ivoz\Provider\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendar
          relationProperty: filter
          relatedProperty: calendar
          related: \Ivoz\Provider\Domain\Model\Calendar\Calendar
          relatedFieldName: name
          filterClass: IvozProvider_Klear_Filter_Company
    holidayTarget:
      title: _('Holiday target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_ExternalCallFiltersTarget
        method: getHolidayData
    outOfScheduleTarget:
      title: _('Out of schedule target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_ExternalCallFiltersTarget
        method: getOutOfScheduleData
    whiteLists:
      title: _('White Lists')
      type: multiselect
      source:
        data: mapper
        config:
          relation: \Ivoz\Provider\Domain\Model\ExternalCallFilterWhiteList\ExternalCallFilterWhiteList
          relationProperty: matchlist
          relatedProperty: matchlist
          related: \Ivoz\Provider\Domain\Model\MatchList\MatchList
          relatedFieldName: name
          filterClass: \IvozProvider_Klear_Filter_Company
      info:
        type: box
        text: _("Incoming numbers that match this lists will be always ACCEPTED without checking this filter configuration.")
        label: _("Need help?")
    blackLists:
      title: _('Black Lists')
      type: multiselect
      source:
        data: mapper
        config:
          relation: \Ivoz\Provider\Domain\Model\ExternalCallFilterBlackList\ExternalCallFilterBlackList
          relationProperty: matchlist
          relatedProperty: matchlist
          related: \Ivoz\Provider\Domain\Model\MatchList\MatchList
          relatedFieldName: name
          filterClass: IvozProvider_Klear_Filter_Company
      info:
        type: box
        text: _("Incoming numbers that match this lists will be always REJECTED without checking this filter configuration.")
        label: _("Need help?")

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
