production:
  class: \IvozProvider\Model\FixedCosts
  entity: Ivoz\Provider\Domain\Model\FixedCost\FixedCost
  fields: 
    brandId:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    name:
      title: _('Name')
      type: text
      maxLength: 255
      required: true
    description:
      title: _('Description')
      type: textarea
    cost:
      title: _('Cost')
      type: text
      pattern: "^[0-9]{1,6}([.][0-9]{1,4})?$"
      sufix: "â‚¬"
      required: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
