#include ../conf.d/invoiceTemplateHelp.yaml

production:
  class: \IvozProvider\Model\InvoiceTemplates
  entity: Ivoz\Provider\Domain\Model\InvoiceTemplate\InvoiceTemplate
  fields: 
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
      maxLength: 55
      default: true
    description:
      title: _('Description')
      type: text
      trim: both
      maxLength: 300
    template:
      title: ngettext('Template', 'Templates', 1)
      type: textarea
      required: true
      source:
        control: Codemirror
        settings:
          mode:
            - application/xml
            - xml
          lineNumbers: true
          matchBrackets: true
      <<: *invoiceTemplateHelp
    templateHeader:
      title: _('Template header')
      type: textarea
      source:
        control: Codemirror
        settings:
          mode:
            - application/xml
            - xml
          lineNumbers: true
          matchBrackets: true
      <<: *invoiceTemplateFooterHeaderHelp
    templateFooter:
      title: _('Template footer')
      type: textarea
      source:
        control: Codemirror
        settings:
          mode:
            - application/xml
            - xml
          lineNumbers: true
          matchBrackets: true
      <<: *invoiceTemplateFooterHeaderHelp
    brandId:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
staging: 
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
