production:
  class: \IvozProvider\Model\TrunksUacreg
  entity: Ivoz\Kam\Domain\Model\TrunksUacreg\TrunksUacreg
  fields:
    multiDDI:
      title: _('Multi DDI')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              show: ["l_uuid"]
              hide: []
          '1':
            title: _("Yes")
            visualFilter:
              show: []
              hide: ["l_uuid"]
    lUuid:
      title: _('DDI')
      type: text
      trim: both
      defaultValue:
      default: true
      info:
        type: box
        position: left
        icon: help
        text: _("Is sent in the username of Contact header in generated REGISTER.")
        label: _("Need help?")
      required: true
    lUsername:
      type: text
      trim: both
      defaultValue:
    lDomain:
      type: text
      trim: both
      defaultValue:
      maxLength: 190
    rUsername:
      title: _('Username')
      type: text
      trim: both
      defaultValue:
      required: true
    rDomain:
      title: _('Domain')
      type: text
      trim: both
      defaultValue:
      required: true
    realm:
      title: _('Realm')
      type: text
      trim: both
      defaultValue:
      info:
        type: box
        position: left
        icon: help
        text: _("Leave empty to use the suggested default")
        label: _("Need help?")
    authUsername:
      title: _('Auth username')
      type: text
      trim: both
      defaultValue:
      required: false
      info:
        type: box
        position: left
        icon: help
        text: _("Only if it's different from the Username")
        label: _("Need help?")
    authPassword:
      title: _('Password')
      type: password
      defaultValue:
      adapter: PlainText
      required: true
    authProxy:
      title: _('Registrar Server URI')
      type: text
      trim: both
      defaultValue:
      pattern: "^sip:.*$|^sips:.*$"
      required: false
      info:
        type: box
        position: left
        icon: help
        text: _("Must start with sip or sips followed by colon")
        label: _("Need help?")
    expires:
      title: _('Expire')
      type: number
      defaultValue: 3600
      source:
        control: Spinner
      required: true
    brandId:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Brand.name: asc
    peeringContractId:
      title: _('Peering contract id')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\PeeringContract\PeeringContract
          fieldName:
            fields:
              - description
            template: '%description%'
          order:
            PeeringContract.description: asc
    flags:
      title: _('Flag')
      type: number
      defaultValue: 0
      source:
        control: Spinner
    regDelay:
      title: _('Reg delay')
      type: number
      defaultValue: 0
      source:
        control: Spinner
    targetDDI:
      title: _('DDI')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_KamTrunksUacRegTargetDDI
        method: getData
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
