production: 
  class: \IvozProvider\Model\TrunksLcrRuleTarget
  entity: Ivoz\Kam\Domain\Model\TrunksLcrRuleTarget\TrunksLcrRuleTarget
  fields: 
    lcrId:
      title: _('Lcr id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Brands
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    rule:
      title: _('Rule id')
      type: number
      required: true
      source: 
        control: Spinner
    gw:
      title: _('Gw id')
      type: number
      required: true
      source: 
        control: Spinner
    priority:
      title: _('Priority')
      type: number
      required: true
      source: 
        control: Spinner
    weight:
      title: _('Weight')
      type: number
      defaultValue: 1
      source: 
        control: Spinner
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
