production:
  entity: Ivoz\Kam\Domain\Model\UsersAddress\UsersAddress
  fields: 
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
      default: true
    sourceAddress:
      title: _('Authorized source')
      type: text
      trim: both
      required: true
      maxLength: 100
      info:
        type: box
        position: left
        icon: help
        text: _("CIDR notation (e.g. 8.8.8.0/24) or specific IP address (e.g. 8.8.8.8)")
        label: _("Need help?")
    ipAddr:
      title: _('Ip addr')
      type: text
      trim: both
      maxLength: 50
    mask:
      title: _('Mask')
      type: number
      defaultValue: 32
      source:
        control: Spinner
    port:
      title: _('Port')
      type: number
      defaultValue: 0
      source:
        control: Spinner
    tag:
      title: _('Tag')
      type: text
      trim: both
      maxLength: 64
    description:
      title: _('Description')
      type: text
      trim: both
      maxLength: 200
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
