production: 
  class: \IvozProvider\Model\Languages
  entity: Ivoz\Provider\Domain\Model\Language\Language
  fields: 
    iden:
      title: ngettext('Iden', 'Idens', 1)
      type: text
      trim: both
      required: true
      default: true
    name:
      title: ngettext('Name', 'Names', 1)
      type: text
      isMultilang: true
      trim: both
      defaultValue: 
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
