production: 
  class: \IvozProvider\Model\LcrRuleTarget
  entity: Ivoz\Provider\Domain\Model\LcrRuleTarget\LcrRuleTarget
  fields: 
    brandId:
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
      default: true
    ruleId:
      title: _('Rule id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          entity: \IvozProvider\Mapper\LcrRule\LcrRule
          fieldName: 
            fields: 
              - prefix
            template: '%prefix%'
          order:
            LcrRule.prefix: asc
    gw:
      title: _('Gw id')
      type: number
      required: true
      source: 
        control: Spinner
    priority:
      title: _('Priority')
      type: number
      required: true
      source: 
        control: Spinner
    weight:
      title: _('Weight')
      type: number
      defaultValue: 1
      source: 
        control: Spinner
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
