production:
  entity: Ivoz\Provider\Domain\Model\Locution\Locution
  fields: 
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
    originalFile:
      title: ngettext('Uploaded file', 'Uploaded files', 1)
      type: file
      source:
        data: fso
        size_limit: 20M
        extensions: [ wav, mp3 ]
        options:
          download:
            external: true
            type: command
            target: locutionsOriginalFileDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          upload:
            type: command
            target: locutionsOriginalFileUpload_command
            title: _("Upload file")
            class: qq-uploader
            onNull: show
          mediaembed:
            type: command
            title: _("Listen to MoH")
            class: jmedia
            onNull: hide
            target: locutionsOriginalFileDownload_command
    encodedFile:
      title: ngettext('File for play', 'Files for play', 1)
      type: file
      source:
        data: fso
        size_limit: 20M
        options:
          download:
            external: true
            type: command
            target: locutionsEncodedFileDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          mediaembed:
            type: command
            title: _("Listen to MoH")
            class: jmedia
            onNull: hide
            target: locutionsEncodedFileDownload_command
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
      default: true
    recordingExtension:
      title: _('Recording extension')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_RecordLocution
        method: getRecordingExtension
      info:
        type: box
        position: left
        icon: help
        text: _("You can call this extension from any company terminal to record this locution")
        label: _("Need help?")
    status:
      title: _('Status')
      type: select
      source:
        data: inline
        values:
          'pending': _('pending')
          'encoding': _('encoding')
          'ready': _('ready')
          'error': _('error')
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
