production:
  class: \IvozProvider\Model\MatchListPatterns
  entity: Ivoz\Provider\Domain\Model\MatchListPattern\MatchListPattern
  fields:
    matchListId:
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: Ivoz\Provider\Domain\Model\MatchList\MatchList
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            MatchList.name: asc
      default: true
    description:
      title: _('Description')
      type: text
      trim: both
      maxLength: 55
    type:
      title: _('Type')
      type: select
      required: true
      source:
        data: inline
        values:
          'number':
            title: _("Number")
            visualFilter:
              show: ["numberCountryId", "numberValue"]
              hide: ["regExp"]
          'regexp':
            title: _("Regular Expression")
            visualFilter:
              show: ["regExp"]
              hide: ["numberCountryId", "numberValue"]
    regExp:
      title: _('Regular Expression')
      type: text
      required: true
      maxLength: 255
      trim: both
      info:
        ￼type: box
        ￼position: left
        ￼icon: help
        text: _("Enter number patterns in E.164 format.")
        label: _("Need help?")
    numberCountryId:
      title: _('Country')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - countryCode
            template: '%name${lang}% (%countryCode%)'
          order:
            Country.name.${lang}: asc
    numberValue:
      title: _('Number')
      type: text
      trim: both
      required: true
      maxLength: 25
    matchValue:
      title: _('Match Value')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_MatchListPattern
        method: getMatchValue
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
