#include ../conf.d/notificationTemplateHelp.yaml

production:
  entity: Ivoz\Provider\Domain\Model\NotificationTemplateContent\NotificationTemplateContent
  fields:
    notificationTemplateId:
      title: ngettext('Notification template', 'Notification templates', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplate
          fieldName:
            fields:
              - name
            template: '%name%'
    languageId:
      title: _('Language')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: Ivoz\Provider\Domain\Model\Language\Language
          fieldName:
            fields:
              - name${lang}
            template: '%name${lang}%'
          order:
            Language.name.${lang}: asc
    fromName:
      title: _('From name')
      trim: both
      maxLength: 255
      required: true
      info:
        type: box
        position: left
        icon: help
        text: _("Name shown as source when sending mails (e.g. IvozProvider Notifications)")
        label: _("Need help?")
    fromAddress:
      title: _('From address')
      type: text
      trim: both
      maxLength: 255
      required: true
      info:
        type: box
        position: left
        icon: help
        text: _("Mail address shown as source when sending mails. MTA must allow this value.")
        label: _("Need help?")
    voicemailVariables:
      title: _('Substitution variables')
      type: ghost
      maxLength: 255
      readonly: true
      source:
        class: IvozProvider_Klear_Ghost_NotificationTemplate
        method: getVariables
      <<: *voicemailVariablesHelp
    faxVariables:
      title: _('Substitution variables')
      type: ghost
      maxLength: 255
      readonly: true
      source:
        class: IvozProvider_Klear_Ghost_NotificationTemplate
        method: getVariables
      <<: *faxVariablesHelp
    lowBalanceVariables:
      title: _('Substitution variables')
      type: ghost
      maxLength: 255
      readonly: true
      source:
        class: IvozProvider_Klear_Ghost_NotificationTemplate
        method: getVariables
      <<: *lowBalanceVariablesHelp
    subject:
      title: _('Subject')
      trim: both
      maxLength: 255
      required: true
    body:
      title: _('Body')
      type: textarea
      required: true
      source:
        control: Codemirror
        settings:
          mode:
            - html
          lineNumbers: true
          matchBrackets: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
