production:
  entity: Ivoz\Provider\Domain\Model\Schedule\Schedule
  fields: 
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      attributes:
        data-autofilter-select-by-data:
          'ExternalCallFilterRelSchedules\[\]': iden
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
      default: true
    timeIn:
      title: _('Time in')
      type: picker
      required: true
      source:
        control: time
        settings:
          disabled: 'false'
    timeout:
      title: _('Time out')
      type: picker
      required: true
      source:
        control: time
        settings:
          disabled: 'false'
    monday:
      title: _('Monday')
      type: checkbox
      defaultValue: 0
    tuesday:
      title: _('Tuesday')
      type: checkbox
      defaultValue: 0
    wednesday:
      title: _('Wednesday')
      type: checkbox
      defaultValue: 0
    thursday:
      title: _('Thursday')
      type: checkbox
      defaultValue: 0
    friday:
      title: _('Friday')
      type: checkbox
      defaultValue: 0
    saturday:
      title: _('Saturday')
      type: checkbox
      defaultValue: 0
    sunday:
      title: _('Sunday')
      type: checkbox
      defaultValue: 0
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
