production:
  class: \IvozProvider\Model\TargetPatterns
  entity: Ivoz\Provider\Domain\Model\TargetPattern\TargetPattern
  fields: 
    id:
      title: ngettext('Id', 'Ids', 1)
      required: false 
    name:
      title: _('Name')
      type: text
      isMultilang: true
      trim: both
      required: true
      maxLength: 55
      default: true
    description:
      title: _('Description')
      type: text
      isMultilang: true
      trim: both
      maxLength: 300
    regExp:
      title: _('Prefix')
      pattern: "^[0-9]+$"
      required: true
      maxLength: 80
      info:
        type: box
        position: left
        icon: help
        text: _("Prefix must be numeric-only")
        label: _("Need help?")
    brandId:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
staging: 
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
