production:
  entity: Ivoz\Provider\Domain\Model\TerminalModel\TerminalModel
  fields:
    iden:
      title: ngettext('Iden', 'Idens', 1)
      type: text
      pattern: '[a-zA-Z0-9_-]+'
      trim: both
      required: true
    name:
      title: _('Name')
      type: text
      trim: both
      defaultValue:
      default: true
    description:
      title: _('Description')
      type: text
      trim: both
      defaultValue:
    terminalManufacturer:
      title: _('Terminal manufacturer')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\TerminalManufacturer\TerminalManufacturer
          fieldName:
            fields:
              - iden
              - name
            template: '%name%'
          order:
            TerminalManufacturer.iden: asc
    genericUrlPattern:
      title: _('Generic URL Pattern')
      type: text
      trim: both
      prefix: 'http://{PROVISIONING_URL}/provision/'
      info:
        type: box
        position: left
        icon: help
        text: _("Exact URL that will be accessed.")
    genericTemplate:
      title: _('Generic template')
      type: textarea
      source:
        control: Codemirror
        settings:
          mode:
            - application/x-httpd-php
            - htmlmixed
            - xml
            - php
          lineNumbers: true
          matchBrackets: true
      options:
        title: _("Options")
        dialogs:
          uploadFile_dialog: true
          downloadFile_dialog: true
          genericBackup_dialog: true
          genericDefault_dialog: true
          runGenericCode_dialog: true
      info:
        type: box
        position: left
        icon: help
        text: _('Use <strong>$this->terminalModel</strong> to access the model data.')
    specificUrlPattern:
      title: _('Specific URL Pattern')
      type: text
      trim: both
      prefix: 'https://{PROVISIONING_URL}:{PORT_IN_GENERIC_FILE}/provision/{OPTIONAL_SUBPATHS}/'
      info:
        type: box
        position: left
        icon: help
        text: _("You can optionally prepend the terminal model or any other subpath to the url before the MAC address for verbosity/debugging purposes. If a extension is given (e.g. {mac}.cfg), requested file must have that extension too. Otherwise, only requested filename will be checked.")
    specificTemplate:
      title: _('Specific Template')
      type: textarea
      source:
        control: Codemirror
        settings:
          mode:
            - application/x-httpd-php
            - htmlmixed
            - xml
            - php
          lineNumbers: true
          matchBrackets: true
      options:
        title: _("Options")
        dialogs:
          uploadFile_dialog: true
          downloadFile_dialog: true
          specificBackup_dialog: true
          specificDefault_dialog: true
          runSpecificCode_dialog: true
      info:
        type: box
        position: left
        icon: help
        text: _('Use <strong>$this->terminalModel</strong> to access model data, <strong>$this->terminal</strong> to access terminal data, <strong>$this->user</strong> for the user and <strong>$this->company</strong> for the company.');
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
