production:
  class: \IvozProvider\Model\TransformationRuleSet
  entity: Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSet
  fields: 
    brandId:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Brand.name: asc
    name:
      title: _('Name')
      type: text
      trim: both
      isMultilang: true
      required: true
      maxLength: 100
      default: true
    description:
      title: _('Description')
      type: text
      trim: both
      maxLength: 250
    internationalCode:
      title: _('International Code')
      type: text
      pattern: "^[0-9]{2,10}$"
      maxLength: 5
      defaultValue: '00'
      info:
        type: box
        position: left
        icon: help
        text: _("Code used for internationals calls, usually 00.")
        label: _("Need help?")
    countryId:
      title: _('Country code')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - countryCode
            template: '%name${lang}% (%countryCode%)'
          order:
            Country.name.${lang}: asc
      defaultValue: 70
    trunkPrefix:
      title: _('Trunk Prefix')
      type: text
      pattern: "^[0-9]+$"
      maxLength: 5
      info:
        type: box
        position: left
        icon: help
        text: _("Prefix used for national out of area calls.")
        label: _("Need help?")
    areaCode:
      title: _('Area code')
      type: text
      maxLength: 10
      info:
        type: box
        position: left
        icon: help
        text: _("Calling a number within the same Area can omit Area Code")
        label: _("Need help?")
    nationalLen:
      title: _('National number length')
      type: number
      defaultValue: 9
      source:
        control: Spinner
      info:
        type: box
        position: left
        icon: help
        text: _("How long are the normal phone numbers called inside this country?")
        label: _("Need help?")
    generateRules:
      title: _('Generate Transformation Rules automatically')
      type: checkbox
      info:
        type: box
        position: left
        icon: help
        text: _("Mark this option to regenerate all rules after saving.")
        label: _("Need help?")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
