########################################
## Raw
########################################
Ivoz\Kam\Domain\Model\TrunksUacreg\DdiProviderRegistrationStatus:
  itemOperations: []
  collectionOperations: []

Ivoz\Kam\Domain\Model\UsersLocation\RegistrationStatus:
  itemOperations: []
  collectionOperations: []
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
    normalization_context:
      groups: ['']

Ivoz\Kam\Domain\Model\UsersAddress\UsersAddress:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
    read_access_control:
      ROLE_BRAND_ADMIN:
        company:
          in: "companyRepository.getSupervisedCompanyIdsByAdmin(user)"
