mappers:
  - &ApplicationServers {mapper: \IvozProvider\Mapper\Sql\ApplicationServers, modelFile: ApplicationServers}
  - &BillableCalls {mapper: \IvozProvider\Mapper\Sql\BillableCalls, modelFile: BillableCalls}
  - &BrandOperators {mapper: \IvozProvider\Mapper\Sql\BrandOperators, modelFile: BrandOperators}
  - &BrandServices {mapper: \IvozProvider\Mapper\Sql\BrandServices, modelFile: BrandServices}
  - &BrandURLs {mapper: \IvozProvider\Mapper\Sql\BrandURLs, modelFile: BrandURLs}
  - &Brands {mapper: \IvozProvider\Mapper\Sql\Brands, modelFile: Brands}
  - &Calendars {mapper: \IvozProvider\Mapper\Sql\Calendars, modelFile: Calendars}
  - &CallACL {mapper: \IvozProvider\Mapper\Sql\CallACL, modelFile: CallACL}
  - &CallACLPatterns {mapper: \IvozProvider\Mapper\Sql\CallACLPatterns, modelFile: CallACLPatterns}
  - &CallACLRelPatterns {mapper: \IvozProvider\Mapper\Sql\CallACLRelPatterns, modelFile: CallACLRelPatterns}
  - &CallForwardSettings {mapper: \IvozProvider\Mapper\Sql\CallForwardSettings, modelFile: CallForwardSettings}
  - &ChangeHistory {mapper: \IvozProvider\Mapper\Sql\ChangeHistory, modelFile: ChangeHistory}
  - &Companies {mapper: \IvozProvider\Mapper\Sql\Companies, modelFile: Companies}
  - &CompanyAdmins {mapper: \IvozProvider\Mapper\Sql\CompanyAdmins, modelFile: CompanyAdmins}
  - &CompanyServices {mapper: \IvozProvider\Mapper\Sql\CompanyServices, modelFile: CompanyServices}
  - &CompanyURLs {mapper: \IvozProvider\Mapper\Sql\BrandURLs, modelFile: CompanyURLs}
  - &ConferenceRooms {mapper: \IvozProvider\Mapper\Sql\ConferenceRooms, modelFile: ConferenceRooms}
  - &Countries {mapper: \IvozProvider\Mapper\Sql\Countries, modelFile: Countries}
  - &DDIs {mapper: \IvozProvider\Mapper\Sql\DDIs, modelFile: DDIs}
  - &Domains {mapper: \IvozProvider\Mapper\Sql\Domains, modelFile: Domains}
  - &EtagVersions {mapper: \IvozProvider\Mapper\Sql\EtagVersions, modelFile: EtagVersions}
  - &Extensions {mapper: \IvozProvider\Mapper\Sql\Extensions, modelFile: Extensions}
  - &ExternalCallFilterRelCalendars {mapper: \IvozProvider\Mapper\Sql\ExternalCallFilterRelCalendars, modelFile: ExternalCallFilterRelCalendars}
  - &ExternalCallFilterRelSchedules {mapper: \IvozProvider\Mapper\Sql\ExternalCallFilterRelSchedules, modelFile: ExternalCallFilterRelSchedules}
  - &ExternalCallFilters {mapper: \IvozProvider\Mapper\Sql\ExternalCallFilters, modelFile: ExternalCallFilters}
  - &ExternalCallFiltersRetail { mapper: \IvozProvider\Mapper\Sql\ExternalCallFilters, modelFile: ExternalCallFiltersRetail}
  - &Faxes {mapper: \IvozProvider\Mapper\Sql\Faxes, modelFile: Faxes}
  - &FaxesInOut {mapper: \IvozProvider\Mapper\Sql\FaxesInOut, modelFile: FaxesInOut}
  - &Features {mapper: \IvozProvider\Mapper\Sql\Features, modelFile: Features}
  - &FeaturesRelBrands {mapper: \IvozProvider\Mapper\Sql\FeaturesRelBrands, modelFile: FeaturesRelBrands}
  - &FeaturesRelCompanies {mapper: \IvozProvider\Mapper\Sql\FeaturesRelCompanies, modelFile: FeaturesRelCompanies}
  - &FixedCosts {mapper: \IvozProvider\Mapper\Sql\FixedCosts, modelFile: FixedCosts}
  - &FixedCostsRelInvoices {mapper: \IvozProvider\Mapper\Sql\FixedCostsRelInvoices, modelFile: FixedCostsRelInvoices}
  - &Friends {mapper: \IvozProvider\Mapper\Sql\Friends, modelFile: Friends}
  - &FriendsPatterns {mapper: \IvozProvider\Mapper\Sql\FriendsPatterns, modelFile: FriendsPatterns}
  - &GenericCallACLPatterns {mapper: \IvozProvider\Mapper\Sql\GenericCallACLPatterns, modelFile: GenericCallACLPatterns}
  - &GenericMusicOnHold {mapper: \IvozProvider\Mapper\Sql\GenericMusicOnHold, modelFile: GenericMusicOnHold}
  - &HolidayDates {mapper: \IvozProvider\Mapper\Sql\HolidayDates, modelFile: HolidayDates}
  - &HuntGroups {mapper: \IvozProvider\Mapper\Sql\HuntGroups, modelFile: HuntGroups}
  - &HuntGroupsRelUsers {mapper: \IvozProvider\Mapper\Sql\HuntGroupsRelUsers, modelFile: HuntGroupsRelUsers}
  - &IVRCommon {mapper: \IvozProvider\Mapper\Sql\IVRCommon, modelFile: IVRCommon}
  - &IVRCustom {mapper: \IvozProvider\Mapper\Sql\IVRCustom, modelFile: IVRCustom}
  - &IVRCustomEntries {mapper: \IvozProvider\Mapper\Sql\IVRCustomEntries, modelFile: IVRCustomEntries}
  - &InvoiceTemplates {mapper: \IvozProvider\Mapper\Sql\InvoiceTemplates, modelFile: InvoiceTemplates}
  - &Invoices {mapper: \IvozProvider\Mapper\Sql\Invoices, modelFile: Invoices}
  - &Languages {mapper: \IvozProvider\Mapper\Sql\Languages, modelFile: Languages}
  - &LcrGateways {mapper: \IvozProvider\Mapper\Sql\LcrGateways, modelFile: LcrGateways}
  - &LcrRuleTargets {mapper: \IvozProvider\Mapper\Sql\LcrRuleTargets, modelFile: LcrRuleTargets}
  - &LcrRules {mapper: \IvozProvider\Mapper\Sql\LcrRules, modelFile: LcrRules}
  - &Locutions {mapper: \IvozProvider\Mapper\Sql\Locutions, modelFile: Locutions}
  - &MainOperators {mapper: \IvozProvider\Mapper\Sql\MainOperators, modelFile: MainOperators}
  - &MatchListPatterns {mapper: \IvozProvider\Mapper\Sql\MatchListPatterns, modelFile: MatchListPatterns}
  - &MatchLists {mapper: \IvozProvider\Mapper\Sql\MatchLists, modelFile: MatchLists}
  - &MediaRelaySets {mapper: \IvozProvider\Mapper\Sql\MediaRelaySets, modelFile: MediaRelaySets}
  - &MusicOnHold {mapper: \IvozProvider\Mapper\Sql\MusicOnHold, modelFile: MusicOnHold}
  - &OutgoingDDIRules {mapper: \IvozProvider\Mapper\Sql\OutgoingDDIRules, modelFile: OutgoingDDIRules}
  - &OutgoingDDIRulesPatterns {mapper: \IvozProvider\Mapper\Sql\OutgoingDDIRulesPatterns, modelFile: OutgoingDDIRulesPatterns}
  - &OutgoingRouting {mapper: \IvozProvider\Mapper\Sql\OutgoingRouting, modelFile: OutgoingRouting}
  - &ParsedCDRs {mapper: \IvozProvider\Mapper\Sql\ParsedCDRs, modelFile: ParsedCDRs}
  - &ParsedCDRsGod {mapper: \IvozProvider\Mapper\Sql\ParsedCDRs, modelFile: ParsedCDRsGod}
  - &PeerServers {mapper: \IvozProvider\Mapper\Sql\PeerServers, modelFile: PeerServers}
  - &PeeringContracts {mapper: \IvozProvider\Mapper\Sql\PeeringContracts, modelFile: PeeringContracts}
  - &PickUpGroups {mapper: \IvozProvider\Mapper\Sql\PickUpGroups, modelFile: PickUpGroups}
  - &PickUpRelUsers {mapper: \IvozProvider\Mapper\Sql\PickUpRelUsers, modelFile: PickUpRelUsers}
  - &PricingPlans {mapper: \IvozProvider\Mapper\Sql\PricingPlans, modelFile: PricingPlans}
  - &PricingPlansRelCompanies {mapper: \IvozProvider\Mapper\Sql\PricingPlansRelCompanies, modelFile: PricingPlansRelCompanies}
  - &PricingPlansRelTargetPatterns {mapper: \IvozProvider\Mapper\Sql\PricingPlansRelTargetPatterns, modelFile: PricingPlansRelTargetPatterns}
  - &ProxyTrunks {mapper: \IvozProvider\Mapper\Sql\ProxyTrunks, modelFile: ProxyTrunks}
  - &ProxyUsers {mapper: \IvozProvider\Mapper\Sql\ProxyUsers, modelFile: ProxyUsers}
  - &QueueMembers {mapper: \IvozProvider\Mapper\Sql\QueueMembers, modelFile: QueueMembers}
  - &Queues {mapper: \IvozProvider\Mapper\Sql\Queues, modelFile: Queues}
  - &Recordings {mapper: \IvozProvider\Mapper\Sql\Recordings, modelFile: Recordings}
  - &RetailAccounts {mapper: \IvozProvider\Mapper\Sql\RetailAccounts, modelFile: RetailAccounts}
  - &RetailClients {mapper: \IvozProvider\Mapper\Sql\Companies, modelFile: RetailClients}
  - &RoutingPatternGroups {mapper: \IvozProvider\Mapper\Sql\RoutingPatternGroups, modelFile: RoutingPatternGroups}
  - &RoutingPatternGroupsRelPatterns {mapper: \IvozProvider\Mapper\Sql\RoutingPatternGroupsRelPatterns, modelFile: RoutingPatternGroupsRelPatterns}
  - &RoutingPatterns {mapper: \IvozProvider\Mapper\Sql\RoutingPatterns, modelFile: RoutingPatterns}
  - &Schedules {mapper: \IvozProvider\Mapper\Sql\Schedules, modelFile: Schedules}
  - &Services {mapper: \IvozProvider\Mapper\Sql\Services, modelFile: Services}
  - &TargetPatterns {mapper: \IvozProvider\Mapper\Sql\TargetPatterns, modelFile: TargetPatterns}
  - &TerminalManufacturers {mapper: \IvozProvider\Mapper\Sql\TerminalManufacturers, modelFile: TerminalManufacturers}
  - &TerminalModels {mapper: \IvozProvider\Mapper\Sql\TerminalModels, modelFile: TerminalModels}
  - &Terminals {mapper: \IvozProvider\Mapper\Sql\Terminals, modelFile: Terminals}
  - &Timezones {mapper: \IvozProvider\Mapper\Sql\Timezones, modelFile: Timezones}
  - &TransformationRulesetGroupsTrunks {mapper: \IvozProvider\Mapper\Sql\TransformationRulesetGroupsTrunks, modelFile: TransformationRulesetGroupsTrunks}
  - &Users {mapper: \IvozProvider\Mapper\Sql\Users, modelFile: Users}
  - &XMLRPCLogs {mapper: \IvozProvider\Mapper\Sql\XMLRPCLogs, modelFile: XMLRPCLogs}
  - &AstHints {mapper: \IvozProvider\Mapper\Sql\AstHints, modelFile: AstHints}
  - &AstMusiconhold {mapper: \IvozProvider\Mapper\Sql\AstMusiconhold, modelFile: AstMusiconhold}
  - &AstPsAors {mapper: \IvozProvider\Mapper\Sql\AstPsAors, modelFile: AstPsAors}
  - &AstPsEndpoints {mapper: \IvozProvider\Mapper\Sql\AstPsEndpoints, modelFile: AstPsEndpoints}
  - &AstVoicemail {mapper: \IvozProvider\Mapper\Sql\AstVoicemail, modelFile: AstVoicemail}
  - &AstQueueMembers {mapper: \IvozProvider\Mapper\Sql\AstQueueMembers, modelFile: AstQueueMembers}
  - &AstQueues {mapper: \IvozProvider\Mapper\Sql\AstQueues, modelFile: AstQueues}
  - &Changelog {mapper: \IvozProvider\Mapper\Sql\Changelog, modelFile: Changelog}
  - &KamAccCdrsBrand {mapper: \IvozProvider\Mapper\Sql\KamAccCdrs, modelFile: KamAccCdrsBrand}
  - &KamAccCdrs {mapper: \IvozProvider\Mapper\Sql\KamAccCdrs, modelFile: KamAccCdrs}
  - &KamDispatcher {mapper: \IvozProvider\Mapper\Sql\KamDispatcher, modelFile: KamDispatcher}
  - &KamPikeTrusted {mapper: \IvozProvider\Mapper\Sql\KamPikeTrusted, modelFile: KamPikeTrusted}
  - &KamRtpproxy {mapper: \IvozProvider\Mapper\Sql\KamRtpproxy, modelFile: KamRtpproxy}
  - &KamTrunksAcc {mapper: \IvozProvider\Mapper\Sql\KamTrunksAcc, modelFile: KamTrunksAcc}
  - &KamTrunksAddress {mapper: \IvozProvider\Mapper\Sql\KamTrunksAddress, modelFile: KamTrunksAddress}
  - &KamTrunksDialplan {mapper: \IvozProvider\Mapper\Sql\KamTrunksDialplan, modelFile: KamTrunksDialplan}
  - &KamTrunksDomain {mapper: \IvozProvider\Mapper\Sql\KamTrunksDomain, modelFile: KamTrunksDomain}
  - &KamTrunksDomainAttrs {mapper: \IvozProvider\Mapper\Sql\KamTrunksDomainAttrs, modelFile: KamTrunksDomainAttrs}
  - &KamTrunksHtable {mapper: \IvozProvider\Mapper\Sql\KamTrunksHtable, modelFile: KamTrunksHtable}
  - &KamTrunksUacreg {mapper: \IvozProvider\Mapper\Sql\KamTrunksUacreg, modelFile: KamTrunksUacreg}
  - &KamUsers {mapper: \IvozProvider\Mapper\Sql\KamUsers, modelFile: KamUsers}
  - &KamUsersAcc {mapper: \IvozProvider\Mapper\Sql\KamUsersAcc, modelFile: KamUsersAcc}
  - &KamUsersAddress {mapper: \IvozProvider\Mapper\Sql\KamUsersAddress, modelFile: KamUsersAddress}
  - &KamUsersDomain {mapper: \IvozProvider\Mapper\Sql\KamUsersDomain, modelFile: KamUsersDomain}
  - &KamUsersDomainAttrs {mapper: \IvozProvider\Mapper\Sql\KamUsersDomainAttrs, modelFile: KamUsersDomainAttrs}
  - &KamUsersHtable {mapper: \IvozProvider\Mapper\Sql\KamUsersHtable, modelFile: KamUsersHtable}
  - &KamUsersLocation {mapper: \IvozProvider\Mapper\Sql\KamUsersLocation, modelFile: KamUsersLocation}
  - &KamUsersLocationAttrs {mapper: \IvozProvider\Mapper\Sql\KamUsersLocationAttrs, modelFile: KamUsersLocationAttrs}
  - &KamUsersMissedCalls {mapper: \IvozProvider\Mapper\Sql\KamUsersMissedCalls, modelFile: KamUsersMissedCalls}
  - &KamVersion {mapper: \IvozProvider\Mapper\Sql\KamVersion, modelFile: KamVersion}
