production: 
  class: \Oasis\Model\BrandOperators
  fields: 
    brandId: 
      title: _('Brand id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Oasis\Mapper\Sql\Brands
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
      default: true
    username: 
      title: _('Username')
      type: text
      required: true
      maxLength: 50
    pass: 
      title: _('Pass')
      type: password
      required: true
      adapter: Blowfish
    email: 
      title: ngettext('Email', 'Emails', 1)
      type: text
      defaultValue: 
      maxLength: 100
    active: 
      title: _('Active')
      type: select
      defaultValue: 1
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    timezoneId: 
      title: _('Timezone id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Oasis\Mapper\Sql\Timezones
          fieldName: 
            fields: 
              - tz
            template: '%tz%'
          order: tz
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      maxLength: 100
    lastname: 
      title: _('Lastname')
      type: text
      required: true
      maxLength: 100
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
