imports:
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/application_server.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/brand.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/brand_service.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/call_forward_setting.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/company.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/domain.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/extension.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/faxes_in_out.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/friend.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/invoice.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/locution.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/music_on_hold.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/outgoing_routing.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/peering_contract.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/peer_server.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/pick_up_rel_user.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/queue.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/retail_account.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/routing_pattern_group.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/routing_pattern.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/terminal_model.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/terminal.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/transformation_rule_set.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/transformation_rule.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz/user.yml" }

services:
  _defaults:
    autowire: true
    public: false
