## To get started with security, check out the documentation:
## http://symfony.com/doc/current/security.html
security:

    providers:
        admin_orm:
            id: 'Service\UserProvider::Administrator'
        user_orm:
            id: 'Service\UserProvider::User'
        any:
            chain:
                providers: ['admin_orm', 'user_orm']

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_index:
            pattern: ^/index.[^.{3,6}]/?.*$
            security: false

        api_docs:
            pattern: ^/docs.[^.{3,6}]/?.*$
            security: false

        admin_login:
            pattern:  ^/admin_login
            stateless: true
            anonymous: true
            provider: admin_orm
            user_checker: Ivoz\Provider\Domain\Service\Administrator\AdminLoginChecker
            form_login:
                check_path: /admin_login
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        user_login:
            pattern:  ^/user_login
            stateless: true
            anonymous: true
            provider: user_orm
            user_checker: Ivoz\Provider\Domain\Service\User\UserLoginChecker
            form_login:
                check_path: /user_login
                username_parameter: email
                password_parameter: password
                success_handler: Ivoz\Provider\Infrastructure\Api\Jwt\UserAuthenticationSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        web_theme:
            pattern: ^/my/web_theme$
            stateless: true
            security: false

        refresh:
            pattern:  ^/token/refresh
            stateless: true
            anonymous: true

        exchange:
            pattern:  ^/token/exchange
            stateless: true
            anonymous: true

        api:
            pattern:   ^/.+
            stateless: true
            provider: any
            guard:
                authenticators:
                    - Ivoz\Provider\Infrastructure\Api\Jwt\AdminTokenAuthenticator
                    - Ivoz\Provider\Infrastructure\Api\Jwt\UserTokenAuthenticator
                entry_point: Ivoz\Provider\Infrastructure\Api\Jwt\AdminTokenAuthenticator

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/token/exchange, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.+, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
