services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ivoz\Core\Application\Service\Assembler\DtoAssembler:
    arguments:
      $serviceContainer: '@service_container'

  Ivoz\Core\Application\Service\Assembler\EntityAssembler:
    arguments:
      $serviceContainer: '@service_container'

  ##########################################
  ## Brand
  ##########################################
  Ivoz\Provider\Application\Service\Brand\BrandAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Brand'

  Ivoz\Provider\Application\Service\Brand\BrandDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Brand'

  ##########################################
  ## BrandUrl
  ##########################################
  Ivoz\Provider\Application\Service\BrandUrl\BrandUrlAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::BrandUrl'

  Ivoz\Provider\Application\Service\BrandUrl\BrandUrlDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::BrandUrl'

  ##########################################
  ## CallCsvReport
  ##########################################
  Ivoz\Provider\Application\Service\CallCsvReport\CallCsvReportAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::CallCsvReport'

  Ivoz\Provider\Application\Service\CallCsvReport\CallCsvReportDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::CallCsvReport'

  ##########################################
  ## FaxesInOut
  ##########################################
  Ivoz\Provider\Application\Service\FaxesInOut\FaxesInOutAssembler:
    public: true
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::FaxesInOut'

  Ivoz\Provider\Application\Service\FaxesInOut\FaxesInOutDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::FaxesInOut'

  ##########################################
  ## Locution
  ##########################################
  Ivoz\Provider\Application\Service\Locution\LocutionAssembler:
    public: true
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Locution'

  Ivoz\Provider\Application\Service\Locution\LocutionDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Locution'

  ##########################################
  ## Invoice
  ##########################################
  Ivoz\Provider\Application\Service\Invoice\InvoiceAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Invoice'

  Ivoz\Provider\Application\Service\Invoice\InvoiceDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Invoice'

  ##########################################
  ## MusicOnHold
  ##########################################
  Ivoz\Provider\Application\Service\MusicOnHold\MusicOnHoldAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::MusicOnHold'

  Ivoz\Provider\Application\Service\MusicOnHold\MusicOnHoldDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::MusicOnHold'

  ##########################################
  ## Recording
  ##########################################
  Ivoz\Provider\Application\Service\Recording\RecordingAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Recording'

  Ivoz\Provider\Application\Service\Recording\RecordingDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Recording'

  ##########################################
  ## User
  ##########################################
  Ivoz\Provider\Application\Service\User\UserAssembler:
    arguments: ~

  ##########################################
  ## DestinationRateGroup
  ##########################################
  Ivoz\Provider\Application\Service\DestinationRateGroup\DestinationRateGroupAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::DestinationRateGroup'

  Ivoz\Provider\Application\Service\DestinationRateGroup\DestinationRateGroupDtoAssembler:
      arguments:
        $storagePathResolver: '@Service\StoragePathResolverCollection::DestinationRateGroup'
