services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Application\RequestId:
    public: true

  Ivoz\Core\Application\Service\CommandEventSubscriber: ~
  Ivoz\Core\Domain\Service\EntityEventSubscriber: ~

  # DomainEventPublisher calls are autocompleted on cache regenerations (Compiler fase)
  Ivoz\Core\Domain\Service\DomainEventPublisher:
     shared: true
     calls:
      - [subscribe, ['@Ivoz\Core\Application\Service\CommandEventSubscriber']]
      - [subscribe, ['@Ivoz\Core\Domain\Service\EntityEventSubscriber']]
