#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  applicationServersBlacklist: &applicationServersBlacklist
    transport: true
    from_pattern: true
    tag: true

  main:
    module: klearMatrix
    defaultScreen: applicationServersList_screen
  screens: &applicationServers_screensLink
    applicationServersList_screen: &applicationServersList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *ApplicationServers
      class: ui-silk-asterisk-yellow
      title: _("List of %s %2s", ngettext('Application Server', 'Application Servers', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/infrastructure/application_servers.html"
      fields:
        blacklist:
          <<: *applicationServersBlacklist
        options:
          title: _("Options")
          screens:
            applicationServersEdit_screen: true
          dialogs:
            applicationServersDel_dialog: true
          default: applicationServersEdit_screen
        order: &applicationServersOrder
            name: true
            ip: true
      options:
        title: _("Options")
        screens:
          applicationServersNew_screen: true
        dialogs:
          applicationServersDel_dialog: true

    applicationServersNew_screen: &applicationServersNew_screenLink
      <<: *ApplicationServers
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Application Server', 'Application Servers', 1))
      shortcutOption: N
      fields:
        blacklist:
          <<: *applicationServersBlacklist
        order:
          <<: *applicationServersOrder

    applicationServersEdit_screen: &applicationServersEdit_screenLink
      <<: *ApplicationServers
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Application Server', 'Application Servers', 1), "[format| (%item%)]")
      fields:
        blacklist:
          <<: *applicationServersBlacklist
        order:
          <<: *applicationServersOrder

  dialogs: &applicationServers_dialogsLink
    applicationServersDel_dialog: &applicationServersDel_dialogLink
      <<: *ApplicationServers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Application Server', 'Application Servers', 1))
      description: _("Do you want to delete this %s?", ngettext('Application Server', 'Application Servers', 1))
      message: _("%s successfully deleted.", ngettext('Application Server', 'Application Servers', 1))
      multiItem: 1
      labelOnList: 1

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
