#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: billableCallsList_screen

  screens: &billableCalls_screensLink
    billableCallsList_screen: &billableCallsList_screenLink
      controller: list
      rawCondition: "BillableCall.startTime >= DATESUB(CURRENT_DATE(), 1, 'YEAR')"
      csv: false
      order:
        field:
          - BillableCall.startTime
        type: desc
      pagination:
        items: 25
      <<: *BillableCalls
      class: ui-silk-application-view-list
      title: _("List of %s %2s", ngettext('External call', 'External calls', 0), "[format| (%parent%)]")
      options:
        commands:
          exportBillableCallsToCsv_command: ${auth.acls.BillableCalls.read}
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/external_calls.html"
      fields: &billableCalls_fieldsLink
        options:
          title: _("Options")
          screens:
            billableCallsView_screen: ${auth.acls.BillableCalls}
          default: billableCallsView_screen
        blacklist: &billableCalls_blacklistLink
          callid: true
          ratingPlanName: true
          destinationName: true
          carrierName: true
          endpointType: true
          endpointId: true
        order:
          startTime: true
          brand: true
          company: true
          direction: true
          caller: true
          callee: true
          duration: true
          direction: true
          price: true
          cost: true
          invoice: true
    billableCallsView_screen: &billableCallsView_screenLink
      <<: *BillableCalls
      controller: edit
      class: ui-silk-eye
      label: false
      disableSave: true
      labelOnPostAction: _("View %s %2s", ngettext('External call', 'External calls', 1), "[format| (%item%)]")
      title: _("View %s %2s", ngettext('External call', 'External calls', 1), "[format| (%item%)]")
      fields: &billableCallsView_fieldsLink
        order:
          brand: true
          company: true
          startTime: true
          duration: true
          direction: true
          caller: true
          callee: true
          price: true
          cost: true
          ratingPlanName: true
          destinationName: true
          carrierName: true
          invoice: true
          callid: true
      fixedPositions:
        group0:
          label: _("Basic Information")
          colsPerRow: 12
          fields:
            brand: 6
            company: 6
            startTime: 6
            duration: 6
            direction: 6
            caller: 6
            callee: 6
        group1:
          label: _("Billing Information")
          colsPerRow: 12
          fields:
            price: 6
            cost: 6
            ratingPlanName: 6
            destinationName: 6
            carrierName: 6
            invoice: 6
        group2:
          label: _("Extra Information")
          colsPerRow: 12
          fields:
            callid: 12
            endpointType: 8
            endpointId: 4

  dialogs:  &billableCalls_dialogsLink
    tarificateCall_dialog:
      <<: *BillableCalls
      module: default
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
      title: ngettext('Rerate call', 'Rerate calls', 1)
      labelOnList: ngettext('Rerate call', 'Rerate calls', 0)
      controller: klear-custom-tarificator
      action: tarificate-call
      class:  ui-silk-coins-add
      multiItem: true
      alwaysEnabled: false

  commands: &exportBillableCallsToCsv_commandsLink
    exportBillableCallsToCsv_command: &exportBillableCallsToCsv_commandLink
      <<: *BillableCalls
      title: _("Export to CSV")
      label: true
      module: default
      controller: klear-custom-billable-calls
      action: export-to-csv
      class:  ui-silk-page-white-database
      forcedValues: []

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
