#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include BillableCallsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: billableCallsList_screen

  screens: &billableCallsClient_screensLink
    billableCallsList_screen: &billableCallsList_screenLink
      controller: list
      order:
        field:
          - BillableCall.startTime
        type: desc
      pagination:
        items: 25
      <<: *BillableCalls
      class: ui-silk-application-view-list
      title: _("List of %s %2s", ngettext('Call registry', 'Call registries', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/calls/external_calls.html"
      fields: &billableCalls_fieldsLink
        options:
          title: _("Options")
          screens:
            billableCallsView_screen: ${auth.acls.BillableCalls.read}
          default: billableCallsView_screen
        blacklist:
          brand: true
          company: true
          invoice: true
          callid: true
          carrierName: true
          ddiProvider: true
          cost: true
          destinationName: true
          ratingPlanName: true
          endpointType: true
          endpointId: true
          endpointName: true
        order:
          startTime: true
          direction: true
          brand: true
          company: true
          caller: true
          callee: true
          duration: true
          price: true
          cost: true
      options: &billableCalls_optionsLink
        title: _("Options")
        commands:
          exportBillableCallsToCsv_command: ${auth.acls.BillableCalls.read}
    billableCallsView_screen:
      <<: *BillableCalls
      controller: edit
      class: ui-silk-eye
      label: false
      disableSave: true
      labelOnPostAction: _("View %s %2s", ngettext('Call registry', 'Call registries', 1), "[format| (%item%)]")
      title: _("View %s %2s", ngettext('Call registry', 'Call registries', 1), "[format| (%item%)]")
      fields:
        blacklist:
          brand: true
          company: true
          carrierName: true
          ddiProvider: true
          invoice: true
          cost: true
        order:
          startTime: true
          duration: true
          callee: true
          price: true
      fixedPositions:
        group0:
          label: _("Basic Information")
          colsPerRow: 12
          fields:
            startTime: 6
            duration: 6
            direction: 6
            __empty: 6
            caller: 6
            callee: 6
        group1:
          label: _("Billing Information")
          colsPerRow: 16
          fields:
            price: 4
            ratingPlanName: 6
            destinationName: 6
        group2:
          label: _("Extra Information")
          colsPerRow: 12
          fields:
            callid: 12
            endpointType: 4
            endpointId: 4
            endpointName: 4
  dialogs:
    <<: *billableCalls_dialogsLink

  commands: &exportBillableCallsToCsv_commandsLink
    exportBillableCallsToCsv_command: &exportBillableCallsToCsv_commandLink
      <<: *BillableCalls
      title: _("Export to CSV")
      label: true
      module: default
      controller: klear-custom-billable-calls
      action: export-to-csv
      class:  ui-silk-page-white-database
      forcedValues:
        "company": ${auth.companyId}

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
