#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: brandOperatorsList_screen
  screens: &brandOperators_screensLink
    brandOperatorsList_screen: &brandOperatorsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *BrandOperators
      class: ui-silk-user-suit
      title: _("List of %s %2s", ngettext('Brand operator', 'Brand operators', 0), "[format| (%parent%)]")
      fields:
        options:
          title: _("Options")
          screens:
            brandOperatorsEdit_screen: true
          dialogs:
            brandOperatorsDel_dialog: true
          default: brandOperatorsEdit_screen
        order: &BrandOperators_orderLink
          brand: true
          name: true
          lastname: true
          email: true
          username: true
          pass: true
          timezone: true
          active: true
          name: true
          lastname: true
        blacklist:
          pass: true
          timezone: true
          email: true
          name: true
          lastname: true
      options:
        title: _("Options")
        screens:
          brandOperatorsNew_screen: true
        dialogs:
          brandOperatorsDel_dialog: true
    brandOperatorsNew_screen: &brandOperatorsNew_screenLink
      <<: *BrandOperators
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s %2s", ngettext('Brand operator', 'Brand operators', 1), "[format| (%parent%)]")
      shortcutOption: N
      fields:
        blacklist:
            active: true
        order:
          <<: *BrandOperators_orderLink
      fixedPositions: &BrandOperatorsFixedPositions_link
        group0:
          label: _("Login Info")
          colsPerRow: 2
          fields:
            username: 1
            pass: 1
            active: 1
            timezoneId: 1
        group1:
          label: _("Personal data")
          colsPerRow: 3
          collapsed: true
          fields:
            name: 1
            lastname: 1
            email: 1
    brandOperatorsEdit_screen: &brandOperatorsEdit_screenLink
      <<: *BrandOperators
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Brand operator', 'Brand operators', 1), "[format| (%item%)]")
      fields:
        order:
          <<: *BrandOperators_orderLink
      fixedPositions:
        <<: *BrandOperatorsFixedPositions_link
  dialogs: &brandOperators_dialogsLink
    brandOperatorsDel_dialog: &brandOperatorsDel_dialogLink
      <<: *BrandOperators
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Brand operator', 'Brand operators', 1))
      description: _("Do you want to delete this %s?", ngettext('Brand operator', 'Brand operators', 1))
      message: _("%s successfully deleted.", ngettext('Brand operator', 'Brand operators', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
