#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: brandURLsList_screen
  screens: &brandURLs_screensLink
    brandURLsList_screen: &brandURLsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *BrandURLs
      class: ui-silk-world-link
      title: _("List of %s %2s", ngettext('Brand URL', 'Brand URLs', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/brands.html#brand-urls"
      fields: &brandURLs_fieldsLink
        options:
          title: _("Options")
          screens:
            brandURLsEdit_screen: true
          dialogs:
            brandURLsDel_dialog: true
          default: brandURLsEdit_screen
        blacklist:
          klearTheme: true
          userTheme: true
        order: &brandURLsOrder_Link
          name: true
          urlType: true
          url: true
          logo: true
      options:
        title: _("Options")
        screens:
          brandURLsNew_screen: true
        dialogs:
          brandURLsDel_dialog: true
    brandURLsNew_screen: &brandURLsNew_screenLink
      <<: *BrandURLs
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Brand URL', 'Brand URLs', 1), "[format| (%parent%)]")
      shortcutOption: N
      fields:
        order:
          <<: *brandURLsOrder_Link
      fixedPositions: &brandURLsFixedPos_Link
        group0:
          colsPerRow: 8
          fields:
            name: 5
            urlType: 2
            url: 7
        group1:
          colsPerRow: 3
          fields:
            klearTheme: 1
            userTheme: 1
            logo: 2
    brandURLsEdit_screen: &brandURLsEdit_screenLink
      <<: *BrandURLs
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Brand URL', 'Brand URLs', 1), "[format| (%item%)]")
      fields:
        order:
          <<: *brandURLsOrder_Link
      fixedPositions:
        <<: *brandURLsFixedPos_Link
  dialogs: &brandURLs_dialogsLink
    brandURLsDel_dialog: &brandURLsDel_dialogLink
      <<: *BrandURLs
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Brand URL', 'Brand URLs', 1))
      description: _("Do you want to delete this %s?", ngettext('Brand URL', 'Brand URLs', 1))
      message: _("%s successfully deleted.", ngettext('Brand URL', 'Brand URLs', 1))
      multiItem: 1
      labelOnList: 1

  commands: &brandURLs_commandsLink
    brandURLsLogoDownload_command: &brandURLsLogoDownload_commandLink
      <<: *BrandURLs
      controller: File
      action: force-download
      mainColumn: logo
    brandURLsLogoUpload_command: &brandURLsLogoUpload_commandLink
      <<: *BrandURLs
      controller: File
      action: upload
      mainColumn: logo
    brandURLsLogoPreview_command: &brandURLsLogoPreview_commandLink
      <<: *BrandURLs
      controller: File
      action: preview
      mainColumn: logo
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
