#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include AdministratorsList.yaml
#include BrandPortalsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: brandsList_screen
  screens:
    brandsList_screen: &brandsList_screenLink
      controller: list
      order:
        field:
        - Brand.name
        type: asc
      pagination:
        items: 25
      <<: *Brands
      class: ui-silk-world
      title: _("List of %s %2s", ngettext('Brand', 'Brands', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/brands.html"
      fields:
        order:
          name: true
          invoice.nif: true
          logo: true
          invoice.postalCode: true
          domainUsers: true
          relProxyTrunks: true
          relFeatures: true
        blacklist:
          domain_trunks: true
          iden: true
          invoice.postalAddress: true
          invoice.province: true
          invoice.country: true
          invoice.town: true
          invoice.registryData: true
          language: true
          defaultTimezone: true
          currency: true
          voicemailNotificationTemplate: true
          faxNotificationTemplate: true
          invoiceNotificationTemplate: true
          callCsvNotificationTemplate: true
          maxDailyUsageNotificationTemplate: true
          recordingsLimitMB: true
          recordingsLimitEmail: true
          recordingsDiskUsage: true
          maxCalls: true
        options:
          title: _("Options")
          screens:
            brandsEdit_screen: true
            administratorsList_screen: true
            brandPortalsList_screen: true
          dialogs:
            emulateBrand_dialog: true
            brandsDel_dialog: false
          default: brandsEdit_screen
      options:
        title: _("Options")
        screens:
          brandsNew_screen: true
        dialogs:
          brandsDel_dialog: true

    brandsNew_screen: &brandsNew_screenLink
      <<: *Brands
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Brand', 'Brands', 1))
      shortcutOption: N
      forcedValues:
        invoice.nif: '12345678-Z'
        invoice.postalAddress: 'Postal address'
        invoice.postalCode: 'ZIP'
        invoice.town: 'town'
        invoice.country: 'country'
        invoice.province: 'province'
        invoice.registryData: 'registryData'
      fields:
        blacklist:
          invoice.nif: true
          logo: true
          invoice.postalAddress: true
          invoice.postalCode: true
          invoice.town: true
          invoice.province: true
          invoice.country: true
          invoice.registryData: true
          voicemailNotificationTemplate: true
          faxNotificationTemplate: true
          invoiceNotificationTemplate: true
          callCsvNotificationTemplate: true
          maxDailyUsageNotificationTemplate: true
          recordingsLimitMB: true
          recordingsDiskUsage: true
          recordingsDiskAvailable: true
          recordingsLimitEmail: true
        order: &brandsOrder_Link
          name: true
          invoice.nif: true
          relProxyTrunks: true
          relFeatures: true
          logo: true
          maxCalls: true
          defaultTimezone: true
          language: true
          domainUsers: true
          invoice.postalAddress: true
          invoice.postalCode: true
          invoice.town: true
          invoice.province: true
          invoice.country: true
          invoice.registryData: true
      fixedPositions: &brandsFixedPositions_Link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 2
          fields:
            name: 1
            invoice.nif: 1
            relProxyTrunks: 1
            relFeatures: 1
            logo: 1
            maxCalls: 1
        group2:
          label: _("Locales")
          colsPerRow: 3
          fields:
            defaultTimezone: 1
            language: 1
            currency: 1
        group3:
          colsPerRow: 2
          label: _("Invoice data")
          fields:
            invoice.postalAddress: 2
            invoice.postalCode: 1
            invoice.town: 1
            invoice.province: 1
            invoice.country: 1
            invoice.registryData: 2
        group4:
          colsPerRow: 4
          label: _("SIP domain")
          fields:
            domainUsers: 2
        group5:
          colsPerRow: 2
          collapsed: true
          label: _("Notification options")
          fields:
            voicemailNotificationTemplate: 1
            faxNotificationTemplate: 1
            invoiceNotificationTemplate: 1
            callCsvNotificationTemplate: 1
            maxDailyUsageNotificationTemplate: 1

    brandsEdit_screen: &brandsEdit_screenLink
      <<: *Brands
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Brand', 'Brands', 1), "[format| (%item%)]")
      fields:
        blacklist:
          recordingsLimitMB: true
          recordingsDiskUsage: true
          recordingsDiskAvailable: true
          recordingsLimitEmail: true
        order:
          <<: *brandsOrder_Link
      fixedPositions:
        <<: *brandsFixedPositions_Link

    # Administrators
    <<: *administrators_screensLink
    administratorsList_screen:
      <<: *administratorsList_screenLink
      class: ui-silk-user-suit
      title: _("List of %s %2s", ngettext('Brand operator', 'Brand operators', 0), "[format| (%parent%)]")
      filterField: Brand
      forcedValues:
        "self::company": null
      parentOptionCustomizer:
        - recordCount

    administratorsNew_screen:
      <<: *administratorsNew_screenLink
      title: _("Add %s %2s", ngettext('Brand operator', 'Brand operators', 1), "[format| (%parent%)]")
      filterField: Brand
      fields:
        <<: *administratorsFields
        blacklist:
          <<: *administratorsBlacklist
          timezone: true

    administratorsEdit_screen:
      <<: *administratorsEdit_screenLink
      title: _("Edit %s %2s", ngettext('Brand operator', 'Brand operators', 1), "[format| (%item%)]")
      filterField: Brand

    # Brand Portals
    <<: *brandPortals_screensLink
    brandPortalsList_screen:
      <<: *brandPortalsList_screenLink
      filterField: Brand
      parentOptionCustomizer:
        - recordCount
    brandPortalsNew_screen:
      <<: *brandPortalsNew_screenLink
      filterField: Brand
    brandPortalsEdit_screen:
      <<: *brandPortalsEdit_screenLink
      filterField: Brand

  dialogs:
    brandsDel_dialog: &brandsDel_dialogLink
      <<: *Brands
      controller: delete
      secureDelete: true
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Brand', 'Brands', 1))
      description: _("Do you want to delete this %s?", ngettext('Brand', 'Brands', 1))
      message: _("%s successfully deleted.", ngettext('Brand', 'Brands', 1))
      multiItem: 1
      labelOnList: 1

    emulateBrand_dialog:
      title: _("Emulate Brand %s", "[format| (%item%)]")
      module: default
      controller: klear-custom-extra-auth
      action: emulate
      class: ui-silk-world-add
      label: false
      labelOnEdit: false
      labelOnList: false
      labelOnEntityPostSave: false
      multiItem: false
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer

    # Administrators dialogs
    <<: *administrators_dialogsLink
    administratorsDel_dialog:
      <<: *administratorsDel_dialogLink
      title: _("Delete %s", ngettext('Brand operator', 'Brand operators', 1))
      description: _("Do you want to delete this %s?", ngettext('Brand operator', 'Brand operators', 1))
      message: _("%s successfully deleted.", ngettext('Brand operator', 'Brand operators', 1))

    # Brand URLs dialogs
    <<: *brandPortals_dialogsLink

  commands: &brands_commandsLink
    brandsLogoDownload_command: &brandsLogoDownload_commandLink
      <<: *Brands
      controller: File
      action: force-download
      mainColumn: logo
    brandsLogoUpload_command: &brandsLogoUpload_commandLink
      <<: *Brands
      controller: File
      action: upload
      mainColumn: logo
    brandsLogoPreview_command: &brandsLogoPreview_commandLink
      <<: *Brands
      controller: File
      action: preview
      mainColumn: logo

    # Brand URLs commands
    <<: *brandPortals_commandsLink

testing:
  _extends: production
staging:
  _extends: production
development:
  _extends: production
