#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include HolidayDatesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: calendarsList_screen
  screens: &calendars_screensLink
    calendarsList_screen: &calendarsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Calendars
      class: ui-silk-calendar
      title: _("List of %s %2s", ngettext('Calendar', 'Calendars', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/routing_tools/calendars.html"
      forcedValues:
        <<: *forcedCompany
      fields:
        options:
          title: _("Options")
          screens:
            calendarsEdit_screen: true
            holidayDatesList_screen: true
          dialogs:
            calendarsDel_dialog: true
          default: calendarsEdit_screen
      options:
        title: _("Options")
        screens:
          calendarsNew_screen: true
        dialogs:
          calendarsDel_dialog: true
    calendarsNew_screen: &calendarsNew_screenLink
      <<: *Calendars
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s %2s", ngettext('Calendar', 'Calendars', 1), "[format| (%parent%)]")
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
    calendarsEdit_screen: &calendarsEdit_screenLink
      <<: *Calendars
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Calendar', 'Calendars', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
    #HolidayDates
    <<: *holidayDates_screensLink
    holidayDatesList_screen:
      <<: *holidayDatesList_screenLink
      filterField: Calendar
      parentOptionCustomizer:
        - recordCount

    holidayDatesNew_screen:
      <<: *holidayDatesNew_screenLink
      filterField: Calendar
    holidayDatesEdit_screen:
      <<: *holidayDatesEdit_screenLink

  dialogs: &calendars_dialogsLink
    calendarsDel_dialog: &calendarsDel_dialogLink
      <<: *Calendars
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Calendar', 'Calendars', 1))
      description: _("Do you want to delete this %s?", ngettext('Calendar', 'Calendars', 1))
      message: _("%s successfully deleted.", ngettext('Calendar', 'Calendars', 1))
      multiItem: 1
      labelOnList: 1

    #HolidayDates
    <<: *holidayDates_dialogsLink
  commands:
    <<: *holidayDates_commandsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
