#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include CallAclRelMatchListsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: callACLList_screen
  screens: &callACL_screensLink
    callACLList_screen: &callACLList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *CallACL
      class: ui-silk-telephone-key
      title: _("List of %s %2s", ngettext('Call ACL', 'Call ACLs', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/user_configuration/call_acls.html"
      forcedValues:
        <<: *forcedCompany
      fields:
        options:
          title: _("Options")
          screens:
            callACLEdit_screen: $[${auth.acls.CallACL.update} && ${auth.companyVPBX}]
          dialogs:
            callACLDel_dialog: $[${auth.acls.CallACL.delete} && ${auth.companyVPBX}]
          default: callACLEdit_screen
        blacklist:
          CallAclRelMatchLists: true
      options:
        title: _("Options")
        screens:
          callACLNew_screen: $[${auth.acls.CallACL.create} && ${auth.companyVPBX}]
        dialogs:
          callACLDel_dialog: $[${auth.acls.CallACL.delete} && ${auth.companyVPBX}]
    callACLNew_screen: &callACLNew_screenLink
      <<: *CallACL
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s %2s", ngettext('Call ACL', 'Call ACLs', 1), "[format| (%parent%)]")
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          CallAclRelMatchLists: true
    callACLEdit_screen: &callACLEdit_screenLink
      <<: *CallACL
      controller: edit
      class: ui-silk-pencil
      label: false
      forcedValues:
        <<: *forcedCompany
      title: _("Edit %s %2s", ngettext('Call ACL', 'Call ACLs', 1), "[format| (%item%)]")
      fields:
        order:
          name: true
          defaultPolicy: true
          CallAclRelMatchLists: true
      fixedPositions:
        group0:
          label: _("ACL data")
          colsPerRow: 3
          fields:
            name: 2
            defaultPolicy: 1
        group1:
          label: ngettext('Call ACL MatchList', 'Call ACL MatchLists', 0)
          colsPerRow: 3
          fields:
            CallAclRelMatchLists: 3

    # callACLRelMatchLists
    <<: *callACLRelMatchLists_screensLink
    callACLRelMatchListsList_screen:
      <<: *callACLRelMatchListsList_screenLink
      title: _("List of %s %2s", ngettext('Call ACL MatchList', 'Call ACL MatchLists', 0), "[format| (%parent%)]")
      filterField: callACL
    callACLRelMatchListsNew_screen:
      <<: *callACLRelMatchListsNew_screenLink
      title: _("Add pattern to %2s", "[format| %parent%]")
      filterField: callACL
    callACLRelMatchListsEdit_screen:
      <<: *callACLRelMatchListsEdit_screenLink
      filterField: callACL
      title: _("Edit pattern of %s", ngettext('Call ACL MatchList', 'Call ACL MatchLists', 1))

  dialogs: &callACL_dialogsLink
    callACLDel_dialog: &callACLDel_dialogLink
      <<: *CallACL
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Call ACL', 'Call ACLs', 1))
      description: _("Do you want to delete this %s?", ngettext('Call ACL', 'Call ACLs', 1))
      message: _("%s successfully deleted.", ngettext('Call ACL', 'Call ACLs', 1))
      multiItem: 1
      labelOnList: 1

    # callACLRelMatchLists
    <<: *callACLRelMatchLists_dialogsLink
    callACLRelMatchListsDel_dialog:
      <<: *callACLRelMatchListsDel_dialogLink
      title: _("Delete %s", ngettext('Call ACL Pattern', 'Call ACL Patterns', 1))
      description: _("Do you want to delete this %s?", ngettext('Call ACL Pattern', 'Call ACL Patterns', 1))
      message: _("%s successfully deleted.", ngettext('Call ACL Pattern', 'Call ACL Patterns', 1))

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
