#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include AdministratorsList.yaml
#include PricingPlansRelCompaniesList.yaml
#include RatingProfilesList.yaml
#include KamUsersAddressList.yaml
#include IpFilterBlockedAddressesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: companiesList_screen
  screens: &companies_screensLink
    companiesList_screen: &companiesList_screenLink
      controller: list
      order:
        field:
        - Company.name
        type: asc
      pagination:
        items: 25
      <<: *Companies
      class: ui-silk-building
      title: _("List of %s %2s", ngettext('Virtual PBX', 'Virtual PBXs', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/clients/virtual_pbx.html"
      forcedValues:
        type: 'vpbx'
        <<: *forcedBrand
      fields:
        options:
          title: _("Options")
          screens:
            companiesEdit_screen: ${auth.acls.Companies.update}
            kamUsersAddressList_screen: true
            ipFilterBlockedAddressList_screen: true
            administratorsList_screen: true
            ratingProfilesList_screen: ${auth.brandFeatures.billing.enabled}
          dialogs:
            companiesDel_dialog: false
            emulateCompany_dialog: true
          default: companiesEdit_screen
        blacklist:
          typeIcon: true
          transformationRuleSet: true
          postalAddress: true
          postalCode: true
          town: true
          province: true
          countryName: true
          outgoingDdiRule: true
          registryData: true
          maxCalls: true
          defaultTimezone: true
          currency: true
          distributeMethod: true
          applicationServer: true
          mediaRelaySets: true
          ipFilter: true
          language: true
          onDemandRecord: true
          onDemandRecordCode: true
          recordingsLimitMB: true
          recordingsLimitEmail: true
          recordingsDiskUsage: true
          voicemailNotificationTemplate: true
          faxNotificationTemplate: true
          invoiceNotificationTemplate: true
          callCsvNotificationTemplate: true
          balance: true
          currentDayUsage: true
          currentDayMaxUsage: true
          accountStatus: true
          country: true
          showInvoices: true
          outgoingDdi: true
          maxDailyUsage: true
          allowRecordingRemoval: true
          externallyExtraOpts: true
        order:
          name: true
          nif: true
          billingMethod: true
          outgoingDdiE164: true
          domainUsers: true
          relFeatures: true
      options:
        title: _("Options")
        screens:
          companiesNew_screen: ${auth.acls.Companies.create}
        dialogs:
          companiesDel_dialog: ${auth.acls.Companies.delete}
          importCompanies_dialog: false
      csv:
        active: false
        filename: "Companies"
        headers: true
        enclosure: '"'
        separator: ";"
        nameklear: false
        rawValues: true
        ignoreBlackList: true
        newLine: "\r\n"
        encoding: "utf-8"
        executionSeconds: ""

    companiesNew_screen: &companiesNew_screenLink
      <<: *Companies
      controller: new
      fields:
        blacklist:
          nif: true
          type: true
          typeIcon: true
          postalAddress: true
          postalCode: true
          town: true
          province: true
          onDemandRecord: true
          onDemandRecordCode: true
          mediaRelaySets: true
          distributeMethod: true
          applicationServer: true
          countryName: true
          outgoingDdi: true
          outgoingDdiRule: true
          externallyExtraOpts: true
          recordingsLimitMB: true
          recordingsLimitEmail: true
          recordingsDiskUsage: true
          voicemailNotificationTemplate: true
          invoiceNotificationTemplate: true
          callCsvNotificationTemplate: true
          faxNotificationTemplate: true
          balance: true
          showInvoices: true
          outgoingDdiE164: true
          currentDayUsage: true
          currentDayMaxUsage: true
          accountStatus: true
          allowRecordingRemoval: true
        order: &companiesOrder_Link
          id: true
          name: true
          maxCalls: true
          maxDialyUsage: true
          language: true
          outgoingDdi: true
          showInvoices: true
          onDemandRecord: true
          voicemailNotificationTemplate: true
      fixedPositions:
        group0:
          colsPerRow: 6
          label: _("Basic Configuration")
          fields:
            name: 3
            domainUsers: 3
            relFeatures: 3
            billingMethod: 3
        group1:
          colsPerRow: 3
          label: _("Security")
          fields:
            maxCalls: 1
            ipFilter: 1
            maxDailyUsage: 1
        group2:
          colsPerRow: 3
          label: _("Geographic Configuration")
          fields:
            country: 1
            defaultTimezone: 1
            language: 1
            transformationRuleSet: 2
            currency: 1
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Virtual PBX', 'Virtual PBXs', 1))
      shortcutOption: N
      forcedValues:
        type: "vpbx"
        <<: *forcedBrand
        nif: '12345678-Z'
        postalAddress: 'Postal address'
        postalCode: 'PC'
        town: 'Town'
        countryName: 'Country'
        province: 'Province'

    companiesEdit_screen: &companiesEdit_screenLink
      <<: *Companies
      controller: edit
      fields:
        blacklist:
          type: true
          typeIcon: true
          distributeMethod: ${auth.isNotMainOperator}
          applicationServer: ${auth.isNotMainOperator}
          mediaRelaySets: ${auth.isNotMainOperator}
          recordingsLimitMB: ${auth.brandFeatures.recordings.disabled}
          recordingsLimitEmail: ${auth.brandFeatures.recordings.disabled}
          recordingsDiskUsage: ${auth.brandFeatures.recordings.disabled}
          onDemandRecord: ${auth.brandFeatures.recordings.disabled}
          onDemandRecordCode: ${auth.brandFeatures.recordings.disabled}
          nif: ${auth.brandFeatures.invoices.disabled}
          postalAddress: ${auth.brandFeatures.invoices.disabled}
          postalCode: ${auth.brandFeatures.invoices.disabled}
          town: ${auth.brandFeatures.invoices.disabled}
          province: ${auth.brandFeatures.invoices.disabled}
          countryName: ${auth.brandFeatures.invoices.disabled}
          invoiceNotificationTemplate: ${auth.brandFeatures.invoices.disabled}
          recordingsLimitMB: true
          recordingsLimitEmail: true
          recordingsDiskUsage: true
          outgoingDdiE164: true
          balance: true
          currentDayUsage: true
          currentDayMaxUsage: true
          accountStatus: true
        whitelist:
          id: ${auth.isMainOperator}
        order:
          <<: *companiesOrder_Link
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Virtual PBX', 'Virtual PBXs', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fixedPositions: &companiesFixedPositions_Link
        group0:
          colsPerRow: 6
          label: _("Basic Configuration")
          fields:
            name: 3
            domainUsers: 3
            relFeatures: 3
            billingMethod: 3
        group1:
          colsPerRow: 3
          label: _("Security")
          fields:
            maxCalls: 1
            ipFilter: 1
            maxDailyUsage: 1
        group2:
          colsPerRow: 3
          label: _("Geographic Configuration")
          fields:
            language: 1
            country: 1
            defaultTimezone: 1
            transformationRuleSet: 2
            currency: 1
        group3:
          colsPerRow: 12
          collapsed: true
          label: _("Platform data")
          fields:
            outgoingDdi: 6
            outgoingDdiRule: 6
            domain_users: 9
            mediaRelaySets: 4
            distributeMethod: 4
            applicationServer: 4
        group4:
          colsPerRow: 12
          collapsed: true
          label: _("Invoice data")
          fields:
            showInvoices: 6
            nif: 6
            postalAddress: 8
            postalCode: 4
            town: 4
            province: 4
            countryName: 4
        group5:
          colsPerRow: 12
          label: ngettext('Recording', 'Recordings', 0)
          collapsed: true
          fields:
            onDemandRecord: 6
            allowRecordingRemoval: 6
            onDemandRecordCode: 6
        group6:
          colsPerRow: 1
          collapsed: true
          label: _("Externally rater options")
          fields:
            externallyExtraOpts: 1
        group7:
          colsPerRow: 2
          collapsed: true
          label: _("Notification options")
          fields:
            voicemailNotificationTemplate: 1
            faxNotificationTemplate: 1
            invoiceNotificationTemplate: 1
            callCsvNotificationTemplate: 1

    # Administrators
    <<: *administrators_screensLink
    administratorsList_screen:
      <<: *administratorsList_screenLink
      class: ui-silk-user-gray
      title: _("List of %s %2s", ngettext('Client admin', 'Client admins', 0), "[format| (%parent%)]")
      filterField: Company
      parentOptionCustomizer:
        - recordCount
    administratorsNew_screen:
      <<: *administratorsNew_screenLink
      title: _("Add %s", ngettext('Client admin', 'Client admins', 1), "[format| (%parent%)]")
      filterField: Company
      forcedValues:
        <<: *forcedBrand
      fields:
        <<: *administratorsFields
        blacklist:
          <<: *administratorsBlacklist
          timezone: true
    administratorsEdit_screen:
      <<: *administratorsEdit_screenLink
      title: _("Edit %s %2s", ngettext('Client admin', 'Client admins', 1), "[format| (%item%)]")
      filterField: Company
      forcedValues:
        <<: *forcedBrand
      fields:
        <<: *administratorsFields
        blacklist:
          <<: *administratorsBlacklist
          timezone: true

    # AdministratorRelPublicEntities screens
    administratorRelPublicEntitiesList_screen:
      <<: *administratorRelPublicEntitiesList_screenLink
      filterField: Administrator

    administratorRelPublicEntitiesEdit_screen:
      <<: *administratorRelPublicEntitiesEdit_screenLink
      filterField: Administrator

    # Rating Profiles:
    <<: *ratingProfiles_screensLink
    ratingProfilesList_screen:
      <<: *ratingProfilesList_screenLink
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/billing/rating_plans.html#assigning-rating-plans-to-clients"
      filterField: company
      forcedValues:
        "self::routingTag": null
      parentOptionCustomizer:
        - recordCount
    ratingProfilesNew_screen:
      <<: *ratingProfilesNew_screenLink
      filterField: company
      forcedValues:
        "self::routingTag": null
    ratingProfilesEdit_screen:
      <<: *ratingProfilesEdit_screenLink
      filterField: company
      forcedValues:
        "self::routingTag": null

    #kamUsersAddress:
    kamUsersAddressList_screen:
      <<: *kamUsersAddressList_screenLink
      filterField: Company
      parentOptionCustomizer:
        - recordCount
    kamUsersAddressNew_screen:
      <<: *kamUsersAddressNew_screenLink
      filterField: Company
    kamUsersAddressEdit_screen:
      <<: *kamUsersAddressEdit_screenLink
      filterField: Company

    #bannedAddress:
    ipFilterBlockedAddressList_screen:
      <<: *ipFilterBlockedAddressList_screenLink
      filterField: Company
      parentOptionCustomizer:
        - recordCount

  dialogs: &companies_dialogsLink
    companiesDel_dialog: &companiesDel_dialogLink
      <<: *Companies
      controller: delete
      class: ui-silk-bin
      secureDelete: true
      labelOption: false
      title: _("Delete %s", ngettext('Virtual PBX', 'Virtual PBXs', 1))
      description: _("Do you want to delete this %s?", ngettext('Virtual PBX', 'Virtual PBXs', 1))
      message: _("%s successfully deleted.", ngettext('Virtual PBX', 'Virtual PBXs', 1))
      multiItem: 1
      labelOnList: 1

    emulateCompany_dialog:
      title: _("Emulate Company %s", "[format| (%item%)]")
      module: default
      controller: klear-custom-extra-auth
      action: emulate
      class: ui-silk-building-go
      label: false
      labelOnEdit: false
      labelOnList: false
      labelOnEntityPostSave: false
      multiItem: false
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer

    importCompanies_dialog:
      <<: *Companies
      module: default
      title: _("Import %s", ngettext('Virtual PBX', 'Virtual PBXs', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-file
      action: import
      class:  ui-silk-page-gear
      freeUploadCommand: importCompaniesFreeUpload_command
      delimiter: ";"
      enclosure: '"'
      escape: "\\"
      forcedValues:
        <<: *forcedBrand

    # ratingProfiles:
    <<: *ratingProfiles_dialogsLink
    <<: *simulateCall_dialogLink

    # Administrators dialogs
    <<: *administrators_dialogsLink
    administratorsDel_dialog:
      <<: *administratorsDel_dialogLink
      title: _("Delete %s", ngettext('Client admin', 'Client admins', 1))
      description: _("Do you want to delete this %s?", ngettext('Client admin', 'Client admins', 1))
      message: _("%s successfully deleted.", ngettext('Client admin', 'Client admins', 1))

    # kamUsersAddress dialogs:
    <<: *kamUsersAddress_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
