#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include BrandURLsList.yaml

# This yaml handles CompanyURLs screens
# We call CompanyURLs to the BrandURLs that have urlType 'admin' or 'user', so both
# views share the same database table, while the list have special conditions and the
# urlType in CompanyURLs have only 'admin' and 'user' available.

production:
  main:
    module: klearMatrix
    defaultScreen: companyURLsList_screen
  screens: &companyURLs_screensLink
    companyURLsList_screen: &companyURLsList_screenLink
      controller: list
      rawCondition: "BrandUrl.urlType IN ('admin', 'user')"
      forcedValues:
        <<: *forcedBrand
      pagination:
        items: 25
      <<: *CompanyURLs
      class: ui-silk-world-link
      title: _("List of %s %2s", ngettext('Company URL', 'Company URLs', 0), "[format| (%parent%)]")
      fields: &companyURLs_fieldsLink
        options:
          title: _("Options")
          screens:
            companyURLsEdit_screen: true
          dialogs:
            companyURLsDel_dialog: true
          default: companyURLsEdit_screen
        blacklist:
          klearTheme: true
          userTheme: true
        order: &companyURLsOrder_Link
          name: true
          urlType: true
          url: true
          logo: true
      options:
        title: _("Options")
        screens:
          companyURLsNew_screen: true
        dialogs:
          companyURLsDel_dialog: true
    companyURLsNew_screen: &companyURLsNew_screenLink
      <<: *CompanyURLs
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Company URL', 'Company URLs', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fields:
        order:
          <<: *companyURLsOrder_Link
      fixedPositions: &companyURLsFixedPos_Link
        group0:
          colsPerRow: 8
          fields:
            name: 5
            urlType: 2
            url: 7
        group1:
          colsPerRow: 3
          fields:
            klearTheme: 1
            userTheme: 1
            logo: 2
    companyURLsEdit_screen: &companyURLsEdit_screenLink
      <<: *CompanyURLs
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Company URL', 'Company URLs', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *companyURLsOrder_Link
      fixedPositions:
        <<: *companyURLsFixedPos_Link
  dialogs: &companyURLs_dialogsLink
    companyURLsDel_dialog: &companyURLsDel_dialogLink
      <<: *CompanyURLs
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Company URL', 'Company URLs', 1))
      description: _("Do you want to delete this %s?", ngettext('Company URL', 'Company URLs', 1))
      message: _("%s successfully deleted.", ngettext('Company URL', 'Company URLs', 1))
      multiItem: 1
      labelOnList: 1

  commands:
    <<: *brandURLs_commandsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
