#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include CompanyAdminsList.yaml
#include PricingPlansRelCompaniesList.yaml
#include OutgoingRoutingList.yaml
#include KamUsersAddressList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: companiesList_screen
  screens: &companies_screensLink
    companiesList_screen: &companiesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Companies
      class: ui-silk-building
      title: _("List of %s %2s", ngettext('Company', 'Companies', 0), "[format| (%parent%)]")
      forcedValues:
        type: 'vpbx'
        <<: *forcedBrand
      fields:
        options:
          title: _("Options")
          screens:
            companiesEdit_screen: true
            kamUsersAddressList_screen: true
            companyAdminsList_screen: true
            pricingPlansRelCompaniesList_screen: ${auth.brand.billing.enabled}
            outgoingRoutingList_screen: true
          dialogs:
            companiesDel_dialog: false
            emulateCompany_dialog: true
          default: companiesEdit_screen
        blacklist:
          transformationRulesetGroup: true
          postalAddress: true
          postalCode: true
          town: true
          province: true
          countryName: true
          areaCode: true
          outgoingDDIId: true
          outgoingDdiRuleId: true
          registryData: true
          externalMaxCalls: true
          defaultTimezoneId: true
          distributeMethod: true
          applicationServerId: true
          mediaRelaySetsId: true
          ipFilter: true
          languageId: true
          outboundPrefix: true
          onDemandRecord: true
          onDemandRecordCode: true
          recordingsLimitMB: true
          recordingsLimitEmail: true
          externallyExtraOpts: true
#          type: true
          recordingsDiskUsage: ${auth.brand.recordings.disabled}
        order:
          name: true
          nif: true
          outboundPrefix: true
          countryId: true
          domainUsers: true
          recordingsDiskUsage: true
      options:
        title: _("Options")
        screens:
          companiesNew_screen: true
        dialogs:
          companiesDel_dialog: true
          importCompanies_dialog: false
      csv:
        active: false
        filename: "Companies"
        headers: true
        enclosure: '"'
        separator: ";"
        nameklear: false
        rawValues: true
        ignoreBlackList: true
        newLine: "\r\n"
        encoding: "utf-8"
        executionSeconds: ""

    companiesNew_screen: &companiesNew_screenLink
      <<: *Companies
      controller: new
      fields:
        blacklist:
          transformationRulesetGroups: true
          nif: true
          type: true
          postalAddress: true
          postalCode: true
          town: true
          province: true
          countryId: true
          onDemandRecord: true
          onDemandRecordCode: true
          mediaRelaySetsId: true
          outboundPrefix: true
          distributeMethod: true
          applicationServerId: true
          countryId: true
          areaCode: true
          outgoingDDIId: true
          outgoingDdiRuleId: true
          languageId: true
          defaultTimezoneId: true
          externallyExtraOpts: true
          recordingsLimitMB: true
          recordingsLimitEmail: true
          recordingsDiskUsage: true
        order: &companiesOrder_Link
          id: true
          name: true
          externalMaxCalls: true
          defaultTimezoneId: true
          outboundPrefix: true
          postalAddress: true
          recordingsLimitMB: true
          externallyExtraOpts: true
      fixedPositions:
        group0:
          colsPerRow: 12
          label: _("Basic Configuration")
          fields:
            name: 4
            domainUsers: 5
            relFeatures: 2
        group1:
          colsPerRow: 2
          label: _("Security")
          fields:
            externalMaxCalls: 1
            ipFilter: 1
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Company', 'Companies', 1))
      shortcutOption: N
      forcedValues:
        type: "vpbx"
        <<: *forcedBrand
        nif: '12345678-Z'
        postalAddress: 'Postal address'
        postalCode: 'PC'
        town: 'Town'
        country: 'Country'
        province: 'Province'
    companiesEdit_screen: &companiesEdit_screenLink
      <<: *Companies
      controller: edit
      fields:
        blacklist:
          type: true
          distributeMethod: ${auth.isNotMainOperator}
          applicationServerId: ${auth.isNotMainOperator}
          mediaRelaySet: ${auth.isNotMainOperator}
          recordingsLimitMB: ${auth.brand.recordings.disabled}
          recordingsLimitEmail: ${auth.brand.recordings.disabled}
          recordingsDiskUsage: ${auth.brand.recordings.disabled}
          onDemandRecord: ${auth.brand.recordings.disabled}
          onDemandRecordCode: ${auth.brand.recordings.disabled}
          nif: ${auth.brand.invoices.disabled}
          postalAddress: ${auth.brand.invoices.disabled}
          postalCode: ${auth.brand.invoices.disabled}
          town: ${auth.brand.invoices.disabled}
          province: ${auth.brand.invoices.disabled}
          countryId: ${auth.brand.invoices.disabled}
        whitelist:
          id: ${auth.isMainOperator}
        order:
          <<: *companiesOrder_Link
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Company', 'Companies', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fixedPositions: &companiesFixedPositions_Link
        group0:
          colsPerRow: 12
          label: _("Basic Configuration")
          fields:
            name: 4
            nif: 4
            domainUsers: 5
            relFeatures: 2
        group1:
          colsPerRow: 2
          label: _("Security")
          fields:
            externalMaxCalls: 1
            ipFilter: 1
        group2:
          colsPerRow: 2
          label: _("Locales")
          fields:
            defaultTimezoneId: 1
            languageId: 1
        group3:
          colsPerRow: 12
          label: _("Server data")
          fields:
            outgoingDDIId: 6
            outgoingDDIRuleId: 6
            outbound_prefix: 4
            domain_users: 9
            countryId: 6
            areaCode: 6
            mediaRelaySetsId: 4
            distributeMethod: 4
            applicationServerId: 4
        group4:
          colsPerRow: 2
          label: _("Invoice data")
          fields:
            postalAddress: 2
            postalCode: 1
            town: 1
            province: 1
            countryName: 1
            registryData: 2
        group5:
          colsPerRow: 12
          label: ngettext('Recording', 'Recordings', 0)
          collapsed: true
          fields:
            recordingsLimitMB: 6
            recordingsDiskUsage: 6
            recordingsLimitEmail: 6
            onDemandRecord: 6
            onDemandRecordCode: 6
        group6:
          colsPerRow: 1
          collapsed: true
          label: _("Externally rated options")
          fields:
            externallyExtraOpts: 1
    #companyAdmins:
    companyAdminsList_screen:
      <<: *companyAdminsList_screenLink
      filterField: Company
      parentOptionCustomizer:
        - recordCount
    companyAdminsNew_screen:
      <<: *companyAdminsNew_screenLink
      filterField: Company
    companyAdminsEdit_screen:
      <<: *companyAdminsEdit_screenLink
      filterField: companyId

    #pricingPlansRelCompanies:
    <<: *pricingPlansRelCompanies_screensLink
    pricingPlansRelCompaniesList_screen:
      <<: *pricingPlansRelCompaniesList_screenLink
      filterField: Company
      parentOptionCustomizer:
        - recordCount
    pricingPlansRelCompaniesNew_screen:
      <<: *pricingPlansRelCompaniesNew_screenLink
      filterField: Company
    pricingPlansRelCompaniesEdit_screen:
      <<: *pricingPlansRelCompaniesEdit_screenLink
      filterField: Company

    # outgoingRouting
    <<: *outgoingRouting_screensLink
    outgoingRoutingList_screen:
      <<: *outgoingRoutingList_screenLink
      filterField: Company
      parentOptionCustomizer:
        - recordCount
    outgoingRoutingNew_screen:
      <<: *outgoingRoutingNew_screenLink
      filterField: Company
    outgoingRoutingEdit_screen:
      <<: *outgoingRoutingEdit_screenLink
      filterField: Company

    #kamUsersAddress:
    kamUsersAddressList_screen:
      <<: *kamUsersAddressList_screenLink
      filterField: Company
      parentOptionCustomizer:
        - recordCount
    kamUsersAddressNew_screen:
      <<: *kamUsersAddressNew_screenLink
      filterField: Company
    kamUsersAddressEdit_screen:
      <<: *kamUsersAddressEdit_screenLink
      filterField: Company

  dialogs: &companies_dialogsLink
    companiesDel_dialog: &companiesDel_dialogLink
      <<: *Companies
      controller: delete
      class: ui-silk-bin
      secureDelete: true
      labelOption: false
      title: _("Delete %s", ngettext('Company', 'Companies', 1))
      description: _("Do you want to delete this %s?", ngettext('Company', 'Companies', 1))
      message: _("%s successfully deleted.", ngettext('Company', 'Companies', 1))
      multiItem: 1
      labelOnList: 1

    emulateCompany_dialog:
      title: _("Emulate Company %s", "[format| (%item%)]")
      module: default
      controller: klear-custom-extra-auth
      action: emulate
      class: ui-silk-building-add
      label: false
      labelOnEdit: false
      labelOnList: false
      labelOnEntityPostSave: false
      multiItem: false
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer

    importCompanies_dialog:
      <<: *Companies
      module: default
      title: _("Import %s", ngettext('Company', 'Companies', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-file
      action: import
      class:  ui-silk-page-gear
      freeUploadCommand: importCompaniesFreeUpload_command
      delimiter: ";"
      enclosure: '"'
      escape: "\\"
      forcedValues:
        <<: *forcedBrand

    # pricingPlansRelCompanies dialogs:
    <<: *pricingPlansRelCompanies_dialogsLink
    # companyAdmins dialogs:
    <<: *companyAdmins_dialogsLink
    # outgoingRouting dialogs:
    <<: *outgoingRouting_dialogsLink
    # kamUsersAddress dialogs:
    <<: *kamUsersAddress_dialogsLink

  commands:
    importCompaniesFreeUpload_command:
      <<: *Companies
      controller: File
      action: free-upload
    <<: *pricingPlansRelCompanies_commandsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
