#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include AdministratorsList.yaml
#include PricingPlansRelCompaniesList.yaml
#include TpRatingProfilesList.yaml
#include OutgoingRoutingList.yaml
#include KamUsersAddressList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: companiesList_screen
  screens: &companies_screensLink
    companiesList_screen: &companiesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Companies
      class: ui-silk-building
      title: _("List of %s %2s", ngettext('Company', 'Companies', 0), "[format| (%parent%)]")
      forcedValues:
        type: 'vpbx'
        <<: *forcedBrand
      fields:
        options:
          title: _("Options")
          screens:
            companiesEdit_screen: true
            kamUsersAddressList_screen: true
            administratorsList_screen: true
            tpRatingProfilesList_screen: ${auth.brand.billing.enabled}
            outgoingRoutingList_screen: true
          dialogs:
            companiesDel_dialog: false
            emulateCompany_dialog: true
          default: companiesEdit_screen
        blacklist:
          typeIcon: true
          transformationRuleSetId: true
          postalAddress: true
          postalCode: true
          town: true
          province: true
          countryName: true
          outgoingDDIId: true
          outgoingDdiRuleId: true
          registryData: true
          maxCalls: true
          defaultTimezoneId: true
          distributeMethod: true
          applicationServerId: true
          mediaRelaySetsId: true
          ipFilter: true
          languageId: true
          onDemandRecord: true
          onDemandRecordCode: true
          recordingsLimitMB: true
          recordingsLimitEmail: true
          recordingsDiskUsage: true
          externallyExtraOpts: true
          voicemailNotificationTemplateId: true
          faxNotificationTemplateId: true
          billingMethod: true
          balance: true
        order:
          name: true
          languageId: true
          nif: true
          countryId: true
          domainUsers: true
      options:
        title: _("Options")
        screens:
          companiesNew_screen: true
        dialogs:
          companiesDel_dialog: true
          importCompanies_dialog: false
      csv:
        active: false
        filename: "Companies"
        headers: true
        enclosure: '"'
        separator: ";"
        nameklear: false
        rawValues: true
        ignoreBlackList: true
        newLine: "\r\n"
        encoding: "utf-8"
        executionSeconds: ""

    companiesNew_screen: &companiesNew_screenLink
      <<: *Companies
      controller: new
      fields:
        blacklist:
          nif: true
          type: true
          typeIcon: true
          postalAddress: true
          postalCode: true
          town: true
          province: true
          onDemandRecord: true
          onDemandRecordCode: true
          mediaRelaySetsId: true
          distributeMethod: true
          applicationServerId: true
          countryName: true
          outgoingDDIId: true
          outgoingDdiRuleId: true
          externallyExtraOpts: true
          recordingsLimitMB: true
          recordingsLimitEmail: true
          recordingsDiskUsage: true
          voicemailNotificationTemplateId: true
          faxNotificationTemplateId: true
          balance: true
        order: &companiesOrder_Link
          id: true
          name: true
          languageId: true
          maxCalls: true
          contryId: true
          postalAddress: true
          recordingsLimitMB: true
          externallyExtraOpts: true
          voicemailNotificationTemplateId: true
      fixedPositions:
        group0:
          colsPerRow: 6
          label: _("Basic Configuration")
          fields:
            name: 3
            domainUsers: 3
            relFeatures: 3
            billingMethod: 3
        group1:
          colsPerRow: 2
          label: _("Security")
          fields:
            maxCalls: 1
            ipFilter: 1
        group2:
          colsPerRow: 2
          label: _("Geographic Configuration")
          fields:
            defaultTimezoneId: 1
            countryId: 1
            languageId: 1
            transformationRuleSetId: 1
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Company', 'Companies', 1))
      shortcutOption: N
      forcedValues:
        type: "vpbx"
        <<: *forcedBrand
        nif: '12345678-Z'
        postalAddress: 'Postal address'
        postalCode: 'PC'
        town: 'Town'
        countryName: 'Country'
        province: 'Province'

    companiesEdit_screen: &companiesEdit_screenLink
      <<: *Companies
      controller: edit
      fields:
        blacklist:
          type: true
          typeIcon: true
          distributeMethod: ${auth.isNotMainOperator}
          applicationServerId: ${auth.isNotMainOperator}
          mediaRelaySet: ${auth.isNotMainOperator}
          recordingsLimitMB: ${auth.brand.recordings.disabled}
          recordingsLimitEmail: ${auth.brand.recordings.disabled}
          recordingsDiskUsage: ${auth.brand.recordings.disabled}
          onDemandRecord: ${auth.brand.recordings.disabled}
          onDemandRecordCode: ${auth.brand.recordings.disabled}
          nif: ${auth.brand.invoices.disabled}
          postalAddress: ${auth.brand.invoices.disabled}
          postalCode: ${auth.brand.invoices.disabled}
          town: ${auth.brand.invoices.disabled}
          province: ${auth.brand.invoices.disabled}
          countryId: ${auth.brand.invoices.disabled}
          recordingsLimitMB: true
          recordingsLimitEmail: true
          recordingsDiskUsage: true
          balance: true
        whitelist:
          id: ${auth.isMainOperator}
        order:
          <<: *companiesOrder_Link
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Company', 'Companies', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fixedPositions: &companiesFixedPositions_Link
        group0:
          colsPerRow: 6
          label: _("Basic Configuration")
          fields:
            name: 3
            domainUsers: 3
            relFeatures: 3
            billingMethod: 3
        group1:
          colsPerRow: 2
          label: _("Security")
          fields:
            maxCalls: 1
            ipFilter: 1
        group2:
          colsPerRow: 3
          label: _("Geographic Configuration")
          fields:
            languageId: 1
            countryId: 1
            defaultTimezoneId: 1
            transformationRuleSetId: 3
        group3:
          colsPerRow: 12
          label: _("Server data")
          fields:
            outgoingDDIId: 6
            outgoingDDIRuleId: 6
            domain_users: 9
            mediaRelaySetsId: 4
            distributeMethod: 4
            applicationServerId: 4
        group4:
          colsPerRow: 2
          label: _("Invoice data")
          fields:
            postalAddress: 2
            postalCode: 1
            town: 1
            province: 1
            countryName: 1
            registryData: 2
        group5:
          colsPerRow: 12
          label: ngettext('Recording', 'Recordings', 0)
          collapsed: true
          fields:
            onDemandRecord: 6
            onDemandRecordCode: 6
        group6:
          colsPerRow: 1
          collapsed: true
          label: _("Externally rated options")
          fields:
            externallyExtraOpts: 1
        group7:
          colsPerRow: 2
          collapsed: true
          label: _("Notification options")
          fields:
            voicemailNotificationTemplateId: 1
            faxNotificationTemplateId: 1

    # Administrators
    <<: *administrators_screensLink
    administratorsList_screen:
      <<: *administratorsList_screenLink
      class: ui-silk-user-gray
      title: _("List of %s %2s", ngettext('Company admin', 'Company admins', 0), "[format| (%parent%)]")
      filterField: Company
      parentOptionCustomizer:
        - recordCount
    administratorsNew_screen:
      <<: *administratorsNew_screenLink
      title: _("Add %s", ngettext('Company admin', 'Company admins', 1), "[format| (%parent%)]")
      filterField: Company
      forcedValues:
        <<: *forcedBrand
    administratorsEdit_screen:
      <<: *administratorsEdit_screenLink
      title: _("Edit %s %2s", ngettext('Company admin', 'Company admins', 1), "[format| (%item%)]")
      filterField: Company
      forcedValues:
        <<: *forcedBrand

    # tpRatingPlan:
    <<: *tpRatingProfiles_screensLink
    tpRatingProfilesList_screen:
      <<: *tpRatingProfilesList_screenLink
      filterField: company
      parentOptionCustomizer:
        - recordCount
    tpRatingProfilesNew_screen:
      <<: *tpRatingProfilesNew_screenLink
      filterField: company
    tpRatingProfilesEdit_screen:
      <<: *tpRatingProfilesEdit_screenLink
      filterField: company

    # outgoingRouting
    <<: *outgoingRouting_screensLink
    outgoingRoutingList_screen:
      <<: *outgoingRoutingList_screenLink
      filterField: Company
      parentOptionCustomizer:
        - recordCount
    outgoingRoutingNew_screen:
      <<: *outgoingRoutingNew_screenLink
      filterField: Company
    outgoingRoutingEdit_screen:
      <<: *outgoingRoutingEdit_screenLink
      filterField: Company

    #kamUsersAddress:
    kamUsersAddressList_screen:
      <<: *kamUsersAddressList_screenLink
      filterField: Company
      parentOptionCustomizer:
        - recordCount
    kamUsersAddressNew_screen:
      <<: *kamUsersAddressNew_screenLink
      filterField: Company
    kamUsersAddressEdit_screen:
      <<: *kamUsersAddressEdit_screenLink
      filterField: Company

  dialogs: &companies_dialogsLink
    companiesDel_dialog: &companiesDel_dialogLink
      <<: *Companies
      controller: delete
      class: ui-silk-bin
      secureDelete: true
      labelOption: false
      title: _("Delete %s", ngettext('Company', 'Companies', 1))
      description: _("Do you want to delete this %s?", ngettext('Company', 'Companies', 1))
      message: _("%s successfully deleted.", ngettext('Company', 'Companies', 1))
      multiItem: 1
      labelOnList: 1

    emulateCompany_dialog:
      title: _("Emulate Company %s", "[format| (%item%)]")
      module: default
      controller: klear-custom-extra-auth
      action: emulate
      class: ui-silk-building-add
      label: false
      labelOnEdit: false
      labelOnList: false
      labelOnEntityPostSave: false
      multiItem: false
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer

    importCompanies_dialog:
      <<: *Companies
      module: default
      title: _("Import %s", ngettext('Company', 'Companies', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-file
      action: import
      class:  ui-silk-page-gear
      freeUploadCommand: importCompaniesFreeUpload_command
      delimiter: ";"
      enclosure: '"'
      escape: "\\"
      forcedValues:
        <<: *forcedBrand

    # tpRatingProfiles:
    <<: *tpRatingProfiles_dialogsLink

    # Administrators dialogs
    <<: *administrators_dialogsLink
    administratorsDel_dialog:
      <<: *administratorsDel_dialogLink
      title: _("Delete %s", ngettext('Company admin', 'Company admins', 1))
      description: _("Do you want to delete this %s?", ngettext('Company admin', 'Company admins', 1))
      message: _("%s successfully deleted.", ngettext('Company admin', 'Company admins', 1))

    # outgoingRouting dialogs:
    <<: *outgoingRouting_dialogsLink
    # kamUsersAddress dialogs:
    <<: *kamUsersAddress_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
