#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: conditionalRoutesConditionsList_screen

  screens: &conditionalRoutesConditions_screensLink
    conditionalRoutesConditionsList_screen: &conditionalRoutesConditionsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *ConditionalRoutesConditions
      class: ui-silk-tag
      title: _("List of %s %2s", ngettext('Condition', 'Conditions', 0), "[format| (%parent%)]")
      order:
        field:
          ConditionalRoutesCondition.priority asc
      fields: &conditionalRoutesConditions_fieldsLink
        options:
          title: _("Options")
          screens:
            conditionalRoutesConditionsEdit_screen: ${auth.acls.ConditionalRoutesConditions.update}
          dialogs:
            conditionalRoutesConditionsDel_dialog: ${auth.acls.ConditionalRoutesConditions.delete}
          default: conditionalRoutesConditionsEdit_screen
        blacklist:
          ivr: true
          huntGroup: true
          conferenceRoom: true
          user: true
          voiceMailUser: true
          numberCountry: true
          numberValue: true
          friendValue: true
          queue: true
          conferenceRoom: true
          extension: true
          relMatchlists: true
          relSchedules: true
          relCalendars: true
          relRouteLocks: true
        order:
          priority: true
          ConditionMatch: true
          locution: true
          routeType: true
          target: true
      options:
        title: _("Options")
        screens:
          conditionalRoutesConditionsNew_screen: ${auth.acls.ConditionalRoutesConditions.create}
        dialogs:
          conditionalRoutesConditionsDel_dialog: ${auth.acls.ConditionalRoutesConditions.delete}

    conditionalRoutesConditionsNew_screen: &conditionalRoutesConditionsNew_screenLink
      <<: *ConditionalRoutesConditions
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Condition', 'Conditions', 1), "[format| (%parent%)]")
      shortcutOption: N
      defaultValues:
        numberCountry: ${auth.companyCountryId}
      fields:
        blacklist: &conditionalRoutesConditionsBlacklist_link
          target: true
          ConditionMatch: true
        order: &conditionalRoutesConditionsOrder_link
            priority: true
            relMatchlists: true
            locution: true
      fixedPositions: &conditionalRoutesConditionsPositions_link
        group0:
          label: _("Matching priority")
          colsPerRow: 12
          fields:
            priority: 4
        group1:
          label: _("Matching type")
          colsPerRow: 8
          fields:
            type: 5
            relMatchlists: 4
            relRouteLocks: 4
            relSchedules: 4
            relCalendars: 4
        group2:
          label: _("Matching handler")
          colsPerRow: 6
          fields:
            locution: 6
            routeType: 2
            ivr: 3
            huntGroup: 3
            voiceMailUser: 3
            user: 3
            numberCountry: 2
            numberValue: 2
            friendValue: 3
            queue: 3
            conferenceRoom: 3
            extension: 3

    conditionalRoutesConditionsEdit_screen: &conditionalRoutesConditionsEdit_screenLink
      <<: *ConditionalRoutesConditions
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Condition', 'Conditions', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Condition', 'Conditions', 1), "[format| (%item%)]")
      fields:
        blacklist:
          <<: *conditionalRoutesConditionsBlacklist_link
        order:
          <<: *conditionalRoutesConditionsOrder_link
      fixedPositions:
          <<: *conditionalRoutesConditionsPositions_link

  dialogs: &conditionalRoutesConditions_dialogsLink
    conditionalRoutesConditionsDel_dialog: &conditionalRoutesConditionsDel_dialogLink
      <<: *ConditionalRoutesConditions
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Condition', 'Conditions', 1))
      description: _("Do you want to delete this %s?", ngettext('Condition', 'Conditions', 1))
      message: _("%s successfully deleted.", ngettext('Condition', 'Conditions', 1))
      multiItem: 1
      labelOnList: 1

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
