#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include DdisList.yaml
#include DdiProviderAddressesList.yaml
#include DdiProviderRegistrationsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: ddiProvidersList_screen
  screens: &ddiProviders_screensLink
    ddiProvidersList_screen: &ddiProvidersList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *DdiProviders
      class: ui-silk-server-lightning
      title: _("List of %s %2s", ngettext('DDI Provider', 'DDI Providers', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/providers/ddi_providers.html"
      forcedValues:
        <<: *forcedBrand
      fields:
        options:
          title: _("Options")
          screens:
            ddiProvidersEdit_screen: true
            ddiProviderAddressesList_screen: true
            ddiProviderRegistrationsList_screen: true
            ddisList_screen: true
          dialogs:
            ddiProvidersDel_dialog: true
          default: ddiProvidersEdit_screen
        order: &PeerContractsOrder_Link
          brand: true
          name: true
          description: true
        blacklist:
          externallyRated: true
      options:
        title: _("Options")
        screens:
          ddiProvidersNew_screen: true
        dialogs:
          ddiProvidersDel_dialog: true

    ddiProvidersNew_screen: &ddiProvidersNew_screenLink
      <<: *DdiProviders
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('DDI Provider', 'DDI Providers', 1))
      shortcutOption: N
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *PeerContractsOrder_Link
        blacklist:
          externallyRated: ${auth.brandFeatures.billing.disabled}
      fixedPositions:
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            name: 5
            description: 7
        group1:
          label: _("Extra Configuration")
          colsPerRow: 6
          fields:
            transformationRuleSet: 3
            externallyRated: 3

    ddiProvidersEdit_screen: &ddiProvidersEdit_screenLink
      <<: *DdiProviders
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('DDI Provider', 'DDI Providers', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *PeerContractsOrder_Link
        blacklist:
          externallyRated: ${auth.brandFeatures.billing.disabled}

    # DDI Provider Addresses screens
    <<: *ddiProviderAddresses_screensLink
    ddiProviderAddressesList_screen:
      <<: *ddiProviderAddressesList_screenLink
      filterField: ddiProvider
      parentOptionCustomizer:
        - recordCount
    ddiProviderAddressesNew_screen:
      <<: *ddiProviderAddressesNew_screenLink
      filterField: ddiProvider
    ddiProviderAddressesEdit_screen:
      <<: *ddiProviderAddressesEdit_screenLink
      filterField: ddiProvider

    # DDI Provider Registration screens
    ddiProviderRegistrationsList_screen:
      <<: *ddiProviderRegistrationsList_screenLink
      filterField: ddiProvider
      parentOptionCustomizer:
        - recordCount
    ddiProviderRegistrationsNew_screen:
      <<: *ddiProviderRegistrationsNew_screenLink
      filterField: ddiProvider
    ddiProviderRegistrationsEdit_screen:
      <<: *ddiProviderRegistrationsEdit_screenLink
      filterField: ddiProvider

    # DDI Provider related DDIs screens
    ddisList_screen:
      <<: *ddisList_screenLink
      filterField: ddiProvider
      parentOptionCustomizer:
        - recordCount
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          country: true
          ddi: true
          company: true
        blacklist:
          user: true
          fax: true
          ivr: true
          huntGroup: true
          conferenceRoom: true
          friendValue: true
          brand: true
          recordCalls: true
          displayName: true
          externalCallFilter: true
          language: true
          queue: true
          residentialDevice: true
          conditionalRoute: true
          routeType: true
          target: true
        options:
          title: _("Options")
          screens:
          dialogs:
      options:
        screens:
        dialogs:

  dialogs: &ddiProviders_dialogsLink
    ddiProvidersDel_dialog: &ddiProvidersDel_dialogLink
      <<: *DdiProviders
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('DDI Provider', 'DDI Providers', 1))
      description: _("Do you want to delete this %s?", ngettext('DDI Provider', 'DDI Providers', 1))
      message: _("%s successfully deleted.", ngettext('DDI Provider', 'DDI Providers', 1))
      multiItem: 1
      labelOnList: 1

    # DDI Provider Addresses dialogs
    <<: *ddiProviderAddresses_dialogsLink
    # DDI Provider Registry dialogs
    <<: *ddiProviderRegistrations_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
