#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/importPricesHelp.yaml
#include conf.d/documentationLink.yaml
#include DestinationRatesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: destinationRateGroupsList_screen
  screens: &destinationRateGroups_screensLink
    destinationRateGroupsList_screen: &destinationRateGroupsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *DestinationRateGroups
      class: ui-silk-page-find
      title: _("List of %s %2s", ngettext('Destination rate', 'Destination rates', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/billing/destination_rates.html"
      forcedValues:
        <<: *forcedBrand
      fields: &destinationRateGroups_fieldsLink
        order:
          tag: true
          name: true
          description: true
          currency: true
        options:
          title: _("Options")
          screens:
            destinationRateGroupsEdit_screen: true
            destinationRatesList_screen: true
          dialogs:
            importDestinationRates_dialog: true
            destinationRateGroupsDel_dialog: true
          default: destinationRateGroupsEdit_screen
      options:
        title: _("Options")
        screens:
          destinationRateGroupsNew_screen: true
        dialogs:
          destinationRateGroupsDel_dialog: true
      csv:
        active: false
        filename: "Prices"
        headers: true
        enclosure: '"'
        separator: ";"
        nameklear: false
        rawValues: true
        ignoreBlackList: true
        newLine: "\r\n"
        encoding: "utf-8"
        executionSeconds: ""
      <<: *importPricesHelp

    destinationRateGroupsNew_screen: &destinationRateGroupsNew_screenLink
      <<: *DestinationRateGroups
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Destination rate', 'Destination rates', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fields:
        blacklist:
          file: true
          status: true
      fixedPositions: &pdestinationRateGroupsFixedPositions_Link
        group1:
          colsPerRow: 9
          fields:
            name: 4
            description: 5
            currency: 4
        group2:
          colsPerRow: 8
          fields:
            file: 6
            status: 2

    destinationRateGroupsEdit_screen: &destinationRateGroupsEdit_screenLink
      <<: *DestinationRateGroups
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Destination rate', 'Destination rates', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fixedPositions:
        <<: *pdestinationRateGroupsFixedPositions_Link

    # destinationRates:
    <<: *destinationRates_screensLink
    destinationRatesList_screen:
      <<: *destinationRatesList_screenLink
      filterField: destinationRateGroup
      parentOptionCustomizer:
        - recordCount
    destinationRatesNew_screen:
      <<: *destinationRatesNew_screenLink
      filterField: destinationRateGroup
    destinationRatesEdit_screen:
      <<: *destinationRatesEdit_screenLink
      filterField: destinationRateGroup

  dialogs: &destinationRateGroups_dialogsLink
    destinationRateGroupsDel_dialog: &destinationRateGroupsDel_dialogLink
      <<: *DestinationRateGroups
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Destination rate', 'Destination rates', 1))
      description: _("Do you want to delete this %s?", ngettext('Destination rate', 'Destination rates', 1))
      message: _("%s successfully deleted.", ngettext('Destination rate', 'Destination rates', 1))
      multiItem: 1
      labelOnList: 1

    importDestinationRates_dialog: &importDestinationRates_dialogLink
      <<: *DestinationRateGroups
      module: default
      title: _("Import %s", ngettext('Rate', 'Rates', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-destination-rates-custom-file
      action: import
      class:  ui-silk-page-white-get
      freeUploadCommand: importDestinationRateGroupsFreeUpload_command
      delimiter: ","
      enclosure: '"'
      escape: "\\"
      forcedValues:
        brand: ${auth.brandId}

    # destinationRates dialogs:
    <<: *destinationRates_dialogsLink

  commands: &destinationRateGroups_commandsLink
    destinationRateGroupsFileDownload_command: &destinationRateGroupsFileDownload_command
      <<: *DestinationRateGroups
      controller: File
      action: force-download
      mainColumn: File
      class: ui-silk-bullet-disk
    destinationRateGroupsFileUpload_command: &destinationRateGroupsFileUpload_command
      <<: *DestinationRateGroups
      controller: File
      action: upload
      mainColumn: File
    importDestinationRateGroupsFreeUpload_command:
      <<: *DestinationRateGroups
      controller: File
      action: free-upload

    # destinationRates commands
    <<: *destinationRates_commandsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
