#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: destinationRatesList_screen
  screens: &destinationRates_screensLink
    destinationRatesList_screen: &destinationRatesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *DestinationRates
      class: ui-silk-money-euro
      title: _("List of %s %2s", ngettext('Rate', 'Rates', 0), "[format| (%parent%)]")
      fields: &destinationRates_fieldsLink
        order:
          destination: true
          connectFeeCurrency: true
          groupIntervalStart: true
          costCurrency: true
          rateIncrement: true
        blacklist:
          connectFee: true
          cost: true
        options:
          title: _("Options")
          screens:
            destinationRatesEdit_screen: true
          dialogs:
            destinationRatesDel_dialog: true
          default: destinationRatesEdit_screen
      options:
        title: _("Options")
        screens:
          destinationRatesNew_screen: true
        dialogs:
          destinationRatesDel_dialog: true

    destinationRatesNew_screen: &destinationRatesNew_screenLink
      <<: *DestinationRates
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Rate', 'Rates', 1), "[format| (%parent%)]")
      shortcutOption: N
      fields:
        order: &destinationRates_orderLink
          destination: true
          connectFee: true
          groupIntervalStart: true
          cost: true
          rateIncrement: true
        blacklist:
          connectFeeCurrency: true
          costCurrency: true
      fixedPositions: &destinationRates_fixedPositionsLink
        group1:
          colsPerRow: 9
          fields:
            destination: 3
        group2:
          colsPerRow: 6
          fields:
            connectFee: 3
            groupIntervalStart: 3
            cost: 3
            rateIncrement: 3

    destinationRatesEdit_screen: &destinationRatesEdit_screenLink
      <<: *DestinationRates
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Rate', 'Rates', 1), "[format| (%item%)]")
      fields:
        order:
          <<: *destinationRates_orderLink
      fixedPositions:
        <<: *destinationRates_fixedPositionsLink

  dialogs: &destinationRates_dialogsLink
    destinationRatesDel_dialog: &destinationRatesDel_dialogLink
      <<: *DestinationRates
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Rate', 'Rates', 1))
      description: _("Do you want to delete this %s?", ngettext('Rate', 'Rates', 1))
      message: _("%s successfully deleted.", ngettext('Rate', 'Rates', 1))
      multiItem: 1
      labelOnList: 1

  commands: &destinationRates_commandsLink
    destinationsRatesautocomplete_command: &destinationRatesautocomplete_commandLink
      <<: *DestinationRates
      controller: field-decorator
      action: index
      autocomplete:
        entity: \Ivoz\Provider\Domain\Model\Destination\Destination
        filterClass: IvozProvider_Klear_Filter_Brand
        fieldName:
          fields:
            - name.${lang}
            - prefix
          template: "%name.${lang}% (%prefix%)"
        fullTemplateMatch: true
        limit: 8
        order:
          Destination.name.${lang}: asc

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
