#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/importPricesHelp.yaml
#include conf.d/documentationLink.yaml
#include TpDestinationRatesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: destinationRatesList_screen
  screens: &destinationRates_screensLink
    destinationRatesList_screen: &destinationRatesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *DestinationRates
      class: ui-silk-page-find
      title: _("List of %s %2s", ngettext('Destination rate', 'Destination rates', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/${lang}/brand/billing/destination_rates.html"
      forcedValues:
        <<: *forcedBrand
      fields: &destinationRates_fieldsLink
        order:
          tag: true
          name: true
          description: true
        options:
          title: _("Options")
          screens:
            destinationRatesEdit_screen: true
            tpDestinationRatesList_screen: true
          dialogs:
            importTpDestinationRates_dialog: true
            destinationRatesDel_dialog: true
          default: destinationRatesEdit_screen
      options:
        title: _("Options")
        screens:
          destinationRatesNew_screen: true
        dialogs:
          destinationRatesDel_dialog: true
      csv:
        active: false
        filename: "Prices"
        headers: true
        enclosure: '"'
        separator: ";"
        nameklear: false
        rawValues: true
        ignoreBlackList: true
        newLine: "\r\n"
        encoding: "utf-8"
        executionSeconds: ""
      <<: *importPricesHelp

    destinationRatesNew_screen: &destinationRatesNew_screenLink
      <<: *DestinationRates
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Destination rate', 'Destination rates', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fields:
        blacklist:
          file: true
          status: true
      fixedPositions: &pdestinationRatesFixedPositions_Link
        group1:
          colsPerRow: 9
          fields:
            name: 4
            description: 5
        group2:
          colsPerRow: 8
          fields:
            file: 6
            status: 2

    destinationRatesEdit_screen: &destinationRatesEdit_screenLink
      <<: *DestinationRates
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Destination rate', 'Destination rates', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fixedPositions:
        <<: *pdestinationRatesFixedPositions_Link

    # tpDestinationRates:
    <<: *tpDestinationRates_screensLink
    tpDestinationRatesList_screen:
      <<: *tpDestinationRatesList_screenLink
      filterField: destinationRate
      parentOptionCustomizer:
        - recordCount
    tpDestinationRatesNew_screen:
      <<: *tpDestinationRatesNew_screenLink
      filterField: destinationRate
    tpDestinationRatesEdit_screen:
      <<: *tpDestinationRatesEdit_screenLink
      filterField: destinationRate

  dialogs: &destinationRates_dialogsLink
    destinationRatesDel_dialog: &destinationRatesDel_dialogLink
      <<: *DestinationRates
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Destination rate', 'Destination rates', 1))
      description: _("Do you want to delete this %s?", ngettext('Destination rate', 'Destination rates', 1))
      message: _("%s successfully deleted.", ngettext('Destination rate', 'Destination rates', 1))
      multiItem: 1
      labelOnList: 1

    importTpDestinationRates_dialog: &importTpDestinationRates_dialogLink
      <<: *DestinationRates
      module: default
      title: _("Import %s", ngettext('Destination rate', 'Destination rates', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-tp-destination-rates-custom-file
      action: import
      class:  ui-silk-page-white-get
      freeUploadCommand: importTpDestinationRatesFreeUpload_command
      delimiter: ","
      enclosure: '"'
      escape: "\\"
      forcedValues:
        brand: ${auth.brandId}

    # tpDestinationRates dialogs:
    <<: *tpDestinationRates_dialogsLink

  commands: &destinationRates_commandsLink
    destinationRatesFileDownload_command: &destinationRatesFileDownload_command
      <<: *DestinationRates
      controller: File
      action: force-download
      mainColumn: File
      class: ui-silk-bullet-disk
    destinationRatesFileUpload_command: &destinationRatesFileUpload_command
      <<: *DestinationRates
      controller: File
      action: upload
      mainColumn: File
    importTpDestinationRatesFreeUpload_command:
      <<: *DestinationRates
      controller: File
      action: free-upload

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
