production:
  klearCommon:
    30000: _("There is an inconditional call forward with that call type. You can't add call forwards")
    30001: _("There are already call forwards with that call type. You can't add inconditional call forward")
    30002: _("There is already a busy call forward with that call type.")
    30003: _("There is already a noAnswer call forward with that call type.")
    30004: _("There is already a userNotRegistered call forward with that call type.")
    30005: _("There is already a retail account with that name.")
    30006: _("There is already a residential device with that name.")
    30007: _("There is already a friend with that name.")
    30008: _("There is already a terminal with that name.")
    30100: _("Error reloading modules. Please reload modules manually.")
    30200: _("There is a call forward with that call type. You can't add this call forward")
    40000: _("'Valid From' must be earlier than 'Valid to'")
    40001: _("You can't create a pricing plan that starts in de past")
    40002: _("Selected weight is already in use")
    50001: _("There are unmetered calls.")
    50002: _("There are unbilled calls before in date.")
    50003: _("There are invoices in the same range of date.")
    50004: _("There are unbilled calls after out date.")
    50005: _("'Out date' must be equal or greater than 'In date'.")
    50006: _("Cannot invoice calls from today in the future.")
    60000: _("Brand is not set")
    70000: _("Invalid IP address, discarding value.")
    70001: _("Wrong mask, discarding value.")
    70003: _("When Outbound Proxy is used, SIP Proxy must not include a port.")
    70004: _("Outbound Proxy IP value is not valid.")
    80000: _("Template field can not be null.")
    90000: _("Inbound Calls cannot be billed as DDI Provider is not externally rated.")
    90001: _("Externally rated cannot be disabled as some DDIs wants to bill inbound calls.")
  adminErrors:
    2001: _("SIP Domain can't be empty")
    2201: _("Email already in use")
  connectorErrors:
    9001: _("No Application Server available.")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
