#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

# ************************ ExternalCallFiltersList.yaml ************************
production:
  main:
    module: klearMatrix
    defaultScreen: externalCallFiltersList_screen
  screens: &externalCallFilters_screensLink
    externalCallFiltersList_screen: &externalCallFiltersList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *ExternalCallFilters
      class: ui-silk-arrow-branch
      title: _("List of %s %2s", ngettext('External call filter', 'External call filters', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        options:
          title: _("Options")
          screens:
            externalCallFiltersEdit_screen: true
          dialogs:
            externalCallFiltersDel_dialog: true
          default: externalCallFiltersEdit_screen
        blacklist:
          companyId: false
          name: false
          welcomeLocutionId: true
          holidayLocutionId: true
          outOfScheduleLocutionId: true
          holidayTargetType: false
          holidayNumberCountryId: true
          holidayNumberValue: true
          holidayExtensionId: true
          holidayVoiceMailUserId: true
          outOfScheduleTargetType: false
          outOfScheduleNumberCountryId: true
          outOfScheduleNumberValue: true
          outOfScheduleExtensionId: true
          outOfScheduleVoiceMailUserId: true
          whiteLists: true
          blackLists: true
        order: &externalCallFilters_orderLink
          name: true
          welcomeLocutionId: true
          whiteLists: true
          blackLists: true
          holidayLocutionId: true
          holidayTargetType: true
          holidayTarget: true
          holidayNumberCountryId: true
          holidayNumberValue: true
          holidayExtensionId: true
          holidayVoiceMailUserId: true
          outOfScheduleLocutionId: true
          outOfScheduleTargetType: true
          outOfScheduleTarget: true
          outOfScheduleNumberCountryId: true
          outOfScheduleNumberValue: true
          outOfScheduleExtensionId: true
          outOfScheduleVoiceMailUserId: true
          calendars: true
          schedules: true
      options:
        title: _("Options")
        screens:
          externalCallFiltersNew_screen: true
        dialogs:
          externalCallFiltersDel_dialog: true

    externalCallFiltersNew_screen: &externalCallFiltersNew_screenLink
      <<: *ExternalCallFilters
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('External call filter', 'External call filters', 1))
      shortcutOption: N
      defaultValues:
        holidayNumberCountryId: ${auth.companyCountryId}
        outOfScheduleNumberCountryId: ${auth.companyCountryId}
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          <<: *externalCallFilters_orderLink
        blacklist:
          holidayTarget: true
          outOfScheduleTarget: true
      fixedPositions: &externalCallFilters_fixedPositionsLink
        group0:
          label: _("Basic Info")
          colsPerRow: 2
          fields:
            companyId: 1
            name: 1
            welcomeLocutionId: 1
        group1:
          label: _("Filtering info")
          colsPerRow: 12
          fields:
            whiteLists: 6
            blackLists: 6
        group3:
          colsPerRow: 7
          label: _("Holidays configuration")
          fields:
            calendars: 3
            holidayLocutionId: 3
            holidayTargetType: 2
            holidayNumberCountryId: 2
            holidayNumberValue: 2
            holidayExtensionId: 3
            holidayVoiceMailUserId: 3
        group4:
          colsPerRow: 6
          label: _("Out of schedule configuration")
          fields:
            schedules: 3
            outOfScheduleLocutionId: 3
            outOfScheduleTargetType: 2
            outOfScheduleNumberCountryId: 2
            outOfScheduleNumberValue: 2
            outOfScheduleExtensionId: 3
            outOfScheduleVoiceMailUserId: 3

    externalCallFiltersEdit_screen: &externalCallFiltersEdit_screenLink
      <<: *ExternalCallFilters
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('External call filter', 'External call filters', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          <<: *externalCallFilters_orderLink
        blacklist:
          holidayTarget: true
          outOfScheduleTarget: true
      fixedPositions:
        <<: *externalCallFilters_fixedPositionsLink

  dialogs: &externalCallFilters_dialogsLink
    externalCallFiltersDel_dialog: &externalCallFiltersDel_dialogLink
      <<: *ExternalCallFilters
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('External call filter', 'External call filters', 1))
      description: _("Do you want to delete this %s?", ngettext('External call filter', 'External call filters', 1))
      message: _("%s successfully deleted.", ngettext('External call filter', 'External call filters', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
