#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: faxesInOutList_screen

  screens: &faxesInOut_screensLink
    faxesInOutList_screen: &faxesInOutList_screenLink
      controller: list
      autoRefresh: true
      autoRefresh: 15
      pagination:
        items: 25
      order:
        field:
        - FaxesInOut.calldate desc
      <<: *FaxesInOut
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Faxfile', 'Faxfiles', 0), "[format| (%parent%)]")
      fields: &faxesInOut_fieldsLink
        options:
          title: _("Options")
          screens:
            faxesInOutEdit_screen: ${auth.acls.FaxesInOut.update}
          dialogs:
            faxesInOutDel_dialog: ${auth.acls.FaxesInOut.delete}
          default: faxesInOutEdit_screen
      options:
        title: _("Options")
        screens:
          faxesInOutNew_screen: ${auth.acls.FaxesInOut.create}
        dialogs:
          faxesInOutDel_dialog: ${auth.acls.FaxesInOut.delete}

    faxesInOutNew_screen: &faxesInOutNew_screenLink
      <<: *FaxesInOut
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Send new %s", ngettext('Faxfile', 'Faxefiles', 1), "[format| (%parent%)]")
      shortcutOption: N

    faxesInOutEdit_screen: &faxesInOutEdit_screenLink
      <<: *FaxesInOut
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Faxfile', 'Faxefiles', 1), "[format| (%item%)]")

  dialogs: &faxesInOut_dialogsLink
    faxesInOutDel_dialog: &faxesInOutDel_dialogLink
      <<: *FaxesInOut
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Faxfile', 'Faxfile', 1))
      description: _("Do you want to delete this %s?", ngettext('Faxfile', 'Faxfile', 1))
      message: _("%s successfully deleted.", ngettext('Faxfile', 'Faxfile', 1))
      multiItem: 1
      labelOnList: 1

  commands: &faxesInOut_commandsLink
    faxesInOutFileDownload_command: &faxesInOutFileDownload_commandLink
      <<: *FaxesInOut
      controller: File
      action: force-download
      mainColumn: file
    faxesInOutFileUpload_command: &faxesInOutFileUpload_commandLink
      <<: *FaxesInOut
      controller: File
      action: upload
      mainColumn: file
    faxesInOutFilePreview_command: &faxesInOutFilePreview_commandLink
      <<: *FaxesInOut
      controller: File
      action: preview
      mainColumn: file
      arguments:
        cache:
          enabled: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
