#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: fixedCostsList_screen
  screens: &fixedCosts_screensLink
    fixedCostsList_screen: &fixedCostsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *FixedCosts
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Fixed cost', 'Fixed costs', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/invoicing/fixed_costs.html"
      forcedValues:
        <<: *forcedBrand
      fields: &fixedCosts_fieldsLink
        options:
          title: _("Options")
          screens:
            fixedCostsEdit_screen: true
          dialogs:
            fixedCostsDel_dialog: true
          default: fixedCostsEdit_screen
        order: &fixedCostsFldOrder
          - name
          - cost
          - description
      options:
        title: _("Options")
        screens:
          fixedCostsNew_screen: true
        dialogs:
          fixedCostsDel_dialog: true
    fixedCostsNew_screen: &fixedCostsNew_screenLink
      <<: *FixedCosts
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Fixed cost', 'Fixed costs', 1), "[format| (%parent%)]")
      shortcutOption: N
      forcedValues:
        <<: *forcedBrand
      fields:
          order:
            <<: *fixedCostsFldOrder

    fixedCostsEdit_screen: &fixedCostsEdit_screenLink
      <<: *FixedCosts
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Fixed cost', 'Fixed costs', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Fixed cost', 'Fixed costs', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
          order:
            <<: *fixedCostsFldOrder

  dialogs: &fixedCosts_dialogsLink
    fixedCostsDel_dialog: &fixedCostsDel_dialogLink
      <<: *FixedCosts
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Fixed cost', 'Fixed costs', 1))
      description: _("Do you want to delete this %s?", ngettext('Fixed cost', 'Fixed costs', 1))
      message: _("%s successfully deleted.", ngettext('Fixed cost', 'Fixed costs', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
