#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include FriendsPatternsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: friendsList_screen
  screens: &friends_screensLink
    friendsList_screen: &friendsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Friends
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Friend', 'Friends', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/routing_endpoints/friends.html"
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          transport: true
          authNeeded: true
          password: true
          allow: true
          disallow: true
          directMediaMethod: true
          updateCallerid: true
          fromDomain: true
          calleridUpdateHeader: true
          directConnectivity: true
          ip: true
          port: true
          transformationRuleSet: true
          language: true
          status: true
          updateCallerid: true
          callACL: true
          ddiIn: true
        order:
          name: true
          domain: true
          description: true
          outgoingDDI: true
          priority: true
          statusIcon: true
        options:
          title: _("Options")
          screens:
            friendsEdit_screen: true
            friendsPatternsList_screen: true
          dialogs:
            friendsDel_dialog: true
          default: friendsEdit_screen
      options:
        title: _("Options")
        screens:
          friendsNew_screen: true
        dialogs:
          friendsDel_dialog: true

    friendsNew_screen: &friendsNew_screenLink
      <<: *Friends
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Friend', 'Friends', 1), "[format| (%parent%)]")
      scripts:
        module: default
        name: jquery.passwordgennew.js
      plugin: passwordgennew
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist: &friends_blacklistLink
          domain: true
          directMediaMethod: true
          updateCallerid: true
          calleridUpdateHeader: true
          authNeeded: true
          disallow: true
          status: true
          statusIcon: true
        order: &friends_orderLink
          name: true
          description: true
          priority: true
          password: true
          directConnectivity: true
          transport: true
          ip: true
          port: true
          language: true
          callACL: true
          outgoingDDI: true
          allow: true
          transformationRuleSet: true
          fromDomain: true
          ddiIn: true
          status: true
      fixedPositions: &friends_FixedPositionsLink
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            name: 4
            description: 6
            priority: 2
            password: 5
            directConnectivity: 3
            __empty1: 4
            transport: 4
            ip: 5
            port: 3
        group1:
          label: _("Geographic Configuration")
          colsPerRow: 12
          fields:
            language: 4
            transformationRuleSet: 8
        group2:
          label: _("Outgoing Configuration")
          colsPerRow: 12
          fields:
            callACL: 5
            outgoingDDI: 5
        group3:
          label: _("Advanced Configuration")
          colsPerRow: 6
          fields:
            allow: 2
            fromDomain: 2
            ddiIn: 2
      shortcutOption: N

    friendsEdit_screen: &friendsEdit_screenLink
      <<: *Friends
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Friend', 'Friends', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Friend', 'Friends', 1), "[format| (%item%)]")
      scripts:
        module: default
        name: jquery.passwordgenedit.js
      plugin: passwordgen
      fields:
        order:
          <<: *friends_orderLink
        blacklist:
          domain: true
          directMediaMethod: true
          updateCallerid: true
          calleridUpdateHeader: true
          authNeeded: true
          disallow: true
          statusIcon: true
      fixedPositions:
          <<: *friends_FixedPositionsLink
      forcedValues:
        <<: *forcedCompany

    #friendsPatterns:
    <<: *friendsPatterns_screensLink
    friendsPatternsList_screen:
      <<: *friendsPatternsList_screenLink
      filterField: Friend
      parentOptionCustomizer:
        - recordCount
    friendsPatternsNew_screen:
      <<: *friendsPatternsNew_screenLink
      filterField: Friend
    friendsPatternsEdit_screen:
      <<: *friendsPatternsEdit_screenLink
      filterField: Friend

  dialogs: &friends_dialogsLink
    friendsDel_dialog: &friendsDel_dialogLink
      <<: *Friends
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Friend', 'Friends', 1))
      description: _("Do you want to delete this %s?", ngettext('Friend', 'Friends', 1))
      message: _("%s successfully deleted.", ngettext('Friend', 'Friends', 1))
      multiItem: 1
      labelOnList: 1
  # friendsPatterns dialogs:
    <<: *friendsPatterns_dialogsLink

  commands:
    generatePassword_command:
      <<: *Friends
      title: "Generate new secure password"
      class: ui-silk-arrow-refresh
      module: default
      controller: Password
      action: generate

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
