#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include FriendsPatternsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: friendsList_screen
  screens: &friends_screensLink
    friendsList_screen: &friendsList_screenLink
      controller: list
      pagination:
        items: 25
      order:
        field:
          - Friend.priority asc
      <<: *Friends
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Friend', 'Friends', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/routing_endpoints/friends/index.html"
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          transport: true
          password: true
          allow: true
          disallow: true
          directMediaMethod: true
          updateCallerid: true
          fromDomain: true
          calleridUpdateHeader: true
          directConnectivity: true
          ip: true
          port: true
          transformationRuleSet: true
          language: true
          status: true
          updateCallerid: true
          callACL: true
          ddiIn: true
          t38Passthrough: true
          outgoingDdi: true
          interCompany: true
        order:
          name: true
          domain: true
          description: true
          outgoingDdi: true
          priority: true
          statusIcon: true
        options:
          title: _("Options")
          screens:
            friendsEdit_screen: $[${auth.acls.Friends.update} && ${auth.companyVPBX}]
            friendsPatternsList_screen: $[${auth.acls.FriendsPatterns.read} && ${auth.companyVPBX}]
          dialogs:
            friendsDel_dialog: ${auth.acls.Friends.delete}
          default: friendsEdit_screen
      options:
        title: _("Options")
        screens:
          friendsNew_screen: $[${auth.acls.Friends.create} && ${auth.companyVPBX}]
        dialogs:
          friendsDel_dialog: $[${auth.acls.Friends.delete} && ${auth.companyVPBX}]

    friendsNew_screen: &friendsNew_screenLink
      <<: *Friends
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Friend', 'Friends', 1), "[format| (%parent%)]")
      scripts:
        module: default
        name: jquery.passwordgennew.js
      plugin: passwordgennew
      forcedValues:
        <<: *forcedCompany
        ddiIn: "yes"
      fields:
        readOnly:
          interCompany: ${auth.isCompanyOperator}
        blacklist: &friends_blacklistLink
          domain: true
          directMediaMethod: true
          updateCallerid: true
          calleridUpdateHeader: true
          disallow: true
          status: true
          statusIcon: true
          t38Passthrough: true
          language: true
          transformationRuleSet: true
          callACL: true
          outgoingDdi: true
          allow: true
          fromDomain: true
          ddiIn: true
        order: &friends_orderLink
          directConnectivity: true
          name: true
          description: true
          priority: true
          password: true
          transport: true
          ip: true
          port: true
          language: true
          callACL: true
          outgoingDdi: true
          allow: true
          transformationRuleSet: true
          fromDomain: true
          ddiIn: true
          status: true
          t38Passthrough: true
      fixedPositions: &friends_FixedPositionsLink
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            directConnectivity: 8
            priority: 4
            description: 10
            __empty1: 2
            name: 6
            password: 6
            interCompany: 10
            __empty1: 2
            transport: 4
            ip: 5
            port: 3
        group1:
          label: _("Geographic Configuration")
          colsPerRow: 12
          fields:
            language: 4
            transformationRuleSet: 8
        group2:
          label: _("Outgoing Configuration")
          colsPerRow: 12
          fields:
            callACL: 5
            outgoingDdi: 5
        group3:
          label: _("Advanced Configuration")
          colsPerRow: 4
          fields:
            allow: 2
            fromDomain: 2
            ddiIn: 2
            t38Passthrough: 2
      shortcutOption: N

    friendsEdit_screen: &friendsEdit_screenLink
      <<: *Friends
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Friend', 'Friends', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Friend', 'Friends', 1), "[format| (%item%)]")
      scripts:
        module: default
        name: jquery.passwordgenedit.js
      plugin: passwordgen
      fields:
        order:
          <<: *friends_orderLink
        readOnly:
          interCompany: ${auth.isCompanyOperator}
        blacklist:
          domain: true
          directMediaMethod: true
          updateCallerid: true
          calleridUpdateHeader: true
          disallow: true
          statusIcon: true
      fixedPositions:
          <<: *friends_FixedPositionsLink
      forcedValues:
        <<: *forcedCompany

    #friendsPatterns:
    <<: *friendsPatterns_screensLink
    friendsPatternsList_screen:
      <<: *friendsPatternsList_screenLink
      filterField: Friend
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
        - recordCount
    friendsPatternsNew_screen:
      <<: *friendsPatternsNew_screenLink
      filterField: Friend
    friendsPatternsEdit_screen:
      <<: *friendsPatternsEdit_screenLink
      filterField: Friend

  dialogs: &friends_dialogsLink
    friendsDel_dialog: &friendsDel_dialogLink
      <<: *Friends
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Friend', 'Friends', 1))
      description: _("Do you want to delete this %s?", ngettext('Friend', 'Friends', 1))
      message: _("%s successfully deleted.", ngettext('Friend', 'Friends', 1))
      multiItem: 1
      labelOnList: 1
  # friendsPatterns dialogs:
    <<: *friendsPatterns_dialogsLink

  commands:
    generatePassword_command:
      <<: *Friends
      title: "Generate new secure password"
      class: ui-silk-arrow-refresh
      module: default
      controller: Password
      action: generate

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
