#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include BillableCallsList.yaml
#include FixedCostsRelInvoicesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: invoicesList_screen
  screens: &invoices_screensLink
    invoicesList_screen: &invoicesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Invoices
      class: ui-silk-report
      title: _("List of %s %2s", ngettext('Invoice', 'Invoices', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/invoicing/invoices.html"
      forcedValues:
        <<: *forcedBrand
      fields: &invoices_fieldsLink
        options:
          title: _("Options")
          screens:
            invoicesEdit_screen: true
            fixedCostsRelInvoicesList_screen: true
            billableCallsList_screen: true
          dialogs:
            generateInvoice_dialog: true
            invoicesDel_dialog: true
          default: invoicesEdit_screen
        order: &invoicesOrder_Link
          company: true
          number: true
          numberSequence: true
          inDate: true
          outDate: true
          total: true
          taxRate: true
          totalWithTax: true
          status: true
          invoiceTemplate: true
          pdf: true
        blacklist:
          FixedCostsRelInvoices: true
          numberSequence: true
          scheduler: true
      options:
        title: _("Options")
        screens:
          invoicesNew_screen: true

    invoicesNew_screen: &invoicesNew_screenLink
      <<: *Invoices
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Invoice', 'Invoices', 1), "[format| (%parent%)]")
      shortcutOption: N
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *invoicesOrder_Link
        blacklist:
          total: true
          totalWithTax: true
          status: true
          pdf: true
          FixedCostsRelInvoices: true
          scheduler: true
      fixedPositions: &invoicesFixedPositions_Link
        group0:
          colsPerRow: 2
          fields:
            numberSequence: 1
            number: 1
            company: 1
            invoiceTemplate: 1
        group1:
          colsPerRow: 2
          fields:
            inDate: 1
            outDate: 1
        group2:
          colsPerRow: 6
          fields:
            total: 2
            taxRate: 2
            totalWithTax: 2
        group3:
          colsPerRow: 2
          fields:
            status: 1
            pdf: 1

    invoicesEdit_screen: &invoicesEdit_screenLink
      <<: *Invoices
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Invoice', 'Invoices', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *invoicesOrder_Link
        blacklist:
          FixedCostsRelInvoices: true
          numberSequence: true
          scheduler: true
        readOnly:
          total: true
          totalWithTax: true
          status: true
          FixedCostsRelInvoices: true
      fixedPositions:
        <<: *invoicesFixedPositions_Link

    <<: *fixedCostsRelInvoices_screensLink
    fixedCostsRelInvoicesList_screen:
      <<: *fixedCostsRelInvoicesList_screenLink
      filterField: Invoice
      parentOptionCustomizer:
        - recordCount
    billableCallsList_screen:
      <<: *billableCallsList_screenLink
      class: ui-silk-application-view-list
      filterField: Invoice
      parentOptionCustomizer:
        - recordCount
      fields:
        <<: *billableCalls_fieldsLink
        blacklist:
          <<: *billableCalls_blacklistLink
          company: true
          brand: true
    billableCallsView_screen:
      <<: *billableCallsView_screenLink
      fields:
        <<: *billableCallsView_fieldsLink
        blacklist:
          company: true
          brand: true

  dialogs: &invoices_dialogsLink
    invoicesDel_dialog: &invoicesDel_dialogLink
      <<: *Invoices
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s",  ngettext('Invoice', 'Invoices', 1))
      description: _("Do you want to delete this %s?",  ngettext('Invoice', 'Invoices', 1))
      message: _("%s successfully deleted.",  ngettext('Invoice', 'Invoices', 1))
      multiItem: 1
      labelOnList: 1
    generateInvoice_dialog:
      <<: *Invoices
      module: default
      title: _("Generate %s",  ngettext('Invoice', 'Invoices', 1))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOption: false
      labelOnEntityPostSave: false
      controller: klear-custom-generate-invoice
      action: generate
      class:  ui-silk-report-add
      multiItem: true

    <<: *fixedCostsRelInvoices_dialogsLink
  commands: &invoices_commandsLink
    invoicesPdfFileDownload_command: &invoicesPdfFileDownload_commandLink
      <<: *Invoices
      controller: File
      action: force-download
      mainColumn: pdf
      class: ui-silk-bullet-disk
    invoicesPdfFileUpload_command: &invoicesPdfFileUpload_commandLink
      <<: *Invoices
      controller: File
      action: upload
      mainColumn: pdf
    invoicesPdfFilePreview_command: &invoicesPdfFilePreview_commandLink
      <<: *Invoices
      controller: File
      action: preview
      mainColumn: pdf
      arguments:
        cache:
          enabled: true
    <<: *exportBillableCallsToCsv_commandsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
