#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: IvrCommonList_screen
  screens:
    IvrCommonList_screen: &IvrCommonList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *IvrCommon
      title: _("List of %s %2s", ngettext('IVR Common', 'IVRs Common', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          order:
          name: true
          timeout: true
          noAnswerTimeout: true
          timeoutTargetType: true
          timeoutTarget: true
          errorTargetType: true
          errorTarget: true
        blacklist:
          maxDigits: true
          welcomeLocutionId: true
          noAnswerLocutionId: true
          errorLocutionId: true
          successLocutionId: true
          timeoutNumberValue: true
          timeoutExtensionId: true
          timeoutVoiceMailUserId: true
          errorNumberValue: true
          errorExtensionId: true
          errorVoiceMailUserId: true
          blackListRegExp: true
        options:
          title: _("Options")
          screens:
            IvrCommonEdit_screen: true
          dialogs:
            IvrCommonDel_dialog: true
          default: IvrCommonEdit_screen
      options:
        title: _("Options")
        screens:
          IvrCommonNew_screen: true
        dialogs:
          IvrCommonDel_dialog: true
    IvrCommonNew_screen: &IvrCommonNew_screenLink
      <<: *IvrCommon
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('IVR Common', 'IVRs Common', 1))
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          timeoutTarget: true
          errorTarget: true
      fixedPositions: &IvrCommonFixedPositions_link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            name: 4
            timeout: 4
            maxDigits: 4
            welcomeLocutionId: 6
            successLocutionId: 6
            blackListRegExp: 8
        group1:
          label: _("No answer configuration")
          colsPerRow: 3
          fields:
            noAnswerLocutionId: 2
            noAnswerTimeout: 1
            timeoutTargetType: 1
            timeoutNumberValue: 1
            timeoutExtensionId: 1
            timeoutVoiceMailUserId: 1
        group2:
          label: _("Error configuration")
          colsPerRow: 6
          fields:
            errorLocutionId: 5
            errorTargetType: 2
            errorNumberValue: 2
            errorExtensionId: 2
            errorVoiceMailUserId: 2
    IvrCommonEdit_screen: &IvrCommonEdit_screenLink
      <<: *IvrCommon
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('IVR Common', 'IVRs Common', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          timeoutTarget: true
          errorTarget: true
      fixedPositions:
        <<: *IvrCommonFixedPositions_link
  dialogs:
    IvrCommonDel_dialog: &IvrCommonDel_dialogLink
      <<: *IvrCommon
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('IVR Common', 'IVRs Common', 1))
      description: _("Do you want to delete this %s?", ngettext('IVR Common', 'IVRs Common', 1))
      message: _("%s successfully deleted.", ngettext('IVR Common', 'IVRs Common', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
