#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: ivrEntriesList_screen

  screens: &ivrEntries_screensLink
    ivrEntriesList_screen: &ivrEntriesList_screenLink
      controller: list
      class: ui-silk-chart-organisation-add
      pagination:
        items: 25
      <<: *IvrEntries
      title: _("List of %s %2s", ngettext('IVR entry', 'IVR entries', 0), "[format| (%parent%)]")
      fields:
        order:
          entry: true
          welcomeLocutionId: true
          routeType: true
          target: true
        blacklist:
          numberCountryId: true
          numberValue: true
          extensionId: true
          voiceMailUserId: true
          conditionalRouteId: true
        options:
          title: _("Options")
          screens:
            ivrEntriesEdit_screen: true
          dialogs:
            ivrEntriesDel_dialog: true
          default: ivrEntriesEdit_screen
      options:
        title: _("Options")
        screens:
          ivrEntriesNew_screen: true
        dialogs:
          ivrEntriesDel_dialog: true

    ivrEntriesNew_screen: &ivrEntriesNew_screenLink
      <<: *IvrEntries
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('IVR entry', 'IVR entries', 1))
      shortcutOption: N
      defaultValues:
        numberCountryId: ${auth.companyCountryId}
      fields:
        blacklist:
          target: true
      fixedPositions: &ivrEntriesFixedPositions_link
        group0:
          label: _("Entry information")
          colsPerRow: 8
          fields:
            entry: 4
            welcomeLocutionId: 4
        group1:
          label: _("Routing configuration")
          colsPerRow: 12
          fields:
            routeType: 4
            numberCountryId: 4
            numberValue: 4
            extensionId: 4
            voiceMailUserId: 5
            conditionalRouteId: 5

    ivrEntriesEdit_screen: &ivrEntriesEdit_screenLink
      <<: *IvrEntries
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('IVR entry', 'IVR entries', 1), "[format| (%item%)]")
      fields:
        blacklist:
          target: true
      fixedPositions:
        <<: *ivrEntriesFixedPositions_link

  dialogs: &ivrEntries_dialogsLink
    ivrEntriesDel_dialog: &ivrEntriesDel_dialogLink
      <<: *IvrEntries
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('IVR entry', 'IVR entries', 1))
      description: _("Do you want to delete this %s?", ngettext('IVR entry', 'IVR entries', 1))
      message: _("%s successfully deleted.", ngettext('IVR entry', 'IVR entries', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
