#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include IvrEntriesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: ivrList_screen
  screens:
    ivrList_screen: &ivrList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Ivr
      title: _("List of %s %2s", ngettext('IVR', 'IVRs', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/routing_endpoints/ivrs.html"
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          name: true
          timeout: true
          allowExtensions: true
          noInputRouteType: true
          noInputTarget: true
          errorRouteType: true
          errorTarget: true
        blacklist:
          maxDigits: true
          excludedExtensions: true
          welcomeLocution: true
          noInputLocution: true
          errorLocution: true
          successLocution: true
          noInputNumberCountry: true
          noInputNumberValue: true
          noInputExtension: true
          noInputVoiceMailUser: true
          errorNumberCountry: true
          errorNumberValue: true
          errorExtension: true
          errorVoiceMailUser: true
        options:
          title: _("Options")
          screens:
            ivrEdit_screen: ${auth.acls.IVRs.update}
            ivrEntriesList_screen: ${auth.acls.IVREntries.read}
          dialogs:
            ivrDel_dialog: ${auth.acls.IVRs.delete}
          default: ivrEdit_screen
      options:
        title: _("Options")
        screens:
          ivrNew_screen: ${auth.acls.IVRs.create}
        dialogs:
          ivrDel_dialog: ${auth.acls.IVRs.delete}

    ivrNew_screen: &ivrNew_screenLink
      <<: *Ivr
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('IVR', 'IVRs', 1))
      shortcutOption: N
      defaultValues:
        noInputNumberCountry: ${auth.companyCountryId}
        errorNumberCountry: ${auth.companyCountryId}
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          name: true
          allowExtensions: true
          noInputLocution: true
          errorLocution: true
        blacklist:
          noInputTarget: true
          errorTarget: true
          noInputTarget : true
      fixedPositions: &ivrFixedPositions_link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            name: 4
            timeout: 4
            maxDigits: 4
            welcomeLocution: 6
            successLocution: 6
        group1:
          label: _("Extension dialing")
          colsPerRow: 3
          fields:
            allowExtensions: 1
            excludedExtensions: 2
        group2:
          label: _("No input configuration")
          colsPerRow: 3
          fields:
            noInputLocution: 2
            __empty1: 1
            noInputRouteType: 1
            noInputNumberCountry: 1
            noInputNumberValue: 1
            noInputExtension: 1
            noInputVoiceMailUser: 1
        group3:
          label: _("Error configuration")
          colsPerRow: 6
          fields:
            errorLocution: 5
            errorRouteType: 2
            errorNumberCountry: 2
            errorNumberValue: 2
            errorExtension: 2
            errorUser: 2
            errorVoiceMailUser: 2
    ivrEdit_screen: &ivrEdit_screenLink
      <<: *Ivr
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('IVR', 'IVRs', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          name: true
          allowExtensions: true
          noInputLocution: true
          errorLocution: true
        blacklist:
          noInputTarget: true
          errorTarget: true
          noInputTarget: true
      fixedPositions:
        <<: *ivrFixedPositions_link

    #ivrEntries
    <<: *ivrEntries_screensLink
    ivrEntriesList_screen:
      <<: *ivrEntriesList_screenLink
      filterField: Ivr
      parentOptionCustomizer:
        - recordCount
    ivrEntriesNew_screen:
      <<: *ivrEntriesNew_screenLink
      filterField: Ivr
    ivrEntriesEdit_screen:
      <<: *ivrEntriesEdit_screenLink
      filterField: Ivr

  dialogs:
    ivrDel_dialog: &ivrDel_dialogLink
      <<: *Ivr
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('IVR', 'IVRs', 1))
      description: _("Do you want to delete this %s?", ngettext('IVR', 'IVRs', 1))
      message: _("%s successfully deleted.", ngettext('IVR', 'IVRs', 1))
      multiItem: 1
      labelOnList: 1

    #ivrEntries
    <<: *ivrEntries_dialogsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
