#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/kamRtpproxyHelp.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: kamRtpproxyList_screen
  screens: &kamRtpproxy_screensLink
    kamRtpproxyList_screen: &kamRtpproxyList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Rtpproxy
      class: ui-silk-bell-link
      title: _("List of %s %2s", ngettext('Media relay', 'Media relays', 0), "[format| (%parent%)]")
      fields: &kamRtpproxy_fieldsLink
        blacklist:
          setid: true
          flags: true
        options:
          title: _("Options")
          screens:
            kamRtpproxyEdit_screen: true
          dialogs:
            kamRtpproxyDel_dialog: true
          default: kamRtpproxyEdit_screen
      options:
        title: _("Options")
        screens:
          kamRtpproxyNew_screen: true
        dialogs:
          kamRtpproxyDel_dialog: true
      <<: *kamRtpproxyHelp
    kamRtpproxyNew_screen: &kamRtpproxyNew_screenLink
      <<: *Rtpproxy
      controller: new
      class: ui-silk-add
      fields:
        blacklist:
          flags: true
          setid: true
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Media relay', 'Media relays', 1), "[format| (%parent%)]")
      shortcutOption: N
      <<: *kamRtpproxyHelp
    kamRtpproxyEdit_screen: &kamRtpproxyEdit_screenLink
      <<: *Rtpproxy
      controller: edit
      class: ui-silk-pencil
      fields:
        blacklist:
          flags: true
          setid: true
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Media relay', 'Media relays', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Media relay', 'Media relays', 1), "[format| (%item%)]")
      <<: *kamRtpproxyHelp
  dialogs: &kamRtpproxy_dialogsLink
    kamRtpproxyDel_dialog: &kamRtpproxyDel_dialogLink 
      <<: *Rtpproxy
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Media relay', 'Media relays', 1))
      description: _("Do you want to delete this %s?", ngettext('Media relay', 'Media relays', 1))
      message: _("%s successfully deleted.", ngettext('Media relay', 'Media relays', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
