#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: kamTrunksCdrsList_screen

  screens: &kamTrunksCdrs_screensLink
    kamTrunksCdrsList_screen: &kamTrunksCdrsList_screenLink
      controller: list
      csv: true
      order:
        field:
          - TrunksCdr.startTime
          - TrunksCdr.brand
          - TrunksCdr.company
        type: desc
      rawCondition: "TrunksCdr.direction='outbound'"
      pagination: 
        items: 25
      <<: *KamTrunksCdrs
      class: ui-silk-application-view-list
      title: _("List of %s %2s", ngettext('Billable call', 'Billable calls', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/${lang}/brand/billing/billable_calls.html"
      fields: &kamTrunksCdrs_fieldsLink
        options:
          title: _("Options")
          screens:
            kamTrunksCdrsView_screen: true
          default: kamTrunksCdrsView_screen
        order:
          startTime: true
          brand: true
          company: true
          callee: true
          duration: true
          price: true
          cost: true
          carrier: true
          invoice: true
    kamTrunksCdrsView_screen: &kamTrunksCdrsView_screenLink
      <<: *KamTrunksCdrs
      controller: edit
      class: ui-silk-eye
      label: false
      disableSave: true
      labelOnPostAction: _("View %s %2s", ngettext('Billable call', 'Billable calls', 1), "[format| (%item%)]")
      title: _("View %s %2s", ngettext('Billable call', 'Billable calls', 1), "[format| (%item%)]")
      fields:
        order:
          startTime: true
          brand: true
          company: true
          callee: true
          duration: true
          price: true
          cost: true
          carrier: true
          invoice: true
      fixedPositions:
        group0:
          label: _("Basic Information")
          colsPerRow: 12
          fields:
            brand: 6
            company: 6
            callee: 6
            startTime: 6
            duration: 6
        group1:
          label: _("Billing Information")
          colsPerRow: 12
          fields:
            price: 6
            cost: 6
            carrier: 6
            direction: 6
            invoice: 6

  dialogs:  &kamTrunksCdrs_dialogsLink
    tarificateCall_dialog:
      <<: *KamTrunksCdrs
      module: default
      title: ngettext('Rerate call', 'Rerate calls', 1)
      labelOnList: ngettext('Rerate call', 'Rerate calls', 0)
      controller: klear-custom-tarificator
      action: tarificate-call
      class:  ui-silk-coins-add
      multiItem: true
      alwaysEnabled: false

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
