#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: kamTrunksUacregList_screen
  screens:
    kamTrunksUacregList_screen: &kamTrunksUacregList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *KamTrunksUacreg
      class: ui-silk-server-link
      title: _("List of %s %2s", ngettext('Provider register', 'Provider registers', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        blacklist:
          lUuid: true
          realm: true
          expires: true
          authUsername: true
          authPassword: true
          authProxy: true
          multiDDI: true
        order:
          rUsername: true
          rDomain: true
        options:
          title: _("Options")
          screens:
            kamTrunksUacregEdit_screen: true
          dialogs:
            kamTrunksUacregDel_dialog: true
          default: kamTrunksUacregEdit_screen
      options:
        title: _("Options")
        screens:
          kamTrunksUacregNew_screen: true
        dialogs:
          kamTrunksUacregDel_dialog: true
    kamTrunksUacregNew_screen: &kamTrunksUacregNew_screenLink
      <<: *KamTrunksUacreg
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Provider register', 'Provider registers', 1))
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fields: &kamTrunksUacregFields_link
        order:
          rUsername: true
          rDomain: true
          authPassword: true
          multiDDI: true
          lUuid: true
          authUsername: true
          authProxy: true
          realm: true
          expires: true
      fixedPositions: &kamTrunksUacregFixedPositions_link
        group0:
          label: _("Main Settings")
          colsPerRow: 12
          fields:
            rUsername: 5
            rDomain: 5
            authPassword: 12
        group1:
          label: _("Contact Settings")
          colsPerRow: 12
          collapsed: true
          fields:
            multiDDI: 6
            lUuid: 6
        group2:
          label: _("Optional Settings")
          colsPerRow: 12
          collapsed: true
          fields:
            authUsername: 5
            authProxy: 5
            realm: 6
            expires: 6
    kamTrunksUacregEdit_screen: &kamTrunksUacregEdit_screenLink
      <<: *KamTrunksUacreg
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Provider register', 'Provider registers', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        <<: *kamTrunksUacregFields_link
      fixedPositions:
        <<: *kamTrunksUacregFixedPositions_link
  dialogs: &kamTrunksUacreg_dialogsLink
    kamTrunksUacregDel_dialog: &kamTrunksUacregDel_dialogLink 
      <<: *KamTrunksUacreg
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Provider register', 'Provider registers', 1))
      description: _("Do you want to delete this %s?", ngettext('Provider register', 'Provider registers', 1))
      message: _("%s successfully deleted.", ngettext('Provider register', 'Provider registers', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
