#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: kamTrunksDialplanList_screen
  screens: &kamTrunksDialplan_screensLink
    kamTrunksDialplanList_screen: &kamTrunksDialplanList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *TrunksDialplan
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Transformation', 'Transformations', 0), "[format| (%parent%)]")
      filterField: TransformationRulesetGroupsTrunk
      fields: &kamTrunksDialplan_fieldsLink
        options:
          title: _("Options")
          screens:
            kamTrunksDialplanEdit_screen: true
          dialogs:
            kamTrunksDialplanDel_dialog: true
          default: kamTrunksDialplanEdit_screen
        blacklist: &kamTrunksDialplanBlacklist_Link
          dpid: true
          matchOp: true
          matchLen: true
          substExp: true
      options:
        title: _("Options")
        screens:
          kamTrunksDialplanNew_screen: true
        dialogs:
          kamTrunksDialplanDel_dialog: true
    kamTrunksDialplanNew_screen: &kamTrunksDialplanNew_screenLink
      <<: *TrunksDialplan
      module: default
      controller: klear-custom-kam-trunks-dialplan-new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Transformation', 'Transformations', 1), "[format| (%parent%)]")
      filterField: TransformationRulesetGroupsTrunk
      shortcutOption: N
      forcedValues:
        "self::matchOp": 1
        "self::matchLen": 0
      fields:
        blacklist:
          <<: *kamTrunksDialplanBlacklist_Link
      fixedPositions: &kamTrunksDialplanFixedPositions_screenLink
        group0:
          colsPerRow: 2
          fields:
            pr: 1
            attrs: 1
            matchExp: 1
            replExp: 1
    kamTrunksDialplanEdit_screen: &kamTrunksDialplanEdit_screenLink
      <<: *TrunksDialplan
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Transformation', 'Transformations', 1), "[format| (%item%)]")
      filterField: TransformationRulesetGroupsTrunk
      fields:
        blacklist:
          <<: *kamTrunksDialplanBlacklist_Link
      fixedPositions:
        <<: *kamTrunksDialplanFixedPositions_screenLink
  dialogs: &kamTrunksDialplan_dialogsLink
    kamTrunksDialplanDel_dialog: &kamTrunksDialplanDel_dialogLink 
      <<: *TrunksDialplan
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Transformation', 'Transformations', 1))
      description: _("Do you want to delete this %s?", ngettext('Transformation', 'Transformations', 1))
      message: _("%s successfully deleted.", ngettext('Transformation', 'Transformations', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
