#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: mainOperatorsList_screen
  screens:
    mainOperatorsList_screen: &mainOperatorsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *MainOperators
      class: fa fa-users red
      title: _("List of %s %2s", ngettext('Main operator', 'Main operators', 0), "[format| (%parent%)]")
      fields:
        options:
          title: _("Options")
          screens:
            mainOperatorsEdit_screen: true
          dialogs:
            mainOperatorsDel_dialog: true
          default: mainOperatorsEdit_screen
        order: &MainOperators_orderLink
          email: true
          username: true
          pass: true
          timezone: true
          name: true
          lastname: true
          active: true
        blacklist:
          email: true
          pass: true
          name: true
          lastname: true
          timezone: true
      options: 
        title: _("Options")
        screens:
          mainOperatorsNew_screen: true
        dialogs:
          mainOperatorsDel_dialog: true
    mainOperatorsNew_screen: &mainOperatorsNew_screenLink
      <<: *MainOperators
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Main operator', 'Main operators', 1))
      shortcutOption: N
      fields:
        blacklist:
          active: true
        order:
          <<: *MainOperators_orderLink
      fixedPositions: &MainOperatorsFixedPositions_link
        group0:
          label: _("Login Info")
          colsPerRow: 2
          fields:
            username: 1
            pass: 1
            active: 1
            timezoneId: 1
        group1:
          label: _("Personal data")
          colsPerRow: 3
          collapsed: true
          fields:
            name: 1
            lastname: 1
            email: 1
    mainOperatorsEdit_screen: &mainOperatorsEdit_screenLink
      <<: *MainOperators
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Main operator', 'Main operators', 1), "[format| (%item%)]")
      fields:
        order:
          <<: *MainOperators_orderLink
      fixedPositions:
        <<: *MainOperatorsFixedPositions_link
  dialogs:
    mainOperatorsDel_dialog: &mainOperatorsDel_dialogLink
      <<: *MainOperators
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Main operator', 'Main operators', 1))
      description: _("Do you want to delete this %s?", ngettext('Main operator', 'Main operators', 1))
      message: _("%s successfully deleted.", ngettext('Main operator', 'Main operators', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
