#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include MatchListPatternsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: matchListsList_screen
  screens: &matchLists_screensLink
    matchListsList_screen: &matchListsList_screenLink
      controller: list
      rawCondition: "(MatchList.company = '${auth.companyId}' OR MatchList.brand = '${auth.brandId}')"
      order:
        field:
          - "MatchList.brand asc"
          - "MatchList.name asc"
      pagination:
        items: 25
      <<: *MatchLists
      class: ui-silk-text-list-numbers
      title: _("List of %s %2s", ngettext('Match List', 'Match Lists', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/routing_tools/match_lists.html"
      fields: &matchLists_fieldsLink
        blacklist:
          company: true
          brand: true
        options:
          title: _("Options")
          screens:
            matchListsEdit_screen: $[${auth.acls.MatchLists.update} && ${auth.companyVPBX}]
            matchListPatternsList_screen: $[${auth.acls.MatchListPatterns.read} && ${auth.companyVPBX}]
            matchListPatternsView_screen: $[${auth.acls.MatchListPatterns.read} && ${auth.companyVPBX}]
          dialogs:
            matchListsDel_dialog: $[${auth.acls.MatchLists.delete} && ${auth.companyVPBX}]
      options:
        title: _("Options")
        screens:
          matchListsNew_screen: ${auth.acls.MatchLists.create}
        dialogs:
          matchListsDel_dialog: ${auth.acls.MatchLists.delete}

    matchListsNew_screen: &matchListsNew_screenLink
      <<: *MatchLists
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Match List', 'Match Lists', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      shortcutOption: N

    matchListsEdit_screen: &matchListsEdit_screenLink
      <<: *MatchLists
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Match List', 'Match Lists', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Match List', 'Match Lists', 1), "[format| (%item%)]")
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
      forcedValues:
        <<: *forcedCompany

    #matchListPatterns:
    matchListPatternsList_screen:
      <<: *matchListPatternsList_screenLink
      filterField: matchList

    matchListPatternsNew_screen:
      <<: *matchListPatternsNew_screenLink
      filterField: matchList
    matchListPatternsEdit_screen:
      <<: *matchListPatternsEdit_screenLink
      filterField: matchList

    # MatchList Patterns ReadOnly Screens
    matchListPatternsView_screen:
      <<: *matchListPatternsView_screenLink
      filterField: matchList

  dialogs: &matchLists_dialogsLink
    matchListsDel_dialog: &matchListsDel_dialogLink
      <<: *MatchLists
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Match List', 'Match Lists', 1))
      description: _("Do you want to delete this %s?", ngettext('Match List', 'Match Lists', 1))
      message: _("%s successfully deleted.", ngettext('Match List', 'Match Lists', 1))
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
      multiItem: 1
      labelOnList: 1

  # matchListPatterns dialogs:
    <<: *matchListPatterns_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
