#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include MatchListPatternsList.yaml


production:
  main:
    module: klearMatrix
    defaultScreen: matchListsList_screen
  screens: &matchLists_screensLink
    matchListsList_screen: &matchListsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *MatchLists
      class: ui-silk-text-list-numbers
      title: _("List of %s %2s", ngettext('Match List', 'Match Lists', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields: &matchLists_fieldsLink
        options:
          title: _("Options")
          screens:
            matchListsEdit_screen: true
            matchListPatternsList_screen: true
          dialogs:
            matchListsDel_dialog: true
          default: matchListsEdit_screen
      options:
        title: _("Options")
        screens:
          matchListsNew_screen: true
        dialogs:
          matchListsDel_dialog: true
    matchListsNew_screen: &matchListsNew_screenLink
      <<: *MatchLists
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Match List', 'Match Lists', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      shortcutOption: N
    matchListsEdit_screen: &matchListsEdit_screenLink
      <<: *MatchLists
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Match List', 'Match Lists', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Match List', 'Match Lists', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany

    #matchListPatterns:
    matchListPatternsList_screen:
      <<: *matchListPatternsList_screenLink
      filterField: matchList
      parentOptionCustomizer:
        - recordCount
    matchListPatternsNew_screen:
      <<: *matchListPatternsNew_screenLink
      filterField: matchList
    matchListPatternsEdit_screen:
      <<: *matchListPatternsEdit_screenLink
      filterField: matchList

  dialogs: &matchLists_dialogsLink
    matchListsDel_dialog: &matchListsDel_dialogLink
      <<: *MatchLists
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Match List', 'Match Lists', 1))
      description: _("Do you want to delete this %s?", ngettext('Match List', 'Match Lists', 1))
      message: _("%s successfully deleted.", ngettext('Match List', 'Match Lists', 1))
      multiItem: 1
      labelOnList: 1

  # matchListPatterns dialogs:
    <<: *matchListPatterns_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
