#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: notificationTemplatesContentsList_screen

  screens: &notificationTemplatesContents_screensLink
    notificationTemplatesContentsList_screen: &notificationTemplatesContentsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *NotificationTemplatesContents
      class: ui-silk-page-white-stack
      title: _("List of %s %2s", ngettext('Notification content', 'Notification contents', 0), "[format| (%parent%)]")
      fields: &notificationTemplatesContents_fieldsLink
        blacklist:
          subject: true
          body: true
          voicemailVariables: true
          faxVariables: true
          lowBalanceVariables: true
        options:
          title: _("Options")
          screens:
            notificationTemplatesContentsEdit_screen: true
          dialogs:
            notificationTemplatesContentsDel_dialog: true
          default: notificationTemplatesContentsEdit_screen
      options:
        title: _("Options")
        screens:
          notificationTemplatesContentsNew_screen: true
        dialogs:
          notificationTemplatesContentsDel_dialog: true
    notificationTemplatesContentsNew_screen: &notificationTemplatesContentsNew_screenLink
      <<: *NotificationTemplatesContents
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Notification content', 'Notification contents', 1), "[format| (%parent%)]")
      fullWidth: true
      fields:
        order: &notificationTemplatesContentsFieldsOrderPositions_Link
          languageId: true
          fromName: true
          fromAddress: true
          voicemailVariables: true
          faxVariables: true
          lowBalanceVariables: true
          subject: true
          body: true
      fixedPositions: &notificationTemplatesContentsFixedPositions_Link
        group0:
          label:
          colsPerRow: 2
          fields:
            languageId: 1
        group1:
          label: _("From configuration")
          colsPerRow: 3
          fields:
            fromName: 1
            fromAddress: 1
        group2:
          label: _("Contents configuration")
          colsPerRow: 1
          fields:
            voicemailVariables: 1
            faxVariables: 1
            lowBalanceVariables: 1
            subject: 1
            body: 1
    notificationTemplatesContentsEdit_screen: &notificationTemplatesContentsEdit_screenLink
      <<: *NotificationTemplatesContents
      controller: edit
      class: ui-silk-pencil
      label: false
      fullWidth: true
      title: _("Edit %s %2s", ngettext('Notification content', 'Notification contents', 1), "[format| (%item%)]")
      fixedPositions:
        <<: *notificationTemplatesContentsFixedPositions_Link

    ###################################################################################################################
    # Screens for Voicemail Notification templates
    # This screens is like the generic one but hidding the other substitution variables helpers
    ###################################################################################################################
    notificationTemplatesContentsVoicemailList_screen: &notificationTemplatesContentsVoicemailList_screenLink
      <<: *notificationTemplatesContentsList_screenLink
      fields:
        <<: *notificationTemplatesContents_fieldsLink
        options:
          title: _("Options")
          screens:
            notificationTemplatesContentsVoicemailEdit_screen: true
          dialogs:
            notificationTemplatesContentsDel_dialog: true
          default: notificationTemplatesContentsVoicemailEdit_screen
      options:
        title: _("Options")
        screens:
          notificationTemplatesContentsVoicemailNew_screen: true
        dialogs:
          notificationTemplatesContentsDel_dialog: true
    notificationTemplatesContentsVoicemailNew_screen: &notificationTemplatesContentsVoicemailNew_screenLink
      <<: *notificationTemplatesContentsNew_screenLink
      fields:
        order:
          <<: *notificationTemplatesContentsFieldsOrderPositions_Link
        blacklist:
          faxVariables: true
          lowBalanceVariables: true
    notificationTemplatesContentsVoicemailEdit_screen: &notificationTemplatesContentsVoicemailEdit_screenLink
      <<: *notificationTemplatesContentsEdit_screenLink
      fields:
        order:
          <<: *notificationTemplatesContentsFieldsOrderPositions_Link
        blacklist:
          faxVariables: true
          lowBalanceVariables: true

    ###################################################################################################################
    # Screens for Fax Notification templates
    # This screens is like the generic one but hidding the other substitution variables helpers
    ###################################################################################################################
    notificationTemplatesContentsFaxList_screen: &notificationTemplatesContentsFaxList_screenLink
      <<: *notificationTemplatesContentsList_screenLink
      fields:
        <<: *notificationTemplatesContents_fieldsLink
        options:
          title: _("Options")
          screens:
            notificationTemplatesContentsFaxEdit_screen: true
          dialogs:
            notificationTemplatesContentsDel_dialog: true
          default: notificationTemplatesContentsFaxEdit_screen
      options:
        title: _("Options")
        screens:
          notificationTemplatesContentsFaxNew_screen: true
        dialogs:
          notificationTemplatesContentsDel_dialog: true
    notificationTemplatesContentsFaxNew_screen: &notificationTemplatesContentsFaxNew_screenLink
      <<: *notificationTemplatesContentsNew_screenLink
      fields:
        order:
          <<: *notificationTemplatesContentsFieldsOrderPositions_Link
        blacklist:
          voicemailVariables: true
          lowBalanceVariables: true
    notificationTemplatesContentsFaxEdit_screen: &notificationTemplatesContentsFaxEdit_screenLink
      <<: *notificationTemplatesContentsEdit_screenLink
      fields:
        order:
          <<: *notificationTemplatesContentsFieldsOrderPositions_Link
        blacklist:
          voicemailVariables: true
          lowBalanceVariables: true

    ###################################################################################################################
    # Screens for LowBalance Notification templates
    # This screens is like the generic one but hidding the other substitution variables helpers
    ###################################################################################################################
    notificationTemplatesContentsLowBalanceList_screen: &notificationTemplatesContentsLowBalanceList_screenLink
      <<: *notificationTemplatesContentsList_screenLink
      fields:
        <<: *notificationTemplatesContents_fieldsLink
        options:
          title: _("Options")
          screens:
            notificationTemplatesContentsLowBalanceEdit_screen: true
          dialogs:
            notificationTemplatesContentsDel_dialog: true
          default: notificationTemplatesContentsLowBalanceEdit_screen
      options:
        title: _("Options")
        screens:
          notificationTemplatesContentsLowBalanceNew_screen: true
        dialogs:
          notificationTemplatesContentsDel_dialog: true
    notificationTemplatesContentsLowBalanceNew_screen: &notificationTemplatesContentsLowBalanceNew_screenLink
      <<: *notificationTemplatesContentsNew_screenLink
      fields:
        order:
          <<: *notificationTemplatesContentsFieldsOrderPositions_Link
        blacklist:
          voicemailVariables: true
          faxVariables: true
    notificationTemplatesContentsLowBalanceEdit_screen: &notificationTemplatesContentsLowBalanceEdit_screenLink
      <<: *notificationTemplatesContentsEdit_screenLink
      fields:
        order:
          <<: *notificationTemplatesContentsFieldsOrderPositions_Link
        blacklist:
          voicemailVariables: true
          faxVariables: true

  dialogs: &notificationTemplatesContents_dialogsLink
    notificationTemplatesContentsDel_dialog: &notificationTemplatesContentsDel_dialogLink
      <<: *NotificationTemplatesContents
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Notification content', 'Notification contents', 1))
      description: _("Do you want to delete this %s?", ngettext('Notification content', 'Notification contents', 1))
      message: _("%s successfully deleted.", ngettext('Notification content', 'Notification contents', 1))
      multiItem: 1
      labelOnList: 1


staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
