#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include NotificationTemplatesContentsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: notificationTemplatesList_screen

  screens: &notificationTemplates_screensLink
    notificationTemplatesList_screen: &notificationTemplatesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *NotificationTemplates
      class: ui-silk-email
      title: _("List of %s %2s", ngettext('Notification template', 'Notification templates', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fields: &notificationTemplates_fieldsLink
        options:
          title: _("Options")
          screens:
            notificationTemplatesEdit_screen: true
            notificationTemplatesContentsVoicemailList_screen: true
            notificationTemplatesContentsFaxList_screen: true
            notificationTemplatesContentsLowBalanceList_screen: true
          dialogs:
            notificationTemplatesDel_dialog: true
          default: notificationTemplatesEdit_screen
      options:
        title: _("Options")
        screens:
          notificationTemplatesNew_screen: true
        dialogs:
          notificationTemplatesDel_dialog: true

    notificationTemplatesNew_screen: &notificationTemplatesNew_screenLink
      <<: *NotificationTemplates
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Notification template', 'Notification templates', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fixedPositions: &notificationTemplatesFixedPositions_Link
        group0:
          colsPerRow: 2
          fields:
            name: 1
            type: 1

    notificationTemplatesEdit_screen: &notificationTemplatesEdit_screenLink
      <<: *NotificationTemplates
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Notification template', 'Notification templates', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fixedPositions:
        <<: *notificationTemplatesFixedPositions_Link

    # notificationTemplatesVoicemailContents screens:
    notificationTemplatesContentsVoicemailList_screen:
      <<: *notificationTemplatesContentsVoicemailList_screenLink
      filterField: notificationTemplate
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizerFilterForNotificationVoicemail
        - recordCount
    notificationTemplatesContentsVoicemailNew_screen:
      <<: *notificationTemplatesContentsVoicemailNew_screenLink
      filterField: notificationTemplate
    notificationTemplatesContentsVoicemailEdit_screen:
      <<: *notificationTemplatesContentsVoicemailEdit_screenLink
      filterField: notificationTemplate

    # notificationTemplatesFaxContents screens:
    notificationTemplatesContentsFaxList_screen:
      <<: *notificationTemplatesContentsFaxList_screenLink
      filterField: notificationTemplate
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizerFilterForNotificationFax
        - recordCount
    notificationTemplatesContentsFaxNew_screen:
      <<: *notificationTemplatesContentsFaxNew_screenLink
      filterField: notificationTemplate
    notificationTemplatesContentsFaxEdit_screen:
      <<: *notificationTemplatesContentsFaxEdit_screenLink
      filterField: notificationTemplate

    # notificationTemplatesLowBalanceContents screens:
    notificationTemplatesContentsLowBalanceList_screen:
      <<: *notificationTemplatesContentsLowBalanceList_screenLink
      filterField: notificationTemplate
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizerFilterForNotificationLowBalance
        - recordCount
    notificationTemplatesContentsLowBalanceNew_screen:
      <<: *notificationTemplatesContentsLowBalanceNew_screenLink
      filterField: notificationTemplate
    notificationTemplatesContentsLowBalanceEdit_screen:
      <<: *notificationTemplatesContentsLowBalanceEdit_screenLink
      filterField: notificationTemplate

  dialogs: &notificationTemplates_dialogsLink
    notificationTemplatesDel_dialog: &notificationTemplatesDel_dialogLink
      <<: *NotificationTemplates
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Notification template', 'Notification templates', 1))
      description: _("Do you want to delete this %s?", ngettext('Notification template', 'Notification templates', 1))
      message: _("%s successfully deleted.", ngettext('Notification template', 'Notification templates', 1))
      multiItem: 1
      labelOnList: 1

    # notificationTemplatesContents dialogs:
    <<: *notificationTemplatesContents_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
