#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include PeerServersList.yaml
#include KamTrunksUacregList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: peeringContractsList_screen
  screens: &peeringContracts_screensLink
    peeringContractsList_screen: &peeringContractsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *PeeringContracts
      class: ui-silk-connect
      title: _("List of %s %2s", ngettext('Peering contract', 'Peering contracts', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        options:
          title: _("Options")
          screens:
            peeringContractsEdit_screen: true
            peerServersList_screen: true
            kamTrunksUacregList_screen: true
          dialogs:
            peeringContractsDel_dialog: true
          default: peeringContractsEdit_screen
        order: &PeerContractsOrder_Link
          brand: true
          name: true
          description: true
        blacklist:
          externallyRated: true
      options:
        title: _("Options")
        screens:
          peeringContractsNew_screen: true
        dialogs:
          peeringContractsDel_dialog: true
    peeringContractsNew_screen: &peeringContractsNew_screenLink
      <<: *PeeringContracts
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Peering contract', 'Peering contracts', 1))
      shortcutOption: N
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *PeerContractsOrder_Link
        blacklist:
          externallyRated: ${auth.brand.billing.disabled}
    peeringContractsEdit_screen: &peeringContractsEdit_screenLink
      <<: *PeeringContracts
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Peering contract', 'Peering contracts', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand

      fields:
        order:
          <<: *PeerContractsOrder_Link
        blacklist:
          externallyRated: ${auth.brand.billing.disabled}
    #PeerServers
    <<: *peerServers_screensLink
    peerServersList_screen:
      <<: *peerServersList_screenLink
      filterField: PeeringContract
      parentOptionCustomizer:
        - recordCount
    peerServersNew_screen:
      <<: *peerServersNew_screenLink
      filterField: PeeringContract
    peerServersEdit_screen:
      <<: *peerServersEdit_screenLink
      filterField: PeeringContract

    #kamTrunksUacreg:
    kamTrunksUacregList_screen:
      <<: *kamTrunksUacregList_screenLink
      filterField: PeeringContract
      parentOptionCustomizer:
        - recordCount
    kamTrunksUacregNew_screen:
      <<: *kamTrunksUacregNew_screenLink
      filterField: PeeringContract
    kamTrunksUacregEdit_screen:
      <<: *kamTrunksUacregEdit_screenLink
      filterField: PeeringContract

  dialogs: &peeringContracts_dialosgLink
    peeringContractsDel_dialog: &peeringContractsDel_dialogLink
      <<: *PeeringContracts
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Peering contract', 'Peering contracts', 1))
      description: _("Do you want to delete this %s?", ngettext('Peering contract', 'Peering contracts', 1))
      message: _("%s successfully deleted.", ngettext('Peering contract', 'Peering contracts', 1))
      multiItem: 1
      labelOnList: 1

    #PeerServers
    <<: *peerServers_dialogsLink
    # kamTrunksUacreg dialogs:
    <<: *kamTrunksUacreg_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
