#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: pickUpGroupsList_screen
  screens:
    pickUpGroupsList_screen: &pickUpGroupsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *PickUpGroups
      class: fa fa-phone orange
      title: _("List of %s %2s", ngettext('Pick up group', 'Pick up groups', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        options:
          title: _("Options")
          screens:
            pickUpGroupsEdit_screen: true
          dialogs:
            pickUpGroupsDel_dialog: true
          default: pickUpGroupsEdit_screen
      options:
        title: _("Options")
        screens:
          pickUpGroupsNew_screen: true
        dialogs:
          pickUpGroupsDel_dialog: true
    pickUpGroupsNew_screen: &pickUpGroupsNew_screenLink
      <<: *PickUpGroups
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Pick up group', 'Pick up groups', 1))
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
    pickUpGroupsEdit_screen: &pickUpGroupsEdit_screenLink
      <<: *PickUpGroups
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Pick up group', 'Pick up groups', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
  dialogs:
    pickUpGroupsDel_dialog: &pickUpGroupsDel_dialogLink
      <<: *PickUpGroups
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Pick up group', 'Pick up groups', 1))
      description: _("Do you want to delete this %s?", ngettext('Pick up group', 'Pick up groups', 1))
      message: _("%s successfully deleted.", ngettext('Pick up group', 'Pick up groups', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
