#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include PricingPlansRelTargetPatternsList.yaml


production:
  main:
    module: klearMatrix
    defaultScreen: pricingPlansList_screen
  screens: &pricingPlans_screensLink
    pricingPlansList_screen: &pricingPlansList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *PricingPlans
      class: ui-silk-money
      title: _("List of %s %2s", ngettext('Pricing plan', 'Pricing plans', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fields: &pricingPlans_fieldsLink
        options:
          title: _("Options")
          screens:
            pricingPlansRelTargetPatternsList_screen: true
            pricingPlansEdit_screen: true
          dialogs:
            pricingPlansDel_dialog: true
          default: pricingPlansEdit_screen
      options:
        title: _("Options")
        screens:
          pricingPlansNew_screen: true
        dialogs:
          pricingPlansDel_dialog: true
          findPlan_dialog: true
          importPlans_dialog: false
      csv:
        active: false
        filename: "PricingPlans"
        headers: true
        enclosure: '"'
        separator: ";"
        nameklear: false
        rawValues: true
        ignoreBlackList: true
        newLine: "\r\n"
        encoding: "utf-8"
        executionSeconds: ""
    pricingPlansNew_screen: &pricingPlansNew_screenLink
      <<: *PricingPlans
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Pricing plan', 'Pricing plans', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fields:
        blacklist:
          createdOn: true
      fixedPositions: &pricingPlansFixedPositions_Link
        group1:
          colsPerRow: 1
          fields:
            name: 1
            description: 1
    pricingPlansEdit_screen: &pricingPlansEdit_screenLink
      <<: *PricingPlans
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Pricing plan', 'Pricing plans', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        blacklist:
          createdOn: true
      fixedPositions:
        <<: *pricingPlansFixedPositions_Link

    #pricingPlansRelTargetPatterns:
    pricingPlansRelTargetPatternsList_screen: &pricingPlansRelTargetPatternsListEdit_screenLink
      <<: *pricingPlansRelTargetPatternsList_screenLink
      filterField: PricingPlan
      parentOptionCustomizer:
#        - IvozProvider_Klear_Options_OptionsCustomizer
        - recordCount
    pricingPlansRelTargetPatternsNew_screen:
      <<: *pricingPlansRelTargetPatternsNew_screenLink
      filterField: PricingPlan
    pricingPlansRelTargetPatternsEdit_screen:
      <<: *pricingPlansRelTargetPatternsEdit_screenLink
      filterField: PricingPlan

    #TargetPatterns:
    targetPatternsList_screen:
      controller: list
      pagination:
        items: 25
      <<: *TargetPatterns
      class: ui-silk-page-find
      title: _("List of %s %2s", ngettext('Target pattern', 'Target patterns', 0), "[format| (%parent%)]")
      filterClass: IvozProvider_Klear_Filter_PricingPlanTargetPatterns
      forcedValues:
        <<: *forcedBrand
      parentOptionCustomizer:
        - recordCount

  dialogs: &pricingPlans_dialogsLink
    pricingPlansDel_dialog: &pricingPlansDel_dialogLink
      <<: *PricingPlans
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Pricing plan', 'Pricing plans', 1))
      description: _("Do you want to delete this %s?", ngettext('Pricing plan', 'Pricing plans', 1))
      message: _("%s successfully deleted.", ngettext('Pricing plan', 'Pricing plans', 1))
      multiItem: true
      labelOnList: 1

    findPlan_dialog:
      <<: *PricingPlans
      module: default
      title: _("Find a %s", ngettext('Plan', 'Plans', 1))
      label: false
      labelOnEdit: false
      labelOnList: true
      labelOption: false
      labelOnEntityPostSave: false
      controller: klear-custom-tarificator
      action: find-plan
      class:  ui-silk-find

    testPlan_dialog:
      module: default
      title: _("Test %s", ngettext('Plan', 'Plans', 1))
      label: false
      labelOnEdit: false
      labelOnList: false
      labelOption: false
      labelOnEntityPostSave: false
      controller: klear-custom-tarificator
      action: test-plan
      class:  ui-silk-coins

    importPlans_dialog:
      <<: *PricingPlans
      module: default
      title: _("Import %s", ngettext('Pricing plan', 'Pricing plans', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-custom-file
      action: import
      class:  ui-silk-page-gear
      freeUploadCommand: importPlansFreeUpload_command
      delimiter: ","
      enclosure: '"'
      escape: "\\"
      forcedValues:
        <<: *forcedBrand

  # pricingPlansRelTargetPatterns dialogs:
    <<: *pricingPlansRelTargetPatterns_dialogsLink


  commands:
    importPlansFreeUpload_command:
      <<: *PricingPlans
      controller: File
      action: free-upload

    <<: *pricingPlansRelTargetPatterns_commandsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
