#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include QueueMembersList.yaml
#include CompaniesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: queuesList_screen
  screens: &queues_screensLink
    queuesList_screen: &queuesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Queues
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Queue', 'Queues', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/routing_endpoints/queues.html"
      forcedValues:
        <<: *forcedCompany
      fields: &queues_fieldsLink
        options:
          title: _("Options")
          screens:
            queuesEdit_screen: $[${auth.acls.Queues.update} && ${auth.companyVPBX}]
            queueMembersList_screen: $[${auth.acls.QueueMembers.read} && ${auth.companyVPBX}]
          dialogs:
            queuesDel_dialog: $[${auth.acls.Queues.delete} && ${auth.companyVPBX}]
          default: queuesEdit_screen
        order: &Queues_orderLink
          name: true
          strategy: true
          weight: true
          memberCallTimeout: true
          memberCallRest: true
          preventMissedCalls: true
          periodicAnnounceLocution: true
          maxWaitTime: true
          maxlen: true
        blacklist:
          timeoutLocution: true
          timeoutTargetType: true
          timeoutVoiceMailUser: true
          timeoutExtension: true
          timeoutNumberCountry: true
          timeoutNumberValue: true
          fullLocution: true
          fullTargetType: true
          fullExtension: true
          fullNumberCountry: true
          fullNumberValue: true
          fullVoiceMailUser: true
          periodicAnnounceLocution: true
          periodicAnnounceFrequency: true
          preventMissedCalls: true
      options:
        title: _("Options")
        screens:
          queuesNew_screen: $[${auth.acls.Queues.create} && ${auth.companyVPBX}]
        dialogs:
          queuesDel_dialog: $[${auth.acls.Queues.delete} && ${auth.companyVPBX}]

    queuesNew_screen: &queuesNew_screenLink
      <<: *Queues
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Queue', 'Queues', 1), "[format| (%parent%)]")
      shortcutOption: N
      defaultValues:
        timeoutNumberCountry: ${auth.companyCountryId}
        fullNumberCountry: ${auth.companyCountryId}
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          <<: *Queues_orderLink
      fixedPositions: &QueuesFixedPositions_Link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            name: 7
            weight: 5
            strategy: 12
        group2:
          label: _('Announce')
          colsPerRow: 12
          fields:
            periodicAnnounceLocution: 6
            periodicAnnounceFrequency: 6
        group3:
          label: _('Members configuration')
          colsPerRow: 12
          fields:
            memberCallTimeout: 6
            memberCallRest: 6
            preventMissedCalls: 6
        group4:
          label: _('Timeout configuration')
          colsPerRow: 12
          fields:
            maxWaitTime: 6
            timeoutLocution: 6
            timeoutTargetType: 4
            timeoutExtension: 6
            timeoutVoiceMailUser: 6
            timeoutNumberCountry: 4
            timeoutNumberValue: 4
        group5:
          label: _('Full Queue configuration')
          colsPerRow: 12
          fields:
            maxlen: 6
            fullLocution: 6
            fullTargetType: 4
            fullExtension: 6
            fullVoiceMailUser: 6
            fullNumberCountry: 4
            fullNumberValue: 4
    queuesEdit_screen: &queuesEdit_screenLink
      <<: *Queues
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Queue', 'Queues', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Queue', 'Queues', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          <<: *Queues_orderLink
      fixedPositions:
        <<: *QueuesFixedPositions_Link

    # queueMembers
    queueMembersList_screen:
      <<: *queueMembersList_screenLink
      filterField: Queue
      parentOptionCustomizer:
        - recordCount
    queueMembersNew_screen:
      <<: *queueMembersNew_screenLink
      filterField: Queue
    queueMembersEdit_screen:
      <<: *queueMembersEdit_screenLink
      filterField: Queue

  dialogs: &queues_dialogsLink
    queuesDel_dialog: &queuesDel_dialogLink
      <<: *Queues
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Queue', 'Queues', 1))
      description: _("Do you want to delete this %s?", ngettext('Queue', 'Queues', 1))
      message: _("%s successfully deleted.", ngettext('Queue', 'Queues', 1))
      multiItem: 1
      labelOnList: 1
  # queueMembers dialogs:
    <<: *queueMembers_dialogsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
