#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: ratingProfilesList_screen
  screens: &ratingProfiles_screensLink
    ratingProfilesList_screen: &ratingProfilesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *RatingProfiles
      class: ui-silk-money
      title: _("List of %s %2s", ngettext('Rating Profile', 'Rating Profiles', 0), "[format| (%parent%)]")
      fields: &ratingProfiles_fieldsLink
        order:
          activationTime: true
          routingProfile: true
          routingTag: true
        options:
          title: _("Options")
          screens:
            ratingProfilesEdit_screen: true
          dialogs:
            ratingProfilesDel_dialog: true
          default: ratingProfilesEdit_screen
      options:
        title: _("Options")
        screens:
          ratingProfilesNew_screen: true
        dialogs:
          ratingProfilesDel_dialog: true
          simulateCall_dialog: true

    ratingProfilesNew_screen: &ratingProfilesNew_screenLink
      <<: *RatingProfiles
      controller: new
      class: ui-silk-money-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Rating Profile', 'Rating Profiles', 1), "[format| (%parent%)]")
      shortcutOption: N
      fixedPositions: &ratingProfilesFixedPositions_Link
        group1:
          colsPerRow: 9
          fields:
            tag: 4
            name: 5
            description: 8

    ratingProfilesEdit_screen: &ratingProfilesEdit_screenLink
      <<: *RatingProfiles
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Rating Profile', 'Rating Profiles', 1), "[format| (%item%)]")
      fixedPositions:
        <<: *ratingProfilesFixedPositions_Link

  dialogs: &ratingProfiles_dialogsLink
    ratingProfilesDel_dialog: &ratingProfilesDel_dialogLink
      <<: *RatingProfiles
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Rating Profile', 'Rating Profiles', 1))
      description: _("Do you want to delete this %s?", ngettext('Rating Profile', 'Rating Profiles', 1))
      message: _("%s successfully deleted.", ngettext('Rating Profile', 'Rating Profiles', 1))
      multiItem: 1
      labelOnList: 1

    simulateCall_dialog: &simulateCall_dialogLink
      <<: *RatingProfiles
      module: default
      title: _("Simulate a call")
      label: false
      labelOnEdit: false
      labelOnList: true
      labelOption: false
      labelOnEntityPostSave: false
      controller: klear-custom-tarificator
      action: test-company-plans
      class:  ui-silk-telephone

  commands: &ratingProfiles_commandLink
    exportRatingPlansToCsv_command: &exportRatingPlansToCsv_commandLink
      <<: *RatingPlans
      title: _("Export to CSV")
      label: false
      module: default
      controller: klear-custom-download-rating-plan
      action: export-to-csv
      class:  ui-silk-bullet-disk
      forcedValues:
        company: ${auth.companyId}

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
