#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: recordingsList_screen
  screens: &recordings_screensLink
    recordingsList_screen: &recordingsList_screenLink
      controller: list
      order:
        field:
          - Recording.calldate
        type: desc      
      pagination: 
        items: 25
      <<: *Recordings
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Recording', 'Recordings', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/calls/call_recordings.html"
      forcedValues:
        <<: *forcedCompany
      fields: &recordings_fieldsLink
        blacklist:
          recordedFile: true
          callid: true
          recorder: true
          type: true
        order:
          calldate: true
          typeGhost: true
          caller: true
          callee: true
          duration: true
        options:
          title: _("Options")
          screens:
            recordingsEdit_screen: ${auth.acls.Recordings.read}
          dialogs:
            recordingsDel_dialog: $[${auth.acls.Recordings.delete} && ${auth.companyRecordingRemoval}]
          default: recordingsEdit_screen
      options:
        title: _("Options")
        dialogs:
          recordingsDel_dialog: $[${auth.acls.Recordings.delete} && ${auth.companyRecordingRemoval}]
        commands:
          recordingsRecordedFileMultiDownload_command: ${auth.acls.Recordings.read}
    recordingsEdit_screen: &recordingsEdit_screenLink
      <<: *Recordings
      controller: edit
      class: ui-silk-eye
      label: false
      labelOnPostAction: _("View %s %2s", ngettext('Recording', 'Recordings', 1), "[format| (%item%)]")
      title: _("View %s %2s", ngettext('Recording', 'Recordings', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          caller: true
          callee: true
          duration: true
        blacklist:
          calldate: true
          callid: true
          recorder: true
          type: true
        readOnly:
          recordedFile: true
          calldate: true
          callee: true
          caller: true
          duration: true
          type: true
  dialogs: &recordings_dialogsLink
    recordingsDel_dialog: &recordingsDel_dialogLink
      <<: *Recordings
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Recording', 'Recordings', 1))
      description: _("Do you want to delete this %s?", ngettext('Recording', 'Recordings', 1))
      message: _("%s successfully deleted.", ngettext('Recording', 'Recordings', 1))
      multiItem: 1
      labelOnList: 1
  commands: &recordings_commandsLink
    recordingsRecordedFileDownload_command: &recordingsRecordedFileDownload_commandLink
      <<: *Recordings
      controller: File
      action: force-download
      mainColumn: recordedFile
    recordingsRecordedFilePreview_command: &recordingsRecordedFilePreview_commandLink
      <<: *Recordings
      controller: File
      action: preview
      mainColumn: recordedFile
    recordingsRecordedFileMultiDownload_command: &recordingsRecordedFileMultiDownload_commandLink
      <<: *Recordings
      title: _("Download")
      controller: File
      action: zip-and-download
      mainColumn: recordedFile
      class: ui-silk-bullet-disk
      label: true
      multiItem: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
