#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include DdisList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: retailAccountsList_screen
  screens: &retailAccounts_screensLink
    retailAccountsList_screen: &retailAccountsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *RetailAccounts
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Retail Account', 'Retail Accounts', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/retail/retail_accounts.html"
      forcedValues:
        <<: *forcedCompany
        <<: *forcedBrand
      fields:
        blacklist: &retailAccounts_blacklistLink
          transport: true
          password: true
          fromDomain: true
          transformationRuleSet: true
          directConnectivity: true
          ip: true
          port: true
          language: true
          status: true
          ddiIn: true
        order:
          name: true
          domain: true
          description: true
          outgoingDdi: true
          statusIcon: true
        options:
          title: _("Options")
          screens:
            retailAccountsEdit_screen: ${auth.canSeeBrand}
            ddisList_screen: true
          dialogs:
            retailAccountsDel_dialog: ${auth.canSeeBrand}
          default: retailAccountsEdit_screen
      options:
        title: _("Options")
        screens:
          retailAccountsNew_screen: ${auth.canSeeBrand}
        dialogs:
          retailAccountsDel_dialog: ${auth.canSeeBrand}

    retailAccountsNew_screen: &retailAccountsNew_screenLink
      <<: *RetailAccounts
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Retail Account', 'Retail Accounts', 1), "[format| (%parent%)]")
      scripts:
        module: default
        name: jquery.passwordgennew.js
      plugin: passwordgennew
      forcedValues:
        <<: *forcedCompany
        <<: *forcedBrand
      fields:
        blacklist: &retailAccounts_blacklistLink
          domain: true
          status: true
          statusIcon: true
        order: &retailAccounts_orderLink
          id: true
          name: true
          description: true
          password: true
          directConnectivity: true
          transport: true
          ip: true
          port: true
          outgoingDdi: true
          transformationRuleSet: true
          fromDomain: true
          ddiIn: true
          status: true
      fixedPositions: &retailAccounts_FixedPositionsLink
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            name: 4
            description: 6
            priority: 2
            password: 5
            directConnectivity: 3
            __empty1: 4
            transport: 4
            ip: 5
            port: 3
        group1:
          label: _("Geographic Configuration")
          colsPerRow: 12
          fields:
            language: 4
            transformationRuleSet: 8
        group2:
          label: _("Outgoing Configuration")
          colsPerRow: 12
          fields:
            outgoingDdi: 5
        group3:
          label: _("Advanced Configuration")
          colsPerRow: 6
          fields:
            fromDomain: 3
            ddiIn: 3

    retailAccountsEdit_screen: &retailAccountsEdit_screenLink
      <<: *RetailAccounts
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Retail Account', 'Retail Accounts', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Retail Account', 'Retail Accounts', 1), "[format| (%item%)]")
      scripts:
        module: default
        name: jquery.passwordgenedit.js
      plugin: passwordgen
      fields:
        order:
          <<: *retailAccounts_orderLink
        blacklist:
          domain: true
          statusIcon: true
        whitelist:
          id: true
      fixedPositions:
          <<: *retailAccounts_FixedPositionsLink
      forcedValues:
        <<: *forcedCompany
        <<: *forcedBrand

    <<: *ddis_screenLink
    ddisList_screen:
      <<: *ddisList_screenLink
      filterField: retailAccount
      parentOptionCustomizer:
        - recordCount
    ddisNew_screen:
      <<: *ddisNew_screenLink
      filterField: retailAccount
    ddisEdit_screen:
      <<: *ddisEdit_screenLink
      filterField: retailAccount

  dialogs: &retailAccounts_dialogsLink
    retailAccountsDel_dialog: &retailAccountsDel_dialogLink
      <<: *RetailAccounts
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Retail Account', 'Retail Accounts', 1))
      description: _("Do you want to delete this %s?", ngettext('Retail Account', 'Retail Accounts', 1))
      message: _("%s successfully deleted.", ngettext('Retail Account', 'Retail Accounts', 1))
      multiItem: 1
      labelOnList: 1

    <<: *ddis_dialogsLink

  commands:
    generatePassword_command:
      <<: *RetailAccounts
      title: "Generate new secure password"
      class: ui-silk-arrow-refresh
      module: default
      controller: Password
      action: generate

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
