#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: routingPatternGroupsList_screen
  screens: &routingPatternGroups_screensLink
    routingPatternGroupsList_screen: &routingPatternGroupsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *RoutingPatternGroups
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Routing pattern group', 'Routing pattern groups', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/routing/routing_patterns_groups.html"
      forcedValues:
        <<: *forcedBrand
      fields: &routingPatternGroups_fieldsLink
        options:
          title: _("Options")
          screens:
            routingPatternGroupsEdit_screen: true
          dialogs:
            routingPatternGroupsDel_dialog: true
          default: routingPatternGroupsEdit_screen
      options:
        title: _("Options")
        screens:
          routingPatternGroupsNew_screen: true
        dialogs:
          routingPatternGroupsDel_dialog: true
    routingPatternGroupsNew_screen: &routingPatternGroupsNew_screenLink
      <<: *RoutingPatternGroups
      controller: new
      class: ui-silk-add
      forcedValues:
        <<: *forcedBrand
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Routing pattern group', 'Routing pattern groups', 1))
      shortcutOption: N
    routingPatternGroupsEdit_screen: &routingPatternGroupsEdit_screenLink
      <<: *RoutingPatternGroups
      controller: edit
      class: ui-silk-pencil
      label: false
      forcedValues:
        <<: *forcedBrand
      labelOnPostAction: _("Edit %s %2s", ngettext('Routing pattern group', 'Routing pattern groups', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Routing pattern group', 'Routing pattern groups', 1), "[format| (%item%)]")

  dialogs: &routingPatternGroups_dialogsLink
    routingPatternGroupsDel_dialog: &routingPatternGroupsDel_dialogLink
      <<: *RoutingPatternGroups
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Routing pattern group', 'Routing pattern groups', 1))
      description: _("Do you want to delete this %s?", ngettext('Routing pattern group', 'Routing pattern groups', 1))
      message: _("%s successfully deleted.", ngettext('Routing pattern group', 'Routing pattern groups', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
