#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: routingPatternsList_screen
  screens: &routingPatterns_screensLink
    routingPatternsList_screen: &routingPatternsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *RoutingPatterns
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Routing pattern', 'Routing patterns', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/routing/routing_patterns.html"
      forcedValues:
        <<: *forcedBrand
      fields: &routingPatterns_fieldsLink
        options:
          title: _("Options")
          screens:
            routingPatternsEdit_screen: true
          dialogs:
            routingPatternsDel_dialog: true
          default: routingPatternsEdit_screen
      options:
        title: _("Options")
        screens:
          routingPatternsNew_screen: true
        dialogs:
          routingPatternsDel_dialog: true
    routingPatternsNew_screen: &routingPatternsNew_screenLink
      <<: *RoutingPatterns
      controller: new
      class: ui-silk-add
      forcedValues:
        <<: *forcedBrand
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Routing pattern', 'Routing patterns', 1), "[format| (%parent%)]")
      shortcutOption: N
    routingPatternsEdit_screen: &routingPatternsEdit_screenLink
      <<: *RoutingPatterns
      controller: edit
      class: ui-silk-pencil
      forcedValues:
        <<: *forcedBrand
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Routing pattern', 'Routing patterns', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Routing pattern', 'Routing patterns', 1), "[format| (%item%)]")

  dialogs: &routingPatterns_dialogsLink
    routingPatternsDel_dialog: &routingPatternsDel_dialogLink
      <<: *RoutingPatterns
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Routing pattern', 'Routing patterns', 1))
      description: _("Do you want to delete this %s?", ngettext('Routing pattern', 'Routing patterns', 1))
      message: _("%s successfully deleted.", ngettext('Routing pattern', 'Routing patterns', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
