#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: schedulesList_screen
  screens: &schedules_screensLink
    schedulesList_screen: &schedulesList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *Schedules
      class: ui-silk-clock
      title: _("List of %s %2s", ngettext('Schedule', 'Schedules', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        options:
          title: _("Options")
          screens:
            schedulesEdit_screen: true
          dialogs:
            schedulesDel_dialog: true
          default: schedulesEdit_screen
        blacklist: &schedule_blacklistLink
          monday: true
          tuesday: true
          wednesday: true
          thursday: true
          friday: true
          saturday: true
          sunday: true
      options:
        title: _("Options")
        screens:
          schedulesNew_screen: true
        dialogs:
          schedulesDel_dialog: true
    schedulesNew_screen: &schedulesNew_screenLink
      <<: *Schedules
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s %2s", ngettext('Schedule', 'Schedules', 1), "[format| (%parent%)]")
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
      fixedPositions: &schedule_fixedPosLink
        group0:
          colsPerRow: 2
          fields:
            company: 1
            name: 1
        group1:
          colsPerRow: 2
          fields:
            timeIn: 1
            timeOut: 1
        group2:
          colsPerRow: 6
          fields:
            monday: true
            tuesday: true
            wednesday: true
            thursday: true
            friday: true
            saturday: true
            sunday: true

    schedulesEdit_screen: &schedulesEdit_screenLink
      <<: *Schedules
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Schedule', 'Schedules', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fixedPositions:
        <<: *schedule_fixedPosLink
  dialogs: &schedules_dialogsLink
    schedulesDel_dialog: &schedulesDel_dialogLink
      <<: *Schedules
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Schedule', 'Schedules', 1))
      description: _("Do you want to delete this %s?", ngettext('Schedule', 'Schedules', 1))
      message: _("%s successfully deleted.", ngettext('Schedule', 'Schedules', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
