#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include PricingPlansRelTargetPatternsList.yaml
#include PricingPlansList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: targetPatternsList_screen
  screens: &targetPatterns_screensLink
    targetPatternsList_screen: &targetPatternsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *TargetPatterns
      class: ui-silk-page-find
      title: _("List of %s %2s", ngettext('Pricing pattern', 'Pricing patterns', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fields: &targetPatterns_fieldsLink
        options:
          title: _("Options")
          screens:
#            pricingPlansRelTargetPatternsList_screen: true
            targetPatternsEdit_screen: true
          dialogs:
            targetPatternsDel_dialog: true
          default: targetPatternsEdit_screen
      options:
        title: _("Options")
        screens:
          targetPatternsNew_screen: true
        dialogs:
          targetPatternsDel_dialog: true
          importPatterns_dialog: false
      csv:
        active: false
        filename: "TargetPatterns"
        headers: true
        enclosure: '"'
        separator: ";"
        nameklear: false
        rawValues: true
        ignoreBlackList: true
        newLine: "\r\n"
        encoding: "utf-8"
        executionSeconds: ""

    targetPatternsNew_screen: &targetPatternsNew_screenLink
      <<: *TargetPatterns
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Pricing pattern', 'Pricing patterns', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fixedPositions: &ptargetPatternsFixedPositions_Link
        group1:
          colsPerRow: 9
          fields:
            name: 4
            description: 5
        group2:
          colsPerRow: 1
          fields:
            regexp: 1
    targetPatternsEdit_screen: &targetPatternsEdit_screenLink
      <<: *TargetPatterns
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Pricing pattern', 'Pricing patterns', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fixedPositions:
        <<: *ptargetPatternsFixedPositions_Link

    #pricingPlansRelTargetPatterns:
    <<: *pricingPlansRelTargetPatterns_screensLink
    pricingPlansRelTargetPatternsList_screen:
      <<: *pricingPlansRelTargetPatternsList_screenLink
      filterField: TargetPattern
      parentOptionCustomizer:
        - recordCount
    pricingPlansRelTargetPatternsNew_screen:
      <<: *pricingPlansRelTargetPatternsNew_screenLink
      filterField: targetPattern
    pricingPlansRelTargetPatternsEdit_screen:
      <<: *pricingPlansRelTargetPatternsEdit_screenLink
      filterField: targetPattern

    #PricingPlans:
    pricingPlansList_screen:
      controller: list
      pagination:
        items: 25
      <<: *PricingPlans
      class: ui-silk-money
      title: _("List of %s %2s", ngettext('Pricing plan', 'Pricing plans', 0), "[format| (%parent%)]")
      filterClass: IvozProvider_Klear_Filter_TargetPatternPricingPlans
      forcedValues:
        <<: *forcedBrand
      parentOptionCustomizer:
        - recordCount

  dialogs: &targetPatterns_dialogsLink
    targetPatternsDel_dialog: &targetPatternsDel_dialogLink
      <<: *TargetPatterns
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Pricing pattern', 'Pricing patterns', 1))
      description: _("Do you want to delete this %s?", ngettext('Pricing pattern', 'Pricing patterns', 1))
      message: _("%s successfully deleted.", ngettext('Pricing pattern', 'Pricing patterns', 1))
      multiItem: 1
      labelOnList: 1

    importPatterns_dialog:
      <<: *TargetPatterns
      module: default
      title: _("Import %s", ngettext('Pricing pattern', 'Pricing patterns', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-file
      action: import
      class:  ui-silk-page-gear
      freeUploadCommand: importPatternsFreeUpload_command
      delimiter: ";"
      enclosure: '"'
      escape: "\\"
      forcedValues:
        <<: *forcedBrand

  #PricingPlans:
    <<: *pricingPlans_dialogsLink

  # pricingPlansRelTargetPatterns dialogs:
    <<: *pricingPlansRelTargetPatterns_dialogsLink

  commands:
    importPatternsFreeUpload_command:
      <<: *TargetPatterns
      controller: File
      action: free-upload
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
