#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include conf.d/terminalManufacturersHelp.yaml:
#include TerminalModelsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: terminalManufacturersList_screen
  screens:
    terminalManufacturersList_screen: &terminalManufacturersList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *TerminalManufacturers
      class: ui-silk-telephone-link
      title: _("List of %s %2s", ngettext('Terminal manufacturer', 'Terminal manufacturers', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/terminal_manufacturers.html"
      fields:
        options:
          title: _("Options")
          screens:
            terminalManufacturersEdit_screen: true
            terminalModelsList_screen: ${auth.acls.TerminalModels.read}
          dialogs:
            terminalManufacturersDel_dialog: true
          default: terminalManufacturersEdit_screen
      options:
        title: _("Options")
        screens:
          terminalManufacturersNew_screen: true
        dialogs:
          terminalManufacturersDel_dialog: true
      <<: *terminalManufacturersHelp
    terminalManufacturersNew_screen: &terminalManufacturersNew_screenLink
      <<: *TerminalManufacturers
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Terminal manufacturer', 'Terminal manufacturers', 1))
      shortcutOption: N
      <<: *terminalManufacturersHelp
    terminalManufacturersEdit_screen: &terminalManufacturersEdit_screenLink
      <<: *TerminalManufacturers
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Terminal manufacturer', 'Terminal manufacturers', 1), "[format| (%item%)]")
      <<: *terminalManufacturersHelp

    #TerminalModels
    <<: *terminalModels_screensLink
    terminalModelsList_screen:
      <<: *terminalModelsList_screenLink
      filterField: terminalManufacturer
      parentOptionCustomizer:
        - recordCount
    terminalModelsNew_screen:
      <<: *terminalModelsNew_screenLink
      filterField: terminalManufacturer
    terminalModelsEdit_screen:
      <<: *terminalModelsEdit_screenLink
      filterField: terminalManufacturer
      fields:
        order:
          <<: *terminalModels_orderLink
        readOnly:
          TerminalManufacturer: true

  dialogs:
    terminalManufacturersDel_dialog: &terminalManufacturersDel_dialogLink
      <<: *TerminalManufacturers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Terminal manufacturer', 'Terminal manufacturers', 1))
      description: _("Do you want to delete this %s?", ngettext('Terminal manufacturer', 'Terminal manufacturers', 1))
      message: _("%s successfully deleted.", ngettext('Terminal manufacturer', 'Terminal manufacturers', 1))
      multiItem: 1
      labelOnList: 1

    #TerminalModels
    <<: *terminalModels_dialogsLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
