#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include TerminalsList.yaml
#include conf.d/terminalManufacturersHelp.yaml:

production:
  main:
    module: klearMatrix
    defaultScreen: terminalModelsList_screen
  screens: &terminalModels_screensLink
    terminalModelsList_screen: &terminalModelsList_screenLink
      <<: *terminalManufacturersHelp
      controller: list
      pagination:
        items: 25
      <<: *TerminalModels
      class: ui-silk-telephone-key
      title: _("List of %s %2s", ngettext('Terminal model', 'Terminal models', 0), "[format| (%parent%)]")
      fields:
        options:
          title: _("Options")
          screens:
            terminalModelsEdit_screen: ${auth.acls.TerminalModels.update}
          dialogs:
            terminalModelsDel_dialog: ${auth.acls.TerminalModels.delete}
          default: terminalModelsEdit_screen
        order: &terminalModels_orderLink
          terminalManufacturer: true
          iden: true
          name: true
          description: true
          genericUrlPattern: true
          genericTemplate: true
          specificUrlPattern: true
          specificTemplate: true
        blacklist:
          genericTemplate: true
          specificTemplate: true
      options:
        title: _("Options")
        screens:
          terminalModelsNew_screen: ${auth.acls.TerminalModels.create}
        dialogs:
          terminalModelsDel_dialog: ${auth.acls.TerminalModels.delete}
    terminalModelsNew_screen: &terminalModelsNew_screenLink
      <<: *terminalManufacturersHelp
      <<: *TerminalModels
      controller: new
      class: ui-silk-add
      label: true
      fullWidth: true
      multiInstance: true
      title: _("Add %s", ngettext('Terminal model', 'Terminal models', 1))
      shortcutOption: N
      fields:
        order:
          <<: *terminalModels_orderLink
    terminalModelsEdit_screen: &terminalModelsEdit_screenLink
      <<: *terminalManufacturersHelp
      <<: *TerminalModels
      controller: edit
      class: ui-silk-pencil
      label: false
      fullWidth: true
      title: _("Edit %s %2s", ngettext('Terminal model', 'Terminal models', 1), "[format| (%item%)]")
      fields:
        order:
          <<: *terminalModels_orderLink
  dialogs: &terminalModels_dialogsLink
    terminalModelsDel_dialog: &terminalModelsDel_dialogLink
      <<: *TerminalModels
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Terminal model', 'Terminal models', 1))
      description: _("Do you want to delete this %s?", ngettext('Terminal model', 'Terminal models', 1))
      message: _("%s successfully deleted.", ngettext('Terminal model', 'Terminal models', 1))
      multiItem: 1
      labelOnList: 1

    uploadFile_dialog: &uploadFile_dialogLink
      title: _("Load file")
      module: default
      controller: klear-custom-upload-file
      labelOnEdit: true
      action: upload-file
      class: ui-silk-arrow-up
    downloadFile_dialog: &downloadFile_dialogLink
      title: _("Download file")
      module: default
      controller: klear-custom-download-file
      labelOnEdit: true
      action: download-file
      class: ui-silk-arrow-down
    genericBackup_dialog: &genericBackup_dialogLink
      title: _("Restore last backup")
      module: default
      controller: klear-custom-restore-backup
      labelOnEdit: true
      action: restore-generic-backup
      class: ui-silk-arrow-undo
    specificBackup_dialog: &specificcBackup_dialogLink
      title: _("Restore last backup")
      module: default
      controller: klear-custom-restore-backup
      labelOnEdit: true
      action: restore-specific-backup
      class: ui-silk-arrow-undo
    genericDefault_dialog: &genericDefault_dialogLink
      title: _("Restore default template")
      module: default
      controller: klear-custom-restore-default
      labelOnEdit: true
      action: restore-generic-default
      class: ui-silk-page-white-star
    specificDefault_dialog: &specificDefault_dialogLink
      title: _("Restore default template")
      module: default
      controller: klear-custom-restore-default
      labelOnEdit: true
      action: restore-specific-default
      class: ui-silk-page-white-star
    runGenericCode_dialog: &runGenericCode_dialogLink
      title: _("Run template")
      module: default
      controller: klear-custom-run-code
      labelOnEdit: true
      action: run-generic-code
      class: ui-silk-control-play-blue
    runSpecificCode_dialog: &runSpecificCode_dialogLink
      title: _("Run template")
      module: default
      controller: klear-custom-run-code
      labelOnEdit: true
      action: run-specific-code
      class: ui-silk-control-play-blue
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
