#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: tpRatingPlansList_screen
  screens: &tpRatingPlans_screensLink
    tpRatingPlansList_screen: &tpRatingPlansList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *TpRatingPlans
      class: ui-silk-page-find
      title: _("List of %s %2s", ngettext('Rating plan', 'Rating plans', 0), "[format| (%parent%)]")
      fields: &tpRatingPlans_fieldsLink
        order:
          tag: true
          name: true
          description: true
        blacklist: &tpRatingPlans_blacklistLink
          timing: true
        options:
          title: _("Options")
          screens:
            tpRatingPlansEdit_screen: true
          dialogs:
            tpRatingPlansDel_dialog: true
          default: tpRatingPlansEdit_screen
      options:
        title: _("Options")
        screens:
          tpRatingPlansNew_screen: true
        dialogs:
          tpRatingPlansDel_dialog: true
          simulateRatingPlanCall_dialog: true

    tpRatingPlansNew_screen: &tpRatingPlansNew_screenLink
      <<: *TpRatingPlans
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Rating plan', 'Rating plans', 1), "[format| (%parent%)]")
      shortcutOption: N
      fields:
        blacklist:
          <<: *tpRatingPlans_blacklistLink
      fixedPositions: &tpRatingPlans_fixedPositionsLink
        group1:
          colsPerRow: 4
          fields:
            destinationRateGroup: 3
            weight: 1
        group2:
          colsPerRow: 6
          fields:
            timingType: 3
            timeIn: 3
            monday: 1
            tuesday: 1
            wednesday: 1
            thursday: 1
            friday: 1
            saturday: 1
            sunday: 1

    tpRatingPlansEdit_screen: &tpRatingPlansEdit_screenLink
      <<: *TpRatingPlans
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Rating plan', 'Rating plans', 1), "[format| (%item%)]")
      fields:
        blacklist:
          <<: *tpRatingPlans_blacklistLink
      fixedPositions:
        <<: *tpRatingPlans_fixedPositionsLink

  dialogs: &tpRatingPlans_dialogsLink
    tpRatingPlansDel_dialog: &tpRatingPlansDel_dialogLink
      <<: *TpRatingPlans
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Rating plan', 'Rating plans', 1))
      description: _("Do you want to delete this %s?", ngettext('Rating plan', 'Rating plans', 1))
      message: _("%s successfully deleted.", ngettext('Rating plan', 'Rating plans', 1))
      multiItem: 1
      labelOnList: 1

    simulateRatingPlanCall_dialog: &simulateRatingPlanCall_dialogLink
      <<: *DestinationRates
      module: default
      title: _("Simulate a call")
      label: false
      labelOnEdit: false
      labelOnList: true
      labelOption: false
      labelOnEntityPostSave: false
      controller: klear-custom-tarificator
      action: test-rating-plan
      class:  ui-silk-telephone

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
