#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include TransformationRulesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: transformationRuleSetsList_screen
  screens: &transformationRuleSets_screensLink
    transformationRuleSetsList_screen: &transformationRuleSetsList_screenLink
      controller: list
      pagination:
        items: 25
      class: ui-silk-shape-rotate-anticlockwise
      <<: *TransformationRuleSets
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Numeric transformation', 'Numeric transformations', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/settings/numeric_transformations.html"
      rawCondition: "(TransformationRuleSet.brand IS NULL OR TransformationRuleSet.brand = '${auth.brandId}')"
      order:
        field:
          - "TransformationRuleSet.brand desc"
          - "TransformationRuleSet.name.${lang} asc"
      fields: &transformationRuleSets_fieldsLink
        options:
          title: _("Options")
          screens:
            transformationRuleSetsEdit_screen: ${auth.acls.TransformationRuleSets.update}
            transformationRuleSetsView_screen: ${auth.acls.TransformationRuleSets.read}
            transformationRulesCallerInList_screen: true
            transformationRulesCalleeInList_screen: true
            transformationRulesCallerOutList_screen: true
            transformationRulesCalleeOutList_screen: true
            transformationRulesCallerInView_screen: true
            transformationRulesCalleeInView_screen: true
            transformationRulesCallerOutView_screen: true
            transformationRulesCalleeOutView_screen: true
          dialogs:
            transformationRuleSetsDel_dialog: ${auth.acls.TransformationRuleSets.delete}
        blacklist:
          brand: true
          trunkPrefix: true
          areaCode: true
          nationalLen: true
          country: true
          internationalCode: true
          generateRules: true
        order: &transformationRuleSets_orderLink
          brand: true
          name: true
          description: true
          country: true
          internationalCode: true
      options:
        title: _("Options")
        screens:
          transformationRuleSetsNew_screen: ${auth.acls.TransformationRuleSets.create}


    transformationRuleSetsNew_screen: &transformationRuleSetsNew_screenLink
      <<: *TransformationRuleSets
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Numeric transformation', 'Numeric transformations', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      defaultValues:
        generateRules: 1
      fields:
        order:
          <<: *transformationRuleSets_orderLink
      fixedPositions: &transformationRuleSetsFixedPositions_Link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 2
          fields:
            name: 1
            description: 1
        group1:
          label: _("Geographic Configuration")
          colsPerRow: 12
          fields:
            internationalCode: 5
            country: 5
            trunkPrefix: 3
            areaCode: 3
            nationalLen: 4
        group2:
          label: _("Automatic creation of rules")
          colsPerRow: 12
          fields:
            generateRules: 12

    transformationRuleSetsEdit_screen: &transformationRuleSetsEdit_screenLink
      <<: *TransformationRuleSets
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Numeric transformation', 'Numeric transformations', 0), "[format| (%item%)]")
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
      forcedValues:
        <<: *forcedBrand
      fields:
        order:
          <<: *transformationRuleSets_orderLink
      fixedPositions:
        <<: *transformationRuleSetsFixedPositions_Link

    transformationRuleSetsView_screen:
      <<: *transformationRuleSetsEdit_screenLink
      class: ui-silk-eye
      label: false
      title: _("View %s %2s", ngettext('Numeric transformation', 'Numeric transformations', 0), "[format| (%item%)]")
      fields:
        blacklist:
          generateRules: true
        readOnly:
          name: true
          description: true
          internationalCode: true
          country: true
          trunkPrefix: true
          areaCode: true
          nationalLen: true

    # Transformation Rules Editable Screens
    <<: *transformationRules_screensLink
    transformationRulesCallerInList_screen:
      <<: *transformationRulesList_screenLink
      title: _("Caller In transformations")
      class: ui-silk-shape-rotate-anticlockwise
      forcedValues:
        type: callerin
      options:
        <<: *transformationRulesNew_optionsLink
        screens:
          transformationRulesCallerInNew_screen: true
    transformationRulesCalleeInList_screen:
      <<: *transformationRulesList_screenLink
      title: _("Callee In transformations")
      class: ui-silk-shape-rotate-anticlockwise
      forcedValues:
        type: calleein
      options:
        <<: *transformationRulesNew_optionsLink
        screens:
          transformationRulesCalleeInNew_screen: true
    transformationRulesCallerOutList_screen:
      <<: *transformationRulesList_screenLink
      title: _("Caller Out transformations")
      class: ui-silk-shape-rotate-clockwise
      forcedValues:
        type: callerout
      options:
        <<: *transformationRulesNew_optionsLink
        screens:
          transformationRulesCallerOutNew_screen: true
    transformationRulesCalleeOutList_screen:
      <<: *transformationRulesList_screenLink
      title: _("Callee Out transformations")
      class: ui-silk-shape-rotate-clockwise
      forcedValues:
        type: calleeout
      options:
        <<: *transformationRulesNew_optionsLink
        screens:
          transformationRulesCalleeOutNew_screen: true

    # Transformation Rules NewRule screens
    transformationRulesCallerInNew_screen:
      <<: *transformationRulesNew_screenLink
      forcedValues:
        type: callerin
    transformationRulesCalleeInNew_screen:
      <<: *transformationRulesNew_screenLink
      forcedValues:
        type: calleein
    transformationRulesCallerOutNew_screen:
      <<: *transformationRulesNew_screenLink
      forcedValues:
        type: callerout
    transformationRulesCalleeOutNew_screen:
      <<: *transformationRulesNew_screenLink
      forcedValues:
        type: calleeout

    # Transformation Rules ReadOnly Screens
    transformationRulesCallerInView_screen:
      <<: *transformationRuleSetsView_screenLink
      title: _("Caller In transformations")
      class: ui-silk-shape-rotate-anticlockwise inherited
      forcedValues:
        type: callerin
    transformationRulesCalleeInView_screen:
      <<: *transformationRuleSetsView_screenLink
      title: _("Callee In transformations")
      class: ui-silk-shape-rotate-anticlockwise
      forcedValues:
        type: calleein
    transformationRulesCallerOutView_screen:
      <<: *transformationRuleSetsView_screenLink
      title: _("Caller Out transformations")
      class: ui-silk-shape-rotate-clockwise
      forcedValues:
        type: callerout
    transformationRulesCalleeOutView_screen:
      <<: *transformationRuleSetsView_screenLink
      title: _("Callee Out transformations")
      class: ui-silk-shape-rotate-clockwise
      forcedValues:
        type: calleeout

  dialogs: &transformationRuleSets_dialogsLink
    transformationRuleSetsDel_dialog: &transformationRuleSetsDel_dialogLink
      <<: *TransformationRuleSets
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Numeric transformation', 'Numeric transformations', 0))
      description: _("Do you want to delete this %s?", ngettext('Numeric transformation', 'Numeric transformations', 0))
      message: _("%s successfully deleted.", ngettext('Numeric transformation', 'Numeric transformations', 0))
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizer
      multiItem: 1
      labelOnList: 1

    # Transformation Rules Dialogs
    <<: *transformationRules_dialogsLink
    transformationRulesDel_dialog:
      <<: *transformationRulesDel_dialogLink

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
