#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include PeerServersList.yaml
#include KamTrunksDialplanList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: transformationRulesetGroupsTrunksList_screen
  screens: &transformationRulesetGroupsTrunks_screensLink
    transformationRulesetGroupsTrunksList_screen: &transformationRulesetGroupsTrunksList_screenLink
      controller: list
      pagination:
        items: 25
      class: ui-silk-shape-rotate-anticlockwise
      <<: *TransformationRulesetGroupsTrunks
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Numeric transformation group', 'Numeric transformation groups', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      fields: &transformationRulesetGroupsTrunks_fieldsLink
        options:
          title: _("Options")
          screens:
            transformationRulesetGroupsTrunksEdit_screen: true
            kamTrunksDialplan_callee_inList_screen: true
            kamTrunksDialplan_caller_inList_screen: true
            kamTrunksDialplan_callee_outList_screen: true
            kamTrunksDialplan_caller_outList_screen: true
            peerServersList_screen: false
          dialogs:
            transformationRulesetGroupsTrunksDel_dialog: true
          default: transformationRulesetGroupsTrunksEdit_screen
        blacklist: &transformationRulesetGroupsTrunks_blacklistLink
          callerIn: true
          calleeIn: true
          callerOut: true
          calleeOut: true
          automatic: true
          countryId: true
          nationalNumLength: true
          internationalCode: true
        order: &transformationRulesetGroupsTrunks_orderLink
          brandId: true
          name: true
          description: true
          automatic: true
          countryId: true
          internationalCode: true
      options:
        title: _("Options")
        screens:
          transformationRulesetGroupsTrunksNew_screen: true
        dialogs:
          transformationRulesetGroupsTrunksDel_dialog: true
    transformationRulesetGroupsTrunksNew_screen: &transformationRulesetGroupsTrunksNew_screenLink
      <<: *TransformationRulesetGroupsTrunks
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Numeric transformation group', 'Numeric transformation groups', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedBrand
      shortcutOption: N
      fields:
        blacklist:
          callerIn: true
          calleeIn: true
          callerOut: true
          calleeOut: true
          nationalNumLength: true
        order:
          <<: *transformationRulesetGroupsTrunks_orderLink
      fixedPositions: &transformationRulesetGroupsTrunksFixedPositions_Link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 2
          fields:
            name: 1
            description: 1
        group1:
          label: _("Automatic creation of rules")
          colsPerRow: 12
          fields:
            automatic: 3
            countryId: 5
            internationalCode: 4
    transformationRulesetGroupsTrunksEdit_screen: &transformationRulesetGroupsTrunksEdit_screenLink
      <<: *TransformationRulesetGroupsTrunks
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Numeric transformation group', 'Numeric transformation groups', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedBrand
      fields:
        blacklist:
          <<: *transformationRulesetGroupsTrunks_blacklistLink
        order:
          <<: *transformationRulesetGroupsTrunks_orderLink
      fixedPositions:
        <<: *transformationRulesetGroupsTrunksFixedPositions_Link
    #peerServers:
    <<: *peerServers_screensLink
    peerServersList_screen:
      <<: *peerServersList_screenLink
      filterField: TransformationRulesetGroupsTrunk
      parentOptionCustomizer:
        - recordCount
    peerServersNew_screen:
      <<: *peerServersNew_screenLink
      filterField: TransformationRulesetGroupsTrunk
    peerServersEdit_screen:
      <<: *peerServersEdit_screenLink
      filterField: TransformationRulesetGroupsTrunk

    #TrunksDialplan
    <<: *kamTrunksDialplan_screensLink

    kamTrunksDialplan_caller_inList_screen:
      <<: *kamTrunksDialplanList_screenLink
      title: _("Caller In transformations")
      order:
        field:
          - TrunksDialplan.pr
        type: asc
      filterClass: IvozProvider_Klear_Filter_KamDialplanCallerIn
      parentOptionCustomizer:
        - recordCount
      options:
        title: _("Options")
        screens:
          kamTrunksDialplan_caller_inNew_screen: true
        dialogs:
          kamTrunksDialplanDel_dialog: true
    kamTrunksDialplan_caller_inNew_screen:
      <<: *kamTrunksDialplanNew_screenLink
      forcedValues:
        "self::matchOp": 1
        "self::matchLen": 0
        parentReferenceField: "CallerIn"

    kamTrunksDialplan_callee_inList_screen:
      <<: *kamTrunksDialplanList_screenLink
      title: _("Callee In transformations")
      order:
        field:
          - TrunksDialplan.pr
        type: asc
      filterClass: IvozProvider_Klear_Filter_KamDialplanCalleeIn
      parentOptionCustomizer:
        - recordCount
      options:
        title: _("Options")
        screens:
          kamTrunksDialplan_callee_inNew_screen: true
        dialogs:
          kamTrunksDialplanDel_dialog: true
    kamTrunksDialplan_callee_inNew_screen:
      <<: *kamTrunksDialplanNew_screenLink
      forcedValues:
        "self::matchOp": 1
        "self::matchLen": 0
        parentReferenceField: "CalleeIn"

    kamTrunksDialplan_caller_outList_screen:
      <<: *kamTrunksDialplanList_screenLink
      title: _("Caller Out transformations")
      order:
        field:
          - TrunksDialplan.pr
        type: asc
      filterClass: IvozProvider_Klear_Filter_KamDialplanCallerOut
      parentOptionCustomizer:
        - recordCount
      options:
        title: _("Options")
        screens:
          kamTrunksDialplan_caller_outNew_screen: true
        dialogs:
          kamTrunksDialplanDel_dialog: true
    kamTrunksDialplan_caller_outNew_screen:
      <<: *kamTrunksDialplanNew_screenLink
      forcedValues:
        "self::matchOp": 1
        "self::matchLen": 0
        parentReferenceField: "CallerOut"

    kamTrunksDialplan_callee_outList_screen:
      <<: *kamTrunksDialplanList_screenLink
      title: _("Callee Out transformations")
      order:
        field:
          - TrunksDialplan.pr
        type: asc
      filterClass: IvozProvider_Klear_Filter_KamDialplanCalleeOut
      parentOptionCustomizer:
        - recordCount
      options:
        title: _("Options")
        screens:
          kamTrunksDialplan_callee_outNew_screen: true
        dialogs:
          kamTrunksDialplanDel_dialog: true
    kamTrunksDialplan_callee_outNew_screen:
      <<: *kamTrunksDialplanNew_screenLink
      forcedValues:
        "self::matchOp": 1
        "self::matchLen": 0
        parentReferenceField: "CalleeOut"

  dialogs: &transformationRulesetGroupsTrunks_dialogsLink
    transformationRulesetGroupsTrunksDel_dialog: &transformationRulesetGroupsTrunksDel_dialogLink
      <<: *TransformationRulesetGroupsTrunks
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Numeric transformation group', 'Numeric transformation groups', 1))
      description: _("Do you want to delete this %s?", ngettext('Numeric transformation group', 'Numeric transformation groups', 1))
      message: _("%s successfully deleted.", ngettext('Numeric transformation group', 'Numeric transformation groups', 1))
      multiItem: 1
      labelOnList: 1

  # peerServers dialogs:
    <<: *peerServers_dialogsLink

  #TrunksDialplan
    <<: *kamTrunksDialplan_dialogsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
