#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include HuntGroupMembersList.yaml
#include CallForwardSettingsList.yaml
#include DDIsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: usersList_screen
  screens: &users_screensLink
    usersList_screen: &usersList_screenLink
      controller: list
      pagination:
        items: 25
      order:
        field:
          - User.name asc
      <<: *Users
      class: ui-silk-user
      title: _("List of %s %2s", ngettext('User', 'Users', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/users.html"
      forcedValues:
        <<: *forcedCompany
      fields:
        options:
          title: _("Options")
          screens:
            usersEdit_screen: $[${auth.acls.Users.update} && ${auth.companyVPBX}]
            callForwardSettingsList_screen: $[${auth.acls.CallForwardSettings.read} && ${auth.companyVPBX}]
            huntGroupMembersList_screen: $[${auth.acls.HuntGroupMembers.read} && ${auth.companyVPBX}]
          dialogs:
            usersDel_dialog: $[${auth.acls.Users.delete} && ${auth.companyVPBX}]
          default: usersEdit_screen
        order: &Users_orderLink
          company: true
          name: true
          lastname: true
          email: true
          language: true
          active: true
          pass: true
          gsQRCode: true
          doNotDisturb: true
          timezone: true
          extension: true
          terminal: true
          outgoingDdi: true
          statusIcon: true
          callACL: true
          isBoss: true
          bossAssistant: true
          bossAssistantWhiteList: true
          PickUpRelUsers: true
          multiContact: true
          rejectCallMethod: true
        blacklist:
          email: true
          active: true
          doNotDisturb: true
          pass: true
          gsQRCode: true
          timezone: true
          callACL: true
          bossAssistant: true
          bossAssistantWhiteList: true
          HuntGroupMembers: true
          PickUpRelUsers: true
          timeout: true
          isBoss: true
          maxCalls: true
          tokenKey: true
          transformationRuleSet: true
          language: true
          location: true
          externalIpCalls: true
          outgoingDdiRule: true
          rejectCallMethod: true
          multiContact: true
      options:
        title: _("Options")
        screens:
          usersNew_screen: $[${auth.acls.Users.create} && ${auth.companyVPBX}]
        dialogs:
          usersDel_dialog: $[${auth.acls.Users.delete} && ${auth.companyVPBX}]
          importUsers_dialog: false
    usersNew_screen: &usersNew_screenLink
      <<: *Users
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('User', 'Users', 1))
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
        pass: 1234
      fields:
        order:
          <<: *Users_orderLink
        blacklist:
          HuntGroupMembers: true
          tokenKey: true
          active: true
          doNotDisturb: true
          pass: true
          gsQRCode: true
          timezone: true
          callACL: true1
          bossAssistant: true
          bossAssistantWhiteList: true
          PickUpRelUsers: true
          timeout: true
          isBoss: true
          maxCalls: true
          tokenKey: true
          language: true
          location: true
          transformationRuleSet: true
          externalIpCalls: true
          statusIcon: true
          rejectCallMethod: true
          multiContact: true
      fixedPositions: &UsersFixedPositions_link
        group0:
          label: _("Personal data")
          colsPerRow: 24
          fields:
            name: 7
            lastname: 7
            email: 10
        group1:
          label: _("Basic Configuration")
          colsPerRow: 6
          fields:
            terminal: 2
            extension: 2
            outgoingDdi: 3
            outgoingDdiRule: 3
    usersEdit_screen: &usersEdit_screenLink
      <<: *Users
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('User', 'Users', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          tokenKey: true
          statusIcon: true
        order:
          <<: *Users_orderLink
      fixedPositions: &UsersFixedPositions_link
        group0:
          label: _("Personal data")
          colsPerRow: 12
          fields:
            name: 4
            lastname: 4
            email: 4
        group1:
          label: _("Geographic Configuration")
          colsPerRow: 12
          fields:
            language: 6
            timezone: 6
            transformationRuleSet: 6
            location: 6
        group2:
          label: _("Login Info")
          colsPerRow: 3
          fields:
            active: 1
            pass: 1
            gsQRCode: 1
        group3:
          label: _("Boss-Assistant")
          colsPerRow: 12
          fields:
            isBoss: 4
            bossAssistant: 8
            bossAssistantWhiteList: 12
        group4:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            terminal: 6
            extension: 6
            outgoingDdi: 6
            outgoingDdiRule: 6
            callACL: 6
            doNotDisturb: 6
            maxCalls: 6
            externalIpCalls: 6
            multiContact: 6
            _empty: 6
            rejectCallMethod: 10
        group6:
          label: _("Group belonging")
          colsPerRow: 3
          fields:
            PickUpRelUsers: 3
            HuntGroupMembers: 3

    #HuntGroupMembers
    <<: *huntGroupMembers_screensLink
    huntGroupMembersList_screen:
      <<: *huntGroupMembersList_screenLink
      title: _("List of %s %2s", ngettext('Hunt Group', 'Hunt Groups', 0), "[format| (%parent%)]")
      filterField: User
      parentOptionCustomizer:
        - recordCount
      fields:
        options:
          title: _("Options")
          dialogs:
            huntGroupMembersDel_dialog: ${auth.acls.HuntGroupMembers.delete}
          default: huntGroupMembersEdit_screen
      options:
        title: _("Options")
        dialogs:
          huntGroupMembersDel_dialog: ${auth.acls.HuntGroupMembers.delete}

    #CallForwardSettings
    <<: *callForwardSettings_screensLink
    callForwardSettingsList_screen:
      <<: *callForwardSettingsList_screenLink
      filterField: User
      parentOptionCustomizer:
        - recordCount
      fields:
        <<: *callForwardSettingsListFields_Link
        blacklist:
          <<: *callForwardSettingsListBlacklist_Link
          ddi: true
    callForwardSettingsNew_screen:
      <<: *callForwardSettingsNew_screenLink
      filterField: User
      fields:
        <<: *callForwardSettingsNewFields_Link
        blacklist:
          <<: *callForwardSettingsNewBlacklist_Link
          ddi: true
    callForwardSettingsEdit_screen:
      <<: *callForwardSettingsEdit_screenLink
      filterField: User
      fields:
        <<: *callForwardSettingsEditFields_Link
        blacklist:
          <<: *callForwardSettingsEditBlacklist_Link
          ddi: true

  dialogs: &users_dialogsLink
    usersDel_dialog: &usersDel_dialogLink
      <<: *Users
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('User', 'Users', 1))
      description: _("Do you want to delete this %s?", ngettext('User', 'Users', 1))
      message: _("%s successfully deleted.", ngettext('User', 'Users', 1))
      multiItem: 1
      labelOnList: 1

    importUsers_dialog:
      <<: *Users
      module: default
      title: _("Import %s", ngettext('User', 'Users', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-file
      action: import
      class:  ui-silk-page-gear
      freeUploadCommand: importUsersFreeUpload_command
      delimiter: ";"
      enclosure: '"'
      escape: "\\"
      forcedValues:
        company: *forcedCompany

    #HuntGroupMembers
    <<: *huntGroupMembers_dialogsLink
    huntGroupMembersDel_dialog:
      <<: *huntGroupMembersDel_dialogLink
      title: _("Delete %s", ngettext('Hunt Group', 'Hunt Groups', 1))
      description: _("Do you want to delete this %s?", ngettext('Hunt Group', 'Hunt Groups', 1))
      message: _("%s successfully deleted.", ngettext('Hunt Group', 'Hunt Groups', 1))

    #callForwardSettings
    <<: *callForwardSettings_dialogsLink

  commands:
    importUsersFreeUpload_command:
      <<: *Users
      controller: File
      action: free-upload
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
