#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include HuntGroupsRelUsersList.yaml
#include CallForwardSettingsList.yaml
#include DDIsList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: usersList_screen
  screens: &users_screensLink
    usersList_screen: &usersList_screenLink
      controller: list
      pagination:
        items: 25
      order:
        field:
          - User.name asc
      <<: *Users
      class: ui-silk-user
      title: _("List of %s %2s", ngettext('User', 'Users', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        options:
          title: _("Options")
          screens:
            usersEdit_screen: true
            callForwardSettingsList_screen: true
            huntGroupsRelUsersList_screen: true
          dialogs:
            usersDel_dialog: true
          default: usersEdit_screen
        order: &Users_orderLink
          companyId: true
          name: true
          lastname: true
          email: true
          languageId: true
          active: true
          pass: true
          gsQRCode: true
          doNotDisturb: true
          timezoneId: true
          extensionId: true
          terminalId: true
          outgoingDDIId: true
          callACLId: true
          voicemailEnabled: true
          isBoss: true
          bossAssistantId: true
          exceptionBoosAssistantRegExp: true
          PickUpRelUsers: true
        blacklist:
          email: true
          username: true
          active: true
          doNotDisturb: true
          pass: true
          gsQRCode: true
          timezoneId: true
          callACLId: true
          bossAssistantId: true
          exceptionBoosAssistantRegExp: true
          HuntGroupsRelUsers: true
          PickUpRelUsers: true
          timeout: true
          isBoss: true
          maxCalls: true
          tokenKey: true
          voicemailEnabled: true
          voicemailLocutionId: true
          voicemailAttachSound: true
          voicemailSendMail: true
          transformationRuleSetId: true
          languageId: true
          externalIpCalls: true
          outgoingDdiRuleId: true
      options:
        title: _("Options")
        screens:
          usersNew_screen: true
        dialogs:
          usersDel_dialog: true
          importUsers_dialog: false
    usersNew_screen: &usersNew_screenLink
      <<: *Users
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('User', 'Users', 1))
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          <<: *Users_orderLink
        blacklist:
          HuntGroupsRelUsers: true
          tokenKey: true
          username: true
          active: true
          doNotDisturb: true
          pass: true
          gsQRCode: true
          timezoneId: true
          callACLId: true1
          bossAssistantId: true
          exceptionBoosAssistantRegExp: true
          PickUpRelUsers: true
          timeout: true
          isBoss: true
          maxCalls: true
          tokenKey: true
          voicemailEnabled: true
          voicemailLocutionId: true
          voicemailAttachSound: true
          voicemailSendMail: true
          languageId: true
          transformationRuleSetId: true
          externalIpCalls: true
      fixedPositions: &UsersFixedPositions_link
        group0:
          label: _("Personal data")
          colsPerRow: 24
          fields:
            name: 7
            lastname: 7
            email: 10
        group1:
          label: _("Basic Configuration")
          colsPerRow: 6
          fields:
            terminalId: 2
            extensionId: 2
            outgoingDDIId: 3
            outgoingDdiRuleId: 3
    usersEdit_screen: &usersEdit_screenLink
      <<: *Users
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('User', 'Users', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          tokenKey: true
          username: true
        order:
          <<: *Users_orderLink
      fixedPositions: &UsersFixedPositions_link
        group0:
          label: _("Personal data")
          colsPerRow: 12
          fields:
            name: 4
            lastname: 4
            email: 4
        group1:
          label: _("Geographic data")
          colsPerRow: 12
          fields:
            languageId: 6
            timezoneId: 6
            transformationRuleSetId: 8
        group2:
          label: _("Login Info")
          colsPerRow: 3
          fields:
            active: 1
            pass: 1
            gsQRCode: 1
        group3:
          label: _("Boss-Assistant")
          colsPerRow: 12
          fields:
            isBoss: 4
            bossAssistantId: 8
            exceptionBoosAssistantRegExp: 12
        group4:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            terminalId: 6
            extensionId: 6
            outgoingDDIId: 6
            outgoingDdiRuleId: 6
            callACLId: 6
            doNotDisturb: 6
            maxCalls: 6
            externalIpCalls: 6
        group5:
          label: _("Voicemail")
          colsPerRow: 2
          fields:
            voicemailEnabled: 1
            voicemailLocutionId: 1
            voicemailSendMail: 1
            voicemailAttachSound: 1
        group6:
          label: _("Group belonging")
          colsPerRow: 3
          fields:
            PickUpRelUsers: 3
            HuntGroupsRelUsers: 3

    #HuntGroupsRelUsers
    <<: *huntGroupsRelUsers_screensLink
    huntGroupsRelUsersList_screen:
      <<: *huntGroupsRelUsersList_screenLink
      title: _("List of %s %2s", ngettext('Hunt Group', 'Hunt Groups', 0), "[format| (%parent%)]")
      filterField: User
      parentOptionCustomizer:
        - recordCount
    huntGroupsRelUsersNew_screen:
      <<: *huntGroupsRelUsersNew_screenLink
      title: _("Join to %s %2s", ngettext("Hunt Group", "Hunt Groups", 1), "[format| (%parent%)]")
      filterField: User
    huntGroupsRelUsersEdit_screen:
      <<: *huntGroupsRelUsersEdit_screenLink
      filterField: User
      title: _("Edit Join of %s", ngettext('Hunt Group', 'Hunt Groups', 1))

    #CallForwardSettings
    <<: *callForwardSettings_screensLink
    callForwardSettingsList_screen:
      <<: *callForwardSettingsList_screenLink
      filterField: User
      parentOptionCustomizer:
        - recordCount
    callForwardSettingsNew_screen:
      <<: *callForwardSettingsNew_screenLink
      filterField: User
    callForwardSettingsEdit_screen:
      <<: *callForwardSettingsEdit_screenLink
      filterField: User
      fields:
        blacklist:
          targetTypeValue: true

  dialogs: &users_dialogsLink
    usersDel_dialog: &usersDel_dialogLink
      <<: *Users
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('User', 'Users', 1))
      description: _("Do you want to delete this %s?", ngettext('User', 'Users', 1))
      message: _("%s successfully deleted.", ngettext('User', 'Users', 1))
      multiItem: 1
      labelOnList: 1

    importUsers_dialog:
      <<: *Users
      module: default
      title: _("Import %s", ngettext('User', 'Users', 0))
      label: false
      labelOnEdit: true
      labelOnList: true
      labelOnOption: true
      labelOnEntityPostSave: true
      controller: import-file
      action: import
      class:  ui-silk-page-gear
      freeUploadCommand: importUsersFreeUpload_command
      delimiter: ";"
      enclosure: '"'
      escape: "\\"
      forcedValues:
        company: *forcedCompany



    #HuntGroupsRelUsers
    <<: *huntGroupsRelUsers_dialogsLink
    huntGroupsRelUsersDel_dialog:
      <<: *huntGroupsRelUsersDel_dialogLink
      title: _("Delete %s", ngettext('Hunt Group', 'Hunt Groups', 1))
      description: _("Do you want to delete this %s?", ngettext('Hunt Group', 'Hunt Groups', 1))
      message: _("%s successfully deleted.", ngettext('Hunt Group', 'Hunt Groups', 1))

    #callForwardSettings
    <<: *callForwardSettings_dialogsLink

  commands:
    importUsersFreeUpload_command:
      <<: *Users
      controller: File
      action: free-upload
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
