production: 
  class: \IvozProvider\Model\AstPsEndpoints
  fields: 
    sorcery_id: 
      title: _('Sorceryid')
      type: text
      required: true
      maxLength: 40
      default: true
    terminalId: 
      title: _('Terminalid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Terminals
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    friendId: 
      title: _('Friendid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Friends
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    aors: 
      title: _('Aor')
      type: text
      maxLength: 200
    callerid: 
      title: _('Callerid')
      type: text
      maxLength: 100
    context: 
      title: _('Context')
      type: text
      defaultValue: outgoing
      maxLength: 40
    disallow: 
      title: _('Disallow')
      type: text
      defaultValue: all
      maxLength: 200
    allow: 
      title: _('Allow')
      type: text
      defaultValue: all
      maxLength: 200
    direct_media: 
      title: _('Directmedia')
      type: select
      defaultValue: yes
      source: 
        data: inline
        values: 
          'yes': _('yes')
          'no': _('no')
    direct_media_method: 
      title: _('Directmediamethod')
      type: select
      defaultValue: update
      source: 
        data: inline
        values: 
          'invite': _('invite')
          'reinvite': _('reinvite')
          'update': _('update')
    mailboxes: 
      title: _('Mailbox')
      type: text
      maxLength: 100
    pickup_group: 
      title: _('Pickupgroup')
      type: text
      maxLength: 40
    send_diversion: 
      title: _('Senddiversion')
      type: select
      defaultValue: yes
      source: 
        data: inline
        values: 
          'yes': _('yes')
          'no': _('no')
    send_pai: 
      title: _('Sendpai')
      type: select
      defaultValue: yes
      source: 
        data: inline
        values: 
          'yes': _('yes')
          'no': _('no')
    subscribecontext: 
      title: _('Subscribecontext')
      type: text
      defaultValue: default
      maxLength: 40
    100rel: 
      title: _('100rel')
      type: select
      defaultValue: no
      source: 
        data: inline
        values: 
          'no': _('no')
          'required': _('required')
          'yes': _('yes')
    outbound_proxy: 
      title: _('Outboundproxy')
      type: text
      maxLength: 256
    trust_id_inbound: 
      title: _('Trustidinbound')
      type: select
      source: 
        data: inline
        values: 
          'yes': _('yes')
          'no': _('no')
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
