production: 
  class: \IvozProvider\Model\Companies
  fields: 
    brandId: 
      title: _('Brandid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Brands
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
      default: true
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      maxLength: 80
    domain_users: 
      title: _('Domainuser')
      type: text
      required: true
      maxLength: 255
    nif: 
      title: _('Nif')
      type: text
      required: true
      maxLength: 25
    defaultTimezoneId: 
      title: _('Defaulttimezoneid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Timezones
          fieldName: 
            fields: 
              - tz
            template: '%tz%'
          order: tz
    applicationServerId: 
      title: _('Applicationserverid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\ApplicationServers
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
        'null': _("Unasigned")
    externalMaxCalls: 
      title: _('Externalmaxcall')
      type: number
      defaultValue: 0
      source: 
        control: Spinner
    postalAddress: 
      title: _('Postaladdress')
      type: text
      required: true
      maxLength: 255
    postalCode: 
      title: ngettext('Postalcode', 'Postalcodes', 1)
      type: text
      required: true
      maxLength: 10
    town: 
      title: _('Town')
      type: text
      required: true
      maxLength: 255
    province: 
      title: ngettext('Province', 'Provinces', 1)
      type: text
      required: true
      maxLength: 255
    country: 
      title: ngettext('Country', 'Countries', 1)
      type: text
      required: true
      maxLength: 255
    outbound_prefix: 
      title: _('Outboundprefix')
      type: text
      maxLength: 255
    countryId: 
      title: _('Countryid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Countries
          fieldName: 
            fields: 
              - code
            template: '%code%'
          order: code
        'null': _("Unasigned")
    languageId: 
      title: _('Languageid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Languages
          fieldName: 
            fields: 
              - iden
            template: '%iden%'
          order: iden
        'null': _("Unasigned")
    mediaRelaySetsId: 
      title: _('Mediarelaysetsid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\MediaRelaySets
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
        'null': _("Unasigned")
    ipFilter: 
      title: _('Ipfilter')
      type: select
      defaultValue: 1
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    onDemandRecord: 
      title: _('Ondemandrecord')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    onDemandRecordCode: 
      title: _('Ondemandrecordcode')
      type: text
      maxLength: 3
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
