production: 
  class: \IvozProvider\Model\Domains
  fields: 
    domain: 
      title: _('Domain')
      type: text
      required: true
      maxLength: 190
      default: true
    scope: 
      title: _('Scope')
      type: select
      defaultValue: global
      source: 
        data: inline
        values: 
          'global': _('global')
          'company': _('company')
          'brand': _('brand')
    pointsTo: 
      title: _('Pointsto')
      type: select
      defaultValue: proxyusers
      source: 
        data: inline
        values: 
          'proxyusers': _('proxyusers')
          'proxytrunks': _('proxytrunks')
    brandId: 
      title: _('Brandid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Brands
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    companyId: 
      title: _('Companyid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Companies
          fieldName: 
            fields: 
              - type
            template: '%type%'
          order: type
        'null': _("Unassigned")
    description: 
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      maxLength: 500
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
