production: 
  class: \IvozProvider\Model\Friends
  fields: 
    companyId: 
      title: _('Companyid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Companies
          fieldName: 
            fields: 
              - type
            template: '%type%'
          order: type
      default: true
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      maxLength: 65
    domain: 
      title: _('Domain')
      type: text
      maxLength: 190
    description: 
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      defaultValue: 
      maxLength: 500
    transport: 
      title: _('Transport')
      type: select
      required: true
      source: 
        data: inline
        values: 
          'udp': _('udp')
          'tcp': _('tcp')
          'tls': _('tls')
    ip: 
      title: _('Ip')
      type: text
      maxLength: 50
    port: 
      title: _('Port')
      type: number
      source: 
        control: Spinner
    auth_needed: 
      title: _('Authneeded')
      type: select
      defaultValue: yes
      source: 
        data: inline
        values: 
          'yes': _('yes')
          'no': _('no')
    password: 
      title: ngettext('Password', 'Passwords', 1)
      type: password
      adapter: Blowfish
    callACLId: 
      title: _('Callaclid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\CallACL
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
        'null': _("Unassigned")
    countryId: 
      title: _('Countryid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Countries
          fieldName: 
            fields: 
              - code
            template: '%code%'
          order: code
        'null': _("Unassigned")
    areaCode: 
      title: _('Areacode')
      type: text
      maxLength: 10
    outgoingDDIId: 
      title: _('Outgoingddiid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\DDIs
          fieldName: 
            fields: 
              - DDI
            template: '%DDI%'
          order: DDI
        'null': _("Unassigned")
    priority: 
      title: _('Priority')
      type: number
      defaultValue: 1
      source: 
        control: Spinner
    disallow: 
      title: _('Disallow')
      type: text
      defaultValue: all
      maxLength: 200
    allow: 
      title: _('Allow')
      type: text
      defaultValue: alaw
      maxLength: 200
    direct_media_method: 
      title: _('Directmediamethod')
      type: select
      defaultValue: update
      source: 
        data: inline
        values: 
          'invite': _('invite')
          'update': _('update')
    callerid_update_header: 
      title: _('Calleridupdateheader')
      type: select
      defaultValue: pai
      source: 
        data: inline
        values: 
          'pai': _('pai')
          'rpid': _('rpid')
    update_callerid: 
      title: _('Updatecallerid')
      type: select
      defaultValue: yes
      source: 
        data: inline
        values: 
          'yes': _('yes')
          'no': _('no')
    from_domain: 
      title: _('Fromdomain')
      type: text
      maxLength: 190
    directConnectivity: 
      title: _('Directconnectivity')
      type: select
      defaultValue: yes
      source: 
        data: inline
        values: 
          'yes': _('yes')
          'no': _('no')
    languageId: 
      title: _('Languageid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Languages
          fieldName: 
            fields: 
              - iden
            template: '%iden%'
          order: iden
        'null': _("Unassigned")
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
