production: 
  class: \IvozProvider\Model\FriendsPatterns
  fields: 
    friendId: 
      title: _('Friendid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Friends
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
      default: true
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      maxLength: 50
    regExp: 
      title: _('Regexp')
      type: text
      required: true
      maxLength: 255
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
