production: 
  class: \IvozProvider\Model\PricingPlansRelCompanies
  fields: 
    pricingPlanId: 
      title: _('Pricingplanid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\PricingPlans
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name_${lang}
      default: true
    companyId: 
      title: _('Companyid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Companies
          fieldName: 
            fields: 
              - type
            template: '%type%'
          order: type
    validFrom: 
      title: _('Validfrom')
      type: picker
      required: true
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    validTo: 
      title: _('Validto')
      type: picker
      required: true
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    metric: 
      title: _('Metric')
      type: number
      defaultValue: 10
      source: 
        control: Spinner
    brandId: 
      title: _('Brandid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Brands
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
