production: 
  class: \IvozProvider\Model\Users
  fields: 
    companyId: 
      title: _('Companyid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Companies
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
      default: true
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      maxLength: 100
    lastname: 
      title: _('Lastname')
      type: text
      required: true
      maxLength: 100
    email: 
      title: ngettext('Email', 'Emails', 1)
      type: text
      required: true
      maxLength: 100
    pass: 
      title: _('Pass')
      type: password
      required: true
      adapter: Blowfish
    timezoneId: 
      title: _('Timezoneid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Timezones
          fieldName: 
            fields: 
              - tz
            template: '%tz%'
          order: tz
        'null': _("Unasigned")
    terminalId: 
      title: _('Terminalid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Terminals
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
        'null': _("Unasigned")
    extensionId: 
      title: _('Extensionid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Extensions
          fieldName: 
            fields: 
              - number
            template: '%number%'
          order: number
        'null': _("Unasigned")
    outgoingDDIId: 
      title: _('Outgoingddiid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\DDIs
          fieldName: 
            fields: 
              - DDI
            template: '%DDI%'
          order: DDI
        'null': _("Unasigned")
    callACLId: 
      title: _('Callaclid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\CallACL
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
        'null': _("Unasigned")
    doNotDisturb: 
      title: _('Donotdisturb')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    isBoss: 
      title: _('Isboss')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    bossAssistantId: 
      title: _('Bossassistantid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Users
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
        'null': _("Unasigned")
    exceptionBoosAssistantRegExp: 
      title: _('Exceptionboosassistantregexp')
      type: text
      maxLength: 255
    username: 
      title: _('Username')
      type: text
      required: true
      maxLength: 50
    active: 
      title: _('Active')
      type: select
      defaultValue: 1
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    maxCalls: 
      title: _('Maxcall')
      type: number
      defaultValue: 2
      source: 
        control: Spinner
    callWaiting: 
      title: _('Callwaiting')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    voicemailEnabled: 
      title: _('Voicemailenabled')
      type: select
      defaultValue: 1
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    voicemailSendMail: 
      title: _('Voicemailsendmail')
      type: select
      defaultValue: 1
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    voicemailAttachSound: 
      title: _('Voicemailattachsound')
      type: select
      defaultValue: 1
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    tokenKey: 
      title: _('Tokenkey')
      type: text
      maxLength: 125
    countryId: 
      title: _('Countryid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Countries
          fieldName: 
            fields: 
              - code
            template: '%code%'
          order: code
        'null': _("Unasigned")
    languageId: 
      title: _('Languageid')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \IvozProvider\Mapper\Sql\Languages
          fieldName: 
            fields: 
              - iden
            template: '%iden%'
          order: iden
        'null': _("Unasigned")
    areaCode: 
      title: _('Areacode')
      type: text
      maxLength: 10
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
