production: 
  class: \IvozProvider\Model\XMLRPCLogs
  fields: 
    proxy: 
      title: _('Proxy')
      type: text
      required: true
      maxLength: 10
      default: true
    module: 
      title: _('Module')
      type: text
      required: true
      maxLength: 10
    method: 
      title: _('Method')
      type: text
      required: true
      maxLength: 10
    mapperName: 
      title: _('Mapper name')
      type: text
      required: true
      maxLength: 20
    startDate: 
      title: _('Start date')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    execDate: 
      title: _('Exec date')
      type: picker
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    finishDate: 
      title: _('Finish date')
      type: picker
      source: 
        control: datetime
        settings: 
          disabled: 'false'
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
