imports:
  - { resource: "@CoreBundle/Resources/config/lifecycle/core/xml_rpc.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/kam.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/cgr.yml" }

services:
  _defaults:
    autowire: true
    public: false

  Ivoz\Core\Infrastructure\Domain\Service\Lifecycle\DoctrineEventSubscriber:
    arguments:
      $serviceContainer: '@service_container'
      $eventPublisher: '@Ivoz\Core\Domain\Service\DomainEventPublisher'
    tags:
      - { name: doctrine.event_subscriber }

  Ivoz\Core\Domain\Service\PersistErrorHandlerServiceCollection:
    public: true

  Ivoz\Core\Domain\Service\CommonLifecycleServiceCollection:
    public: true
  lifecycle.post_persist.service_collection: '@Ivoz\Core\Domain\Service\CommonLifecycleServiceCollection'
  lifecycle.pre_remove.service_collection: '@Ivoz\Core\Domain\Service\CommonLifecycleServiceCollection'
  lifecycle.post_remove.service_collection: '@Ivoz\Core\Domain\Service\CommonLifecycleServiceCollection'

  Ivoz\Core\Infrastructure\Persistence\Filesystem\Commit:
    tags:
      - { name: lifecycle.post_persist.common, priority: 10 }

  Ivoz\Core\Infrastructure\Persistence\Filesystem\ScheduleForRemove:
    arguments:
      $serviceContainer: '@service_container'
    tags:
      - { name: lifecycle.pre_remove.common, priority: 10 }

  Ivoz\Core\Infrastructure\Persistence\Filesystem\Remove:
    tags:
      - { name: lifecycle.post_remove.common, priority: 10 }
