doctrine:
  orm:
    resolve_target_entities:
      Ivoz\Ast\Domain\Model\Hint\HintInterface:
        Ivoz\Ast\Domain\Model\Hint\Hint
      Ivoz\Ast\Domain\Model\PsEndpoint\PsEndpointInterface:
        Ivoz\Ast\Domain\Model\PsEndpoint\PsEndpoint
      Ivoz\Ast\Domain\Model\Queue\QueueInterface:
        Ivoz\Ast\Domain\Model\Queue\Queue
      Ivoz\Provider\Domain\Model\Administrator\AdministratorInterface:
        Ivoz\Provider\Domain\Model\Administrator\Administrator
      Ivoz\Provider\Domain\Model\ApplicationServer\ApplicationServerInterface:
        Ivoz\Provider\Domain\Model\ApplicationServer\ApplicationServer
      Ivoz\Provider\Domain\Model\BalanceNotification\BalanceNotificationInterface:
        Ivoz\Provider\Domain\Model\BalanceNotification\BalanceNotification
      Ivoz\Provider\Domain\Model\Brand\BrandInterface:
        Ivoz\Provider\Domain\Model\Brand\Brand
      Ivoz\Provider\Domain\Model\BrandService\BrandServiceInterface:
        Ivoz\Provider\Domain\Model\BrandService\BrandService
      Ivoz\Provider\Domain\Model\BrandUrl\BrandUrlInterface:
        Ivoz\Provider\Domain\Model\BrandUrl\BrandUrl
      Ivoz\Provider\Domain\Model\Calendar\CalendarInterface:
        Ivoz\Provider\Domain\Model\Calendar\Calendar
      Ivoz\Provider\Domain\Model\CallAcl\CallAclInterface:
        Ivoz\Provider\Domain\Model\CallAcl\CallAcl
      Ivoz\Provider\Domain\Model\CallAclRelMatchList\CallAclRelMatchListInterface:
        Ivoz\Provider\Domain\Model\CallAclRelMatchList\CallAclRelMatchList
      Ivoz\Provider\Domain\Model\CallForwardSetting\CallForwardSettingInterface:
        Ivoz\Provider\Domain\Model\CallForwardSetting\CallForwardSetting
      Ivoz\Provider\Domain\Model\Commandlog\CommandlogInterface:
        Ivoz\Provider\Domain\Model\Commandlog\Commandlog
      Ivoz\Provider\Domain\Model\Changelog\ChangelogInterface:
        Ivoz\Provider\Domain\Model\Changelog\Changelog
      Ivoz\Provider\Domain\Model\Company\CompanyInterface:
        Ivoz\Provider\Domain\Model\Company\Company
      Ivoz\Provider\Domain\Model\CompanyService\CompanyServiceInterface:
        Ivoz\Provider\Domain\Model\CompanyService\CompanyService
      Ivoz\Provider\Domain\Model\ConditionalRoute\ConditionalRouteInterface:
        Ivoz\Provider\Domain\Model\ConditionalRoute\ConditionalRoute
      Ivoz\Provider\Domain\Model\ConditionalRoutesCondition\ConditionalRoutesConditionInterface:
        Ivoz\Provider\Domain\Model\ConditionalRoutesCondition\ConditionalRoutesCondition
      Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelMatchlist\ConditionalRoutesConditionsRelMatchlistInterface:
        Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelMatchlist\ConditionalRoutesConditionsRelMatchlist
      Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelSchedule\ConditionalRoutesConditionsRelScheduleInterface:
        Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelSchedule\ConditionalRoutesConditionsRelSchedule
      Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelCalendar\ConditionalRoutesConditionsRelCalendarInterface:
        Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelCalendar\ConditionalRoutesConditionsRelCalendar
      Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelRouteLock\ConditionalRoutesConditionsRelRouteLockInterface:
        Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelRouteLock\ConditionalRoutesConditionsRelRouteLock
      Ivoz\Provider\Domain\Model\ConferenceRoom\ConferenceRoomInterface:
        Ivoz\Provider\Domain\Model\ConferenceRoom\ConferenceRoom
      Ivoz\Provider\Domain\Model\Country\CountryInterface:
        Ivoz\Provider\Domain\Model\Country\Country
      Ivoz\Provider\Domain\Model\Ddi\DdiInterface:
        Ivoz\Provider\Domain\Model\Ddi\Ddi
      Ivoz\Provider\Domain\Model\Domain\DomainInterface:
        Ivoz\Provider\Domain\Model\Domain\Domain
      Ivoz\Provider\Domain\Model\EtagVersion\EtagVersionInterface:
        Ivoz\Provider\Domain\Model\EtagVersion\EtagVersion
      Ivoz\Provider\Domain\Model\Extension\ExtensionInterface:
        Ivoz\Provider\Domain\Model\Extension\Extension
      Ivoz\Provider\Domain\Model\ExternalCallFilter\ExternalCallFilterInterface:
        Ivoz\Provider\Domain\Model\ExternalCallFilter\ExternalCallFilter
      Ivoz\Provider\Domain\Model\ExternalCallFilterBlackList\ExternalCallFilterBlackListInterface:
        Ivoz\Provider\Domain\Model\ExternalCallFilterBlackList\ExternalCallFilterBlackList
      Ivoz\Provider\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendarInterface:
        Ivoz\Provider\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendar
      Ivoz\Provider\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelScheduleInterface:
        Ivoz\Provider\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelSchedule
      Ivoz\Provider\Domain\Model\ExternalCallFilterWhiteList\ExternalCallFilterWhiteListInterface:
        Ivoz\Provider\Domain\Model\ExternalCallFilterWhiteList\ExternalCallFilterWhiteList
      Ivoz\Provider\Domain\Model\FaxesInOut\FaxesInOutInterface:
        Ivoz\Provider\Domain\Model\FaxesInOut\FaxesInOut
      Ivoz\Provider\Domain\Model\Fax\FaxInterface:
        Ivoz\Provider\Domain\Model\Fax\Fax
      Ivoz\Provider\Domain\Model\Feature\FeatureInterface:
        Ivoz\Provider\Domain\Model\Feature\Feature
      Ivoz\Provider\Domain\Model\FeaturesRelBrand\FeaturesRelBrandInterface:
        Ivoz\Provider\Domain\Model\FeaturesRelBrand\FeaturesRelBrand
      Ivoz\Provider\Domain\Model\FeaturesRelCompany\FeaturesRelCompanyInterface:
        Ivoz\Provider\Domain\Model\FeaturesRelCompany\FeaturesRelCompany
      Ivoz\Provider\Domain\Model\FixedCost\FixedCostInterface:
        Ivoz\Provider\Domain\Model\FixedCost\FixedCost
      Ivoz\Provider\Domain\Model\FixedCostsRelInvoice\FixedCostsRelInvoiceInterface:
        Ivoz\Provider\Domain\Model\FixedCostsRelInvoice\FixedCostsRelInvoice
      Ivoz\Provider\Domain\Model\Friend\FriendInterface:
        Ivoz\Provider\Domain\Model\Friend\Friend
      Ivoz\Provider\Domain\Model\FriendsPattern\FriendsPatternInterface:
        Ivoz\Provider\Domain\Model\FriendsPattern\FriendsPattern
      Ivoz\Provider\Domain\Model\HolidayDate\HolidayDateInterface:
        Ivoz\Provider\Domain\Model\HolidayDate\HolidayDate
      Ivoz\Provider\Domain\Model\HuntGroup\HuntGroupInterface:
        Ivoz\Provider\Domain\Model\HuntGroup\HuntGroup
      Ivoz\Provider\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUserInterface:
        Ivoz\Provider\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUser
      Ivoz\Provider\Domain\Model\Invoice\InvoiceInterface:
        Ivoz\Provider\Domain\Model\Invoice\Invoice
      Ivoz\Provider\Domain\Model\InvoiceTemplate\InvoiceTemplateInterface:
        Ivoz\Provider\Domain\Model\InvoiceTemplate\InvoiceTemplate
      Ivoz\Provider\Domain\Model\IvrEntry\IvrEntryInterface:
        Ivoz\Provider\Domain\Model\IvrEntry\IvrEntry
      Ivoz\Provider\Domain\Model\Ivr\IvrInterface:
        Ivoz\Provider\Domain\Model\Ivr\Ivr
      Ivoz\Provider\Domain\Model\IvrExcludedExtension\IvrExcludedExtensionInterface:
        Ivoz\Provider\Domain\Model\IvrExcludedExtension\IvrExcludedExtension
      Ivoz\Provider\Domain\Model\Language\LanguageInterface:
        Ivoz\Provider\Domain\Model\Language\Language
      Ivoz\Provider\Domain\Model\LcrGateway\LcrGatewayInterface:
        Ivoz\Provider\Domain\Model\LcrGateway\LcrGateway
      Ivoz\Provider\Domain\Model\LcrRule\LcrRuleInterface:
        Ivoz\Provider\Domain\Model\LcrRule\LcrRule
      Ivoz\Provider\Domain\Model\LcrRuleTarget\LcrRuleTargetInterface:
        Ivoz\Provider\Domain\Model\LcrRuleTarget\LcrRuleTarget
      Ivoz\Provider\Domain\Model\Locution\LocutionInterface:
        Ivoz\Provider\Domain\Model\Locution\Locution
      Ivoz\Provider\Domain\Model\MatchList\MatchListInterface:
        Ivoz\Provider\Domain\Model\MatchList\MatchList
      Ivoz\Provider\Domain\Model\MatchListPattern\MatchListPatternInterface:
        Ivoz\Provider\Domain\Model\MatchListPattern\MatchListPattern
      Ivoz\Provider\Domain\Model\MediaRelaySet\MediaRelaySetInterface:
        Ivoz\Provider\Domain\Model\MediaRelaySet\MediaRelaySet
      Ivoz\Provider\Domain\Model\Musiconhold\MusiconholdInterface:
        Ivoz\Provider\Domain\Model\Musiconhold\Musiconhold
      Ivoz\Provider\Domain\Model\MusicOnHold\MusicOnHoldInterface:
        Ivoz\Provider\Domain\Model\MusicOnHold\MusicOnHold
      Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplateInterface:
        Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplate
      Ivoz\Provider\Domain\Model\NotificationTemplateContent\NotificationTemplateContentInterface:
        Ivoz\Provider\Domain\Model\NotificationTemplateContent\NotificationTemplateContent
      Ivoz\Provider\Domain\Model\OutgoingDdiRule\OutgoingDdiRuleInterface:
        Ivoz\Provider\Domain\Model\OutgoingDdiRule\OutgoingDdiRule
      Ivoz\Provider\Domain\Model\OutgoingDdiRulesPattern\OutgoingDdiRulesPatternInterface:
        Ivoz\Provider\Domain\Model\OutgoingDdiRulesPattern\OutgoingDdiRulesPattern
      Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRoutingInterface:
        Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRouting
      Ivoz\Provider\Domain\Model\PeeringContract\PeeringContractInterface:
        Ivoz\Provider\Domain\Model\PeeringContract\PeeringContract
      Ivoz\Provider\Domain\Model\PeerServer\PeerServerInterface:
        Ivoz\Provider\Domain\Model\PeerServer\PeerServer
      Ivoz\Provider\Domain\Model\PickUpGroup\PickUpGroupInterface:
        Ivoz\Provider\Domain\Model\PickUpGroup\PickUpGroup
      Ivoz\Provider\Domain\Model\PickUpRelUser\PickUpRelUserInterface:
        Ivoz\Provider\Domain\Model\PickUpRelUser\PickUpRelUser
      Ivoz\Provider\Domain\Model\ProxyTrunk\ProxyTrunkInterface:
        Ivoz\Provider\Domain\Model\ProxyTrunk\ProxyTrunk
      Ivoz\Provider\Domain\Model\ProxyUser\ProxyUserInterface:
        Ivoz\Provider\Domain\Model\ProxyUser\ProxyUser
      Ivoz\Provider\Domain\Model\QueueMember\QueueMemberInterface:
        Ivoz\Provider\Domain\Model\QueueMember\QueueMember
      Ivoz\Provider\Domain\Model\Queue\QueueInterface:
        Ivoz\Provider\Domain\Model\Queue\Queue
      Ivoz\Provider\Domain\Model\Recording\RecordingInterface:
        Ivoz\Provider\Domain\Model\Recording\Recording
      Ivoz\Provider\Domain\Model\RetailAccount\RetailAccountInterface:
        Ivoz\Provider\Domain\Model\RetailAccount\RetailAccount
      Ivoz\Provider\Domain\Model\RouteLock\RouteLockInterface:
        Ivoz\Provider\Domain\Model\RouteLock\RouteLock
      Ivoz\Provider\Domain\Model\RoutingPatternGroup\RoutingPatternGroupInterface:
        Ivoz\Provider\Domain\Model\RoutingPatternGroup\RoutingPatternGroup
      Ivoz\Provider\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPatternInterface:
        Ivoz\Provider\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPattern
      Ivoz\Provider\Domain\Model\RoutingPattern\RoutingPatternInterface:
        Ivoz\Provider\Domain\Model\RoutingPattern\RoutingPattern
      Ivoz\Provider\Domain\Model\Schedule\ScheduleInterface:
        Ivoz\Provider\Domain\Model\Schedule\Schedule
      Ivoz\Provider\Domain\Model\Service\ServiceInterface:
        Ivoz\Provider\Domain\Model\Service\Service
      Ivoz\Provider\Domain\Model\TerminalManufacturer\TerminalManufacturerInterface:
        Ivoz\Provider\Domain\Model\TerminalManufacturer\TerminalManufacturer
      Ivoz\Provider\Domain\Model\TerminalModel\TerminalModelInterface:
        Ivoz\Provider\Domain\Model\TerminalModel\TerminalModel
      Ivoz\Provider\Domain\Model\Terminal\TerminalInterface:
        Ivoz\Provider\Domain\Model\Terminal\Terminal
      Ivoz\Provider\Domain\Model\Timezone\TimezoneInterface:
        Ivoz\Provider\Domain\Model\Timezone\Timezone
      Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSetInterface:
        Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSet
      Ivoz\Provider\Domain\Model\TransformationRule\TransformationRuleInterface:
        Ivoz\Provider\Domain\Model\TransformationRule\TransformationRule
      Ivoz\Kam\Domain\Model\TrunksHtable\TrunksHtableInterface:
        Ivoz\Kam\Domain\Model\TrunksHtable\TrunksHtable
      Ivoz\Kam\Domain\Model\TrunksUacreg\TrunksUacregInterface:
        Ivoz\Kam\Domain\Model\TrunksUacreg\TrunksUacreg
      Ivoz\Kam\Domain\Model\UsersHtable\UsersHtableInterface:
        Ivoz\Kam\Domain\Model\UsersHtable\UsersHtable
      Ivoz\Kam\Domain\Model\UsersLocation\UsersLocationInterface:
        Ivoz\Kam\Domain\Model\UsersLocation\UsersLocation
      Ivoz\Provider\Domain\Model\User\UserInterface:
        Ivoz\Provider\Domain\Model\User\User
      Ivoz\Ast\Domain\Model\Voicemail\VoicemailInterface:
        Ivoz\Ast\Domain\Model\Voicemail\Voicemail
      Ivoz\Kam\Domain\Model\AccCdr\AccCdrInterface:
        Ivoz\Kam\Domain\Model\AccCdr\AccCdr
      Ivoz\Kam\Domain\Model\TrunksCdrsBrand\TrunksCdrsBrandInterface:
        Ivoz\Kam\Domain\Model\TrunksCdrsBrand\TrunksCdrsBrand
      Ivoz\Kam\Domain\Model\Dispatcher\DispatcherInterface:
        Ivoz\Kam\Domain\Model\Dispatcher\Dispatcher
      Ivoz\Kam\Domain\Model\PikeTrusted\PikeTrustedInterface:
        Ivoz\Kam\Domain\Model\PikeTrusted\PikeTrusted
      Ivoz\Kam\Domain\Model\Rtpproxy\RtpproxyInterface:
        Ivoz\Kam\Domain\Model\Rtpproxy\Rtpproxy
      Ivoz\Kam\Domain\Model\TrunksAcc\TrunksAccInterface:
        Ivoz\Kam\Domain\Model\TrunksAcc\TrunksAcc
      Ivoz\Kam\Domain\Model\TrunksAddress\TrunksAddressInterface:
        Ivoz\Kam\Domain\Model\TrunksAddress\TrunksAddress
      Ivoz\Kam\Domain\Model\TrunksDomainAttr\TrunksDomainAttrInterface:
        Ivoz\Kam\Domain\Model\TrunksDomainAttr\TrunksDomainAttr
      Ivoz\Kam\Domain\Model\TrunksDomain\TrunksDomainInterface:
        Ivoz\Kam\Domain\Model\TrunksDomain\TrunksDomain
      Ivoz\Kam\Domain\Model\UsersAddress\UsersAddressInterface:
        Ivoz\Kam\Domain\Model\UsersAddress\UsersAddress
      Ivoz\Kam\Domain\Model\UsersDomainAttr\UsersDomainAttrInterface:
        Ivoz\Kam\Domain\Model\UsersDomainAttr\UsersDomainAttr
      Ivoz\Kam\Domain\Model\UsersDomain\UsersDomainInterface:
        Ivoz\Kam\Domain\Model\UsersDomain\UsersDomain
      Ivoz\Kam\Domain\Model\UsersLocationAttr\UsersLocationAttrInterface:
        Ivoz\Kam\Domain\Model\UsersLocationAttr\UsersLocationAttr
      Ivoz\Kam\Domain\Model\UsersMissedCalls\UsersMissedCallsInterface:
        Ivoz\Kam\Domain\Model\UsersMissedCalls\UsersMissedCalls
      Ivoz\Kam\Domain\Model\User\UserInterface:
        Ivoz\Kam\Domain\Model\User\User
      Ivoz\Kam\Domain\Model\Version\VersionInterface:
        Ivoz\Kam\Domain\Model\Version\Version
      Ivoz\Cgr\Domain\Model\Destination\DestinationInterface:
        Ivoz\Cgr\Domain\Model\Destination\Destination
      Ivoz\Cgr\Domain\Model\DestinationRate\DestinationRateInterface:
        Ivoz\Cgr\Domain\Model\DestinationRate\DestinationRate
      Ivoz\Cgr\Domain\Model\Rate\RateInterface:
        Ivoz\Cgr\Domain\Model\Rate\Rate
      Ivoz\Cgr\Domain\Model\RatingPlan\RatingPlanInterface:
        Ivoz\Cgr\Domain\Model\RatingPlan\RatingPlan
      Ivoz\Cgr\Domain\Model\TpAccount\TpAccountInterface:
        Ivoz\Cgr\Domain\Model\TpAccount\TpAccount
      Ivoz\Cgr\Domain\Model\TpCdr\TpCdrInterface:
        Ivoz\Cgr\Domain\Model\TpCdr\TpCdr
      Ivoz\Cgr\Domain\Model\TpDestination\TpDestinationInterface:
        Ivoz\Cgr\Domain\Model\TpDestination\TpDestination
      Ivoz\Cgr\Domain\Model\TpDestinationRate\TpDestinationRateInterface:
        Ivoz\Cgr\Domain\Model\TpDestinationRate\TpDestinationRate
      Ivoz\Cgr\Domain\Model\TpRate\TpRateInterface:
        Ivoz\Cgr\Domain\Model\TpRate\TpRate
      Ivoz\Cgr\Domain\Model\TpRatingPlan\TpRatingPlanInterface:
        Ivoz\Cgr\Domain\Model\TpRatingPlan\TpRatingPlan
      Ivoz\Cgr\Domain\Model\TpRatingProfile\TpRatingProfileInterface:
        Ivoz\Cgr\Domain\Model\TpRatingProfile\TpRatingProfile
      Ivoz\Cgr\Domain\Model\TpTiming\TpTimingInterface:
        Ivoz\Cgr\Domain\Model\TpTiming\TpTiming