parameters:
  soft_delete:
    Ivoz\Provider\Domain\Model\Brand\Brand:
      - Ivoz\Provider\Domain\Model\BrandUrl\BrandUrl
      - Ivoz\Provider\Domain\Model\MusicOnHold\MusicOnHold
      - Ivoz\Provider\Domain\Model\Invoice\Invoice
      - Ivoz\Provider\Domain\Model\Company\Company
    Ivoz\Provider\Domain\Model\Company\Company:
      - Ivoz\Provider\Domain\Model\Locution\Locution
      - Ivoz\Provider\Domain\Model\MusicOnHold\MusicOnHold
      - Ivoz\Provider\Domain\Model\Recording\Recording
      - Ivoz\Provider\Domain\Model\Fax\Fax
      - Ivoz\Cgr\Domain\Model\TpAccountAction\TpAccountAction
      - Ivoz\Cgr\Domain\Model\TpRatingProfile\TpRatingProfile
    Ivoz\Provider\Domain\Model\Fax\Fax:
      - Ivoz\Provider\Domain\Model\FaxesInOut\FaxesInOut
    Ivoz\Provider\Domain\Model\RoutingPatternGroup\RoutingPatternGroup:
      - Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRouting