services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Cgr\Domain\Service\TpRate\TpRateLifecycleServiceCollection:
    public: true

  cgr.lifecycle.tp_rate.service_collection:
    '@Ivoz\Cgr\Domain\Service\TpRate\TpRateLifecycleServiceCollection'

  ##################################
  ## on_commit
  ##################################
#  Ivoz\Cgr\Domain\Service\TpRate\UpdatedTpRateNotificator:
#    tags:
#      - { name: cgr.lifecycle.tp_rate.on_commit, priority: 10}
