########################################
## Raw
########################################
Ivoz\Provider\Domain\Model\BillableCall\BillableCall:
  collectionOperations:
    get:
      swagger_context:
        produces:
          - 'application/ld+json'
          - 'application/json'
          - 'text/csv'
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Brand\Brand:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Brand\Invoice:
Ivoz\Provider\Domain\Model\Brand\Logo:
Ivoz\Provider\Domain\Model\Administrator\Administrator:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
    read_access_control:
      ROLE_SUPER_ADMIN:
        id:
          neq: "0"
    write_access_control:
      ROLE_BRAND_ADMIN:
        raw: "id > 0 or id === null"
Ivoz\Provider\Domain\Model\ApplicationServer\ApplicationServer:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\BrandService\BrandService:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\BrandUrl\BrandUrl:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Company\Company:
  itemOperations: []
  collectionOperations: []
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Country\Name:
Ivoz\Provider\Domain\Model\Country\Zone:
Ivoz\Provider\Domain\Model\Country\Country:
  itemOperations:
    get: ~
  collectionOperations:
    get: ~
  attributes:
    access_control: '"ROLE_USER" in roles'
Ivoz\Provider\Domain\Model\Domain\Domain:
  itemOperations:
    get: ~
  collectionOperations:
    get: ~
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Feature\Feature:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\FeaturesRelBrand\FeaturesRelBrand:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Language\Language:
  itemOperations:
    get: ~
  collectionOperations:
    get: ~
  attributes:
    access_control: '"ROLE_USER" in roles'
Ivoz\Provider\Domain\Model\Language\Name:
Ivoz\Provider\Domain\Model\MediaRelaySet\MediaRelaySet:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
    write_access_control:
      ROLE_SUPER_ADMIN:
        raw: "id !== 0"
Ivoz\Provider\Domain\Model\ProxyTrunk\ProxyTrunk:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\ProxyUser\ProxyUser:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Service\Service:
  itemOperations:
    get: ~
    put: ~
  collectionOperations:
    get: ~
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\TerminalManufacturer\TerminalManufacturer:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\TerminalModel\TerminalModel:
  attributes:
    access_control: '"ROLE_SUPER_ADMIN" in roles'
Ivoz\Provider\Domain\Model\Timezone\Timezone:
  itemOperations:
    get: ~
  collectionOperations:
    get: ~
  attributes:
    access_control: '"ROLE_USER" in roles'
