imports:
    - { resource: "@CoreBundle/Resources/config/parameters.yml" }
    - { resource: security.yml }
    - { resource: logger.yml }
    - { resource: services.yml }
    - { resource: "@CoreBundle/Resources/config/orm_target_entities.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
#    zf1wrapper_bootstrap_path: ../../portals/public/zf.php

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
#    templating:
#        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: UTF8
        server_version: 5.7.19

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'
        mapping_types:
            enum: string
        types:
            datetime: Ivoz\Core\Infrastructure\Persistence\Doctrine\Model\DBAL\Types\UtcDateTimeType
            datetimetz: Ivoz\Core\Infrastructure\Persistence\Doctrine\Model\DBAL\Types\UtcDateTimeType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: yes
        #quote_strategy: doctrine.orm.quote_strategy.ansi
        mappings:
            Provider:
                type: yml
                is_bundle: false
                dir: '%kernel.root_dir%/../../../library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: Ivoz\Provider\Domain\Model
            Ast:
                type: yml
                is_bundle: false
                dir: '%kernel.root_dir%/../../../library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: Ivoz\Ast\Domain\Model
            Kam:
                type: yml
                is_bundle: false
                dir: '%kernel.root_dir%/../../../library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: Ivoz\Kam\Domain\Model

# Swiftmailer Configuration
#swiftmailer:
#    transport: '%mailer_transport%'
#    host: '%mailer_host%'
#    username: '%mailer_user%'
#    password: '%mailer_password%'
#    spool: { type: memory }
