services:
  ################################################
  ## String: exact | partial
  ################################################
  ivoz.api.filter.search:
    parent: 'api_platform.doctrine.orm.search_filter'
    class: Ivoz\Api\Doctrine\Orm\Filter\SearchFilter
    public: false
    shared: false
    arguments:
      $properties: ~
      $requestStack: '@request_stack'
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'
    tags: [ 'api_platform.filter' ]

  ################################################
  ## Date:
  ## ?property[<after|before|strictly_after|strictly_before>]=value
  ################################################
  ivoz.api.filter.date:
    parent: 'api_platform.doctrine.orm.date_filter'
    class: Ivoz\Api\Doctrine\Orm\Filter\DateFilter
    public: false
    shared: false
    arguments:
      $properties: ~
      $requestStack: '@request_stack'
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'
    tags:  [ 'api_platform.filter' ]

  ################################################
  ## Boolean:
  ## ?property=[true|false|1|0]
  ################################################
  ivoz.api.filter.boolean:
    parent: 'api_platform.doctrine.orm.boolean_filter'
    class: Ivoz\Api\Doctrine\Orm\Filter\BooleanFilter
    public: false
    shared: false
    arguments:
      $properties: ~
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'
    tags: [ 'api_platform.filter' ]

  ################################################
  ## Numeric
  ################################################
  ivoz.api.filter.numeric:
    parent: 'api_platform.doctrine.orm.numeric_filter'
    class: Ivoz\Api\Doctrine\Orm\Filter\NumericFilter
    public: false
    shared: false
    arguments:
      $properties: ~
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'
    tags: [ 'api_platform.filter' ]

  ################################################
  ## Range
  ## ?property[lt]|[gt]|[lte]|[gte]|[between]=value
  ################################################
  ivoz.api.filter.range:
    parent: 'api_platform.doctrine.orm.range_filter'
    class: Ivoz\Api\Doctrine\Orm\Filter\RangeFilter
    public: false
    shared: false
    arguments:
      $properties: ~
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'
    tags:  [ 'api_platform.filter' ]

  ################################################
  ## Order
  ## ?_order[property]=<asc|desc>
  ## /endpoint?_order[name]=desc&_order[id]=asc
  ################################################
  ivoz.api.filter.order:
    parent: 'api_platform.doctrine.orm.order_filter'
    class: Ivoz\Api\Doctrine\Orm\Filter\OrderFilter
    public: false
    shared: false
    arguments:
      $properties: ~
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'
    tags: [ 'api_platform.filter' ]

  ################################################
  ## Properties
  ## ?_properties[]=<propertyName>
  ## /endpoint?_properties[]=name&_properties[]=lastname
  ################################################
  ivoz.api.filter.property_filter:
    parent: 'api_platform.serializer.property_filter'
    public: false
    arguments:
      $parameterName: '_properties'
      $overrideDefaultProperties: false
    tags: [ 'api_platform.filter' ]
