imports:
  - { resource: "filters.yml" }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ################################################
  ## Dependencies
  ################################################
  Symfony\Component\Finder\Finder: ~

  ################################################
  ## Listeners
  ################################################
  Ivoz\Api\EventListener\RegisterCommandListener:
    arguments:
      $eventPublisher: '@Ivoz\Core\Domain\Service\DomainEventPublisher'
      $requestId: '@Ivoz\Core\Application\RequestId'
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 7 }

  api_platform.doctrine.listener.view.write:
    class: Ivoz\Api\EventListener\WriteListener
    arguments:
      $entityPersister: '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
    tags:
      - { name: kernel.event_listener, event: kernel.view, priority: 32 }

  ################################################
  ## Serializers
  ################################################
  Ivoz\Api\Core\Serializer\SerializerContextBuilder:
    decorates: "api_platform.serializer.context_builder"
    decoration_priority: 20
    arguments:
      $decorated: '@Ivoz\Api\Core\Serializer\SerializerContextBuilder.inner'
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'

  ################################################
  ## Normalizers
  ################################################
  Ivoz\Api\Json\Serializer\Normalizer\EntityNormalizer:
    arguments:
      $resourceMetadataFactory: "@api_platform.metadata.resource.metadata_factory"
      $resourceClassResolver: "@api_platform.resource_class_resolver"
      $contextBuilder: "@api_platform.jsonld.context_builder"
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  Ivoz\Api\JsonLd\Serializer\Normalizer\EntityNormalizer:
    arguments:
      $resourceMetadataFactory: "@api_platform.metadata.resource.metadata_factory"
      $iriConverter: "@api_platform.iri_converter"
      $resourceClassResolver: "@api_platform.resource_class_resolver"
      $contextBuilder: "@api_platform.jsonld.context_builder"
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  Ivoz\Api\Csv\Serializer\Normalizer\EntityNormalizer:
    arguments:
      $resourceMetadataFactory: "@api_platform.metadata.resource.metadata_factory"
      $resourceClassResolver: "@api_platform.resource_class_resolver"
      $contextBuilder: "@api_platform.jsonld.context_builder"
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  ################################################
  ## Denormalizers
  ################################################
  Ivoz\Api\Entity\Serializer\Normalizer\EntityDenormalizer:
    arguments:
      $createEntityFromDTO:
        '@Ivoz\Core\Application\Service\CreateEntityFromDTO'
      $logger: '@logger'
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  ################################################
  ## Resources
  ################################################
  Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\FilterMetadataFactory:
    decorates: "api_platform.metadata.resource.metadata_factory"
    decoration_priority: 2
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\FilterMetadataFactory.inner'
      $propertyNameCollectionFactory: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory'
      $managerRegistry: '@doctrine'

  Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\OperationMetadataFactory:
    decorates: "api_platform.metadata.resource.metadata_factory"
    decoration_priority: 1
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\OperationMetadataFactory.inner'
      $managerRegistry: ''

  Ivoz\Api\Swagger\Metadata\Resource\Factory\YmlExtractorResourceNameCollectionFactory:
    decorates: "api_platform.metadata.resource.name_collection_factory"
    decoration_priority: 0
    arguments:
      $sourceFilePath: '%kernel.project_dir%/app/config/api/'
      $finder: '@Symfony\Component\Finder\Finder'

  Ivoz\Api\Swagger\Metadata\Resource\Factory\ExtractorResourceMetadataFactory:
    decorates: "api_platform.metadata.resource.metadata_factory"
    decoration_priority: 29 #right before api_platform.metadata.resource.metadata_factory.php_doc
    arguments:
      $extractor: '@api_platform.metadata.extractor.yaml'

  ################################################
  ## Subresources
  ################################################
  Ivoz\Api\Operation\Factory\SubresourceOperationFactoryDecorator:
    decorates: 'api_platform.subresource_operation_factory'
    decoration_priority: 10
    arguments:
      $decoratedNormalizer: '@Ivoz\Api\Operation\Factory\SubresourceOperationFactoryDecorator.inner'
      $propertyNameCollectionFactory: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory'

  ################################################
  ## Properties
  ################################################
  Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory: ~

  Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataLinkFactory:
    decorates: 'api_platform.metadata.property.metadata_factory'
    decoration_priority: 1
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataLinkFactory.inner'

  Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataOverwriteFactory:
    decorates: 'api_platform.metadata.property.metadata_factory'
    decoration_priority: 2
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataOverwriteFactory.inner'
      $reader: '@annotation_reader'

  Ivoz\Api\Swagger\Metadata\Property\IdentifiersExtractor:
    decorates: 'api_platform.identifiers_extractor'
    decoration_priority: 10
    arguments:
      $decoratedIdentifiersExtractor: '@Ivoz\Api\Swagger\Metadata\Property\IdentifiersExtractor.inner'
      $propertyNameCollectionFactory: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory'

  ################################################
  ## Documentation
  ################################################
  Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\MissingReferenceFixerDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    decoration_priority: 11
    arguments:
      $decoratedNormalizer: '@Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\MissingReferenceFixerDecorator.inner'
      $propertyNameCollectionFactory: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory'
      $resourceMetadataFactory: "@api_platform.metadata.resource.metadata_factory"
      $propertyMetadataFactory: "@api_platform.metadata.property.metadata_factory"
      $resourceClassResolver: "@api_platform.resource_class_resolver"

  Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\ReferenceFixerDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    decoration_priority: 10
    arguments:
      $decoratedNormalizer: '@Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\ReferenceFixerDecorator.inner'

  Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\SearchFilterDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    decoration_priority: 9
    arguments:
      $decoratedNormalizer:
        '@Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\SearchFilterDecorator.inner'

  Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\AuthEndpointDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    decoration_priority: 8
    arguments:
      $decoratedNormalizer:
        '@Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\AuthEndpointDecorator.inner'

  Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\BasePathDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    decoration_priority: 7
    arguments:
      $decoratedNormalizer:
        '@Ivoz\Api\Swagger\Serializer\DocumentationNormalizer\BasePathDecorator.inner'
      $router:
        '@router'

  ################################################
  ## ItemDataProviders
  ################################################
  api_platform.doctrine.orm.default.item_data_provider:
    parent: "api_platform.doctrine.orm.item_data_provider"
    autowire: false
    autoconfigure: false
    public: false
    class: 'ApiPlatform\Core\Bridge\Doctrine\Orm\ItemDataProvider'
    arguments:
      index_1: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory'
    tags:
      -  { name: api_platform.item_data_provider }

  ################################################
  ## UI
  ################################################
  api_platform.swagger.action.ui:
    class: Ivoz\Api\Swagger\Ui\SwaggerUiAction
    public: true
    arguments:
      - '@Ivoz\Api\Swagger\Metadata\Resource\Factory\YmlExtractorResourceNameCollectionFactory'
      - "@api_platform.metadata.resource.metadata_factory"
      - "@api_platform.serializer"
      - "@twig"
      - "@router"
      - '%api_platform.title%'
      - '%api_platform.description%'
      - '%api_platform.version%'
      - '%api_platform.formats%'
      - '%api_platform.oauth.enabled%'
      - '%api_platform.oauth.clientId%'
      - '%api_platform.oauth.clientSecret%'
      - '%api_platform.oauth.type%'
      - '%api_platform.oauth.flow%'
      - '%api_platform.oauth.tokenUrl%'
      - '%api_platform.oauth.authorizationUrl%'
      - '%api_platform.oauth.scopes%'
      - '%kernel.environment%'

  ################################################
  ## ORM
  ################################################
  Ivoz\Api\Doctrine\Orm\Extension\DynamicLoadingExtension:
    arguments:
      - '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory'
      - "@api_platform.metadata.property.metadata_factory"
      - "@api_platform.metadata.resource.metadata_factory"
      - "@request_stack"
      - '@api_platform.serializer.context_builder'
      - '@serializer.mapping.class_metadata_factory'
    tags:
      - { name: api_platform.doctrine.orm.query_extension.item }

