imports:
  - { resource: "filters.yml" }
  - { resource: "services/swagger.yml" }
  - { resource: "services/hydra.yml" }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Provider\Infrastructure\Api\Jwt\UserAuthenticationSuccessHandler:
    arguments:
      - '@lexik_jwt_authentication.jwt_manager'
      - '@event_dispatcher'

  Ivoz\Provider\Infrastructure\Api\Jwt\TokenAuthenticator:
    arguments:
      - '@lexik_jwt_authentication.jwt_manager'
      - '@event_dispatcher'
      - '@lexik_jwt_authentication.extractor.chain_extractor'

  ################################################
  ## Dependencies
  ################################################
  Symfony\Component\Finder\Finder: ~
  Ivoz\Api\Core\Security\DataAccessControlParser:
    arguments:
      $requestStack: '@request_stack'
      $tokenStorage: '@security.token_storage'
      $entityManager: '@doctrine.orm.entity_manager'
      $companyRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\Company\\Company")'
      $userRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\User\\User")'

  ################################################
  ## Listeners
  ################################################
  # Check access_control before any database is hit
  api_platform.security.listener.request.deny_access:
    class: ApiPlatform\Core\Security\EventListener\DenyAccessListener
    arguments:
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'
      $resourceAccessCheckerOrExpressionLanguage: '@api_platform.security.resource_access_checker'
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 7 }

  Ivoz\Api\Symfony\EventListener\DomainExceptionListener:
    arguments:
      $serializer: '@api_platform.serializer'
      $errorFormats: '%api_platform.error_formats%'
      $logger: '@logger'
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 2 }

  Ivoz\Api\EventListener\RegisterCommandListener:
    arguments:
      $eventPublisher: '@Ivoz\Core\Domain\Service\DomainEventPublisher'
      $requestId: '@Ivoz\Core\Application\RequestId'
      $jwtTokenAuthenticator: '@lexik_jwt_authentication.security.guard.jwt_token_authenticator'
    tags:
      - { name: kernel.event_listener, event: kernel.view, priority: 33 }

  api_platform.doctrine.listener.view.write:
    class: Ivoz\Api\EventListener\WriteListener
    arguments:
      $entityPersister: '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $dataAccessControlParser: '@Ivoz\Api\Core\Security\DataAccessControlParser'
      $dtoAssembler: '@Ivoz\Core\Application\Service\Assembler\DtoAssembler'
    tags:
      - { name: kernel.event_listener, event: kernel.view, priority: 32 }

  ################################################
  ## Serializers
  ################################################
  Ivoz\Api\Csv\Serializer\Mixer\CsvMixer: ~
  Ivoz\Api\Json\Serializer\Mixer\JsonMixer: ~
  Ivoz\Api\JsonLd\Serializer\Mixer\JsonLdMixer: ~

  Ivoz\Api\Symfony\Serializer\ProgressiveSerializer:
    decorates: 'api_platform.serializer'
    autoconfigure: false
    decoration_priority: 1
    arguments:
      $decoratedSerializer: '@Ivoz\Api\Symfony\Serializer\ProgressiveSerializer.inner'
    calls:
      - [ addMixer, ['@Ivoz\Api\Csv\Serializer\Mixer\CsvMixer']]
      - [ addMixer, ['@Ivoz\Api\Json\Serializer\Mixer\JsonMixer']]
      - [ addMixer, ['@Ivoz\Api\JsonLd\Serializer\Mixer\JsonLdMixer']]

  Ivoz\Api\Core\Serializer\SerializerContextBuilder:
    decorates: "api_platform.serializer.context_builder"
    decoration_priority: 20
    arguments:
      $decorated: '@Ivoz\Api\Core\Serializer\SerializerContextBuilder.inner'
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'

  ################################################
  ## Normalizers
  ################################################
  Ivoz\Api\Entity\Serializer\Normalizer\DateTimeNormalizer:
    arguments:
      $classMetadataFactory: '@doctrine.orm.default_entity_manager.metadata_factory'
      $propertyMetadataFactory: '@api_platform.metadata.property.metadata_factory'
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  Ivoz\Api\Entity\Serializer\Normalizer\DateTimeNormalizerInterface:
    alias: Ivoz\Api\Entity\Serializer\Normalizer\DateTimeNormalizer

  Ivoz\Api\Json\Serializer\Normalizer\EntityNormalizer:
    arguments:
      $resourceMetadataFactory: "@api_platform.metadata.resource.metadata_factory"
      $resourceClassResolver: "@api_platform.resource_class_resolver"
      $contextBuilder: "@api_platform.jsonld.context_builder"
      $propertyNameCollectionFactory: '@Ivoz\Api\Entity\Metadata\Property\Factory\PropertyNameCollectionFactory'
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  Ivoz\Api\Json\EventListener\AddCollectionHeaders:
    arguments:
      $orderParameterName: "%api_platform.collection.order_parameter_name%"
      $pageParameterName: "%api_platform.collection.pagination.page_parameter_name%"
      $enabledParameterName: "%api_platform.collection.pagination.enabled_parameter_name%"
    tags:
      - { name: kernel.event_listener, event: kernel.response }

  Ivoz\Api\JsonLd\Serializer\Normalizer\EntityNormalizer:
    arguments:
      $resourceMetadataFactory: "@api_platform.metadata.resource.metadata_factory"
      $iriConverter: "@api_platform.iri_converter"
      $resourceClassResolver: "@api_platform.resource_class_resolver"
      $contextBuilder: "@api_platform.jsonld.context_builder"
      $dateTimeNormalizer: '@Ivoz\Api\Entity\Serializer\Normalizer\DateTimeNormalizer'
      $propertyNameCollectionFactory: '@Ivoz\Api\Entity\Metadata\Property\Factory\PropertyNameCollectionFactory'
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  Ivoz\Api\Csv\Serializer\Normalizer\EntityNormalizer:
    arguments:
      $resourceMetadataFactory: "@api_platform.metadata.resource.metadata_factory"
      $resourceClassResolver: "@api_platform.resource_class_resolver"
      $contextBuilder: "@api_platform.jsonld.context_builder"
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  Ivoz\Api\Core\Hydra\Serializer\CollectionFilterMappingsNormalizer:
    decorates: "api_platform.hydra.normalizer.collection"
    decoration_priority: -1
    arguments:
      $collectionNormalizer: '@Ivoz\Api\Core\Hydra\Serializer\CollectionFilterMappingsNormalizer.inner'

  ################################################
  ## Denormalizers
  ################################################
  Ivoz\Api\Entity\Serializer\Normalizer\EntityDenormalizer:
    arguments:
      $createEntityFromDTO: '@Ivoz\Core\Application\Service\CreateEntityFromDTO'
      $propertyMetadataFactory: '@api_platform.metadata.property.metadata_factory'
      $logger: '@logger'
      $dateTimeNormalizer: '@Ivoz\Api\Entity\Serializer\Normalizer\DateTimeNormalizer'
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  ################################################
  ## Metadata Extractor
  ################################################
  api_platform.metadata.extractor.yaml:
    class: Ivoz\Api\Core\Metadata\Extractor\YamlExtractor
    arguments:
      $paths: '%api_mapping_paths%'

  ################################################
  ## Resources
  ################################################
  Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\FilterMetadataFactory:
    decorates: "api_platform.metadata.resource.metadata_factory"
    decoration_priority: 2
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\FilterMetadataFactory.inner'
      $propertyNameCollectionFactory: '@Ivoz\Api\Entity\Metadata\Property\Factory\PropertyNameCollectionFactory'
      $managerRegistry: '@doctrine'

  Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\OperationMetadataFactory:
    decorates: "api_platform.metadata.resource.metadata_factory"
    decoration_priority: 1
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\OperationMetadataFactory.inner'
      $managerRegistry: ''

  Ivoz\Api\Swagger\Metadata\Resource\Factory\YmlExtractorResourceNameCollectionFactory:
    decorates: "api_platform.metadata.resource.name_collection_factory"
    decoration_priority: 0
    arguments:
      $sourceFilePath: '%kernel.project_dir%/app/config/api/'
      $finder: '@Symfony\Component\Finder\Finder'

  Ivoz\Api\Swagger\Metadata\Resource\Factory\ExtractorResourceMetadataFactory:
    decorates: "api_platform.metadata.resource.metadata_factory"
    decoration_priority: 29 #right before api_platform.metadata.resource.metadata_factory.php_doc
    arguments:
      $extractor: '@api_platform.metadata.extractor.yaml'

  ################################################
  ## Subresources
  ################################################
  Ivoz\Api\Operation\Factory\SubresourceOperationFactoryDecorator:
    decorates: 'api_platform.subresource_operation_factory'
    decoration_priority: 10
    arguments:
      $decoratedNormalizer: '@Ivoz\Api\Operation\Factory\SubresourceOperationFactoryDecorator.inner'
      $propertyNameCollectionFactory: '@Ivoz\Api\Entity\Metadata\Property\Factory\PropertyNameCollectionFactory'

  ################################################
  ## Properties
  ################################################
  Ivoz\Api\Doctrine\Orm\Metadata\Property\DoctrineOrmPropertyMetadataFactory:
    arguments:
      $managerRegistry: '@doctrine'

  Ivoz\Api\Entity\Metadata\Property\Factory\PropertyNameCollectionFactory:
    arguments:
      $propertyMetadataFactory: '@Ivoz\Api\Doctrine\Orm\Metadata\Property\DoctrineOrmPropertyMetadataFactory'
      $resourceNameCollectionFactory: '@api_platform.metadata.resource.name_collection_factory'

  Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataLinkFactory:
    decorates: 'api_platform.metadata.property.metadata_factory'
    decoration_priority: 1
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataLinkFactory.inner'

  Ivoz\Api\Swagger\Metadata\Property\Factory\PropertySwaggerContextFactory:
    decorates: 'api_platform.metadata.property.metadata_factory'
    decoration_priority: 2
    arguments:
      $classMetadataFactory: '@doctrine.orm.default_entity_manager.metadata_factory'
      $decorated: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertySwaggerContextFactory.inner'

  Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataOverwriteFactory:
    decorates: 'api_platform.metadata.property.metadata_factory'
    decoration_priority: 3
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataOverwriteFactory.inner'
      $reader: '@annotation_reader'

  Ivoz\Api\Swagger\Metadata\Property\IdentifiersExtractor:
    decorates: 'api_platform.identifiers_extractor'
    decoration_priority: 10
    arguments:
      $decoratedIdentifiersExtractor: '@Ivoz\Api\Swagger\Metadata\Property\IdentifiersExtractor.inner'
      $propertyNameCollectionFactory: '@Ivoz\Api\Entity\Metadata\Property\Factory\PropertyNameCollectionFactory'

  ################################################
  ## ItemDataProviders
  ################################################
  api_platform.doctrine.orm.default.item_data_provider:
    parent: "api_platform.doctrine.orm.item_data_provider"
    autowire: false
    autoconfigure: false
    public: false
    class: 'ApiPlatform\Core\Bridge\Doctrine\Orm\ItemDataProvider'
    arguments:
      index_1: '@Ivoz\Api\Entity\Metadata\Property\Factory\PropertyNameCollectionFactory'
    tags:
      -  { name: api_platform.item_data_provider }

  ################################################
  ## ORM
  ################################################
  Ivoz\Api\Doctrine\Orm\Extension\DynamicLoadingExtension:
    arguments:
      - '@Ivoz\Api\Entity\Metadata\Property\Factory\PropertyNameCollectionFactory'
      - "@api_platform.metadata.property.metadata_factory"
      - "@api_platform.metadata.resource.metadata_factory"
      - "@request_stack"
      - '@api_platform.serializer.context_builder'
      - '@serializer.mapping.class_metadata_factory'
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection, priority: 10 }
      - { name: api_platform.doctrine.orm.query_extension.item, priority: 10 }

  Ivoz\Api\Doctrine\Orm\Extension\SecurityFilterExtension:
    arguments:
      $dataAccessControlParser: '@Ivoz\Api\Core\Security\DataAccessControlParser'
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection, priority: 11 }
      - { name: api_platform.doctrine.orm.query_extension.item, priority: 11 }

  Ivoz\Api\Doctrine\Orm\Extension\UnpaginatedResultGeneratorExtension:
    arguments:
      $requestStack: '@request_stack'
      $resourceMetadataFactory: '@api_platform.metadata.resource.metadata_factory'
      $entityManager: '@doctrine.orm.entity_manager'
      $enabled: '%api_platform.collection.pagination.enabled%'
      $clientEnabled: '%api_platform.collection.pagination.client_enabled%'
      $enabledParameterName: '%api_platform.collection.pagination.enabled_parameter_name%'
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection, priority: 7 }

  Ivoz\Api\Doctrine\Orm\Extension\CollectionExtensionList:
    calls:
        - [ addExtension, ['@api_platform.doctrine.orm.query_extension.filter'] ]
        - [ addExtension, ['@api_platform.doctrine.orm.query_extension.pagination'] ]
        - [ addExtension, ['@api_platform.doctrine.orm.query_extension.order'] ]
