mappers:
  - &Administrators {
        modelFile: Administrators,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Administrator\\Administrator'
    }
  - &ApplicationServers {
        modelFile: ApplicationServers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ApplicationServer\\ApplicationServer'
    }
  - &BalanceMovements {
        modelFile: BalanceMovements,
        entity: 'Ivoz\\Provider\\Domain\\Model\\BalanceMovement\\BalanceMovement'
    }    
  - &BalanceNotifications {
        modelFile: BalanceNotifications,
        entity: 'Ivoz\\Provider\\Domain\\Model\\BalanceNotification\\BalanceNotification'
    }
  - &BillableCalls {
        modelFile: BillableCalls,
        entity: 'Ivoz\\Provider\\Domain\\Model\\BillableCall\\BillableCall'
    }
  - &BrandServices {
        modelFile: BrandServices,
        entity: 'Ivoz\\Provider\\Domain\\Model\\BrandService\\BrandService'
    }
  - &Brands {
        modelFile: Brands,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Brand\\Brand'
    }
  - &BrandURLs {
        modelFile: BrandUrls,
        entity: 'Ivoz\\Provider\\Domain\\Model\\BrandUrl\\BrandUrl'
    }
  - &Calendars {
        modelFile: Calendars,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Calendar\\Calendar'
    }
  - &CallACL {
        modelFile: CallAcl,
        entity: 'Ivoz\\Provider\\Domain\\Model\\CallAcl\\CallAcl'
    }
  - &CallAclRelMatchLists {
        modelFile: CallAclRelMatchLists,
        entity: 'Ivoz\\Provider\\Domain\\Model\\CallAclRelMatchLists\\CallAclRelMatchLists'
    }
  - &CallCsvReports {
      modelFile: CallCsvReports,
      entity: 'Ivoz\\Provider\\Domain\\Model\\CallCsvReport\\CallCsvReport'
  }
  - &CallCsvSchedulers {
      modelFile: CallCsvSchedulers,
      entity: 'Ivoz\\Provider\\Domain\\Model\\CallCsvScheduler\\CallCsvScheduler'
  }
  - &CallForwardSettings {
        modelFile: CallForwardSettings,
        entity: 'Ivoz\\Provider\\Domain\\Model\\CallForwardSetting\\CallForwardSetting'
    }
  - &Carriers {
        modelFile: Carriers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Carrier\\Carrier'
    }
  - &CarrierServers {
        modelFile: CarrierServers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\CarrierServer\\CarrierServer'
    }
  - &Companies {
        modelFile: Companies,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Company\\Company'
    }
  - &CompanyServices {
        modelFile: CompanyServices,
        entity: 'Ivoz\\Provider\\Domain\\Model\\CompanyService\\CompanyService'
    }
  - &CompanyURLs {
        modelFile: CompanyUrls,
        entity: 'Ivoz\\Provider\\Domain\\Model\\BrandUrl\\BrandUrl'
    }
  - &ConditionalRoutesConditions {
        modelFile: ConditionalRoutesConditions,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ConditionalRoutesCondition\\ConditionalRoutesCondition'
    }
  - &ConditionalRoutes {
        modelFile: ConditionalRoutes,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ConditionalRoute\\ConditionalRoute'
    }
  - &ConferenceRooms {
        modelFile: ConferenceRoom,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ConferenceRoom\\ConferenceRoom'
    }
  - &ConferenceRooms {
        modelFile: ConferenceRooms,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ConferenceRoom\\ConferenceRoom'
    }
  - &Currencies {
        modelFile: Currencies,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Currency\\Currency'
    }
  - &Ddis {
        modelFile: Ddis,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Ddi\\Ddi'
    }
  - &DdiProviders {
        modelFile: DdiProviders,
        entity: 'Ivoz\\Provider\\Domain\\Model\\DdiProvider\\DdiProvider'
    }
  - &DdiProviderAddresses {
        modelFile: DdiProviderAddresses,
        entity: 'Ivoz\\Provider\\Domain\\Model\\DdiProviderAddress\\DdiProviderAddress'
    }
  - &DdiProviderRegistrations {
        modelFile: DdiProviderRegistrations,
        entity: 'Ivoz\\Provider\\Domain\\Model\\DdiProviderRegistration\\DdiProviderRegistration'
    }
  - &Destinations {
        modelFile: Destinations,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Destination\\Destination'
    }
  - &DestinationRates {
        modelFile: DestinationRates,
        entity: 'Ivoz\\Provider\\Domain\\Model\\DestinationRate\\DestinationRate'
    }
  - &DestinationRateGroups {
        modelFile: DestinationRateGroups,
        entity: 'Ivoz\\Provider\\Domain\\Model\\DestinationRateGroup\\DestinationRateGroup'
    }
  - &Domains {
        modelFile: Domains,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Domain\\Domain'
    }
  - &Extensions {
        modelFile: Extensions,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Extension\\Extension'
    }
  - &ExternalCallFilters {
        modelFile: ExternalCallFilters,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ExternalCallFilter\\ExternalCallFilter'
    }
  - &ExternalCallFiltersResidential {
        modelFile: ExternalCallFiltersResidential,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ExternalCallFilter\\ExternalCallFilter'
    }
  - &FaxesInOut {
        modelFile: FaxesInOut,
        entity: 'Ivoz\\Provider\\Domain\\Model\\FaxesInOut\\FaxesInOut'
    }
  - &Faxes {
        modelFile: Faxes,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Fax\\Fax'
    }
  - &FixedCosts {
        modelFile: FixedCosts,
        entity: 'Ivoz\\Provider\\Domain\\Model\\FixedCosts\\FixedCost'
    }
  - &FixedCostsRelInvoices {
        modelFile: FixedCostsRelInvoices,
        entity: 'Ivoz\\Provider\\Domain\\Model\\FixedCostsRelInvoice\\FixedCostsRelInvoice'
    }
  - &FixedCostsRelInvoiceSchedulers {
        modelFile: FixedCostsRelInvoiceSchedulers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\FixedCostsRelInvoiceScheduler\\FixedCostsRelInvoiceScheduler'
    }
  - &Friends {
        modelFile: Friends,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Friend\\Friend'
    }
  - &FriendsPatterns {
        modelFile: FriendsPatterns,
        entity: 'Ivoz\\Provider\\Domain\\Model\\FriendsPattern\\FriendsPattern'
    }
  - &HolidayDates {
        modelFile: HolidayDates,
        entity: 'Ivoz\\Provider\\Domain\\Model\\HolidayDate\\HolidayDate'
    }
  - &HuntGroups {
        modelFile: HuntGroups,
        entity: 'Ivoz\\Provider\\Domain\\Model\\HuntGroup\\HuntGroup'
    }
  - &HuntGroupsRelUsers {
        modelFile: HuntGroupsRelUsers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\HuntGroupRelUser\\HuntGroupRelUser'
    }
  - &Invoices {
        modelFile: Invoices,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Invoice\\Invoice'
    }
  - &InvoiceTemplates {
        modelFile: InvoiceTemplates,
        entity: 'Ivoz\\Provider\\Domain\\Model\\InvoiceTemplate\\InvoiceTemplate'
    }
  - &InvoiceNumberSequences {
        modelFile: InvoiceNumberSequences,
        entity: 'Ivoz\\Provider\\Domain\\Model\\InvoiceNumberSequence\\InvoiceNumberSequence'
    }
  - &InvoiceSchedulers {
        modelFile: InvoiceSchedulers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\InvoiceScheduler\\InvoiceScheduler'
  }
  - &IvrEntries {
        modelFile: IvrEntries,
        entity: 'Ivoz\\Provider\\Domain\\Model\\IvrEntry\\IvrEntry'
    }
  - &Ivr {
        modelFile: Ivr,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Ivr\\Ivr'
    }
  - &Locutions {
        modelFile: Locutions,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Locution\\Locution'
    }
  - &MatchListPatterns {
        modelFile: MatchListPatterns,
        entity: 'Ivoz\\Provider\\Domain\\Model\\MatchListPattern\\MatchListPattern'
    }
  - &MatchLists {
        modelFile: MatchLists,
        entity: 'Ivoz\\Provider\\Domain\\Model\\MatchList\\MatchList'
    }
  - &MediaRelaySets {
        modelFile: MediaRelaySets,
        entity: 'Ivoz\\Provider\\Domain\\Model\\MediaRelaySet\\MediaRelaySet'
    }
  - &MusicOnHold {
        modelFile: MusicOnHold,
        entity: 'Ivoz\\Provider\\Domain\\Model\\MusicOnHold\\MusicOnHold'
    }
  - &NotificationTemplates {
        modelFile: NotificationTemplates,
        entity: 'Ivoz\\Provider\\Domain\\Model\\NotificationTemplate\\NotificationTemplate'
    }
  - &NotificationTemplatesContents {
        modelFile: NotificationTemplatesContents,
        entity: 'Ivoz\\Provider\\Domain\\Model\\NotificationTemplateContent\\NotificationTemplateContent'
    }
  - &OutgoingDDIRules {
        modelFile: OutgoingDdiRules,
        entity: 'Ivoz\\Provider\\Domain\\Model\\OutgoingDdiRule\\OutgoingDdiRule'
    }
  - &OutgoingDDIRulesPatterns {
        modelFile: OutgoingDdiRulesPatterns,
        entity: 'Ivoz\\Provider\\Domain\\Model\\OutgoingDdiRulesPattern\\OutgoingDdiRulesPattern'
    }
  - &OutgoingRouting {
        modelFile: OutgoingRouting,
        entity: 'Ivoz\\Provider\\Domain\\Model\\OutgoingRouting\\OutgoingRouting'
    }
  - &PickUpGroups {
        modelFile: PickUpGroups,
        entity: 'Ivoz\\Provider\\Domain\\Model\\PickUpGroup\\PickUpGroup'
    }
  - &PickUpRelUsers {
        modelFile: PickUpRelUsers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\PickUpRelUser\\PickUpRelUser'
    }
  - &ProxyTrunks {
        modelFile: ProxyTrunks,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ProxyTrunk\\ProxyTrunk'
    }
  - &ProxyUsers {
        modelFile: ProxyUsers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ProxyUser\\ProxyUser'
    }
  - &QueueMembers {
        modelFile: QueueMembers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\QueueMember\\QueueMember'
    }
  - &Queues {
        modelFile: Queues,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Queue\\Queue'
    }
  - &RatingPlans {
        modelFile: RatingPlans,
        entity: 'Ivoz\\Provider\\Domain\\Model\\RatingPlan\\RatingPlan'
    }
  - &RatingPlanGroups {
        modelFile: RatingPlanGroups,
        entity: 'Ivoz\\Provider\\Domain\\Model\\RatingPlanGroup\\RatingPlanGroup'
    }
  - &RatingProfiles {
        modelFile: RatingProfiles,
        entity: 'Ivoz\\Provider\\Domain\\Model\\RatingProfile\\RatingProfile'
    }
  - &Recordings {
        modelFile: Recordings,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Recording\\Recording'
    }
  - &ResidentialDevices {
        modelFile: ResidentialDevices,
        entity: 'Ivoz\\Provider\\Domain\\Model\\ResidentialDevice\\ResidentialDevice'
    }
  - &ResidentialClients {
        modelFile: ResidentialClients,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Company\\Company'
    }
  - &RetailAccounts {
        modelFile: RetailAccounts,
        entity: 'Ivoz\\Provider\\Domain\\Model\\RetailAccount\\RetailAccount'
    }
  - &RetailClients {
        modelFile: RetailClients,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Company\\Company'
    }
  - &RoutingPatternGroups {
        modelFile: RoutingPatternGroups,
        entity: 'Ivoz\\Provider\\Domain\\Model\\RoutingPatternGroup\\RoutingPatternGroup'
    }
  - &RoutingPatternGroupsRelPatterns {
        modelFile: RoutingPatternGroupsRelPatterns,
        entity: 'Ivoz\\Provider\\Domain\\Model\\RoutingPatternGroupsRelPattern\\RoutingPatternGroupsRelPattern'
    }
  - &RoutingPatterns {
        modelFile: RoutingPatterns,
        entity: 'Ivoz\\Provider\\Domain\\Model\\RoutingPattern\\RoutingPattern'
    }
  - &RoutingTags {
        modelFile: RoutingTags,
        entity: 'Ivoz\\Provider\\Domain\\Model\\RoutingTag\\RoutingTag'
    }
  - &RouteLocks {
        modelFile: RouteLocks,
        entity: 'Ivoz\\Provider\\Domain\\Model\\RouteLock\\RouteLock'
    }
  - &Schedules {
        modelFile: Schedules,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Schedule\\Schedule'
    }
  - &Services {
        modelFile: Services,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Service\\Service'
    }
  - &TerminalManufacturers {
        modelFile: TerminalManufacturers,
        entity: 'Ivoz\\Provider\\Domain\\Model\\TerminalManufacturer\\TerminalManufacturer'
    }
  - &TerminalModels {
        modelFile: TerminalModels,
        entity: 'Ivoz\\Provider\\Domain\\Model\\TerminalModel\\TerminalModel'
    }
  - &Terminals {
        modelFile: Terminals,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Terminal\\Terminal'
    }
  - &TransformationRuleSets {
        modelFile: TransformationRuleSets,
        entity: 'Ivoz\\Provider\\Domain\\Model\\TransformationRuleSet\\TransformationRuleSet'
    }
  - &TransformationRules {
        modelFile: TransformationRules,
        entity: 'Ivoz\\Provider\\Domain\\Model\\TransformationRule\\TransformationRule'
    }
  - &Users {
        modelFile: Users,
        entity: 'Ivoz\\Provider\\Domain\\Model\\User\\User'
    }
  - &WholesaleClients {
        modelFile: WholesaleClients,
        entity: 'Ivoz\\Provider\\Domain\\Model\\Company\\Company'
    }
  - &Trusted {
        modelFile: KamTrusted,
        entity: 'Kam\\Model\\Trusted\\Trusted'
    }
  - &Rtpengine {
        modelFile: KamRtpengine,
        entity: 'Kam\\Model\\Rtpengine\\Rtpengine'
    }
  - &KamTrunksAcc {
        modelFile: KamTrunksAcc,
        entity: 'Kam\\Model\\TrunksAcc\\TrunksAcc'
    }
  - &UsersAcc {
        modelFile: UsersAcc,
        entity: 'Ivoz\\Provider\\Domain\\Model\\UsersAcc\\UsersAcc'
    }
  - &KamUsersAddress {
        modelFile: KamUsersAddress,
        entity: 'Kam\\Model\\UsersAddress\\UsersAddress'
    }
  - &KamUsersCdrs {
        modelFile: KamUsersCdrs,
        entity: 'Ivoz\\Kam\\Model\\UsersCdrs\\UsersCdr'
    }

