voicemailVariablesHelp: &voicemailVariablesHelp
    info:
      type: box
      position: left
      icon: help
      label: _("Need help?")
      text: 'You can use these voicemail variables in subject and body:<br/>
            <pre>
               <b>&#36;{VM_NAME}</b>    <i>Voicemail User name</i><br/>
               <b>&#36;{VM_DATE}</b>    <i>Received date</i><br/>
               <b>&#36;{VM_DUR}</b>     <i>Voicemail duration</i><br/>
               <b>&#36;{VM_CIDNAME}</b> <i>Caller name</i><br/>
               <b>&#36;{VM_CIDNUM}</b>  <i>Caller number</i><br/>
               <b>&#36;{VM_MSGNUM}</b>  <i>Voicemail Number</i><br/>
            </pre>'

faxVariablesHelp: &faxVariablesHelp
    info:
      type: box
      position: left
      icon: help
      label: _("Need help?")
      text: 'You can use these fax variables in subject and body:<br/>
            <pre>
               <b>&#36;{FAX_NAME}</b>    <i>Virtual Fax name</i><br/>
               <b>&#36;{FAX_PDFNAME}</b> <i>Fax PDF filename</i><br/>
               <b>&#36;{FAX_PAGES}</b>   <i>Fax PDF page count</i><br/>
               <b>&#36;{FAX_SRC}</b>     <i>Origin number</i><br/>
               <b>&#36;{FAX_DST}</b>     <i>Received DDI number</i><br/>
               <b>&#36;{FAX_DATE}</b>    <i>Received Date </i><br/>
            </pre>'


lowBalanceVariablesHelp: &lowBalanceVariablesHelp
    info:
      type: box
      position: left
      icon: help
      label: _("Need help?")
      text: 'You can use these balance variables in subject and body:<br/>
            <pre>
               <b>&#36;{BALANCE_COMPANY}</b> <i>Company name</i><br/>
               <b>&#36;{BALANCE_AMOUNT}</b>  <i>Current balance amount</i><br/>
            </pre>'
