imports:
    - { resource: config.yml }
    - { resource: fixtures.yml }

framework:
    router:
        resource: '%kernel.project_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }
