########################################
## Custom models
########################################
Model\WebTheme:
  itemOperations:
    get:
      method: 'GET'
      path: '/my/web_theme'
      route_name: 'get_my_web_theme'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}

Model\UserStatus:
  attributes:
    access_control: '"ROLE_COMPANY_USER" in roles'
  itemOperations:
    get:
      method: 'GET'
      path: '/my/status'
      route_name: 'get_my_status'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}

Model\CallStats:
  attributes:
    access_control: '"ROLE_COMPANY_USER" in roles'
  itemOperations:
    get:
      method: 'GET'
      path: '/my/call_stats'
      route_name: 'get_my_call_stats'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}

########################################
## Custom kam endpoints
########################################
Ivoz\Kam\Domain\Model\UsersCdr\UsersCdr:
  collectionOperations:
    get_my_call_history:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'GET'
      path: '/my/call_history'
      route_name: 'get_my_call_history'
      parameters: []
      swagger_context:
        produces:
          - 'application/ld+json'
          - 'application/json'
          - 'text/csv'
        tags:
          - My

########################################
## Custom provider endpoints
########################################
Ivoz\Provider\Domain\Model\User\User:
  itemOperations:
    get_my_profile:
      access_control: '"ROLE_COMPANY_USER" in roles'
      depth: 1
      method: 'GET'
      path: '/my/profile'
      route_name: 'get_my_profile'
      operation_normalization_context: 'myProfile'
      normalization_context:
        groups: ['myProfile']
      parameters: []
      swagger_context:
        produces:
          - 'application/ld+json'
          - 'application/json'
        tags:
          - My
        parameters: []
    put_my_profile:
      access_control: '"ROLE_COMPANY_USER" in roles'
      attributes:
        depth: 1
      method: 'PUT'
      path: '/my/profile'
      route_name: 'put_my_profile'
      operation_normalization_context: 'updateMyProfile'
      denormalization_context:
        groups: ['updateMyProfile']
      normalization_context:
        groups: ['myProfile']
      parameters: []
      swagger_context:
        tags:
          - My
        consumes: ["application/ld+json"]
        parameters:
          - name: 'user'
            in: 'body'
            description: 'The updated User resource'
            schema:
              $ref: '#/definitions/User-updateMyProfile'
  collectionOperations:
    get_my_company_assistants:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'GET'
      path: '/my/company_assistants'
      route_name: 'get_my_company_assistants'
      parameters: []
      swagger_context:
        produces:
          - 'application/ld+json'
          - 'application/json'
        tags:
          - My
        parameters: []
    get_my_company_voicemails:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'GET'
      path: '/my/company_voicemails'
      route_name: 'get_my_company_voicemails'
      parameters: []
      swagger_context:
        produces:
          - 'application/ld+json'
          - 'application/json'
        tags:
          - My
        parameters: []

Ivoz\Provider\Domain\Model\CallForwardSetting\CallForwardSetting:
  itemOperations:
    post_my_call_forward_settings:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'POST'
      path: '/my/call_forward_settings'
      route_name: 'post_my_call_forward_settings'
      parameters: []
      swagger_context:
        consumes: ["application/ld+json"]
        produces:
          - 'application/ld+json'
          - 'application/json'
        tags:
          - My
        parameters:
          - name: 'CallForwardSetting'
            in: 'body'
            description: 'The updated CallForwardSetting resource'
            schema:
              $ref: '#/definitions/CallForwardSetting'
  collectionOperations:
    get_my_call_forward_settings:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'GET'
      path: '/my/call_forward_settings'
      route_name: 'get_my_call_forward_settings'
      parameters: []
      operation_normalization_context: 'detailedCollection'
      normalization_context:
        groups: ['detailedCollection']
      swagger_context:
        produces:
          - 'application/ld+json'
          - 'application/json'
        tags:
          - My
        parameters: []

Ivoz\Provider\Domain\Model\Extension\Extension:
  collectionOperations:
    get_my_company_extensions:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'GET'
      path: '/my/extensions'
      route_name: 'get_my_company_extensions'
      normalization_context:
        - collection
      parameters: []
      swagger_context:
        produces:
          - 'application/ld+json'
          - 'application/json'
        tags:
          - My
        parameters: []
